### ISSUE TITLE
Can I maybe set bandwidth and number user for a API key ?

### ISSUE THREAD

**Issue by evilcat1997** [Jigsaw-Code/outline-server#1007]
Hello everyone, Can I maybe set bandwidth and number user for a API key ?

**Comment by legiorange** [comment]
Hi,evilcat1997.
You can try using Outline Manager to set bandwidth with an API key.

**Comment by bemasc** [comment]
Yes, bandwidth controls are supported (see [here]).  The feature request for limiting each key to one user is tracked at #546.
