### ISSUE TITLE
Connect Outline Server to other Server (Outline or Wireguard)

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Jigsaw-Code/outline-server#1017]
I have a VPS, with an Outline Server.
(which is located in America for example)

I would like to know if there is the possibility of connecting that server to a remote Outline or Wireguard server (any vpn) that I have in another region.
The idea is to go out through that other server, (redirect all the traffic from the 1st vps to the other server) and not through the one located in America

**Comment by AnonymousWebHacker** [comment]
VPS1 - I have a VPS with an Outline server (you knows, shadowsock) located in America.

VPS2 - My best friend has a server in Europe, and I have a key to connect to his server



How can I connect my VPS1 to the VPS2? In other words, when I connect to my VPS1, all traffic is redirected to VPS2 and leave through Europe.

Note: in case it is not possible to an outline, do it with wireguard or some other vpn. the objective is to go out through the vps of europe

**Comment by legiorange** [comment]
You don't  .

Try trojan.

**Comment by AnonymousWebHacker** [comment]
I could do it.
VPS1 with Outline Server and VPS2 with WireGuard Server

Connect VPS1 with VPS2 using Wireguard
Client   ---[outline]--- > VPS1 ------[wireguard]------>  VPS2 -----------> Internet  :)

**Comment by 2ta** [comment]
@AnonymousWebHacker 
can you explain more, how to use wireguard for this section 
VPS1 ------[wireguard]------> VPS2

**Comment by AnonymousWebHacker** [comment]
> @AnonymousWebHacker can you explain more, how to use wireguard for this section VPS1 ------[wireguard]------> VPS2
Hii, greetings 

VPS1 ---- > VPS2 , using wireguard vpn.
On the VPS2, you install a wireguard server.
You would only have to configure VPS1, as a wireguard client to connect to VPS2
