### ISSUE TITLE
Unexplained "access key is not valid" error

### ISSUE THREAD

**Issue by masoumi-pezhman** [Jigsaw-Code/outline-server#1030]
Hello
I have a server from France. I follow all the commands and steps completely. I also watched YouTube instructional videos, etc. several times, and I did it without any shortcomings.
Outline Manager also successfully connects to the server.
The problem is that when I connect I get a message "It seems like your access key is not valid".
I checked the firewall settings. I even turned off the whole firewall, but the error still persists.

My server is pinging
ssh is enabled
putty is connected

Where can the problem come from?
![Unt3itled](https://user-images.githubusercontent.com/96417361/146751636-83f8661b-a663-4b9f-9687-0dd8015e8e6b.jpg)

![2021-12-20_13-33-20](https://user-images.githubusercontent.com/96417361/146750094-ada92331-4f9f-43e2-9e2e-8bf1e0baeab8.jpg)

Thanks

**Comment by kiat** [comment]
I have exactly the same issue. Please let me know if you have a solution for this. I run it on different OS (ubuntu 20 and 22 ) and different locations (EU and US West) and I got the same issue with "It seems like your access key is not valid"

**Comment by maddyhof** [comment]
Thank you for reaching out! Please submit feedback in through the Outline Client app or contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.
