### ISSUE TITLE
Working on the server that a site is running?

### ISSUE THREAD

**Issue by alexlii1971** [Jigsaw-Code/outline-server#1033]
Hello,

I have a website that is running on digitalocean, is it possible to install outline on that server? Or do I have to install outline on another server please?

Thanks

**Comment by qian2501** [comment]
I am running my web and outline on the same server on AWS, IMHO logically there should be no issue as long as they don’t conflict on the same port. If you worry about make things a mess just make a backup and give it a try, if things become nasty just fallback to the backup.
