### ISSUE TITLE
Split tunnel

### ISSUE THREAD

**Issue by wolf-allywilson** [Jigsaw-Code/outline-server#1035]
Is it possible to have split tunnel on Outline?

It would be great if we could send only specific traffic down the tunnel (e.g. certain IP ranges and only specific FQDNs for resolution to name servers on the other side of the tunnel, or even specific UDP/TCP port ranges).

**Comment by bemasc** [comment]
I think this is covered by https://github.com/Jigsaw-Code/outline-client/issues/887
