### ISSUE TITLE
Routed to an s3 bucket url when I downloaded the manager

### ISSUE THREAD

**Issue by reyesvicente** [Jigsaw-Code/outline-server#1037]
Wondering why I was directed to https://s3.amazonaws.com/outline-vpn/index.html#/en/home. Anyone know?

**Comment by seia-soto** [comment]
I couldn't reproduce but if you still experiencing the error, you can find the manager here: https://github.com/Jigsaw-Code/outline-server/releases

**Comment by reyesvicente** [comment]
> I couldn't reproduce but if you still experiencing the error, you can find the manager here: https://github.com/Jigsaw-Code/outline-server/releases

Yeah I wonder why it got redirected too. I use Firefox.
