### ISSUE TITLE
Wrong transfer limits for new DigitalOcean droplets

### ISSUE THREAD

**Issue by Fudoshiki** [Jigsaw-Code/outline-server#104]
Please update transfer limits 1TB instead 500GB Transfer for new $5 US/Mo droplets
New DigitalOcean [pricing](https://www.digitalocean.com/pricing)

![image](https://user-images.githubusercontent.com/4083992/39037734-ce359368-449a-11e8-83c3-80eaf8ee8033.png)

**Comment by bemasc** [comment]
A proxy server's total transfer is twice the amount of data that passes through it, because each byte must pass in and out again.  Therefore, if you run the Outline Server software on a VM with a 1 TB monthly limit, you can proxy 500 GB of data before hitting the limit.

**Comment by NAVrasZ** [comment]
https://www.digitalocean.com/community/tutorials/digitalocean-bandwidth-billing-faq
>What type of data transfer counts towards the total transfer pool?

>Only outbound transfer is counted.

>This means any transfer sent from a Droplet over a public network interface is deducted from the data transfer pool. In all other situations, transfer is not metered. Uploading data from your computer or the Internet to a Droplet is not metered. Communication among Droplets using private network is not metered.

And the actual transfer shown in the billing is 500G instead 1T ( I used outline for registration and chose $5 plan, it's the same I assume).
But they do give me free transfer over time for some reason.
