### ISSUE TITLE
where is api-port stored?

### ISSUE THREAD

**Issue by hilt86** [Jigsaw-Code/outline-server#1040]
I had to migrate a server due to issues with a host yet when I backed up and restored the `/opt/outline` directory the management / api port was not restored correctly. 

Where is the setting for the management port stored? (it is not access.txt)

**Comment by seia-soto** [comment]
> I wrote solution after `inspections` section.

# Inspections

They're not stored and managed by Docker as I see the sources on the tag `v1.9.0`:

https://github.com/Jigsaw-Code/outline-server/blob/c37dd3751a70dc381105be36715ecaf25d7f922d/src/shadowbox/server/main.ts#L89-L90

Also, this is same from the tag `server-v1.6.1-rc2`:

https://github.com/Jigsaw-Code/outline-server/blob/4bd52f07180cff126d98c4b74ee0848322e62143/src/shadowbox/server/main.ts#L89-L90

Lastly, by referencing the install script, we can know that **the port is set as an environment variable when you install the server and not stored**.

https://github.com/Jigsaw-Code/outline-server/blob/3fb4bd121b1c8a919332f6e1c8dc3b1c169a922d/src/server_manager/install_scripts/install_server.sh#L301-L328

# Solution

First of all, we need to know that Docker doesn't support changing the environment variable by default. Also, as Outline-Server project grows we cannot ensure that a single script would be a help.

So, I think it's best to run installation script again with parameters you want to keep things clean and simple.

1. Stop and delete the shadowbox container

```bash
docker container ls
docker rm -f [ID or NAME]

# By default the container name is `shadowbox` and the following command will work if you just copy-pasted the install command
docker rm -f shadowbox
```

2. Backup and remove `/opt/outline` or the data directory

```bash
# Backup somehow
tar cvf backup.tar /opt/outline/*

# Remove the dir for clean install
rm -r /opt/outline
```

3. Install outline-server again with parameters if you want

https://github.com/Jigsaw-Code/outline-server/blob/3fb4bd121b1c8a919332f6e1c8dc3b1c169a922d/src/server_manager/install_scripts/install_server.sh#L46-L50

```bash
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
```

- `hostname` is also compatible with your domain or IP
- `api-port` is what you want, management server port
- `keys-port` is the port that shadowsocks server works on

You can just append it **with empty $0 variable** as the install script will interpret from `$1` (commonly $0 is the command, not parameter):

> -c string If the -c option is present, then commands are read from string.
If there are arguments after the string, they are assigned to the positional parameters, starting with $0.

```bash
# For e.g.
sudo bash -c "$(wget ...)" "" --api-port 8081 --keys-port 12345
```

When you install the server again, it will automatically set required environment variable.

4. Stop the container and recover the data directory which containers access keys

```bash
# Stop the container
docker stop shadowbox

# Remove clean directory
rm -r /opt/outline

# Recover somehow
tar xvf ...
```

5. Start again and check status

Note that you can find the management port and api key from green text during the installation.

```bash
# Start the container
docker start shadowbox

# Get the server information to ensure if server is actually working well
# We need to append `-k` to ignore the SSL certificate error
curl https://localhost:MANAGEMENT_PORT/API_KEY/server -k

# For e.g. using default port (key is fake generated)
curl https://localhost:8081/________HdRD0PR4MQJhrw/server -k
```

If `curl` prints stuff like below, I can say that your server is now ready:

```json
{"name":"Outline Server","serverId":"UID","metricsEnabled":false,"createdTimestampMs":1643190862571,"version":"1.6.1","portForNewAccessKeys":12345,"hostnameForAccessKeys":"HOSTNAME"}
```

**Comment by fakoor** [comment]
Is there a similar curl URL available to check the keys-port response as well?

**Comment by maddyhof** [comment]
Thanks for reaching out, @fakoor. Does [this endpoint](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys/post) meet your needs?

**Comment by fakoor** [comment]
@maddyhof Yes, Thanks a lot.
