### ISSUE TITLE
Expose data transfer amounts for one or a set of keys via server API

### ISSUE THREAD

**Issue by WenzzyX** [Jigsaw-Code/outline-server#1068]
Hello. I ran into the problem of normal counting of the transferred data, if there are many keys, then statistics are obtained for all keys, therefore, I ask you to add 2 endpoints.

1. `{SECRET_URL}/:id/data-transferred` - Returns transferred data for one key by id
2. `{SECRET_URL}/data-transferred-keys` (Request body : { keys: [1, 2, 3 ... n] }) - Returns the passed data for all keys that are specified in the request (IDs)

**Comment by skala-vl** [comment]
A very necessary function! Please implement!

**Comment by Blueclaus13** [comment]
Could you assign me this issue?

**Comment by maddyhof** [comment]
@Blueclaus13 sorry for the delay over here – would you still like to work on this? We'd love that!

**Comment by fortuna** [comment]
@WenzzyX you can access the metrics directly from the Prometheus metrics backend: https://stackoverflow.com/questions/76869983/monitoring-outline-vpn-how-to-access-performance-metrics-of-an-outline-server
