### ISSUE TITLE
Can I block torrenting through my Outline node?

### ISSUE THREAD

**Issue by backmeupplz** [Jigsaw-Code/outline-server#1071]
Don't want to get DMCA, maybe there is a simple way to block all torrenting activity through the node? Thank you!

**Comment by chaos1t** [comment]
You can use ipp2p iptables module to block p2p traffic. [Example](https://github.com/helixzz/iptables-block-p2p-traffic/blob/master/iptables_block_p2p_traffic.sh)

**Comment by backmeupplz** [comment]
@chaos1t thanks, that's what I did :) hopefully it works

**Comment by Simplici** [comment]
> You can use ipp2p iptables module to block p2p traffic. [Example](https://github.com/helixzz/iptables-block-p2p-traffic/blob/master/iptables_block_p2p_traffic.sh)

it doesn't seem to work with me:
I have download this script to /opt/.
![image](https://user-images.githubusercontent.com/8101111/200291453-c6c2319a-8be4-4a7a-830e-a33837d0adaf.png)

edited /etc/network/interfaces
![image](https://user-images.githubusercontent.com/8101111/200291681-2271e976-e14c-4c4d-a2e2-44329c6bc481.png)
![image](https://user-images.githubusercontent.com/8101111/200291747-12a3418a-42a2-418b-a050-7ec63870c4dd.png)

I restarted the Outline server, but I can still torrenting.
![image](https://user-images.githubusercontent.com/8101111/200291919-1365ec29-a973-4941-9efa-e5c3c1027b47.png)
