### ISSUE TITLE
We need `manual update`!

### ISSUE THREAD

**Issue by c2xusnpq6** [Jigsaw-Code/outline-server#1087]
Can we have a more convenient button or option to update?

I saw some people say that as long as `watchtower` restart, Outline will be updated, but I just can not figure it out.

Officially, it is said that Outline can be updated automatically, but after a few weeks, Outline is still not updated automatically, and I don't know where the problem is.

I see a lot of people asking the same thing on Reddit and Github, but no one can give them a solution... 🤔

**Comment by c2xusnpq6** [comment]
Anyone? 😗

**Comment by legiorange** [comment]
close it.
