### ISSUE TITLE
Does access_url speed vary for different number of connections?

### ISSUE THREAD

**Issue by ChenforCode** [Jigsaw-Code/outline-server#1093]
Does the speed after connection depend on the performance of the server, but also on the number of access_url connections? If there is only one server, and one access_url has one client connection, and another access_url has 100 client connections, can these clients feel the difference in speed?

**Comment by bemasc** [comment]
Creating more access keys does not affect server throughput.  When the number of known access keys is very large (e.g. >1000), the time required to establish a new socket (e.g. when opening a webpage) may be increased, but once the sockets are open, throughput (e.g. download speed) should not be affected.
