### ISSUE TITLE
constantly getting error 1  \ win 7 x64

### ISSUE THREAD

**Issue by JohnyRipsaw** [Jigsaw-Code/outline-server#1102]
constantly getting error 1  \ win 7 x64

**Comment by legiorange** [comment]
Please let us have your specific.

**Comment by JohnyRipsaw** [comment]
Hello, I will gladly provide you with info to solve this vpn problem. What
specific info do you need?

Сб, 28 мая 2022 г. в 04:57, 橙子 ***@***.***>:

**Comment by maddyhof** [comment]
Thanks for reaching out. Can you please provide steps to reproduce this error, including screenshots?
