### ISSUE TITLE
MacOS app availablility

### ISSUE THREAD

**Issue by JeffCleverley** [Jigsaw-Code/outline-server#111]
Since the idea of building a wrapper around SS is to circumvent oppressive internet regimes it seems a bit shortsighted that the MacOS app install directs to the Appstore, which is not available in China...

Don't you think it would be wise to have the app dmg available from other sources via the manager in app link?

**Comment by alalamav** [comment]
Thanks for the feedback @JeffCleverley. Unfortunately, apps that require the Network Extension entitlements, which allow the app to run as a full system VPN, can only be distributed through the App Store.
