### ISSUE TITLE
Can only add manage one server via Outline Manager

### ISSUE THREAD

**Issue by JeffCleverley** [Jigsaw-Code/outline-server#112]
It seems a bit limiting to be able to only manage one server with the Outline Manager.

I applaud your efforts to make Shadowsocks server and client management more user-friendly etc, but I have about 6 SS servers. I swap between them using the Shadowsocks NG app on MacOS.

With the Outline manager I can only manage one server.

**Comment by zhangweijie-cn** [comment]
#78

**Comment by trevj** [comment]
@JeffCleverley Thanks for the feedback! This is a popular feature request:
https://github.com/Jigsaw-Code/outline-server/issues/78

**Comment by banhao** [comment]
It's really an important feature. To against the GFW I must have several servers from different VPS vendors as backups. If I can't use one manager server, it's really tough to manage these Outline servers.

**Comment by JeffCleverley** [comment]
@banhao exactly!

Without this, it really is failing as a way to circumvent restrictions imposed by the GFW. Having access to one server makes it next to useless.

**Comment by fortuna** [comment]
@banhao that's something we are exploring. Please follow #78.
Meanwhile, you can easily destroy and recreate a server if it gets blocked.
