### ISSUE TITLE
How to disable Prometheus

### ISSUE THREAD

**Issue by zouchengli** [Jigsaw-Code/outline-server#1127]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/27568522/181137861-f755531a-f593-493e-b155-295c8c69913d.png">

**Comment by ch3rrydrunk** [comment]
Having. the same issue
with Disk reads up to 256 mb/s, 100% CPU and OOM killer

**Comment by maddyhof** [comment]
Thanks for your feedback. Closing as a duplicate of #442.
