### ISSUE TITLE
Why IP shows in Access Keys?

### ISSUE THREAD

**Issue by MintBlitz** [Jigsaw-Code/outline-server#1137]
**shadowsocks-libev key:**
ss://YWVzLTI1Ni1nY204anhSZjdQWDFdYUBtaW50YmxpdHouZ2E6NAU2PTE

**outline access key:**
ss://Y2hhY2hhMjBtaWV0Zi1wb2y5MTMwNTpyT0w0SjVhTVVybDA@42.170.84.29:6538/?outline=1

Why mentioning the IP and port in the key? When sharing on Chinese social media like Wechat, that sounds like a big security breach. Censors will know our servers very quickly and easily, even if the key is no longer valid. shadowsocks-libev doesn't mention it in the key

**Comment by falahati** [comment]
ipaddress is also included in the shadowsocks keys, it is just in the base64. so not much different. you just should not share URLs on social media.

**Comment by fortuna** [comment]
Outline supports both key formats. However, notice that the first format also has the IP address, but in encoded format.

What exactly is your threat model here? I see how the first format is slightly harder to get the IP address, but it definitely doesn't prevent the censor from getting it. The clearer IP address has been a lot more helpful in terms of usability for everyone (managers and users).
