### ISSUE TITLE
auto restart after rebooting centos7 server not working

### ISSUE THREAD

**Issue by davidwerent** [Jigsaw-Code/outline-server#1144]
hey, I'm reboot my VPS server (centOS7) with `sudo reboot`
but my iphone with outline client can't connect to vpn server
outline manager can't connect too
how i can restart outline server on centos manually? without reinstalling? thx

**Comment by schvetsoff** [comment]
exact same question

**Comment by POSTiGA1** [comment]
> hey, I'm reboot my VPS server (centOS7) with `sudo reboot` but my iphone with outline client can't connect to vpn server outline manager can't connect too how i can restart outline server on centos manually? without reinstalling? thx

restart docker:

sudo service docker start

**Comment by Steve-Brule** [comment]
`sudo systemctl enable docker` will make the outline server start at boot

**Comment by maddyhof** [comment]
Thanks for reaching out! Did restarting docker or running @Steve-Brule's command help you?

**Comment by multypass** [comment]
On Ubuntu after reboot does not worked. I send sudo systemctl enable docker, docker started after reboot but connection from manager and client doesn’t work. Could you help me please.
