### ISSUE TITLE
Getting Access to Password

### ISSUE THREAD

**Issue by JeffCleverley** [Jigsaw-Code/outline-server#115]
In my closed issue #111

You explained that you need to distribute the app via the mac appstore.

I have an outline server set up at the moment, but the funny thing was my shadowsocks app actually detected this server when I copied the code from the manager to the client.

So, I clicked yes on shadowsocks-ng app, and the outline server was added. I can now connect to my outline server without needing the outline client. In the shadowsocks-ng app, it has automatically entered the password to access the outline server.

I have been trying to repeat this process but have been unable, so far. 

What I want to know is, if there is a way to get the autogenerated password to access the outline server. I have the rest of the settings from the terminal, it provides me the port, you are using the same encryption, I have the IP etc, the only thing I am missing to do a manual setup is the password.

May I make a feature request?

Alongside the json config and the ports, can you provide the password in the terminal so that people who can't access the appstore can use one of the other shadowsocks clients that they have available?

Thanks.

**Comment by alalamav** [comment]
Thanks for the feedback @JeffCleverley. We are thinking of ways to provide access to the server. Please take a look at #68 for instructions on how to connect to an Outline server running on DigitalOcean.

**Comment by JeffCleverley** [comment]
Hey there,

Okay, I suppose I can ssh into the server and look for the password in the shadowsocks config file that outline must generate.

Is everything in the same place as usual, I understand you run it from a docker install?

**Comment by alalamav** [comment]
Yes, the server runs in a Docker container. Are you looking for the access key password or the password to SSH into the server?
For the former, you can open the Outline invite, and copy the `ss://` URL. Any Shadowsocks client should be able to accept it.

**Comment by JeffCleverley** [comment]
The shadowsocks access key password. Okay, great thanks.
