### ISSUE TITLE
Package for FreeBSD? 

### ISSUE THREAD

**Issue by gregober** [Jigsaw-Code/outline-server#1163]
Hello, we think that It might be nice for outline-server to benefit from a package. 
If enough info is provided regarding compilation instruction and dependencies, we might help create this package. 

If anyone else is interested, please let us know.

**Comment by 4r7if3x** [comment]
It shouldn't be that difficult to pull this off. You may count on me ;)

**Comment by gregober** [comment]
We actually already have the compilation setup. 
So package is probably quite close.
