### ISSUE TITLE
[macOS] Misleading Outline Manager update alerts

### ISSUE THREAD

**Issue by yakovmanshin** [Jigsaw-Code/outline-server#1167]
I’m running Outline Manager v1.10.0 on macOS 12.6. In the recent days, I’ve been getting alerts telling me a new version has been downloaded and will be installed on next launch of the app. When I do relaunch the app, however, its version stays the same.

![](https://user-images.githubusercontent.com/4648742/192848524-10c35ef4-35e5-498c-9ede-5d0d34144617.png)

**Comment by 4r7if3x** [comment]
Just a guess, but does the app have the required permissions to access the file system and etc.?

**Comment by yakovmanshin** [comment]
The app hasn’t requested access to the file system (Files and Folders, Full Disk Access).

What I see is, [the `latest.yml` file](https://github.com/Jigsaw-Code/outline-releases/blob/f847861c2aaa92802a767f7fd8f3d108dbf7d8d7/manager/latest.yml) declares version 1.11.0, which is newer than 1.10.0 that I have installed, but only contains links to a Windows version (`.exe`). Could that be the cause?

**Comment by 4r7if3x** [comment]
No, since you are on macOS, the latest-mac.yml is being used by Electron for auto-update. It also can be that the app is not signed due to the [requirement](https://github.com/electron/electron/blob/main/docs/api/auto-updater.md) of `Squirrel.Mac`.

**Comment by maddyhof** [comment]
This has been fixed. 
Please download the latest version of the Manager and reopen the ticket if you continue to encounter this issue.
