### ISSUE TITLE
Any Idea for how to Tunnel all Outline Traffic to another server for Internet ? 

### ISSUE THREAD

**Issue by SniperTomb** [Jigsaw-Code/outline-server#1172]
Hi

I have censored national network so I want to use outline for this
I don't have uncensored access to international network!

I have a **VPS1** in my country that have access to international network and second **VPS2** in Europe that have all access to network

how I can setup outline on my First VPS1 with Outline then tunnel it to VPS2 to access uncensored and wide network ?
Is there any way to setup 2 outline service on my VPS1 then tunnel all traffics it to VPS2 & VPS3 on different ports ?

Something like this picture but maybe with two Vps outside my country
![image](https://user-images.githubusercontent.com/114521061/193490095-57ddeb50-532f-4f91-8bfb-c9f846e67ee7.png)

 Thanks in Advance

**Comment by 4r7if3x** [comment]
I'm not sure if your question is relative to Outline due to protocol restrictions (I need to dig into it to give you a confident answer). Still, you can set up a multi-hop VPN using OpenVPN on the highest security settings. You may give it a try with Outline as well, employing the same scenario...
