### ISSUE TITLE
Doesn't work in Iran!

### ISSUE THREAD

**Issue by techjoyment** [Jigsaw-Code/outline-server#1177]
Outline can't bypass Iran's firewall. So, it doesn't work in Iran.

**Comment by ricmod** [comment]
@techjoyment It seems to work for some people in Iran. Try setting up the server in different geographical locations until you end up with a server that is not filtered in Iran.

**Comment by alireza-jafari** [comment]
I am in Iran, I installed the outline server in a could server, and although my client can connect, all of my requests are timed out. what is the problem?

**Comment by xpectropatrunum** [comment]
It is working in Iran,
Apps like instagram and youtube working properly. but in browser, domains are not loading (except ip addresses)

**Comment by mortza** [comment]
behavior differs from one ISP to another, although I recommend do not waste your time and equipment on this project and try other options (take a look at StrongSwan for example)

**Comment by techjoyment** [comment]
> behavior differs from one ISP to another, although I recommend do not waste your time and equipment on this project and try other options (take a look at StrongSwan for example)

My V2ray config also doesn't work anymore. Do you have any recommendations and links to specific guidance?

**Comment by xpectropatrunum** [comment]
> behavior differs from one ISP to another, although I recommend do not waste your time and equipment on this project and try other options (take a look at StrongSwan for example)

Finally I set a openvpn server on ubuntu and it worked!

**Comment by techjoyment** [comment]
> > behavior differs from one ISP to another, although I recommend do not waste your time and equipment on this project and try other options (take a look at StrongSwan for example)
> 
> Finally I set a openvpn server on ubuntu and it worked!

@xpectropatrunum Could you share your solution, please? I tried every protocol and they didn't work for me.

**Comment by xpectropatrunum** [comment]
> 

Yes sure.
I used this:
https://www.cyberciti.biz/faq/howto-setup-openvpn-server-on-ubuntu-linux-14-04-or-16-04-lts/
Don't forget to change default port (1194) . The 1194 port is blocked in Iran.

**Comment by techjoyment** [comment]
> > 
> 
> Yes sure. I used this: https://www.cyberciti.biz/faq/howto-setup-openvpn-server-on-ubuntu-linux-14-04-or-16-04-lts/ Don't forget to change default port (1194) . The 1194 port is blocked in Iran.

@xpectropatrunum Thanks. But it doesn't work for me. They can easily detect OpenVPN protocol and block it without any obfuscation config.

**Comment by alireza-jafari** [comment]
@xpectropatrunum 
thank you openvpn is working. i changed TCP and UDP ports to a number larger than 50000, but the loss of my network is about 50%, between every two packets one is timed out. what should I do?

**Comment by mortza** [comment]
> > behavior differs from one ISP to another, although I recommend do not waste your time and equipment on this project and try other options (take a look at StrongSwan for example)
> > @mortza
> > My V2ray config also doesn't work anymore. Do you have any recommendations and links to specific guidance?

[this](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ikev2-vpn-server-with-strongswan-on-ubuntu-20-04) is a guide on setting up a VPN server on ubuntu

**Comment by mortza** [comment]
> Last error: curl: (35) error:0A000126:SSL routines::unexpected eof while reading curl: (28) SSL connection timeout Failed to determine the server's IP address. Try using --hostname .
@amirali6506 

the error is self explanatory, program is unable to make SSL connection due to restrictions applied in iran.

**Comment by kazemiprince** [comment]
Due to most of VPN protocols such as openVPN (I changed a lots of ports and not working anymore. it was working since beginning new protest here) are blocked here in Iran, I have an Idea but I don't know if it's possible or not.
It's possible on paper, but most of my tries was failed.
Idea is to have one server outside of Iran (for example in US)
And have another one VPS inside (on some servers that have access to outside)
Installing outline server on both servers
Making VPN connection from Inside server to outside server and share it for inside requests.
my problem for the moment is I can not install outline client on ubuntu!
and can not install outline server on inside server due to blocking "https://auth.docker.io/token .... "
it's appreciated if you prepare outline client for ubuntu (terminal version not with desktop)

**Comment by hamid-kamalpour** [comment]
> Hi I can't install this on ubuntu server I get this error: (by the way, I'm in Iran)
> 
> Last error: curl: (35) error:0A000126:SSL routines::unexpected eof while reading curl: (28) SSL connection timeout Failed to determine the server's IP address. Try using --hostname .
> 
> Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you. Full log: /tmp/outline_logsbn

this command should works  for this issue,

`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh) --hostname YOUR_HOST_IP"
`
