### ISSUE TITLE
Cant connect to my server over VPN

### ISSUE THREAD

**Issue by mirkhamidov** [Jigsaw-Code/outline-server#118]
I got a physic server on - 1.1.1.4 and a lot VM in it via ProxMox.

1.1.1.24 - VM with OutlineServer
1.1.55.186 - VM with web server - can connect
1.1.1.29 - on this, i got haproxy and a lot services and cant connect to this server via even SSH over VPN

What is a problem?

**Comment by trevj** [comment]
@mirkhamidov Thanks for using Outline. I'm afraid we need a bit more information before we can help you - on which platform are you running the Outline client?

**Comment by mirkhamidov** [comment]
client on - osx
server on ubuntu

**Comment by trevj** [comment]
@mirkhamidov Going to close due to inactivity, apologies for the very slow response. If you'd like to continue this discussion, please do re-open this issue.
