### ISSUE TITLE
Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container.

### ISSUE THREAD

**Issue by AminYZD** [Jigsaw-Code/outline-server#1186]
I set up a VPS and the outline did not work on my VPS when I'm on step 1:

I Log into your server and run this command.

sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"

I receive an error:
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Setting PUBLIC_HOSTNAME to external IP ...... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
docker: Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container "d2123bc66dedb658a58d87e1798ed8a588ac4e98979f7fd7c6b0f058fb6dc325". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_loghWz

**Comment by AhmadPirzargar** [comment]
use the below command to remove the existing container:
docker container rm d2123bc --force

**Comment by idev-software-group** [comment]
> I set up a VPS and the outline did not work on my VPS when I'm on step 1:
> 
> I Log into your server and run this command.
> 
> sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> 
> I receive an error:
> 
> > Verifying that Docker is installed .......... OK
> > Verifying that Docker daemon is running ..... OK
> > Setting PUBLIC_HOSTNAME to external IP ...... OK
> > Creating persistent state dir ............... OK
> > Generating secret key ....................... OK
> > Generating TLS certificate .................. OK
> > Generating SHA-256 certificate fingerprint .. OK
> > Writing config .............................. OK
> > Starting Shadowbox .......................... FAILED
> > docker: Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container "d2123bc66dedb658a58d87e1798ed8a588ac4e98979f7fd7c6b0f058fb6dc325". You have to remove (or rename) that container to be able to reuse that name.
> > See 'docker run --help'.
> 
> Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you. Full log: /tmp/outline_loghWz

the answer is : sudo docker rm (the container name of the current /shadowbox of the docker is in use by the shadowbox) --force like this : sudo docker container rm **d3irts5** --force
