### ISSUE TITLE
Sharing Same Access Keys Between Servers

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [Jigsaw-Code/outline-server#1199]
How can I add the same key to multiple servers? Most of my services are behind a load balancer which means I have to provide identical services but I can't find a way to do this, outline manager only creates random new keys.

**Comment by cursedwraith** [comment]
Im looking for same thing but using a server as bridge to forward all trafic to the outline server.

**Comment by meanother** [comment]
Look https://artydev.ru/posts/dynamic-outline/
