### ISSUE TITLE
not work in iran

### ISSUE THREAD

**Issue by seingod** [Jigsaw-Code/outline-server#1202]
Currently, I have tested this tool on several servers and several different devices
None of them work, the connection is established, but some applications like Telegram only work and are practically useless
But some people started this tool in a special way and are using it
Can you give a solution? Or do you have a solution for use in Iran?
You wrote on your website that this tool is unfilterable, but it is currently useless in Iran

**Comment by filmaj** [comment]
I set up an outline server on Amazon in the Frankfurt zone using the Lightsail template and can confirm that someone inside Iran reported the same issue that @seingod did above.

There is some[ discussion on Reddit](https://www.reddit.com/r/outlinevpn/comments/xzqg6x/access_key_for_iranian_people_for_outline_vpn/) that seems to point that different cloud providers seem to work differently for Iranian people. I see reports that any DigitalOcean or Amazon-based servers don't work (specifically: a connection can be established, but traffic does not flow through it).

**Comment by MoneyPantry** [comment]
Having the same issue. I set up an Outline server in India zone and my family and friends can not use it. It works for me (am in the U.S.) so I know its set up correctly. 

They get this error:

> " Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback."

**Comment by seingod** [comment]
I did some research
Some servers are not filtered and work
So are some clouds
Others can also connect, but they can only use Telegram
This shows that most of the packets that pass through the VPN fail to return the answer and are filtered
In the meantime, Telegram works because it offers different protocols and its packets are not filtered, but it also faces slow speed and sometimes the connection is interrupted.
I am currently connected to other VPNs and I have the best connection with udp protocol on certain ports like 123
In my opinion, Outline should provide more protocols and provide the possibility of connecting the client with several different ports in order to choose the best way to circumvent and encrypt.
In the meantime, I tried to read the source code and make changes, but it is ineffective because the official outline client does not accept the changes and I have to prepare a special client that is not suitable for the public and is very time-consuming and may be useless because this Filtering may be removed in the future
Only the outline itself can provide the basis for this so that the scalability of the server will grow in the future

**Comment by hamid-kamalpour** [comment]
> Currently, I have tested this tool on several servers and several different devices None of them work, the connection is established, but some applications like Telegram only work and are practically useless But some people started this tool in a special way and are using it Can you give a solution? Or do you have a solution for use in Iran? You wrote on your website that this tool is unfilterable, but it is currently useless in Iran

The solution that works for me in Iran, is to use a dedicated VPS (based in Tehran like 0-1 servers) as a middle tunnel. It tested on Irancell, MCI, Shatel, Hiweb, and Asiatech ISPs.

**Comment by seingod** [comment]
@hamid-kamalpour 
I have two servers in Iran and the Netherlands
I tried to tunnel, but I still connect and only Telegram works
Can you give a little more guidance so that others can use it?

> > Currently, I have tested this tool on several servers and several different devices None of them work, the connection is established, but some applications like Telegram only work and are practically useless But some people started this tool in a special way and are using it Can you give a solution? Or do you have a solution for use in Iran? You wrote on your website that this tool is unfilterable, but it is currently useless in Iran
> 
> The solution that works for me in Iran, is to use a dedicated VPS (based in Tehran like 0-1 servers) as a middle tunnel. It tested on Irancell, MCI, Shatel, Hiweb, and Asiatech ISPs.

**Comment by mqiasi** [comment]
@seingod i have set up some servers using a raspberry pi at my office and at home, have sent them to family and friends in Iran all do work

**Comment by seingod** [comment]
@mqiasi 
Whether you can connect depends on your location and internet service provider
I can currently connect with shadowsocks and the simple obfuscation plugin
I think this problem will be solved in Iran if the outline client supports the simple obfuscation plugin
Or developers guide how to add it
Currently, I think the only way to use shadowsocks is plugins

**Comment by hamedbaftam** [comment]
For fixed this issue you can use this repo https://github.com/hamedbaftam/v2ray-docker-compose
