### ISSUE TITLE
Cannot access Outline from specific ISPs in Iran

### ISSUE THREAD

**Issue by keivanipchihagh** [Jigsaw-Code/outline-server#1204]
Hello from Iran!
There are heavy restrictions on VPNs here and it's getting harder everyday to connect to the free internet out there, so my case is a bit **_urgent!_** (:
I have setup Outline-server on my own server in France. It is currently working fine on one of the ISPs, but not on the rest of them. My server IP itself is neither blocked nor filtered and SSH works just fine. I can ping the IP from every ISP so my guess is, it's something in the middle causing the problem.

What could be the problem and what can be done to solve the issue?

**Comment by rodrikv** [comment]
Hi from the same place!
Did you come to any conclusions?

**Comment by aliotadi** [comment]
Hello there, same issue, same place.
it would be great if you share any potential solution with any protocol, etc... that comes to your mind...
I've tried floating IP, different protocols, etc. but none is working as expected.

**Comment by idev-software-group** [comment]
Same Issue is still standing over of the Internet in IRAN .

I have been run Outline Server on Amazon **Lightsail** Cloud Servers and now I run the Outline by IP Static but when I just run a server it will be blocked on MCI ISP in IRAN . I think they are using NGFW Firewall which is a best and AI based .

if you have any solution I will be happy to be shared and same to me .
