### ISSUE TITLE
Outline-Server vps memory usage keep going up

### ISSUE THREAD

**Issue by pyxarez** [Jigsaw-Code/outline-server#1215]
After installing outline server on AWS vps using the method provided by outline-manager.
When looking at memory usage dashboard, I would notice the memory usage would keep going up through 2 last weeks.

Screenshot from AWS dashboard:
<img width="436" alt="Screenshot 2022-10-31 at 17 13 34" src="https://user-images.githubusercontent.com/23152279/199028971-98a921ad-7e7c-422f-b0fa-a6ef308a5889.png">

**Comment by Sajjad1365** [comment]
##good

**Comment by Sajjad1365** [comment]
Good

**Comment by maddyhof** [comment]
Please re-test on server version 1.7.2 and let us know if that resolves this issue.

**Comment by pyxarez** [comment]
The problem resolved itself
