### ISSUE TITLE
clients (except Windows) require server to have enabled UDP fowarding

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#123]
the server didn't support udp forwarding. 

Could someone please give me some hints about build udp forwarding for the app. I have already set up servers, and the Windows app works fine.

**Comment by sailosha** [comment]
I think i have trouble to build udp on my servers

**Comment by trevj** [comment]
@sailosha Thanks for trying Outline! I'm sorry you're having trouble. I'm afraid right now the Outline clients - except on Windows - require UDP be enabled on the server. If you can enable UDP forwarding on your server, all of the clients should start to work.

**Comment by sailosha** [comment]
@trevj thanks for reply. I was travelling back to China for past few days. I fixed the issue on GCP( i forgot to open UDP forwarding on firewall), it is a very common mistake! Thanks so much, it works well now.

**Comment by sdtaheri** [comment]
I know this should not be asked here and I'm really sorry about this; but can someone please help me how to enable UDP forwarding on my VPS? It's running CentOS 7. I couldn't find anything I could rely on StackOverflow.
@sailosha @trevj

**Comment by sailosha** [comment]
> I know this should not be asked here and I'm really sorry about this; but can someone please help me how to enable UDP forwarding on my VPS? It's running CentOS 7. I couldn't find anything I could rely on StackOverflow.
> @sailosha @trevj

This is a typical firewall set up error. If you are sure about iptables setting correct. It may cuased by you didn't open the firewall in the vps setting page. For examole. Google cloud platform you can only open port in their setting pagr(web), not in the linux. So plz double check your vps setting.

**Comment by sdtaheri** [comment]
> > I know this should not be asked here and I'm really sorry about this; but can someone please help me how to enable UDP forwarding on my VPS? It's running CentOS 7. I couldn't find anything I could rely on StackOverflow.
> > @sailosha @trevj
> 
> This is a typical firewall set up error. If you are sure about iptables setting correct. It may cuased by you didn't open the firewall in the vps setting page. For examole. Google cloud platform you can only open port in their setting pagr(web), not in the linux. So plz double check your vps setting.

Thanks for your reply. I asked my VPS provider and they said they don't have any sort of limitations on ports and I have full root access to my VPS.
I once again checked my implementation. It's like this. I don't know if I'm doing anything wrong. I would really appreciate if you could help. 

`
[root@woody saeed]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: dhcpv6-client http https
  ports: 8883/tcp 8883/udp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
`

Port 8883 is the port on which I'm running an instance of Shadowsocks. I can connect to it using Shadowsocks-NG on macOS, but none of the Outline clients on any platform connect to it. 
Please help me if possible.

**Comment by sailosha** [comment]
if the TCP IP connection is estiblished, it could be other problems at here. Are you using IPV6? Also, I think Outline is using TCP only(cuz udp is unstable in some countries). Can you leave your email? I will send my ss-key to you, and you can try it out. If there is still problem , we could check it together.

**Comment by sdtaheri** [comment]
> @sdtaheri
> if the TCP IP connection is estiblished, it could be other problems at here. Are you using IPV6? Also, I think Outline is using TCP only(cuz udp is unstable in some countries). Can you leave your email? I will send my ss-key to you, and you can try it out. If there is still problem , we could check it together.

IPv6 is activated by default on my VPS. Never though this could cause a problem. 
Here's my email address: contact[at]saeedtaheri.com
I really appreciate.

**Comment by sailosha** [comment]
@sdtaheri  
sent. Feel free to use it, I may re-build entire servers sometime in Apr 20th - Apr 30th.
I am not sure what is the problem now, it seems like your outline server has some problems. If you use outline server commnad to build server, it allows you connect with any client, but if you build by ss-ng. Outlien client may not able to connect it.
