### ISSUE TITLE
Insufficient number of Xs in template 'outline_logXXX' when installing on Open BSD server

### ISSUE THREAD

**Issue by AbrahamQll** [Jigsaw-Code/outline-server#1234]
When I try to install outline on OpenBSD server I run the following command to install the server:
```
doas bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
```
and I get the following error:
```
mktemp: insufficient number of Xs in template `outline_logXXX'
```

**Comment by fortuna** [comment]
It seems OpenBSD requires a minimum number of Xs, so we need to increase the number of Xs in the filename here: https://github.com/Jigsaw-Code/outline-server/blob/6ea0c1d084ab064f945078c0038fa56acf61c4a5/src/server_manager/install_scripts/install_server.sh#L61

**Comment by fortuna** [comment]
This page says it requires 6 Xs: https://www.mktemp.org/docs/mktemp.man/

**Comment by QingXXiong** [comment]
I'd love to help with this change.

If I get it right, we need to  change `FULL_LOG="$(mktemp -t outline_logXXX)"` to `FULL_LOG="$(mktemp -t outline_logXXXXXX)"`,  and the same thing is for `LAST_ERROR="$(mktemp -t outline_last_errorXXX)"`.
