### ISSUE TITLE
Is there a way to make outline work behind a proxy?

### ISSUE THREAD

**Issue by hmffa** [Jigsaw-Code/outline-server#1249]
I have domain name and I use Cloudflare for DNS but when I turn proxy on, Outline stops working. I am currently in Iran and IP of several cloud providers have been blocked. With this way I can hide the server IP.

**Comment by bemasc** [comment]
What "proxy" are you referring to?

**Comment by hmffa** [comment]
I am talking about DNS proxy done by Cloudflare as seen in the picture.
![image](https://user-images.githubusercontent.com/25617950/210503608-df3a403c-15d6-448a-89d7-a123a9ccf764.png)
I have domain but I want to hide IP of the server behind this proxy in a way that Outline connects to my server through this proxy using domain.

**Comment by bemasc** [comment]
It looks like this Cloudflare feature [only supports the HTTP and HTTPS protocols](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/#ports-and-protocols), not Shadowsocks (which is used by Outline).

**Comment by m44soroush** [comment]
Is there any other tools which I can reverse proxy shadowsocks with? Nginx, haproxy or anything?
If yes, please share the proper configuration.

Something like this:

Client --> reverse proxy server --> otuline server

**Comment by Mano-Liaoyan** [comment]
> Cloudflare provides `Zero Trust` with `cloudflared` CLI tool that can be used to create a tunnel.

Which protocol should be used? I have tried all of them but none of the protocol (type) works...

**Comment by navinweb** [comment]
has anyone figured out how to do that?

**Comment by rvalitov** [comment]
There are a few things to check :
1. Did you manage to create a Cloudflare tunnel?
2. It's not blocked by your ISP?
3. If it's blocked by your ISP or government then it will not work. There's no simple way to fix that. It's easier to abandon Cloudflare tunnel in such case and use another solution.
4. If Cloudflare tunnel works then what problem you have? Making a VPN connection inside the tunnel? Or the configuration of your tunnel does not allow access to external IPs?
