### ISSUE TITLE
how the transfer is calculated?

### ISSUE THREAD

**Issue by Simplici** [Jigsaw-Code/outline-server#1254]
I doubt how the transfer for the server for for the keys is calculated. Is this the addition for inbound transfer and outbound transfer?

**Comment by fortuna** [comment]
It calculates the outbound traffic from the Outline server, which is proxy -> target and proxy -> client.

This is the code:
https://github.com/Jigsaw-Code/outline-server/blob/8780b4b80d653ba0da006dd2e46b4b89f3959441/src/shadowbox/server/manager_metrics.ts#L31
