### ISSUE TITLE
Waiting for Outline server to be healthy error

### ISSUE THREAD

**Issue by gitcoinkuang** [Jigsaw-Code/outline-server#1256]
Waiting for Outline server to be healthy

log is：
I2022-12-22T11:57:42.445Z 11 main.js:33] ======== Outline Server main() ========
I2022-12-22T11:57:42.449Z 11 main.js:33] Version is 1.7.2
I2022-12-22T11:57:42.468Z 11 main.js:33] Hostname: 45.xxx.xx.xxx
I2022-12-22T11:57:42.469Z 11 main.js:33] SB_METRICS_URL: https://prod.metrics.getoutline.org
(node:11) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
I2022-12-22T11:57:42.484Z 11 main.js:33] Prometheus is at 127.0.0.1:9090
I2022-12-22T11:57:42.485Z 11 main.js:33] Node metrics is at 127.0.0.1:9091
I2022-12-22T11:57:42.485Z 11 main.js:33] outline-ss-server metrics is at 127.0.0.1:9092
I2022-12-22T11:57:42.488Z 11 main.js:33] Replay protection enabled: true
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 127.0.0.1:9091
    at Server.setupListenHandle [as _listen2] (node:net:1446:21)
    at listenInCluster (node:net:1511:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1660:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1490:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9091
}

**Comment by gitcoinkuang** [comment]
It has been resolved after replacing the ubuntu system

**Comment by Kami-no** [comment]
Add in file `/etc/hosts` in the line starting with `127.0.0.1` value ` localhost` in the end of line.
