### ISSUE TITLE
Outline server not work.Prometheus cannot start.

### ISSUE THREAD

**Issue by McContax** [Jigsaw-Code/outline-server#1258]
I used `sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"` to install outline server and use outline for a while.

Yesterday, server provider restart my server. Then, I cannot connect to it. Neither the VPN nor the Outline manager.

Here's the error log of the outline server.

I2022-12-26T09:01:41.545Z 12 main.js:102] ======== Starting Prometheus ========
I2022-12-26T09:01:41.545Z 12 main.js:102] /opt/outline-server/bin/prometheus "--config.file" "/opt/outline/persisted-state/prometheus/config.yml" "--web.enable-admin-api" "--storage.tsdb.retention.time" "31d" "--storage.tsdb.path" "/opt/outline/persisted-state/prometheus/data" "--web.listen-address" "127.0.0.1:9090" "--log.level" "info"
ts=2022-12-26T09:01:41.587Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
ts=2022-12-26T09:01:41.587Z caller=main.go:540 level=info build_context="(go=go1.18.6, user=root@3caaaea7ba87, date=20220912-12:42:39)"
ts=2022-12-26T09:01:41.587Z caller=main.go:541 level=info host_details="(Linux 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 VM-w74kL45FBUad (none))"
ts=2022-12-26T09:01:41.587Z caller=main.go:542 level=info fd_limits="(soft=32768, hard=32768)"
ts=2022-12-26T09:01:41.587Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2022-12-26T09:01:41.589Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:9090
ts=2022-12-26T09:01:41.591Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669477299473 maxt=1669507200000 ulid=01GJVQ9TDA29T0FBAXFTEV17XD
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669507200000 maxt=1669701600000 ulid=01GK19VCXVDFH9739B3VBX8JBJ
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669701619217 maxt=1669896000000 ulid=01GK7A3QZ3RTPQ4F0TS4DXT2XW
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669896019217 maxt=1670090400000 ulid=01GKD3GBQYHGFTGGBJNDTKRTTS
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670090419217 maxt=1670284800000 ulid=01GKJWWZDR5B0JDXQPEWDANV34
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670284800000 maxt=1670479200000 ulid=01GKRFDVVMFD0NEBGNP4TKYFDJ
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670479219217 maxt=1670673600000 ulid=01GKYFP6ZDEPXG34EXC1KD5M1C
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670673619217 maxt=1670868000000 ulid=01GM492TQJR5FMWRXQAY904EBP
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670868019217 maxt=1671062400000 ulid=01GMA2FERF19HNW89P4TCHAMSF
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671062419217 maxt=1671256800000 ulid=01GMFVVVVE0BEJ5VY762FTPZZW
ts=2022-12-26T09:01:41.592Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671256819217 maxt=1671451200000 ulid=01GMNN8P0AFPEAXYJDRBK4641F
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671451219217 maxt=1671645600000 ulid=01GMVEN9RETHAZDJ030K5VDC94
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671645619217 maxt=1671840000000 ulid=01GN181XFYP0958QXN6QM2DVDP
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671840019217 maxt=1671904800000 ulid=01GN35VEP2R862MBFBVK5FVPCJ
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671904819217 maxt=1671926400000 ulid=01GN3TEMBW0C4VSP208WVBC1NF
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671948019217 maxt=1671955200000 ulid=01GN4862SGJYC8QMJEQB682THV
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671955219217 maxt=1671962400000 ulid=01GN4F1T1GRJDZVN6JBWNMVSBE
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671926419217 maxt=1671948000000 ulid=01GN4F1T48KV0P0YTG0P25E38B
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671962419217 maxt=1671969600000 ulid=01GN4NXH9GH44GM538GFDB2YN2
ts=2022-12-26T09:01:41.594Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671969619217 maxt=1671976800000 ulid=01GN4WS8HGG1K748G3T3MKHAMH
ts=2022-12-26T09:01:41.594Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2022-12-26T09:01:41.825Z caller=main.go:831 level=info msg="Stopping scrape discovery manager..."
ts=2022-12-26T09:01:41.825Z caller=main.go:845 level=info msg="Stopping notify discovery manager..."
ts=2022-12-26T09:01:41.825Z caller=manager.go:955 level=info component="rule manager" msg="Stopping rule manager..."
ts=2022-12-26T09:01:41.826Z caller=manager.go:965 level=info component="rule manager" msg="Rule manager stopped"
ts=2022-12-26T09:01:41.826Z caller=main.go:882 level=info msg="Stopping scrape manager..."
ts=2022-12-26T09:01:41.826Z caller=main.go:841 level=info msg="Notify discovery manager stopped"
ts=2022-12-26T09:01:41.839Z caller=main.go:827 level=info msg="Scrape discovery manager stopped"
ts=2022-12-26T09:01:41.844Z caller=notifier.go:608 level=info component=notifier msg="Stopping notification manager..."
ts=2022-12-26T09:01:41.844Z caller=main.go:1103 level=info msg="Notifier manager stopped"
ts=2022-12-26T09:01:41.844Z caller=main.go:874 level=info msg="Scrape manager stopped"
ts=2022-12-26T09:01:41.844Z caller=manager.go:941 level=info component="rule manager" msg="Starting rule manager..."
ts=2022-12-26T09:01:41.844Z caller=main.go:1112 level=error err="opening storage failed: /opt/outline/persisted-state/prometheus/data/chunks_head/000322: invalid magic number 0"
E2022-12-26T09:01:41.858Z 12 main.js:102] Prometheus has exited with error. Code: 1, Signal: null
E2022-12-26T09:01:41.858Z 12 main.js:102] Restarting Prometheus...
I2022-12-26T09:01:41.858Z 12 main.js:102] ======== Starting Prometheus ========
I2022-12-26T09:01:41.858Z 12 main.js:102] /opt/outline-server/bin/prometheus "--config.file" "/opt/outline/persisted-state/prometheus/config.yml" "--web.enable-admin-api" "--storage.tsdb.retention.time" "31d" "--storage.tsdb.path" "/opt/outline/persisted-state/prometheus/data" "--web.listen-address" "127.0.0.1:9090" "--log.level" "info"
ts=2022-12-26T09:01:41.934Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
ts=2022-12-26T09:01:41.934Z caller=main.go:540 level=info build_context="(go=go1.18.6, user=root@3caaaea7ba87, date=20220912-12:42:39)"
ts=2022-12-26T09:01:41.934Z caller=main.go:541 level=info host_details="(Linux 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 VM-w74kL45FBUad (none))"
ts=2022-12-26T09:01:41.934Z caller=main.go:542 level=info fd_limits="(soft=32768, hard=32768)"
ts=2022-12-26T09:01:41.934Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2022-12-26T09:01:41.936Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:9090
ts=2022-12-26T09:01:41.942Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669477299473 maxt=1669507200000 ulid=01GJVQ9TDA29T0FBAXFTEV17XD
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669507200000 maxt=1669701600000 ulid=01GK19VCXVDFH9739B3VBX8JBJ
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669701619217 maxt=1669896000000 ulid=01GK7A3QZ3RTPQ4F0TS4DXT2XW
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1669896019217 maxt=1670090400000 ulid=01GKD3GBQYHGFTGGBJNDTKRTTS
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670090419217 maxt=1670284800000 ulid=01GKJWWZDR5B0JDXQPEWDANV34
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670284800000 maxt=1670479200000 ulid=01GKRFDVVMFD0NEBGNP4TKYFDJ
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670479219217 maxt=1670673600000 ulid=01GKYFP6ZDEPXG34EXC1KD5M1C
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670673619217 maxt=1670868000000 ulid=01GM492TQJR5FMWRXQAY904EBP
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1670868019217 maxt=1671062400000 ulid=01GMA2FERF19HNW89P4TCHAMSF
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671062419217 maxt=1671256800000 ulid=01GMFVVVVE0BEJ5VY762FTPZZW
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671256819217 maxt=1671451200000 ulid=01GMNN8P0AFPEAXYJDRBK4641F
ts=2022-12-26T09:01:41.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671451219217 maxt=1671645600000 ulid=01GMVEN9RETHAZDJ030K5VDC94
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671645619217 maxt=1671840000000 ulid=01GN181XFYP0958QXN6QM2DVDP
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671840019217 maxt=1671904800000 ulid=01GN35VEP2R862MBFBVK5FVPCJ
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671904819217 maxt=1671926400000 ulid=01GN3TEMBW0C4VSP208WVBC1NF
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671948019217 maxt=1671955200000 ulid=01GN4862SGJYC8QMJEQB682THV
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671955219217 maxt=1671962400000 ulid=01GN4F1T1GRJDZVN6JBWNMVSBE
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671926419217 maxt=1671948000000 ulid=01GN4F1T48KV0P0YTG0P25E38B
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671962419217 maxt=1671969600000 ulid=01GN4NXH9GH44GM538GFDB2YN2
ts=2022-12-26T09:01:41.943Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671969619217 maxt=1671976800000 ulid=01GN4WS8HGG1K748G3T3MKHAMH
ts=2022-12-26T09:01:41.971Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false

**Comment by fortuna** [comment]
It seems the relevant part is:
```
ts=2022-12-26T09:01:41.844Z caller=main.go:1112 level=error err="opening storage failed: /opt/outline/persisted-state/prometheus/data/chunks_head/000322: invalid magic number 0"
E2022-12-26T09:01:41.858Z 12 main.js:102] Prometheus has exited with error. Code: 1, Signal: null
```

The Prometheus data got corrupted somehow.

But in the rest of the logs it looks like it started successfully? Did you get any more errors after that?

**Comment by mikeozornin** [comment]
I have to migrate my server to some newer backed at my hosting provider and after reinstalling outline I got the same issue.

```
I2023-01-26T15:34:09.851Z 12 main.js:102] ======== Starting Prometheus ========
I2023-01-26T15:34:09.851Z 12 main.js:102] /opt/outline-server/bin/prometheus "--config.file" "/opt/outline/persisted-state/prometheus/config.yml" "--web.enable-admin-api" "--storage.tsdb.retention.time" "31d" "--storage.tsdb.path" "/opt/outline/persisted-state/prometheus/data" "--web.listen-address" "127.0.0.1:9090" "--log.level" "info"
ts=2023-01-26T15:34:09.935Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
ts=2023-01-26T15:34:09.936Z caller=main.go:540 level=info build_context="(go=go1.18.6, user=root@3caaaea7ba87, date=20220912-12:42:39)"
ts=2023-01-26T15:34:09.936Z caller=main.go:541 level=info host_details="(Linux 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 mikeozornin (none))"
ts=2023-01-26T15:34:09.937Z caller=main.go:542 level=info fd_limits="(soft=32768, hard=32768)"
ts=2023-01-26T15:34:09.937Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-01-26T15:34:09.939Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:9090
ts=2023-01-26T15:34:09.940Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672034411354 maxt=1672228800000 ulid=01GNCTVMFQSTDQXCBSGEBWT599
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672228811354 maxt=1672423200000 ulid=01GNJM88KK364GQM31RQTSXQW0
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672423211354 maxt=1672617600000 ulid=01GNRDMW6AF8Q438WPV23CFPYZ
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672617611354 maxt=1672812000000 ulid=01GNY71FQXADXMYZGTMGP4BBYP
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672812011354 maxt=1673006400000 ulid=01GP40E3EGE22WAF6Q7NXZ01TC
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673006411354 maxt=1673200800000 ulid=01GP9STQMW1P135349RPCDB38A
ts=2023-01-26T15:34:09.941Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673200811354 maxt=1673395200000 ulid=01GPFK7B0XH67GCJNNZQQDXPDC
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673395211354 maxt=1673589600000 ulid=01GPNCKYSPQZE0HBV2JJZA8MTT
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673589611354 maxt=1673784000000 ulid=01GPV60JFAMS9A8B9KY9RCYA4R
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673784011354 maxt=1673978400000 ulid=01GQ0ZD6G670R8D3PV8YR1QRCR
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673978411354 maxt=1674172800000 ulid=01GQ6RSSYSVRMVDYC7FE65VJX6
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674172811354 maxt=1674367200000 ulid=01GQCJ6DQQQAB2HBGCMF6840X0
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674367211354 maxt=1674561600000 ulid=01GQJBK1GP1AH04AJB2GM2W370
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674561611354 maxt=1674626400000 ulid=01GQM9CJN44SP3GJXBEWBMVZSW
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674691211356 maxt=1674698400000 ulid=01GQP0ACE3NNDGZZDYQJ7VH5EM
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674698400000 maxt=1674705600000 ulid=01GQP7567137NZNFP4C5TAG517
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674626411354 maxt=1674691200000 ulid=01GQP756E3ZQC84QK7NHWNXKR9
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674705611354 maxt=1674712800000 ulid=01GQPE1TY8ND0ZDJE984ZNW7GB
ts=2023-01-26T15:34:09.942Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674712800000 maxt=1674720000000 ulid=01GQPND426DMSKDHGEJVA5PJ7X
ts=2023-01-26T15:34:09.972Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2023-01-26T15:34:10.544Z caller=main.go:831 level=info msg="Stopping scrape discovery manager..."
ts=2023-01-26T15:34:10.544Z caller=main.go:845 level=info msg="Stopping notify discovery manager..."
ts=2023-01-26T15:34:10.544Z caller=manager.go:955 level=info component="rule manager" msg="Stopping rule manager..."
ts=2023-01-26T15:34:10.544Z caller=manager.go:965 level=info component="rule manager" msg="Rule manager stopped"
ts=2023-01-26T15:34:10.544Z caller=main.go:882 level=info msg="Stopping scrape manager..."
ts=2023-01-26T15:34:10.544Z caller=main.go:841 level=info msg="Notify discovery manager stopped"
ts=2023-01-26T15:34:10.572Z caller=main.go:827 level=info msg="Scrape discovery manager stopped"
ts=2023-01-26T15:34:10.572Z caller=notifier.go:608 level=info component=notifier msg="Stopping notification manager..."
ts=2023-01-26T15:34:10.572Z caller=main.go:1103 level=info msg="Notifier manager stopped"
ts=2023-01-26T15:34:10.573Z caller=main.go:874 level=info msg="Scrape manager stopped"
ts=2023-01-26T15:34:10.573Z caller=manager.go:941 level=info component="rule manager" msg="Starting rule manager..."
ts=2023-01-26T15:34:10.587Z caller=main.go:1112 level=error err="opening storage failed: /opt/outline/persisted-state/prometheus/data/chunks_head/000707: invalid magic number 0"
E2023-01-26T15:34:10.612Z 12 main.js:102] Prometheus has exited with error. Code: 1, Signal: null
E2023-01-26T15:34:10.612Z 12 main.js:102] Restarting Prometheus...
I2023-01-26T15:34:10.613Z 12 main.js:102] ======== Starting Prometheus ========
I2023-01-26T15:34:10.614Z 12 main.js:102] /opt/outline-server/bin/prometheus "--config.file" "/opt/outline/persisted-state/prometheus/config.yml" "--web.enable-admin-api" "--storage.tsdb.retention.time" "31d" "--storage.tsdb.path" "/opt/outline/persisted-state/prometheus/data" "--web.listen-address" "127.0.0.1:9090" "--log.level" "info"
ts=2023-01-26T15:34:10.717Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
ts=2023-01-26T15:34:10.717Z caller=main.go:540 level=info build_context="(go=go1.18.6, user=root@3caaaea7ba87, date=20220912-12:42:39)"
ts=2023-01-26T15:34:10.718Z caller=main.go:541 level=info host_details="(Linux 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 mikeozornin (none))"
ts=2023-01-26T15:34:10.718Z caller=main.go:542 level=info fd_limits="(soft=32768, hard=32768)"
ts=2023-01-26T15:34:10.718Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-01-26T15:34:10.726Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:9090
ts=2023-01-26T15:34:10.726Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672034411354 maxt=1672228800000 ulid=01GNCTVMFQSTDQXCBSGEBWT599
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672228811354 maxt=1672423200000 ulid=01GNJM88KK364GQM31RQTSXQW0
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672423211354 maxt=1672617600000 ulid=01GNRDMW6AF8Q438WPV23CFPYZ
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672617611354 maxt=1672812000000 ulid=01GNY71FQXADXMYZGTMGP4BBYP
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672812011354 maxt=1673006400000 ulid=01GP40E3EGE22WAF6Q7NXZ01TC
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673006411354 maxt=1673200800000 ulid=01GP9STQMW1P135349RPCDB38A
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673200811354 maxt=1673395200000 ulid=01GPFK7B0XH67GCJNNZQQDXPDC
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673395211354 maxt=1673589600000 ulid=01GPNCKYSPQZE0HBV2JJZA8MTT
ts=2023-01-26T15:34:10.727Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673589611354 maxt=1673784000000 ulid=01GPV60JFAMS9A8B9KY9RCYA4R
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673784011354 maxt=1673978400000 ulid=01GQ0ZD6G670R8D3PV8YR1QRCR
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673978411354 maxt=1674172800000 ulid=01GQ6RSSYSVRMVDYC7FE65VJX6
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674172811354 maxt=1674367200000 ulid=01GQCJ6DQQQAB2HBGCMF6840X0
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674367211354 maxt=1674561600000 ulid=01GQJBK1GP1AH04AJB2GM2W370
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674561611354 maxt=1674626400000 ulid=01GQM9CJN44SP3GJXBEWBMVZSW
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674691211356 maxt=1674698400000 ulid=01GQP0ACE3NNDGZZDYQJ7VH5EM
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674698400000 maxt=1674705600000 ulid=01GQP7567137NZNFP4C5TAG517
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674626411354 maxt=1674691200000 ulid=01GQP756E3ZQC84QK7NHWNXKR9
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674705611354 maxt=1674712800000 ulid=01GQPE1TY8ND0ZDJE984ZNW7GB
ts=2023-01-26T15:34:10.728Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1674712800000 maxt=1674720000000 ulid=01GQPND426DMSKDHGEJVA5PJ7X
ts=2023-01-26T15:34:10.752Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2023-01-26T15:34:11.414Z caller=main.go:831 level=info msg="Stopping scrape discovery manager..."
ts=2023-01-26T15:34:11.415Z caller=main.go:845 level=info msg="Stopping notify discovery manager..."
ts=2023-01-26T15:34:11.415Z caller=manager.go:955 level=info component="rule manager" msg="Stopping rule manager..."
ts=2023-01-26T15:34:11.415Z caller=manager.go:965 level=info component="rule manager" msg="Rule manager stopped"
ts=2023-01-26T15:34:11.415Z caller=main.go:882 level=info msg="Stopping scrape manager..."
ts=2023-01-26T15:34:11.416Z caller=main.go:841 level=info msg="Notify discovery manager stopped"
ts=2023-01-26T15:34:11.419Z caller=main.go:827 level=info msg="Scrape discovery manager stopped"
ts=2023-01-26T15:34:11.419Z caller=notifier.go:608 level=info component=notifier msg="Stopping notification manager..."
ts=2023-01-26T15:34:11.419Z caller=main.go:1103 level=info msg="Notifier manager stopped"
ts=2023-01-26T15:34:11.420Z caller=main.go:874 level=info msg="Scrape manager stopped"
ts=2023-01-26T15:34:11.420Z caller=manager.go:941 level=info component="rule manager" msg="Starting rule manager..."
ts=2023-01-26T15:34:11.420Z caller=main.go:1112 level=error err="opening storage failed: /opt/outline/persisted-state/prometheus/data/chunks_head/000707: invalid magic number 0"
E2023-01-26T15:34:11.424Z 12 main.js:102] Prometheus has exited with error. Code: 1, Signal: null
E2023-01-26T15:34:11.424Z 12 main.js:102] Restarting Prometheus…
```

**Comment by McContax** [comment]
@fortuna I deleted /opt/outline/persisted-state/prometheus/data and everything works well again. I google Prometheus. Some people(using Prometheus but did not use outline before) have same problems. It seems that the Prometheus does not support NFS.

https://stackoverflow.com/questions/58106982/prometheus-and-nfs-storage

“As per prometheus storage.md , the recommendation is not to use nfs storage as persistent volume for prometheus.”
