### ISSUE TITLE
"IP" showing Outline Manager location instead of server location

### ISSUE THREAD

**Issue by BehdadEs** [Jigsaw-Code/outline-server#126]
hey guys,
today I just ran outline on my linux (ubuntu) server and ran outline manager on my personal computer.
And everything is going well and I can pass my country's censorship but there's a huge problem here.
My server is in Germany, whenever I connect to outline my ip changes to my server's IP but it shows outline manager location which in this case my personal location.
Here's a example:

> IPv4: blah blah blah
> IPv6: Not detected
> My IP Information:
> ISP:  Hetzner Online GmbH
> City:  blah blah
> Region:  blah blah 
> **Country**:  **Iran** 

as you can see it shows my country not Germany!
why this is happening?

**Comment by trevj** [comment]
@BehdadEs Thanks for trying Outline! Can I ask two questions:
- on which platform are you running the client?
- what software you are using to produce that output?

**Comment by alalamav** [comment]
@BehdadEs, thanks for following up. Have you allowed https://whatismyipaddress.com to access location services? If so, that may explain why you see the server's IP but your current location. It is also possible that the site is caching your location, if you visited it without a proxy.

**Comment by BehdadEs** [comment]
@alalamav I cleared my cache and denied location access to that website still it shows my country 
I even tried another browser (Edge) and it shows my country 
I don't why

**Comment by trevj** [comment]
@BehdadEs  Going to close due to inactivity, apologies for the very slow response. If you'd like to continue this discussion, please do re-open this issue.

**Comment by bajpangosh** [comment]
> @BehdadEs Thanks for trying Outline! Can I ask two questions:
> 
> * on which platform are you running the client?
> * what software you are using to produce that output?

i found same issue, with hetzner cloud. 
ubuntu 18.04
location Germany but while accessing to myip.ms it shows india. no issues with digitalocean please take a look
