### ISSUE TITLE
dns_probe_finished_no_internet (AWS Lightsail+Outline)

### ISSUE THREAD

**Issue by Mollyness** [Jigsaw-Code/outline-server#1262]
Hi everyone! I use for a VPN AWS Lightsail server + Outline client, but today I faced with a connection problem.

When i'm trying to connect to any website, after a few minutes I see this error "**dns_probe_finished_no_internet**" (Windows 10/Chrome)? The server on AWS Lightsail (Ubuntu 20.04 LTS) works correctly, no errors, as I see. But the traffic doesn't go through, even though the Outline itself shows no errors and says the connection is set. I've tried changing the server location, creating a new instance, clearing the cache (everywhere where it's possible) and changing/restarting various dns settings, turned off any antivirus apps and etc. But nothing helped. And at the same time on my phone (iOS) the same server works fine and traffic passes through (I use outline on my phone too).

My provider says that nothing has been changed recently and ports should be allowed (I live in Russia).

Every solution, that i've found on internet didn't work out for me. Please, maybe someone faced with simmilar problem and know a solution?

The only clue that I have is this message on my server, that i attached below.

Thanks for any help in advance!

![ubuntu2](https://user-images.githubusercontent.com/122060973/210895533-71adf866-1d02-4f58-ab69-25ed00d7a73e.PNG)

**Comment by Alfick** [comment]
thx for sharing bro<3!
