### ISSUE TITLE
metrics/transfer api not working and prometheus takes too much resource

### ISSUE THREAD

**Issue by Simplici** [Jigsaw-Code/outline-server#1267]
Hello,

I have an issue with the statistic on data transfer.
It works correctly before, but from today morning, the transfers doesn't display on Outline Manage, and the metrics/transfer api is not responding.

there are following error in log:

`unhandledRejection: Error: Failed to query prometheus API: Error: socket hang up
    at ClientRequest.<anonymous> (/opt/outline-server/app/main.js:102:9095)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:518:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
E2023-01-12T07:45:46.383Z 12 main.js:33] unhandledRejection: Error: Failed to query prometheus API: Error: socket hang up
    at ClientRequest.<anonymous> (/opt/outline-server/app/main.js:102:9095)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:518:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
E2023-01-12T07:45:46.383Z 12 main.js:102] Error: Failed to query prometheus API: Error: socket hang up
E2023-01-12T07:45:46.384Z 12 main.js:102] Error: Failed to query prometheus API: Error: socket hang up
E2023-01-12T07:45:46.385Z 12 main.js:102] Error: Failed to query prometheus API: Error: socket hang up
E2023-01-12T07:45:46.386Z 12 main.js:102] Error: Failed to query prometheus API: Error: read ECONNRESET
E2023-01-12T07:45:46.386Z 12 main.js:102] Error: Failed to query prometheus API: Error: socket hang up
E2023-01-12T07:45:46.393Z 12 main.js:33] unhandledRejection: Error: Failed to query prometheus API: Error: socket hang up
    at ClientRequest.<anonymous> (/opt/outline-server/app/main.js:102:9095)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:518:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
E2023-01-12T07:45:46.394Z 12 main.js:102] Prometheus has exited with error. Code: null, Signal: SIGKILL
E2023-01-12T07:45:46.394Z 12 main.js:102] Restarting Prometheus...
`
`
I2023-01-16T08:08:10.684Z 12 main.js:102] ======== Starting Prometheus ========
I2023-01-16T08:08:10.685Z 12 main.js:102] /opt/outline-server/bin/prometheus "--config.file" "/opt/outline/persisted-state/prometheus/config.yml" "--web.enable-admin-api" "--storage.tsdb.retention.time" "31d" "--storage.tsdb.path" "/opt/outline/persisted-state/prometheus/data" "--web.listen-address" "127.0.0.1:9090" "--log.level" "info"
ts=2023-01-16T08:08:12.192Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
ts=2023-01-16T08:08:12.262Z caller=main.go:540 level=info build_context="(go=go1.18.6, user=root@3caaaea7ba87, date=20220912-12:42:39)"
ts=2023-01-16T08:08:12.262Z caller=main.go:541 level=info host_details="(Linux 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 CVM38582 (none))"
ts=2023-01-16T08:08:12.262Z caller=main.go:542 level=info fd_limits="(soft=32768, hard=32768)"
ts=2023-01-16T08:08:12.262Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-01-16T08:08:12.265Z caller=query_logger.go:80 level=info component=activeQueryTracker msg="These queries didn't finish in prometheus' last run:" queries="[{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854844},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854849},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854908},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854933},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854938},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673854969},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673855028},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673855029},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673855088},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673856456},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673856456},{\"query\":\"sum(increase(shadowsocks_data_bytes{dir=~\\\"c\\u003cp|p\\u003et\\\"}[720h])) by (access_key)\",\"timestamp_sec\":1673856464}]"
ts=2023-01-16T08:08:12.277Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:9090
ts=2023-01-16T08:08:12.284Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2023-01-16T08:08:12.370Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2023-01-16T08:08:12.376Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671062400254 maxt=1671256800000 ulid=01GMFVVC2HTC0RAMPJNGD392T6
ts=2023-01-16T08:08:12.378Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671256801756 maxt=1671451200000 ulid=01GMNN81G2FY1YK2M1YNQQWTPJ
ts=2023-01-16T08:08:12.390Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671451201756 maxt=1671645600000 ulid=01GMVEMKWNV2QC2AWMQVW09GCW
ts=2023-01-16T08:08:12.392Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671645601756 maxt=1671840000000 ulid=01GN181FD3CRRNQC5JM052NQZR
ts=2023-01-16T08:08:12.472Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1671840001760 maxt=1672034400000 ulid=01GN71E3XXD02W7HV8PFZXTKJT
ts=2023-01-16T08:08:12.474Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672034400447 maxt=1672228800000 ulid=01GNCTTHG4MM589D3TT5SHM9Z9
ts=2023-01-16T08:08:12.475Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672228801798 maxt=1672423200000 ulid=01GNJM7B9MHNVQ1MJZJC8B064Y
ts=2023-01-16T08:08:12.477Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672423201756 maxt=1672617600000 ulid=01GNRDM065KS4N7ZQBCQ692033
ts=2023-01-16T08:08:12.478Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672617601756 maxt=1672812000000 ulid=01GNY70M33MVXEV5VJ4N1WZ90V
ts=2023-01-16T08:08:12.479Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1672812001793 maxt=1673006400000 ulid=01GP40D9FSSTMY68GY5HVJYEH6
ts=2023-01-16T08:08:12.482Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673006401517 maxt=1673200800000 ulid=01GP9SSW4GDK4J95W55Z9M9CPG
ts=2023-01-16T08:08:12.485Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673200801756 maxt=1673395200000 ulid=01GPFK6HHB5349JYZPKPQT4W4Q
ts=2023-01-16T08:08:12.487Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673395201756 maxt=1673589600000 ulid=01GPNCJS0HJ6TJ1KHKMT1RNK7C
ts=2023-01-16T08:08:12.488Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673589601756 maxt=1673784000000 ulid=01GPV5ZNZA1CBY5V2WPEG36B3H
ts=2023-01-16T08:08:12.489Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673784001756 maxt=1673805600000 ulid=01GPVTJSFG6X5ZVTEYQRNJ96GM
ts=2023-01-16T08:08:12.492Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673827201756 maxt=1673834400000 ulid=01GPW8A7DGHB6K0Y0HFJC6WAXS
ts=2023-01-16T08:08:12.493Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673834401756 maxt=1673841600000 ulid=01GPWF5PY2SKJ5X0MV0HERAWEP
ts=2023-01-16T08:08:12.562Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673805601756 maxt=1673827200000 ulid=01GPWF5V40MM9FG1EA5MFDQ4H2
ts=2023-01-16T08:08:12.564Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673841600000 maxt=1673848800000 ulid=01GPWP1E5FNV8K52568K9AMWKN
ts=2023-01-16T08:08:12.567Z caller=dir_locker.go:77 level=warn component=tsdb msg="A lockfile from a previous execution already existed. It was replaced" file=/opt/outline/persisted-state/prometheus/data/lock
ts=2023-01-16T08:08:12.888Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-01-16T08:08:12.890Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=153.391µs
ts=2023-01-16T08:08:12.891Z caller=head.go:542 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-01-16T08:08:13.876Z caller=head.go:578 level=info component=tsdb msg="WAL checkpoint loaded"
ts=2023-01-16T08:08:15.675Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=776 maxSegment=780
ts=2023-01-16T08:08:16.682Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=777 maxSegment=780
ts=2023-01-16T08:08:17.671Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=778 maxSegment=780
ts=2023-01-16T08:08:18.689Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=779 maxSegment=780
ts=2023-01-16T08:08:18.691Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=780 maxSegment=780
ts=2023-01-16T08:08:18.692Z caller=head.go:619 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=986.509312ms wal_replay_duration=4.813202746s total_replay_duration=5.801818029s
ts=2023-01-16T08:08:18.790Z caller=main.go:993 level=info fs_type=EXT4_SUPER_MAGIC
ts=2023-01-16T08:08:18.863Z caller=main.go:996 level=info msg="TSDB started"
ts=2023-01-16T08:08:18.877Z caller=main.go:1177 level=info msg="Loading configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
ts=2023-01-16T08:08:18.881Z caller=main.go:1214 level=info msg="Completed loading of configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml totalDuration=4.279869ms db_storage=7.654µs remote_storage=26.451µs web_handler=6.931µs query_engine=7.935µs scrape=1.39318ms scrape_sd=262.446µs notify=44.757µs notify_sd=8.639µs rules=17.696µs tracing=196.368µs
ts=2023-01-16T08:08:18.882Z caller=main.go:957 level=info msg="Server is ready to receive web requests."
ts=2023-01-16T08:08:18.883Z caller=manager.go:941 level=info component="rule manager" msg="Starting rule manager..."
I2023-01-16T08:08:19.804Z 12 main.js:102] Prometheus is ready!
I2023-01-16T08:08:20.089Z 12 main.js:33] Manager listening at https://[::]:80/6pHWKbl_GOZ0VoI3LHmGBg
(node:12) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
I2023-01-16T08:09:06.389Z 12 main.js:102] ======== Starting Outline Shadowsocks Service ========
I2023-01-16T08:09:06.391Z 12 main.js:102] /opt/outline-server/bin/outline-ss-server "-config" "/opt/outline/persisted-state/outline-ss-server/config.yml" "-metrics" "127.0.0.1:9092" "-ip_country_db" "/var/lib/libmaxminddb/ip-country.mmdb" "--replay_history=10000"
I2023-01-16T08:09:06.894Z 30 server.go:254] Metrics on http://127.0.0.1:9092/metrics
I2023-01-16T08:09:06.965Z 30 server.go:260] Using IP-Country database at /var/lib/libmaxminddb/ip-country.mmdb
I2023-01-16T08:09:06.988Z 30 server.go:86] Listening TCP and UDP on port 443
I2023-01-16T08:09:06.989Z 30 server.go:154] Loaded 105 access keys
I2023-01-16T08:09:16.785Z 30 server.go:185] Updating config
I2023-01-16T08:09:16.872Z 30 server.go:154] Loaded 106 access keys
E2023-01-16T08:11:59.586Z 12 main.js:102] Failed to enforce access key limits: Error: Got error 503
I2023-01-16T08:11:59.983Z 30 server.go:185] Updating config
I2023-01-16T08:12:00.169Z 30 server.go:154] Loaded 106 access keys
E2023-01-16T08:13:18.094Z 12 main.js:33] unhandledRejection: Error: Got error 503
    at ClientRequest.<anonymous> (/opt/outline-server/app/main.js:102:8860)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
E2023-01-16T08:13:21.969Z 12 main.js:33] unhandledRejection: Error: Got error 503
    at ClientRequest.<anonymous> (/opt/outline-server/app/main.js:102:8860)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
`
at the same time, prometheus is using much memory and CPU. in the final, server run out of memory.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by ch3rrydrunk** [comment]
Having the same issue
