### ISSUE TITLE
Cancel update of Outline Manager

### ISSUE THREAD

**Issue by Joy096** [Jigsaw-Code/outline-server#1270]
In previous versions of Outline Manager for Windows I could generate an Invite Link for every key, and it was very useful. In the last version of Outline Manager I can't do that. 
When I install a previous versions it goes automatically update to the last version. 
How can I stop the automatically update? Thx.

**Comment by nic11** [comment]
For Linux AppImage I worked around that by setting directory permissions to r-x (revoking write access), so that it wouldn't be able to replace AppImage with the new version

**Comment by timorpheus** [comment]
I have the same issue, I need to generate Invite links, and for now the only solution is to keep the Outline running, and if I have to restart, uninstall and install the previous version. Can someone please tell me how to turn access links into old style (s3.amazonaws...) install links?
