### ISSUE TITLE
How to get Outline apiUri and certSha256 output once again?

### ISSUE THREAD

**Issue by shumtravi** [Jigsaw-Code/outline-server#1274]
I want to connect outline server to another outline manager instance on different OS. How can i get certSha256 from server console without reinstallation?

**Comment by murka** [comment]
@shumtravi, the access credentials stored on `/opt/outline/access.txt`, if you not change volume store on docker.
So, you can use command `cat /opt/outline/access.txt` for get apiUrl and certSha256.

**Comment by maddyhof** [comment]
Marking as a feature request for the ability to export server information from one Manager instance and import it into another.

**Comment by maddyhof** [comment]
Closing as duplicate of #1223

**Comment by oruchkin** [comment]
Worked for me from `macbook` to `macbook`
you need to transfer
```shell
~/Library/Application Support/Outline Manager
```
