### ISSUE TITLE
Custom password in API

### ISSUE THREAD

**Issue by miladrahimi** [Jigsaw-Code/outline-server#1282]
Is there any way to set a custom password for users through the APIs?
I want to set up Outline on multiple servers behind a load balancer (HA Proxy). To do so, I need to be able to set the same users and passwords on the upstream servers.

**Comment by arashammm** [comment]
Can you elaborate more about your setup?

**Comment by miladrahimi** [comment]
This is the server architecture I'm working on:
```
                                   /---> (Outline Server 1)
(Outline client) ---> (HA Proxy) -|
                                   \---> (Outline Server 2)
```
HA Proxy selects Outline servers randomly (round-robin), I need to have the same users (passwords) on both servers. There is an API for creating new access keys API but it doesn't accept the password parameter.

**Comment by whoami-idk** [comment]
@miladrahimi بدون این قابلیت هم فکر میکنم شدنی باشه پیاده سازیش.

**Comment by miladrahimi** [comment]
@whoami-idk could you explain how can we implement it without this feature? I've already handled it with a script that syncs the `/opt/outline/persisted-state/shadowbox_config.json` files between servers which obviously not a clean way!

**Comment by whoami-idk** [comment]
@miladrahimi 
راه حل خودت به نظرم در شرایط فعلی ایده آله.
اما اگر میخوای فنی تر با قضیه برخورد کنی،با قابلیت dynamic keys میتونی انجامش بدی.

https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/

بجای اینکه مستقیما کلید اتصال(استاتیک) رو به کاربر بدی،یک signed URL بهش بده که نقش API رو داره و کلید رو برای کاربر میسازه.
توی بک اند میتونی تصمیم بگیری که درخواست جاری به کدوم سرور و یا پورتی متصل بشه. یا حتی تاریخ انقضا واسشون در نظر بگیری.
با یکم دیتابیس و ردیس هم میتونی بهینه سازیش کنی.

و دیگه پسورد و یا آدرس سرور،پورت و.. مهم نیست. چون خودت توی بک اند هر لحظه میتونی کنترل و یا تغییرشون بدی، بدون اینکه کاربر نیازی به تغییر کلیدی که توی کلاینت ثبت کرده،داشته باشه.

**Comment by miladrahimi** [comment]
خیلی فیچر جالبی بود، کلا اینجوری بهش فکر نکرده بودم، اون سرور ssconf می‌تونه نقش لودبالانسر هم داشته باشه که البته جای انتقال ترافیک، کاربر رو به سرور شادوساکس هدایت کنه، یعنی خروجیش حتی بهتر از لودبالانسری مثل HA Proxy و NGINX میشه.
خیلی لطف کردی @whoami-idk

**Comment by whoami-idk** [comment]
@miladrahimi 
بله دقیقا.
بجای پروکسی کردن ترافیک به نودها با لود بالانسر،میتونید کاربر رو مستقیما به سرور خلوت متصل کنید.

**Comment by miladrahimi** [comment]
@maddyhof How long does it take to release it officially?

**Comment by sobhan-m94** [comment]
@miladrahimi مگه با ssconf کارت راه نیوفتاد ؟

**Comment by miladrahimi** [comment]
@sobhan-m94 آره دارم ازش استفاده میکنم  و خیلی عالیه، این مورد رو میخوام واسه اینکه قصد دارم یه پنل وب درست کنم برای اوتلاین که نیازی به نصب نرم افزار نباشه.

**Comment by sobhan-m94** [comment]
@miladrahimi من خودم کلید با رمز دلخواه رو پیاده کردم ولی به نظرم،کلید داینامیک یا همون ssconf مناسب تره.

**Comment by miladrahimi** [comment]
@maddyhof Actually you've closed this topic as "completed". I didn't find any related updates on the master branch. I wanted to know if have you implemented it and if can we expect it on the next release.

**Comment by maddyhof** [comment]
Ah, sorry for the confusion. I closed the ticket because it seemed your request was resolved and you had what you needed. If you need something else, please feel free to open a new issue as a feature request.
