### ISSUE TITLE
The API does not work to limit traffic, for example, to 1 megabyte for a specific key

### ISSUE THREAD

**Issue by BokDan93** [Jigsaw-Code/outline-server#1289]
Hello, I have already tried all possible options. Through sending cURL, traffic is not limited. The following errors are returned:

curl -X PUT -H 'Content-Type: application/json' -d '{"limit": {"bytes": 1000}}' $OUTLINE_MANAGMENT_API_URL/access-keys/0/data-limit --insecure

![image](https://user-images.githubusercontent.com/33230005/218251237-ca71eb51-3825-483f-a69c-c0b7d6cf9e39.png)

curl -v --insecure -X PUT -H "Content-Type: application/json" -d "{"limit": {"bytes": 1000}}" $OUTLINE_MANAGMENT_API_URL/access-keys/0/data-limit

Error console:
{"code":"InvalidContent","message":"Invalid JSON: Unexpected token l in JSON at position 1"}* Connection #0 to host 111.111.11.111 left intact

**Comment by fortuna** [comment]
There's something wrong with your curl command, it thinks "application"is the host. I think the error came from a different command.

The quoting in the second command is wrong. The `"` needs to be quoted.
