### ISSUE TITLE
DigitalOcean Setup Issue

### ISSUE THREAD

**Issue by cravend** [Jigsaw-Code/outline-server#13]
I'm trying to install Jigsaw on a DigitalOcean Droplet. I used a one-click app that automatically installed Docker on Ubuntu 16.04. I downloaded the AppImage from the website and made it executable. However, whenever I try running it, I get the following error: ```desktop-file-install is missing. Skipping /tmp/.mount_OutlinVFcf6r/AppRun.
/tmp/.mount_OutlinVFcf6r/app/outline-manager: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory```

Any ideas why? Is there an installation guide I'm missing? All I saw in the FAQs was that DigitalOcean was the easiest way to install this.

**Comment by bemasc** [comment]
Hi @cravend.  The easiest way to install Outline on DigitalOcean is to download the Outline Server Manager to your laptop/desktop and run it.  The Server Manager will walk you through creating a VM and getting it set up correctly.

Good luck!

**Comment by cravend** [comment]
Sounds good! You might want to add some installation instructions in the FAQ--I thought the server manager was to be run on the machine running the VPN.

**Comment by AnergCorp001** [comment]
Hi, Outline Server Manager to your laptop/desktop here is also outline server management blocked, so I am trying to install it on server and add clients there, How I can do it, please help
