### ISSUE TITLE
Connected VPN unable to access ChatGPT/chat page

### ISSUE THREAD

**Issue by joglomedia** [Jigsaw-Code/outline-server#1320]
Hi all

I have install Outline VPN and able to make it works, but the vpn connection seems unable to access ChatGPT page.

![Screenshot_2023-04-05-15-56-42-518_com.brave.browser.jpg](https://user-images.githubusercontent.com/3152988/230033868-9bc41f0f-9eca-4a21-a2bd-3fa3f336a7f5.jpg)

What's wrong? any idea?

**Comment by hklcf** [comment]
because openai blocked all vpn/vps provider ip
