### ISSUE TITLE
API documentation doesn't open

### ISSUE THREAD

**Issue by cornzzy** [Jigsaw-Code/outline-server#1326]
In the [API section](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/README.md#access-keys-management-api) of shadowbox, this [Full API Documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml) doesn't open.

![image](https://user-images.githubusercontent.com/116248852/233906675-d31831be-41fc-4193-b0c0-42d196d04070.png)

**Comment by cornAndFriends** [comment]
Opened the yml file in another viewer and it works.

**Comment by maddyhof** [comment]
Sorry for the inconvenience. Can you share some more information so that we can trouble shoot? Please include the platform and browser are you using and steps to reproduce the error. Thank you!

**Comment by cornAndFriends** [comment]
Thank you for your respond.
It's chrome on windows, but if it opens for others, I don't think the problem is coming from such a platform.

**Comment by cornAndFriends** [comment]
Found the issue. I had to uncheck CORS next to the URL.

**Comment by hklcf** [comment]
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml&nocors

use this link
