### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by sobhan-m94** [Jigsaw-Code/outline-server#1328]
Whats is the prefix and How can I generate prefix ? any example ?

https://www.reddit.com/r/outlinevpn/wiki/index/prefixing/

**Comment by hklcf** [comment]
As of Outline Client version 1.9.0, access keys support the “prefix” option. The “prefix” is a list of bytes used as the first bytes of the [salt](https://shadowsocks.org/guide/aead.html) of a Shadowsocks TCP connection. This can make the connection look like a protocol that is allowed in the network, circumventing firewalls that reject protocols they don't recognize.

![image](https://user-images.githubusercontent.com/410302/235441244-16b06ad7-7d53-4c18-a250-6e915652b7aa.png)

**Comment by sobhan-m94** [comment]
> The “prefix” is a list of bytes

What is the meaning of list of bytes ?
Array of bytes ?

> To use the prefix feature with [Dynamic Access Keys](https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/) (ssconf://), add a "prefix" key to the JSON object, with a JSON-encoded value representing the prefix you want_ (see examples in the table above)_. You can use escape codes (like \u00FF) to represent non-printable Unicode codepoints in the U+0 to U+FF range. For example:
> 
> { "server": "example.com", "server_port": 8388, "password": "example", "method": "chacha20-ietf-poly1305", "prefix": "\u0005\u00DC\u005F\u00E0\u0001\u0020" }

What is "\u0005\u00DC\u005F\u00E0\u0001\u0020" ? How can I generate prefix like this ?
How would you write prefix generator function in Python?

@hklcf

**Comment by hklcf** [comment]
just copy & paste is ok...

![image](https://user-images.githubusercontent.com/410302/235917524-dd94a8a9-de87-4e34-a0aa-e39205195370.png)

**Comment by hklcf** [comment]
https://github.com/Jigsaw-Code/outline-client/pull/1454

**Comment by sobhan-m94** [comment]
I want to know how create a custom prefix ?

**Comment by sobhan-m94** [comment]
> I want to know how create a custom prefix ?

@bemasc

**Comment by AirFusion45** [comment]
@sobhan-m94 
Check the tutorial [here](https://www.reddit.com/r/outlinevpn/wiki/index/prefixing/). You can use the `encodeURIComponent()` function to generate a custom prefix

**Comment by maddyhof** [comment]
@sobhan-m94 I hope the prefix documentation has addressed your issues. If you have further questions you can post your questions on [reddit](https://www.reddit.com/r/outlinevpn/) for community support or contact customer support [here](https://support.getoutline.org/s/?language=en_US).
