### ISSUE TITLE
How to use extra proxy over the VPS of the Outline Server

### ISSUE THREAD

**Issue by htinaunglu** [Jigsaw-Code/outline-server#1335]
Hello fam, 
I have my VPS setup (Digital Ocean, Lightnode), and can be able to easily install outline server and is working fine. 
The problem is these cloud providers don't provide the ip adress of my choice(i.e, the country I want). So I bought some HTTP,HTTPS,SOCK5 proxy servers with only username, password, ip and port. What I would like to achieve is that I want to forward all of the traffic of my VPS through that proxy server address, including outline server outbound and clients.
The topology I want is here
```Outline Clients --> Outine Server on VPS --> Proxy Server --> Target. ```
 Is there anywhere to achieve that? I tried setting http proxy Environment variables of the VPS with my proxy server, but outline seems to somehow overpass it and outbound through the VPS' original IP address.
 Thanks.

**Comment by hardikhari96** [comment]
you want to  setup  like 

client  ->    country base vps(proxy) ->  your vps (digital ocean)  

right!?

**Comment by hardikhari96** [comment]
or you want to setup VPN ? on outline server

**Comment by htinaunglu** [comment]
> you want to setup like
> 
> client -> country base vps(proxy) -> your vps (digital ocean)
> 
> right!?

no Sir, Opposite to that! 
client -> my vps (digital ocean)-> country base vps(proxy)

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by kiumarsj** [comment]
> Hello fam, I have my VPS setup (Digital Ocean, Lightnode), and can be able to easily install outline server and is working fine. The problem is these cloud providers don't provide the ip adress of my choice(i.e, the country I want). So I bought some HTTP,HTTPS,SOCK5 proxy servers with only username, password, ip and port. What I would like to achieve is that I want to forward all of the traffic of my VPS through that proxy server address, including outline server outbound and clients. The topology I want is here `Outline Clients --> Outine Server on VPS --> Proxy Server --> Target. ` Is there anywhere to achieve that? I tried setting http proxy Environment variables of the VPS with my proxy server, but outline seems to somehow overpass it and outbound through the VPS' original IP address. Thanks.

this is exactly my problem except i have outline on container and the proxy server on another container on the same host. did you find any solution for it by any chance?!
