### ISSUE TITLE
Can't log back into Outline Manager

### ISSUE THREAD

**Issue by pandemicsoul** [Jigsaw-Code/outline-server#136]
I previously set up an Outline server via Outline Manager. Everything was working great – had like a dozen users on there. 

Went in today to add a new user and it said there was a problem – I needed to retry or login. Retried, no dice. Then tried logging in. Now it just keeps looping through the setup process, as opposed to allowing me to manage the server I already have set up. 

Please help – need to manage this server ASAP and there doesn't seem to be a way to do that.

**Comment by pandemicsoul** [comment]
What information would I need to provide to help move this issue forward? Really bumming me out that I can't log back in to add or remove users to my VPN.

**Comment by alalamav** [comment]
Thank you for the feedback @pandemicsoul, and sorry that you're having this issue. Did you set up the server through the automated DigitalOcean flow, or using the advanced mode?

You can ssh into the server and cat the file at `~/shadowbox/access.txt`. It contains the API URL and certificate hash. To import it into the server manager, make sure you format it as JSON, i.e. `{apiUrl: "https://xxxxxxxx, certSha256: "xxxxx"}`.

**Comment by pandemicsoul** [comment]
It was set up using the automated flow. 

See also, previous (resolved) issue: https://github.com/Jigsaw-Code/outline-server/issues/74

**Comment by pandemicsoul** [comment]
I was able to SSH into the server and get the information and using the manual connection I was able to reconnect and manage users. Thank you.
