### ISSUE TITLE
Where are the files stored after installation on the server?

### ISSUE THREAD

**Issue by valera126763298** [Jigsaw-Code/outline-server#1362]
How to find and edit the source code for yourself? Where are the files stored after installation on the server?

**Comment by maddyhof** [comment]
The source code for the server is available on GitHub [here](https://github.com/Jigsaw-Code/outline-ss-server). You could create a branch of the code on GitHub, edit it, and deploy it to your own server if you want. 

Out of curiosity, what functionality are you trying to add or change?
