### ISSUE TITLE
run custom image

### ISSUE THREAD

**Issue by sobhan-m94** [Jigsaw-Code/outline-server#1367]
Imagine I made some changes in the createNewAccessKey method.
Now,how can I install outline on my server with new changes ?

https://github.com/Jigsaw-Code/outline-server/blob/e0a9ae298e7df098b9abbcb8ea31c6ce8c1ceb62/src/shadowbox/server/server_access_key.ts#L169

**Comment by maddyhof** [comment]
Thanks for reaching out. Here are [instructions](https://github.com/Jigsaw-Code/outline-server/tree/master/src/shadowbox#running-from-source-code) to run your server from source code.
