### ISSUE TITLE
Asking for some clarification on how client data usage metrics work

### ISSUE THREAD

**Issue by cornzzy** [Jigsaw-Code/outline-server#1368]
Here in the function [getOutboundByteTransfer ](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/manager_metrics.ts#L28C5-L28C91), it says:

> We measure only traffic leaving the server, since that's what DigitalOcean charges.

So does that mean if an end user downloads 2GB and uploads 1GB, when I call the API  `/metrics/transfer`, is it gonna return 2GB or 3GB for that user?

And how accurate is it if I set the [hour parameter](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/server_access_key.ts#L258) to 1 instead 30*24 (which I did)? So if an end user does the same usage as above from 1:00 PM to 2:00 PM and then I call the API  `/metrics/transfer` at 2:00 PM, is it gonna be this timespan? Or is some of the usage going to end up in the next API call at 3:00 PM because it's what's happening to my clients right now. It feels like there is some delay for the usage calculations.

**Comment by linehman** [comment]
Hi there, I'd also noticed that traffic usage won't reset to zero after 30 days. Instead it would gradualy decrease each day. And this is kinda confusing. It would have been better if traffic usage would reset to zero after a month.

**Comment by cornzzy** [comment]
@linehman The data usage is trailing, which means that it shows the usage for the last 30 days. So if your usage today is zero, but your usage 31 days ago was high, you will see a decrease in your data usage.

**Comment by maysamgamini** [comment]
is there any part in the code that we can change to remove this trailing calculation?

**Comment by iw4p** [comment]
> is there any part in the code that we can change to remove this trailing calculation?

I checked the outline codes. Apparently the only way is customizing and reconfiguring shadowbox to bypass the limit.

**Comment by cornzzy** [comment]
Answers to both questions:
1. The `metrics/transfer` response is the sum of the end-user's upload and download traffic.
2. Setting the hour parameter from 24*30 to 1 seems to slightly offset the time, but the usage data is still accurate. For example, if you call metrics/transfer at 9:00, it will show the usage from approximately 7:50 to 8:50.
