### ISSUE TITLE
Key Recovery / Devices Restriction

### ISSUE THREAD

**Issue by MrSmitix** [Jigsaw-Code/outline-server#1369]
Hello! I'm going to have a few questions, since I can't figure it out myself.

1. I have a VPS on which Outline was installed via Docker a long time ago. The key was copied and pasted into Outline Manager, but after about a month it stopped connecting to the server for configuration. The download was constantly being issued. Although clients using previously generated keys are still quietly connecting after more than six months. Is there any way to restore/regenerate/view the key to access the server via Outline Manager? Without losing user keys. The server is completely at my disposal with root access.

2. Are there effective ways to limit the number of devices to N pieces per 1 key? I read about dynamic keys, but I didn't quite figure it out and would like to do everything inside my server without using third-party services. Since I use multiple servers, I use https://github.com/jadolg/outline-vpn-api to manage them. And there are no functions similar to the ones I need. Now about 50 people use 1 key, which "went hand in hand", which I don't like at all.

Many thanks in advance to anyone who will contribute to solving these problems.

**Comment by MrSmitix** [comment]
I found the file access.txt in /opt/outline, which has a certSha256 key. But where can I find the endpoint specified in apiUrl?

**Comment by maddyhof** [comment]
Thanks for reaching out. Glad you were able to address your first issue! As for the second, we have an open feature request for that capability: #1346, so I'll close this issue as a duplicate.
