### ISSUE TITLE
Outline VPN Server , WhatsApp call 

### ISSUE THREAD

**Issue by a25gh** [Jigsaw-Code/outline-server#1374]
Hi, I using Outline VPN, I have a problem when I want to call in the WhatsApp application. It shows "connecting..."
But messaging works properly.
is there any solution to fix it?

**Comment by maddyhof** [comment]
Thanks for reaching out. Closing this as a duplicate of existing issue https://github.com/Jigsaw-Code/outline-client/issues/1556 on outline-client.
