### ISSUE TITLE
Offer alternative IP setting options when domains.google.com fails

### ISSUE THREAD

**Issue by cjhenck** [Jigsaw-Code/outline-server#1375]
**What would you like the app to enable you to do?**
Users might want to set up Outline server in places where Google is unavailable. domains.google.com/checkip fails in those instances, so we should offer an alternative such as icanhazip.com or manual entry.

**Additional context**
https://www.reddit.com/r/outlinevpn/comments/oyx1vh/how_to_install_the_server_in_china/

**Comment by bemasc** [comment]
Relevant: https://support.google.com/domains/answer/13689670?hl=en

**Comment by fortuna** [comment]
This issue has been addressed since then: https://github.com/Jigsaw-Code/outline-server/blob/1ac9f238132d5917b42d4b6615727e477aa7bbc0/src/server_manager/install_scripts/install_server.sh#L405
