### ISSUE TITLE
Trying to install Outline Server on AWS instance. Checking host firewall ... BLOCKED message and no connection with manager

### ISSUE THREAD

**Issue by gungho424** [Jigsaw-Code/outline-server#1376]
Hello!

I tried to install the Outline server on Ubuntu 22.04.2 that I installed on my AWS instance. My experience is very similar with several previous topic starters, but after searching the solution and many tries I am still on the same pages. 

1. I installed Docker:

> grep " install " /var/log/dpkg.log
...
> 2023-07-26 10:06:48 install docker-buildx-plugin:amd64 <none> 0.11.2-1~ubuntu.22.04~jammy
> 2023-07-26 10:06:51 install docker-ce-cli:amd64 <none> 5:24.0.5-1~ubuntu.22.04~jammy
> 2023-07-26 10:06:52 install docker-ce:amd64 <none> 5:24.0.5-1~ubuntu.22.04~jammy
> 2023-07-26 10:06:55 install docker-ce-rootless-extras:amd64 <none> 5:24.0.5-1~ubuntu.22.04~jammy
> 2023-07-26 10:06:55 install docker-compose-plugin:amd64 <none> 2.20.2-1~ubuntu.22.04~jammy
...

2. Turned Docker services on:
...
> systemctl enable docker && systemctl start docker

3. Then used this command to install the Outline server:

> sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"

4. But Then I got firewall ...................... BLOCKED message. 
 
5. Downloaded and executed Outline Manager. After copy-pasting the key message in the corresponding form, I got this:

![image](https://github.com/Jigsaw-Code/outline-server/assets/91122597/1a6eee85-3bc6-4c6e-abc3-0eb61108431c)
 
6.  For hours start searching to find a solution. I used all combinations of these commands while executing the Outline Manager and trying to connect:

> sudo ufw allow XXXXX
> sudo ufw allow XXXXX/tcp
> sudo ufw allow YYYYY/tcp
> sudo ufw allow YYYYY/udp
> sudo ufw allow 1024:65535/tcp
> sudo ufw allow 1024:65535/udp

7. Disable UFW, tried connection and enabled it again, but the result is the same.

8. I also tried to allow all types of connections in AWS Dashboard...

Please, help me with at least some direction of where to look for solution.

**Comment by maddyhof** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by sitnikovhm** [comment]
Hey) u have solutions?

**Comment by QingXXiong** [comment]
I saw you've got a firewall blocked error.  You may need to follow the in-app instruction to add a firewall rule for AWS.  When starting with AWS, the first step is **Configure your firewall**. Click the  AWS logo to expand the instructions and see step-by-step screenshots. Note the Step 4 of instruction is no longer true.  Now go to **IPv6 firewall**, then click **Add rule**.  For **Application**,  select  **All protocols**.  Click **Create** on the right to save your rule.

**Comment by hklcf** [comment]
AWS has a cloud-base firewall, you need open port on that.

**Comment by llyndor** [comment]
Same problem. Please tell how to fix it
