### ISSUE TITLE
Error invoking remote method 'outline-ips-start-proxying'

### ISSUE THREAD

**Issue by Rolfff** [Jigsaw-Code/outline-server#1381]
For the past two days, my users and I have been unable to connect to my Outline server. I have checked the services. They are up and running. 
I receive this message:
![Unbenannt](https://github.com/Jigsaw-Code/outline-server/assets/35452669/596b96d2-fcb5-4db0-9f29-316ac45b5c9a)
My users (on Iphones) get the message that their keys are wrong. But I don't change them.
The outline manager works fine. 

Does anyone have any idea how to fix this? 
Does anyone else have this problem?
Serverversion: 1.7.2

**Comment by maddyhof** [comment]
Thanks for reaching out! It looks like your screenshot was taken using some kind of emulator. Do you have an iPhone, and if possible, can you reproduce this error on an iPhone rather than the emulator? The code that's producing this error isn't included in the iPhone version of the Client, so doing this on an iPhone may give you a different error that will help us better diagnose the problem.

**Comment by Rolfff** [comment]
Thanks for your message. Ohh... yes. The screenshot is from a Linux in VMPlayer. I have now installed the client on my Windows host system. It works fine here. 
My users are located in Iran. I think now that the regime has changed something. 
I don't have an iphone unfortunately. Sorry for the miscommunication. 

Maybe I can get a screenshot from my users in the days. Tonight my contacts have no internet.

**Comment by maddyhof** [comment]
Thanks for supporting users in Iran! Please do reply with a screenshot if/when one becomes available.

**Comment by Rolfff** [comment]
I get some screenshots.
This is from today.
![ima_f57d895](https://github.com/Jigsaw-Code/outline-server/assets/35452669/46ed6931-f10b-4774-9c02-4df35d3dd725)

That was a few days ago.
![ima_712315c](https://github.com/Jigsaw-Code/outline-server/assets/35452669/4518da32-dbd9-4136-b0fd-988ebaa5a0a0)

**Comment by maddyhof** [comment]
Thanks for this! I recommend contacting Customer Support for help with this issue. Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

**Comment by volatilerink** [comment]
this was never a solution, right? I've quite the same message in windows client.

**Comment by vevsvevs** [comment]
Same here

**Comment by belomor92** [comment]
+++

**Comment by 0xHunterr** [comment]
same issue here, I'm on kali Vm
![2023-12-12 18_58_27-kali-linux-2023 3-vmware-amd64 - VMware Workstation](https://github.com/Jigsaw-Code/outline-server/assets/88955610/99bfa09b-1cc5-413f-a156-445d9aee355e)
