### ISSUE TITLE
Unable to authorize on DO thought the app

### ISSUE THREAD

**Issue by zankevich** [Jigsaw-Code/outline-server#139]
**Can't scroll to authorize button.**

![image](https://user-images.githubusercontent.com/5199298/40259954-076da324-5b01-11e8-9b34-bec5690980fd.png)

**Comment by MaXFalstein** [comment]
I had the same issue but the recent build has sorted the issue; download the [latest build], unpackage and install. It should fix these issues. It has fixed the DigitialOcean teams issue I was halted by.

[latest build]:https://raw.githubusercontent.com/Jigsaw-Code/outline-releases/master/manager/Outline-Manager.dmg
