### ISSUE TITLE
Unsupported Machine Type

### ISSUE THREAD

**Issue by ShayanAtaei** [Jigsaw-Code/outline-server#1393]
Hi !

I tried to installed outline vpn on my server, but i confront below error:

`unsupported machine type aarch64. please run this script on a x86_64 machine`

what should i do ?

![Error](https://github.com/Jigsaw-Code/outline-server/assets/138935023/3516e0cb-79ba-4114-b68b-9fd4266cbc6a)

**Comment by maddyhof** [comment]
Thanks for reaching out! aarch64 is not currently supported, but we do have an open feature request to add support #1039. Closing this one as a duplicate.
