### ISSUE TITLE
Any reasons for certSha256? I can manage server only with apiUrl

### ISSUE THREAD

**Issue by sigseg5** [Jigsaw-Code/outline-server#1395]
Hi,
I'm writing an implementation of an Outline VPN management protocol and I noticed something strange. My application works even with an empty value for certSha256. I checked and I can even control the server via commands like `curl -k -X GET https://<ip>:<port>/<secret_string>/access-keys`. Building security only on a random <secret_string> string seems like a strange solution, or am I missing something? What is certSha256 for? Why can I manage the server without it? But I can't add a server with a random certSha256 value in the official Outline Manager. What is even going on?

P.S. I'm using the latest official version of the install_server.sh script from Outline Manager

**Comment by jyyi1** [comment]
Hi @sigseg5 , `certSha256` is Outline server's certificate. Outline Manager needs it to verify the server's authenticity (the `fingerprint` in code is the `certSha256`): https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/electron_app/fetch.ts#L39-L50.

**Comment by sigseg5** [comment]
@jyyi1 Ok, is there any way to enable validation of this certificate on the server? So that silver can be managed not only with https://<URL:PORT>/<SECRET>, but additionally requires a valid certSha256? That seems a little safer

**Comment by jyyi1** [comment]
@sigseg5 , for now it is impossible. But we can investigate a more secure way to manage the server. Again, thanks for reporting this.

**Comment by sigseg5** [comment]
@jyyi1 ok, thx for response👍🏻

**Comment by ysomad** [comment]
any updates on this?
