### ISSUE TITLE
Outline Manager and Outline Client (Windows) periodically lose settings

### ISSUE THREAD

**Issue by AlexDEVpro** [Jigsaw-Code/outline-server#1396]
I've been trying Outline for two and a half weeks, running it on my laptop almost every day. But during this time, already three times when I launched the Outline Client, I found that the settings were gone - the application just starts up like the first time and offers to add a server. Similarly with the Outline Manager program - it starts as for the first time, again it offers to add a server. I added it again every time. But this is extremely inconvenient.

My friend said that he had the same problem with Outline, he attributed it to updates.

The Outline Client settings are not reset on the smartphone, they are only reset in Windows. This looks like a serious problem. This is extremely annoying.

Is there any way to workaround this at least?

**Comment by maddyhof** [comment]
Thanks for reaching out! We tried to reproduce this issue but were unable to. I recommend reaching out to our Support team who can better assist you with troubleshooting. You can contact them by submitting Feedback from the Outline Client where you're experiencing this, so that they can have access to the relevant logs. The "Submit Feedback" option is in the app menu.

**Comment by AlexDEVpro** [comment]
I've been using Outline Client on another Windows 10 computer for some time now. The problem has never occurred on this computer.

The problem was probably related to the AtlasOS operating system, which I tried on an old low-performance laptop on which the problem occurred. A friend probably had the same problem because of AtlasOS.

Thus, I can confirm that the problem is most likely not in the Outline Client itself, but related to AtlasOS, or to some of its settings. I hope someone else finds this information useful.

Sorry for the interruption and thanks for reacting to the message.
