### ISSUE TITLE
Debian 9.4 install error

### ISSUE THREAD

**Issue by evanrich** [Jigsaw-Code/outline-server#14]
`root@dockerhost:/tmp# dpkg -i Outline-Manager-x64.deb
(Reading database ... 95927 files and directories currently installed.)
Preparing to unpack Outline-Manager-x64.deb ...
Unpacking outline-manager (1.0.2-56) over (1.0.2-56) ...
dpkg: dependency problems prevent configuration of outline-manager:
 outline-manager depends on gconf2; however:
  Package gconf2 is not installed.
 outline-manager depends on gconf-service; however:
  Package gconf-service is not installed.
 outline-manager depends on libnotify4; however:
  Package libnotify4 is not installed.
 outline-manager depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 outline-manager depends on libxss1; however:
  Package libxss1 is not installed.

dpkg: error processing package outline-manager (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 outline-manager
root@dockerhost:/tmp#
`

Is this only supported on GUI based linux distros?  any chance of a CLI server version?

**Comment by bemasc** [comment]
@evanrich It looks like you're trying to install the "Outline Server Manager" (which is a graphical desktop application), when what you want is the "Outline Server".  Instead, you should probably install the Outline Server Manager on your desktop, then follow its instructions for a custom server setup.  It will provide you with instructions for a command-line install of the Outline Server.

**Comment by trevj** [comment]
@evanrich Thanks for the report. Please re-open if you're still having problems.
