### ISSUE TITLE
api-port and keys-port are not working simultaneously - only the last keyword in command is used

### ISSUE THREAD

**Issue by GrigoriiTarasov** [Jigsaw-Code/outline-server#1405]
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" --access_key_port=20 --api-port=21`

gives undesired
```
...
- Management port 21, for TCP
- Access key port 46577, for TCP and UDP
```

the same for 

`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" --keys-port=20 --api-port=21`

There is no problem in port:
`sudo lsof -t -i :20`
is empty and for some other busy port the health stage wasn't proceeding.

**Comment by GrigoriiTarasov** [comment]
Seems that had to be `--api-port 21 --keys-port 20`

still the key port can be changed in

```
sudo nano /opt/outline/persisted-state/shadowbox_config.json
sudo nano /opt/outline/persisted-state/shadowbox_server_config.json
sudo nano /opt/outline/persisted-state/outline-ss-server/config.yml
```

**Comment by GrigoriiTarasov** [comment]
Still no  luck to tune with 2 custom ports
if I change only in mentioned file access keys port it still stays the same in the 
`docker logs shadowbox`

`I2023-09-15T14:52:42.490Z 34 server.go:86] Listening TCP and UDP on port 52691`

For new installation only the last keyword is applied
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" --api-port=20 --keys-port=8081`

```
> Checking host firewall ...................... OK
BLOCKED

- Management port 20, for TCP
- Access key port 22600, for TCP and UDP
```
And when reverse:
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" "--api-port=20 --keys-port=8081"`

```
> Checking host firewall ...................... OK
BLOCKED

- Management port 32075, for TCP
- Access key port 8081, for TCP and UDP
```

**Comment by murka** [comment]
Hi, it is not bug, you should ensure that the flags and their values are passed as arguments to the script inside the `bash -c` context:

```sh
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" bash -s -- --api-port=20 --keys-port=8081
```

**Comment by slden** [comment]
In my case 

`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" bash -s -- --api-port=20 --keys-port=8081`
**Unsupported flag -s**
```
Usage: install_server.sh [--hostname <hostname>] [--api-port <port>] [--keys-port <port>]

  --hostname   The hostname to be used to access the management API and access keys
  --api-port   The port number for the management API
  --keys-port  The port number for the access keys
```

_Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logetdujz5a0_e

**Comment by murka** [comment]
1. `wget https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh`
2. `chmod +x ./install_server.sh`
3. `./install_server.sh --api-port 1234 --keys-port 4321`
