### ISSUE TITLE
direct install source without docker

### ISSUE THREAD

**Issue by nandish486** [Jigsaw-Code/outline-server#1408]
if OutLineManager available without docker please inform me.
 
If you have time, so please give OutLineManager installation without docker.

**Comment by jyyi1** [comment]
Hi @nandish486 , we already have an issue to track this: https://github.com/Jigsaw-Code/outline-server/issues/254.

**Comment by delfer** [comment]
I've made manual how to build and run Outline without Docker https://gist.github.com/delfer/efa0a0bcf6393df255617ed8d1f3f14b
And still have ability to use Outline Manager
