### ISSUE TITLE
SSH keeps disconnecting (possible keepalive issues)

### ISSUE THREAD

**Issue by mirkhamidov** [Jigsaw-Code/outline-server#141]
when connection to servers by ssh unser outline vpn there is strange process

If idle in several seconds (not event monutes) ssh servers kicks me
```
Connection to *.*.*.* closed by remote host.
```

**Comment by themirrortruth** [comment]
I'm pretty sure that this issue is related to the keep-alive setting:
[another issue](https://github.com/Jigsaw-Code/outline-server/issues/85#issuecomment-386220735)

**Comment by mirkhamidov** [comment]
Where I have to set that param? on local machine? or server side?

**Comment by jcoetzee** [comment]
Experiencing the same problem. Also not sure where/how to enable the keep-alive setting.

**Comment by themirrortruth** [comment]
You can try to add following lines in your `~/.ssh/config`:
```
Host *
        ServerAliveInterval 3600
```
https://stackoverflow.com/a/25087194/7688649

Also, I tried to change OS level keep-alive settings (macOS) but it didn't help.

**Comment by shaomeng** [comment]
@themirrortruth I tried to send `ServerAliveInternal` to be enormously large, but still get kicked out. 

One of the shadowsocs authors @madeye [suggests](https://github.com/Jigsaw-Code/outline-server/issues/85#issuecomment-386220735) we need to set *both* server and client timeouts to be larger than 600s. I can imagine most people will have trouble to touch server settings...

**Comment by imfurman** [comment]
Yeah, have problem with this issue too. If anything (sftp clients, database connection etc..) wants to keep little bit longer connection outline breaks it.

**Comment by Pensare** [comment]
Had the same problem, us suggested by @themirrortruth , placing a config file in the .ssh folder, on both sides of the line did the trick, the line stays open!!!

**Comment by mirkhamidov** [comment]
it not helped to me (( set on local and remote, no fix((

**Comment by lolwhoami** [comment]
It's not only affecting SSH, for example voice calls in Telegram get dropped after a minute or so.

**Comment by mirkhamidov** [comment]
coz this annoying, im using nordvpn[dot]com (((
But, better, to have your own vpn server

**Comment by trevj** [comment]
Possibly related:
https://github.com/Jigsaw-Code/outline-server/issues/85

**Comment by trevj** [comment]
Wow, this has been idle for a long time. I'm going to bundle it with this keepalive issue, which I think must be related:
https://github.com/Jigsaw-Code/outline-server/issues/85
