### ISSUE TITLE
Self-signed certificate generated by install_server.sh should use IP SAN if hostname is unspecified

### ISSUE THREAD

**Issue by bundesdoge** [Jigsaw-Code/outline-server#1412]
Hi all,

Not an urgent issue but I thought it's worth flagging anyway:

I wrote a [Python script](https://github.com/bundesdoge/catline) to provision access keys for clients across a set of Outline servers in a more organised way, but found that in the server installation script:

https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh#L267

The public IP of the server is by default set as the common name of the self-signed certificate generated during the installation process, when a DNS name is not specified for the hostname. Specifying such DNS names are often undesirable for clients within censored countries, because these will be resolved in plaintext and observed by firewalls during connection time.

But when the server IP is used as the default, and the API needs to be called by a Python client rather than the official Outline Manager, then Python urllib (which is also used by requests, https://github.com/bundesdoge/catline/blob/main/provision.py#L44) will not recognise the certificate as valid for pinning purposes:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='x.y.z.q', port=61234): Max retries exceeded with url: /xxx_YYYYZZZZ/server (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for 'x.y.z.q'. (_ssl.c:1129)")))
```

This is likely because instead of putting the IP in the common name, they should go into an IP Subject Alternative Name (SAN) field instead. Without being able to validly pin the certificates, server API clients from within untrusted or censored networks cannot verify the server to safely manage it. Although this does not affect Outline clients connecting to the VPN server itself.

I'm happy to send a PR to try to fix this, but please let me know if you'd like to see this fixed.

Thanks.

**Comment by fortuna** [comment]
The reason why the validation fails is because we use a self-signed certificate. Due to the lack of a domain name, we can't get a certificate from a root CA.

To fix the issue you need to update your Python code to use the certificate fingerprint for validation.

**Comment by defance** [comment]
I am going to adress the same issue.

Actually specifying an IP in CN seems like invalid. Having no domain name is also reasonable. Still modern Python cannot verify the cert's host identity. Validation by IP in CN was dropped like ages ago.

BUT. There is a proper way to do this. I suppose, that Outline server should generate certificate with proper ACN field as following:
```bash
export CERTIFICATE_NAME=shadowbox-selfsigned
export PUBLIC_HOSTNAME=<server ip here, not a name>
openssl req -nodes -newkey rsa:4096 -subj "/CN=${PUBLIC_HOSTNAME}" -keyout "${CERTIFICATE_NAME}.key" -out "${CERTIFICATE_NAME}.scr"
openssl x509 -req -in ${CERTIFICATE_NAME}.scr  -days=36500 -extfile <(printf "subjectAltName=IP:${PUBLIC_HOSTNAME}") -key ${CERTIFICATE_NAME}.key -out ${CERTIFICATE_NAME}.crt
```

I re-generated keys for outline server manually with the above, stored them in `/shadowbox/persisted-state`, restarted docker container and it did the trick. Now Python successfully validates certificate host against local CA storage where I have my server's cert, obviously.
