### ISSUE TITLE
Expiration date and data usage limit for keys

### ISSUE THREAD

**Issue by rmin** [Jigsaw-Code/outline-server#142]
It would be a good feature to have the ability to limit keys by date and data usage. 

Right now I'm using key names like this `user_<LABEL>_<EXP-DATE>_<X>GB` 
And I have a small python script which uses the API and runs every minute with cron to parse the key names and compare their usage metrics to their usage limit in the name, and delete the key if their expiration date or usage limit is passed..

**Comment by aliabadi-mehran** [comment]
Hi @rmin 
Could you share your script? Is there a solution to limit concurrent users on the same key?

**Comment by rmin** [comment]
@aliabadi-mehran looks like all requests using each key is served by a single process. so it should be possible to limit the connection to a list of IPs - but we can't limit it to the number of "users", since the key itself is the user.. you can create a new issue on github for this if you want.

**Comment by trevj** [comment]
@rmin Thanks for the suggestions! I think these features have already been requested:
https://github.com/Jigsaw-Code/outline-server/issues/32

**Comment by cjhenck** [comment]
@rmin Is your goal for having a data limit just for a fixed period key (e.g. 1GB, expiring in a month), or do you have a need for a data limit of X GB in 30 days or per month / week, etc.?

Thanks!

**Comment by bemasc** [comment]
The Outline Server now supports data usage limits for keys: [here](https://www.reddit.com/r/outlinevpn/comments/fnqxqg/try_experimental_data_limits_in_outline_140/), so I think this is done :-)
