### ISSUE TITLE
Client connection speed performance is significantly lower than VPS speed

### ISSUE THREAD

**Issue by anskibe** [Jigsaw-Code/outline-server#1420]
speedtest issues (connection speed is lower than it is)

via outline client
![image](https://github.com/Jigsaw-Code/outline-server/assets/68534642/7e36400b-4d87-4c6f-b678-e51694c3051b)

via speedtest cli on the VPS
![image](https://github.com/Jigsaw-Code/outline-server/assets/68534642/eb8e474c-dd15-4c9a-a00c-6378c2b328d5)

I tried to change MTU, chiper (but seems like it was not be applied to aes-256-gcm, even afrer reboot)

**Comment by anskibe** [comment]
After enabling Google TCP BRR, the speed was increased twice, but it's still around 10mbps at the client (but it's around 200-300mbps at the VPS)

**Comment by maddyhof** [comment]
Thanks for reaching out about this issue. Can you share the Outline Client version, OS version, and Cloud provider you're using?
