### ISSUE TITLE
2fa or sso authentication

### ISSUE THREAD

**Issue by davidka79** [Jigsaw-Code/outline-server#1421]
Hello, I tried to find any information, but could not find 
does outline-server have 2fa or sso authentication solutions ?

**Comment by maddyhof** [comment]
Thanks for reaching out! We don't currently offer this but I've labeled this issue as a feature request for future prioritization. Can you share more about your use case that makes you interested in this feature?

**Comment by yapus** [comment]
I can share more info so m.b. you can reopen and prioritize this. 

By the rules we have set in place a user has to either  confirm their login to VPN when the connection is initiated  using second-factor device (TOTP code or Duo-app, Microsoft Authenticator) or use SSO (like Google) which would already have 2fa-requirement already set up.

**Comment by m-tse** [comment]
I would think this is important as well.

I give a key out to the users of my VPN. But if that key is ever exposed, then others can get access to the VPN as well

**Comment by sbruens** [comment]
For posterity as this wasn't mentioned when closed, but this issue was deduped against https://github.com/Jigsaw-Code/outline-apps/issues/1863.
