### ISSUE TITLE
windows 10: error: error invoking remote method 'outline-ipc-start-proxying': error: unknown nativeerror error

### ISSUE THREAD

**Issue by volatilerink** [Jigsaw-Code/outline-server#1431]
subj when trying to connect. have installed goodaccess before that and removed it. outline doesn't work at all after goodaccess

**Comment by volatilerink** [comment]
tried to reinstall outline (after goodaccess). got: "sorry, we couild not configure your system to connect to outline. please try running the installer again. if you still cannot install outline, please get in touch with us and let us know that the tap device failed to install with error code 5. [ok]

**Comment by temporary-tests** [comment]
I have exactly the same problem on Windows 11 Pro (22H2 OS Build 22621.2428). Outline client version 1.11.0 (468189)

**Comment by VladBoyr** [comment]
i have the same problem on Windows 10 after recently update.

**Comment by unps** [comment]
I have the same problem.

**Comment by belomor92** [comment]
+++

**Comment by SergeyAnuchin** [comment]
same error on Windows 11 Pro 22H2  22621.2428

**Comment by temporary-tests** [comment]
I accidentally fixed it but I can't say what exactly helped. In my case "outline-tap0" was missing (I forgot that the installer was complaining about it). And like a dozen of "TAP-Windows Provider V9" created by previous installation attempts were in the device manager.
I found that "outline-tap0" can be created using the "C:\Program Files (x86)\Outline\add_tap_device.bat" script, however, when I ran it, the script was failing saying that path was not found. I deleted all copies of "TAP-Windows Provider V9" from the device manger. And then I took commands from the "add_tap_device.bat" script and executed them manually. And they worked, all paths were valid. Outline client started working. I reinstalled the client one more time and it was smooth and everything works now.

**Comment by transcendreamer** [comment]
Same problem I've got today! 
First: 'outline-ipc-start-proxying': error: unknown nativeerror error
Then: Unexpected error. Quitting and restarting may help.
All servers - the same.
And then internet connecting breaks until full PC restart!
Reinstalling doesn't help.
Deleting network adapter and reinstalling doesn't help either.
It's so sad.

**Comment by transcendreamer** [comment]
Additionally: it's definitely related to the latest Outline update.
I checked reinstalling previous version and connection works.
Then Outline updates itself and after restarting it stops working!

**Comment by Talendar** [comment]
It seems to be a bug introduced in the latest version (v1.12.0) of the Outline Client.

https://github.com/Jigsaw-Code/outline-client/issues/1760

**Comment by ogreogles** [comment]
This may help:
https://support.getoutline.org/s/article/Error-Messages?language=en_US
The steps may vary based on your Windows operating system version, but we’ve provided general steps for how to uninstall the TAP adapter and Outline and then reinstall Outline.
Uninstall the TAP adapter for Outline.
Go to “Device Managers”, then look under “Network Adapters”
Find the “TAP-Windows Adapter V9” file or the TAP adapter associated with Outline
Uninstall or delete this adapter. Keep in mind that this could affect other VPN apps that you have installed. 
Uninstall Outline
Go into “Programs & Features”, then go to “Uninstall Program”
Find the Outline app and uninstall Outline
Download the latest version of Outline from [getoutline.org](https://getoutline.org/) and re-install it on your Windows device. The new installation should install a new TAP adapter for you.

As for me, I haven't uninstalled the TAP adapter. I have just updated it. Then I uninstalled the Outline Client and installed the latest version. It works.

**Comment by manuelernestog** [comment]
I'have the same problem in Ubuntu 22.04 after the last update.

s there any way to prevent it from updating automatically? ?

**Comment by SimonZhuangXH** [comment]
Still getting the error :( 
![image](https://github.com/Jigsaw-Code/outline-server/assets/84184146/44536433-bc4b-4158-a076-ee6a8add9f64)
I shld have the newest client
![image](https://github.com/Jigsaw-Code/outline-server/assets/84184146/2d59327f-9d3a-488c-bfd6-5a1ea8a2ba92)

**Comment by Elsayed91** [comment]
Same thing

**Comment by rustam-python** [comment]
I have same error with 1.12.1 (471860) and Windows 11.

**Comment by DmitriyYukhanov** [comment]
Confirm this is still happening in the latest 1.12.1 (471860) release.

**Comment by gggrafff** [comment]
I have the same error in Linux. It used to work, I didn't understand at what point it broke. Latest outline client, Linux Mint.

**Comment by alexsmik** [comment]
Same error. Did all how instruction above, but not working.

**Comment by Simplici** [comment]
same error with 1.12.1

**Comment by alezhu** [comment]
Just run c:\Program Files (x86)\Outline\add_tap_device.bat as Administrator

**Comment by OskarEichler** [comment]
Having the same issue on Windows 10. After it auto-updated to latest version 1.12.1 can't connect to any server and always getting the error 'outline-ipc-start-proxying' error. In previous version it was working but it updated so now it's broken. Please check up on this urgently!

**Comment by PrevikYT** [comment]
same error 1.12.1, add_tap_device.bat doesn't helped

**Comment by kie14** [comment]
> Same problem I've got today! First: 'outline-ipc-start-proxying': error: unknown nativeerror error Then: Unexpected error. Quitting and restarting may help. All servers - the same. And then internet connecting breaks until full PC restart! Reinstalling doesn't help. Deleting network adapter and reinstalling doesn't help either. It's so sad.

Run command prompt in administrator and run the .bat fixes the issue.

**Comment by DmitriyYukhanov** [comment]
Ah, that could be a case for me as well, as I recently installed OpenVPN to access NAS remotely.
But what if you need both OpenVPN and Outline?..

**Comment by alekvol** [comment]
I haven't run the client on Windows for a long time. I deleted the Outline client and reinstalled it, everything worked. The mobile version of the app was working with an error.

**Comment by freesou0** [comment]
It worked for me  https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class

**Comment by DmitriyYukhanov** [comment]
> I had a similar problem with OpenVPN installed. I removed the TAP-Windows V9 adapter for OpenVPN. After uninstalling everything worked.

Can confirm, it does conflict with OpenVPN.

1. Removed OpenVPN and Outline started working.
2. Installed OpenVPN and Outline can't connect again =(

**Comment by Pattriarch** [comment]
I also encountered this error in the same version. To resolve the issue, I followed these steps:

1. Uninstall all TAP-Windows Adapter V9 (I also had remnants from IVPN).
2. Uninstall Outline and all other VPNs from the computer, as well as from the browser itself (since conflicts can arise even with an active and functioning VPN due to other extensions).
3. Reinstall Outline, and everything started working again.

**Comment by kuzmix** [comment]
I've got problem like that at Windows 11
![image](https://github.com/Jigsaw-Code/outline-server/assets/6255012/b4b3052b-a092-4a15-9752-1b00dc702bc1)
My solution - you should restart service 'outlineService', and it works once.

**Comment by bazilsafronov** [comment]
_I faced the same problem_. Version **1.12.1**
It just helped me to reinstall the client

**Comment by ukarshiev** [comment]
![outline](https://github.com/Jigsaw-Code/outline-server/assets/48053125/fb253a85-eec1-46ac-8526-cedec140e0a1)
> Sorry, we could not configure your system to connect to Outline. Please
> try running the installer again. If you still cannot install Outline, please
> get in touch with us and let us know that the TAP device failed to
> install with error code 1.
-------------------------------------------
RU:
У меня была такая ошибка.
1. Я запустил Outline client от имени администратора
2. Зашел c:\Program Files (x86)\Outline\
3. Запустил файл add_tap_device.bat (от имени администратора)
4. В outline нажал "подключиться" -> подключилось со второго раза.

EN:
I had such a mistake.
1. I started the Outline client as an administrator
2. Zashol c:\Program Files (x86)\Outline\
3. Launched the add_tap_device.bat file (on behalf of the administrator)
4. In the outline, click "connect" -> connected the second time.

**Comment by raqeebhamza** [comment]
Solved it by downgrading  to 1.10.1 on Windows 11

**Comment by transcendreamer** [comment]
> Solved it by downgrading to 1.10.1 on Windows 11

SAME. 
I use 1.10.1 on W11.
Not letting to update.
Waiting for fix.

**Comment by Mikhail-behemoth** [comment]
Solution is here https://github.com/Jigsaw-Code/outline-apps/issues/1007

**Comment by andr-c** [comment]
This one has helped me on Ubuntu:

`systemctl restart outline_proxy_controller.service`

**Comment by D-side** [comment]
I started having the same issue after going on a mild organization spree and renaming my network adapters a lil bit.
I was **not** expecting the Outline client to actually rely on these internally, these always seemed to me like human-oriented labels, but alright, lesson learned, can't do that with Outline apparently.

Renaming the respective interface to `outline-tap0` fixed it in my case.

**Comment by ZNS05** [comment]
Hello everyone. When I distribute the Internet from my phone to my laptop and turn on OutlineVPN on my laptop, absolutely all sites in all browsers (Chrome, Edge) stop loading. He writes that "the site unexpectedly broke the connection" or "the site did not send data." I looked through Wireshark, packets are coming, the Internet is working. The Telegram application is quietly loading on a laptop. My telecom operator is Megafon. If you have met with a similar problem, please write back.

**Comment by D-side** [comment]
@ZNS05 this does not seem to be the same problem as outlined in this issue, I suggest you file a new report for yours; but before you do that, try to rule our your ISP as a possible cause, as this may very well not be a problem with Outline and might just be your ISP interfering with the connection. (Russia is currently cracking down on various censorship circumvention methods, Outline is most certainly on their list of targets and cellular carriers like Megafon are usually the first to start employing new censorship tech.)

---

<details><summary>(Russian translation for convenience)</summary

@ZNS05 это не похоже на проблему, описанную в этом тикете, рекомендую для вашей проблемы создать новый; но перед этим постарайтесь уточнить, не связана ли проблема с провайдером — проблема может быть не в Outline, а во вмешательстве провайдера в соединение. (В России сейчас активно охотятся на разные методы обхода цензуры, Outline совершенно точно есть в списке их целей, а сотовые операторы вроде Мегафона обычно первыми кидаются внедрять новые технологии цензуры.)
</details>

**Comment by D0BRIAK** [comment]
I have the same problem for a long time: if **OpenVPN** is installed on my PC, **Outline** gives the following error when connecting: proxy connection failed to connect server undefined. cause: _error: errpr invuking remote method 'outline-ipc-start-proxying': error: unknow nativeerror. No reinstallation has helped_.
But I found a sudden solution that worked equally well on my home PC, work PC and laptop.

I assigned the name **outline-tap0** to the **TAP-Windows Adapter V9#2** connection in the adapter parameter settings. After that both **Outline** and **OpenVPN** raise the channel without errors, everything works.
![Screenshot_1](https://github.com/Jigsaw-Code/outline-server/assets/48768810/e3ff9643-a40b-4c38-8043-0578a6fa9c2b)

Try it and don't forget to reboot your PC after renaming the connection, just in case )).

**Comment by D0BRIAK** [comment]
Just now saw that D-side above described this method)))))

**Comment by galek** [comment]
> I have the same problem for a long time: if **OpenVPN** is installed on my PC, **Outline** gives the following error when connecting: proxy connection failed to connect server undefined. cause: _error: errpr invuking remote method 'outline-ipc-start-proxying': error: unknow nativeerror. No reinstallation has helped_. But I found a sudden solution that worked equally well on my home PC, work PC and laptop.
> 
> I assigned the name **outline-tap0** to the **TAP-Windows Adapter V9#2** connection in the adapter parameter settings. After that both **Outline** and **OpenVPN** raise the channel without errors, everything works. ![Screenshot_1](https://private-user-images.githubusercontent.com/48768810/332307121-e3ff9643-a40b-4c38-8043-0578a6fa9c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTUwMjksIm5iZiI6MTcxNjU1NDcyOSwicGF0aCI6Ii80ODc2ODgxMC8zMzIzMDcxMjEtZTNmZjk2NDMtYTQwYi00YzM4LTgwNDMtMDU3OGE2ZmE5YzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEyNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWQ2N2ZmOGVlN2I3ODJhMDFkMDk2YTMzNmRkYTkxNjhmNDFmMTNkZDAwMzhhYWJhNGZkMTY0YmM1ODA4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Jj7qDfZuOnrlsjRvmTNK4wQMC1h0FUk_00WcDpq6-w)
> 
> Try it and don't forget to reboot your PC after renaming the connection, just in case )).

Thanks of lot! It worked for me

**Comment by EugnR** [comment]
> I have the same problem for a long time: if **OpenVPN** is installed on my PC, **Outline** gives the following error when connecting: proxy connection failed to connect server undefined. cause: _error: errpr invuking remote method 'outline-ipc-start-proxying': error: unknow nativeerror. No reinstallation has helped_. But I found a sudden solution that worked equally well on my home PC, work PC and laptop.
> 
> I assigned the name **outline-tap0** to the **TAP-Windows Adapter V9#2** connection in the adapter parameter settings. After that both **Outline** and **OpenVPN** raise the channel without errors, everything works. ![Screenshot_1](https://private-user-images.githubusercontent.com/48768810/332307121-e3ff9643-a40b-4c38-8043-0578a6fa9c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTk5NjYsIm5iZiI6MTcxNjU1OTY2NiwicGF0aCI6Ii80ODc2ODgxMC8zMzIzMDcxMjEtZTNmZjk2NDMtYTQwYi00YzM4LTgwNDMtMDU3OGE2ZmE5YzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTBkZTc0ODYzNWU4YTM5NmY1NWEyODdhZWFhYzcxZTYzMzcwNmQ0YWQzYzk1MDUwOTI0MGMyN2MzZTlhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GO6pe11s2uYXPZAGbD-4dnQfFnv76qV8YPhCqCEEW44)
> 
> Try it and don't forget to reboot your PC after renaming the connection, just in case )).

Worked for me too. Thanks!

**Comment by Satisanya** [comment]
> I have the same problem for a long time: if **OpenVPN** is installed on my PC, **Outline** gives the following error when connecting: proxy connection failed to connect server undefined. cause: _error: errpr invuking remote method 'outline-ipc-start-proxying': error: unknow nativeerror. No reinstallation has helped_. But I found a sudden solution that worked equally well on my home PC, work PC and laptop.
> 
> I assigned the name **outline-tap0** to the **TAP-Windows Adapter V9#2** connection in the adapter parameter settings. After that both **Outline** and **OpenVPN** raise the channel without errors, everything works. ![Screenshot_1](https://private-user-images.githubusercontent.com/48768810/332307121-e3ff9643-a40b-4c38-8043-0578a6fa9c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDY5OTMsIm5iZiI6MTcxODEwNjY5MywicGF0aCI6Ii80ODc2ODgxMC8zMzIzMDcxMjEtZTNmZjk2NDMtYTQwYi00YzM4LTgwNDMtMDU3OGE2ZmE5YzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDExNTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjA0ZTQyOGM1ZmY4OWQyYjQ3NDI1NWM3NzNjNDNhNDNhZTc5MmZhOTQ1ZGJmNzhkYWYwNTg0Y2Q2NTc2OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6j7WZxppgCLjG-hD6s4YsDoVl3Gv1c6VbZpNFgHyJI)
> 
> Try it and don't forget to reboot your PC after renaming the connection, just in case )).

спасибо тебе братан, всю жопу порвал не знал что делать))))

**Comment by 0xferr** [comment]
> I assigned the name **outline-tap0** to the **TAP-Windows Adapter V9#2** connection in the adapter parameter settings. After that both **Outline** and **OpenVPN** raise the channel without errors, everything works. ![Screenshot_1](https://private-user-images.githubusercontent.com/48768810/332307121-e3ff9643-a40b-4c38-8043-0578a6fa9c2b.png?
It wokrs for me as well. Thanks!

**Comment by kiberli1960** [comment]
My **outline-tap0** was simply disabled. When I started it again, everything worked.

**Comment by iftsv** [comment]
hi there,
Got the same error on Win 11
> error invoking remote method 'outline-ipc-start-proxying'" on win11

I use user account without admin rights. I feel that during Outline installation, the required network connection was not added.
To fix this issue
1. Open `cmd.exe` with admin rights, 
2. Go to `C:\Program Files (x86)\Outline` 
3. Run `add_tap_device.bat`
...
5. PROFIT!

**Comment by HiradNikoo** [comment]
Update the client app. If there is not other latest version then check (one windows) Event Viewer > Windows Logs > Application

For me same error was fixed by update.

**Comment by dmitry-js** [comment]
This happened to me after I installed NordVpn. Then I reinstalled Outline and it worked again

**Comment by acebiscuits** [comment]
had the same problem. in my case I just deleted outline and installed it again and it works now
