### ISSUE TITLE
changing server

### ISSUE THREAD

**Issue by ParsaSr** [Jigsaw-Code/outline-server#1435]
Hi Jigsaw team. Thank you for making such amazing application!
There is only one issue that is my own. Whenever I want to change servers, all of the access keys just get destroyed. I wanted to know that is there anyway that I could take backups from my access keys and add them to my newly created server?
Could you tell me the address of the directory which Outline keys are stored in?
I would appreciate some help <3

**Comment by fortuna** [comment]
The keys go in /opt/outline/persisted-state:
https://github.com/Jigsaw-Code/outline-server/blob/e157315aa0be13d11b9406ad8590109473488b1c/src/server_manager/install_scripts/install_server.sh#L237

Copy the json files from there.
