### ISSUE TITLE
Manager not working on master

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-server#1449]
When I build the Electron Manager app, the build succeeds, but I get a runtime error:
![image](https://github.com/Jigsaw-Code/outline-server/assets/113565/ea015a73-55dd-40d7-99a4-be060b21c5b2)

And the UI fails to render properly.

I suspect that was caused by the upgrade to Webpack 5 in https://github.com/Jigsaw-Code/outline-server/pull/1422.

I thought it could be related to [Webpack not including Node polyfills](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5), but I tried the suggested [fallback](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5) approach and it didn't work.

@daniellacosse please help, you may have more insights.

**Comment by maddyhof** [comment]
Fixed by https://github.com/Jigsaw-Code/outline-server/pull/1451
