### ISSUE TITLE
Support ovpn file (for openvpn)

### ISSUE THREAD

**Issue by hktalent** [Jigsaw-Code/outline-server#1459]
how get ovpn file for openvnp?
eg:

```
curl -s https://outline.org/invite/abc123 > outline.ovpn

sudo openvpn --config outline.ovpn

```

**Comment by jyyi1** [comment]
Hi @hktalent , we don't support OpenVPN for now. Do you want us to add the OpenVPN invitation file support to our server and Outline Client?
