### ISSUE TITLE
Add support for OpenVPN, PPTP & IPSEC/L2TP

### ISSUE THREAD

**Issue by cameronaaron** [Jigsaw-Code/outline-server#146]
The issue with shadow sockets is that not all applications will run through the proxy so there is a possibility of a data leak it would be nice if there was a mode that allowed for traffic to run through the OpenVPN, PPTP & IPSEC/L2TP protocols for added security

**Comment by studentmain** [comment]
Unluckily, they're all too weak to across the great firewall by themselves.
OpenVPN over shadowsocks is a good idea, but it's a little heavy.

Cameron Aaron <notifications@github.com> 于 2018年5月25日周五 14:06写道：

**Comment by cameronaaron** [comment]
I definitely think it would be nice to have that as a toggle that can be enabled for added security

**Comment by fortuna** [comment]
Hi @cameronaaron , why do you say not all applications will run through the proxy?

On all our clients, expect the Windows one, we proxy all the device's traffic. We are working on doing the same for Windows too. Would that address your concerns?

As @studentmain points out, the problem with the standard VPN protocols and OpenVPN is that they are very easy to identify and block on the wire.

**Comment by cameronaaron** [comment]
I was just thinking that there might be some situations where it would be nice to be able to run open VPN over the shadow-socket proxy it could be added as a toggle for extra security. Yes Windows is what I had in mind but am I wrong to think that someone can make an app that does not respect the proxy settings and ends up revealing itself?

**Comment by fortuna** [comment]
> I was just thinking that there might be some situations where it would be nice to be able to run open VPN over the shadow-socket proxy it could be added as a toggle for extra security.

The extra security may make sense. If configured properly, I believe OpenVPN can provide forward secrecy, which Shadowsocks doesn't. We can also get FF with TLS, which is probably cleaner than OpenVPN. However forward secrecy requires a hand-shake that is usually detectable, even if encrypted, by the byte sizes of the exchanges. We'll keep those things in mind.


>  Yes Windows is what I had in mind but am I wrong to think that someone can make an app that does not respect the proxy settings and ends up revealing itself?

Currently on Windows we run a system proxy, so you're right. That's not the case on mobile and macOS, and we are trying to figure that out for Windows, so all the traffic is intercepted.

**Comment by cameronaaron** [comment]
Thank you for keeping it in mind! I believe if you are somehow able to work out a good way to do forward secrecy it will create a much better and safer product for everyone. That is one of the main things Outline is lacking and I believe really needs

**Comment by shaomeng** [comment]
I wanted to comment on other protocols such as OpenVPN, PPTP & IPSEC/L2TP: it's absolutely correct that they're easy to be identified and also blocked. 
But IPsec IKEv2 might be able to serve our purpose because it is used by Cisco VPN products, and Cisco VPN products are used by many corporations, so the state censorship hesitates to block.

From my experience in China, the Cisco VPNs always work well. So if Outline could appear as Cisco VPN traffic, I doubt it will get blocked :)

**Comment by studentmain** [comment]
The most serious problem is: This project already use Shadowsocks protocol.
If add other protocol, we need setup it's server in Outline Server, import
the protocol client's code (for all platform) to Outline Client.
Maintain multiple service is also a challenge to untrained server manager.
And, most VPN works on private transport protocol. It's hard to NAT them.

Samuel Li <notifications@github.com> 于 2018年6月1日周五 15:18写道：

**Comment by cameronaaron** [comment]
Very true but it still might be worth keeping in mind. If there is a way to implement this in a way that is easier to manage and still can be discreet it will create a better product for everyone
