### ISSUE TITLE
Method not allowed using the API to get a key by id

### ISSUE THREAD

**Issue by jadolg** [Jigsaw-Code/outline-server#1471]
## How to reproduce:
* Create a new key and get it's ID
* Try to get a key by its ID
`GET {API_URL}/access-keys/{KEY_ID}`

## Current behavior
The API responds with status code 405

## Expected behavior
The API responds status code 200 and the key Object

## More details
The response indicates that only the DELETE method is allowed

**Comment by murka** [comment]
Hi, right now this method is released, but outline-server is not yet.

**Comment by jadolg** [comment]
Closing because the method is already in the latest version. Thank you all :partying_face:
