### ISSUE TITLE
API port only listens on IPv6 address

### ISSUE THREAD

**Issue by jcoetzee** [Jigsaw-Code/outline-server#148]
Setting up Outline on a GCP VM and it seems that the node service handling the API endpoint only listens on the IPv6 address, I'm unable to connect via IPv6 due to restrictions in ISP.

Installing via
```
bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
```

Output
```
{"apiUrl":"https://$SB_PUBLIC_IP:36483/$SB_API_PREFIX","certSha256":"$CERT_HEX_FINGERPRINT"}                                                                                        

<snip>

~$ sudo netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      695/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1418/sshd           
tcp        0      0 0.0.0.0:21536           0.0.0.0:*               LISTEN      6368/ss-server      
tcp6       0      0 :::22                   :::*                    LISTEN      1418/sshd           
tcp6       0      0 :::36483                :::*                    LISTEN      6211/node
```

**Comment by fortuna** [comment]
I get the same netstat as you do, but the service is running for me.

Can you try running this with the ipv4 localhost address?
```bash
curl --insecure https://127.0.0.1:36483/${SB_API_PREFIX}/access-keys
```
If it works, then I think your issue may be a firewall on your machine. GCP blocks all connections by default.

**Comment by jcoetzee** [comment]
I ended up disabling IPv6 entirely but then ran into a different problem (curling the endpoint returns `{"code":"ResourceNotFound","message":"/${SB_API_PREFIX} does not exist"}`) so you may be right. I'll need to re-enable IPv6 to confirm. Might have to open a new issue for this other problem.

**Comment by jcoetzee** [comment]
Re-enabled IPv6 and can connect. Think the problem with Outline Manager was copy paste error (was using browser-based SSH console to VM and there was a random line break in the cert hash).

**Comment by john8862** [comment]
I have the same issue. Tried the testing @fortuna mentioned and get below output:
`{"code":"ResourceNotFound","message":"/access-keys does not exist"}`
netstat result as below:
`#sudo netstat -lnpt
`Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1556/sshd
tcp        0      0 0.0.0.0:17024           0.0.0.0:*               LISTEN      1584/ss-server
tcp        0      0 127.0.0.1:32000         0.0.0.0:*               LISTEN      1060/java
tcp        0      0 0.0.0.0:9057            0.0.0.0:*               LISTEN      1585/ss-server
tcp6       0      0 :::34632                :::*                    LISTEN      1533/node`

Sorry, don't know how to break line in markdown

**Comment by fortuna** [comment]
@john8862 You need to add the `SB_API_PREFIX` to your curl command:
```
curl --insecure https://127.0.0.1:${SB_API_PORT}/${SB_API_PREFIX}/access-keys
```
