### ISSUE TITLE
return warning message when a key is generated with the same password

### ISSUE THREAD

**Issue by vahiddsy** [Jigsaw-Code/outline-server#1485]
PUT /access-keys/1
{"id":"1","method":"aes-192-gcm","name":"name-1","password":"P@SsW0rD","limit":{"bytes":10000}}

response : 201

PUT /access-keys/2
{"id":"2","method":"aes-192-gcm","name":"name-2","password":"P@SsW0rD","limit":{"bytes":10000}}

response: 201

By making two different keys but with the same password.

The token that is created is the same for both, and the problem that arises is that the consumed transfer usage is calculated for one of the keys.

According to this, there is a logical problem and it is better to avoid creating keys with the same password

**Comment by fortuna** [comment]
@murka is already fixing it in https://github.com/Jigsaw-Code/outline-server/pull/1506. It makes sense to fail on duplicate password, since that is almost certainly a mistake, and we can't support it anyway because of the trial decryption we do to authenticate the user.
