### ISSUE TITLE
How can i setup an outline vpn server on a Mac ?

### ISSUE THREAD

**Issue by daguitosama** [Jigsaw-Code/outline-server#1487]
Im looking forward a way to install & get up and running an Outline VPN Server on a Mac, that way I can connect the same as if I where on home. After tried to get it going on an Ubuntu running container with the respective ports, it failed, because `systemd` missing error.

There is any guide on how to install & run it on a mac ?

**Comment by jyyi1** [comment]
Thank you for reaching out. We have already had another issue tracking the support of server installation on macOS: https://github.com/Jigsaw-Code/outline-server/issues/801#issuecomment-770022930 . Please feel free to vote on that issue.
