### ISSUE TITLE
Puth method in /access-keys needs to use {id} in the path

### ISSUE THREAD

**Issue by jadolg** [Jigsaw-Code/outline-server#1499]
The method to create a key with a specific id operates under `/access-keys/{id}` and not under just `/access-keys`
https://github.com/Jigsaw-Code/outline-server/blob/64c4f945342ea7725b936a538f9b39353ee55379/src/shadowbox/server/api.yml#L178

The code is correct but the API docs are not

**Comment by sbruens** [comment]
Thank you @murka for fixing this!
