### ISSUE TITLE
Use Google BBR as the default TCP congestion control

### ISSUE THREAD

**Issue by tobyxdd** [Jigsaw-Code/outline-server#15]
Nice project! This could really lower the technical barrier of setting up shadowsocks servers. Here's one suggestion though:
![TCP](https://i.imgur.com/JKGjdY2.png)
I found that the current Outline servers are using default cubic TCP congestion control, which performs terrible over lossy networks. For some reason, connections to any foreign server can sometimes be extremely lossy (~20% packet loss) for Chinese users, transmission will be almost stopped in this situation with cubic. Thus most of us are using [Google BBR](https://github.com/google/bbr). BBR is already a built-in congestion control algorithm for Linux kernel 4.9+, it shouldn't be too hard for you to update your shadowbox image to enable BBR as the default TCP congestion control 😄

**Comment by fortuna** [comment]
Thanks for the suggestion.

Unfortunately the kernel of our image is 4.4, so it doesn't come with BBR
```
# sysctl net.ipv4.tcp_available_congestion_control
net.ipv4.tcp_available_congestion_control = cubic reno
```

We'll investigate how easy it is to use a different kernel. Any guidance is appreciated.

**Comment by fortuna** [comment]
Ok, I learned that Docker actually uses the host kernel. So there's no way in our docker image to guarantee the use of BBR.

I guess we can enhance the install script to check if BBR support is available, and enable it if so.

**Comment by tobyxdd** [comment]
Docker containers don't have their own TCP/IP stacks. The install script has to enable BBR on the host (if it's available).

**Comment by OneHappyForever** [comment]
It should work on KVM vps, like digitalocean. It will NOT work on openvz.

However, based on my personal testing, I HIGHLY recommend implementing this feature.

**Comment by trevj** [comment]
Related performance issue:
https://github.com/Jigsaw-Code/outline-server/issues/63

**Comment by jab** [comment]
When calling the DO API to create the host VM, could the OS be switched from Ubuntu to DO’s Debian 9 image? Looks like that comes with the 4.9 kernel by default.

**Comment by jab** [comment]
Or maybe switching to Ubuntu 18.04 LTS when it comes out later this month is the better move. That has the 4.15 kernel by default.

**Comment by fortuna** [comment]
Those are good ideas. However they don't come with Docker pre-installed, and installing it significantly increased the server creation time the last time we tried.

Ideally DO would update the docker image to have the latest kernel

**Comment by jab** [comment]
For sure. (And if we haven't already maybe let's open a DO support request for this and/or write to the DO user forums.)

In the meantime though, for affected users I can imagine it being well worth it to grab a coffee during a longer server creation step in return for actually having a usable proxy. Or maybe including a "Use BBR (takes longer)" checkbox (possibly buried under an "advanced" section of the UI) during server creation could also work.

**Comment by YegorIevlev** [comment]
I get same speeds with or without BBR, but I get higher speeds with KCP. Maybe we should use `kcptun` instead? It doesn't require replacing the kernel too.

**Comment by sandrigo** [comment]
DigitalOcean has updated their images to include Ubuntu 18.04, which ships with kernel 4.15, so we've modified the installation script for DigitalOcean servers to enable BBR by default. Note that this doesn't affect 'advanced installation' servers yet, though we plan to do that too (with the caveat that we'll only do it if the Kernel already supports BBR, rather than attempt patching it or upgrading it).
