### ISSUE TITLE
Sequential port numbers

### ISSUE THREAD

**Issue by jcoetzee** [Jigsaw-Code/outline-server#150]
Feature request to support sequential port numbers? Would allow me to set small range of ports in firewall instead of allowing the whole 1024-65535 set.

**Comment by SquirrelCoder** [comment]
That was my issue too and you don't need to open all your firewall ports.

Read the solution here 

https://github.com/Jigsaw-Code/outline-server/issues/132

**Comment by jcoetzee** [comment]
Thanks, but that isn't exactly a solution so much as it's a workaround. I started off opening ports individually but if I'm doing this for a small company it quickly get's frustrating, especially when people leave/join. I'd rather be able to open up a block of ports and allocate users from that block.

**Comment by SquirrelCoder** [comment]
Oh yeah, you are right then. Hopefully this feature will be added in next versions.

**Comment by fortuna** [comment]
We are looking into the possibility of running all access keys on a single port, which would remove the need for sequential port numbers.

**Comment by fortuna** [comment]
Initial prototype here: https://github.com/fortuna/ss-example
