### ISSUE TITLE
Shadowbox container disappeared after auto update

### ISSUE THREAD

**Issue by mitya12342** [Jigsaw-Code/outline-server#1501]
After months of uptime my outline server stopped working. I checked docker ps and got only watchtower.
```
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS       PORTS      NAMES
7cf54226f720   containrrr/watchtower   "/watchtower --clean…"   6 months ago   Up 2 weeks   8080/tcp   watchtower
```
relevant docker images looks like this
```
REPOSITORY                  TAG       IMAGE ID       CREATED         SIZE
quay.io/outline/shadowbox   stable    0fbe147c3e44   5 days ago      316MB
containrrr/watchtower       latest    f847e1adb570   12 months ago   14.6MB
quay.io/outline/shadowbox   <none>    a2f02dc7eadd   14 months ago   250MB
```
so I checked watchtower logs and it seemed to be a failed update
```
time="2024-02-05T14:51:59Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
time="2024-02-05T15:51:59Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
time="2024-02-05T16:52:15Z" level=info msg="Found new quay.io/outline/shadowbox:stable image (0fbe147c3e44)"
time="2024-02-05T16:52:15Z" level=info msg="Stopping /shadowbox (6525519f8778) with SIGTERM"
time="2024-02-05T16:52:26Z" level=info msg="Creating /shadowbox"
time="2024-02-05T16:52:26Z" level=error msg="Error response from daemon: invalid config for network host: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined networks"
time="2024-02-05T16:52:26Z" level=info msg="Session done" Failed=1 Scanned=1 Updated=0 notify=no
time="2024-02-05T17:51:58Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```

Are there a way to correctly restart the server without loosing keys/configuration?

**Comment by amatus-** [comment]
I have the same problem. Is this solved only by reinstalling?

**Comment by mitya12342** [comment]
> I have the same problem. Is this solved only by reinstalling?

You can run my commands (replace values with yours), it will keep all the configuration or reinstall
Not sure if it is solved and wont occur on next update so lets wait for maintainers comments on this

**Comment by fortuna** [comment]
I’m sorry for the inconvenience. It seems to be a bug on docker-ce 25.0.0: https://github.com/docker/for-linux/issues/1481.

They have fixed the issue and released 25.0.1. Please make sure you’re running the newest version of Docker.

If you really need, it’s possible to disable auto update by stopping the Watchtower container, but I don’t recommend that.

**Comment by mitya12342** [comment]
Alright then, I had exactly 25.0.0

**Comment by fortuna** [comment]
By the way, the latest manual install script creates a script at `/root/shadowbox/persisted-state/start_container.sh` that lets you easily recreate the container if you need to. This will be in the next Manager release.

Code at https://github.com/Jigsaw-Code/outline-server/blob/88cee12ec494a162fe3018bf345ecda672185fdd/src/server_manager/install_scripts/install_server.sh#L303
