### ISSUE TITLE
Outline Server blocked by government

### ISSUE THREAD

**Issue by kalhori124** [Jigsaw-Code/outline-server#154]
Hi 

Outline Server works on TCP/UDP 2049 ( nfs ) and this port blocked by ISP , How can I change the port ?

Best Regards,

**Comment by sailosha** [comment]
I have the same issue. Even though I changed IP on google cloud platform, it is still not avaiable to connect.   Unless I use another vpn to connect internet and using outline.

**Comment by sailosha** [comment]
@kalhori124 
I fixed my issue, could you please rebuild your servers? And changed IP, including port. I am pretty sure you NEED reset them. My outline works now

**Comment by kalhori124** [comment]
I did and everything is OK , Thanks

**Comment by kalhori124** [comment]
@sailosha 

I did and everything is OK

**Comment by fortuna** [comment]
Keep in mind that if you make changes to the IP and port existing invitations will be invalidated and you need to resend them.

In any case, it seems this has been fixed, so I'll close.
