### ISSUE TITLE
How to reset traffic of a access key?

### ISSUE THREAD

**Issue by aladaghlou** [Jigsaw-Code/outline-server#1563]
How to reset traffic of a access key?

Hello all my friends

We deployed a server with outline server and make many access keys.
Then now we need reset data traffic of one access key of thems.
Please help us .
Best regards

**Comment by torabkheslat** [comment]
Search for the name here and extract the id:
```
cat /opt/outline/persisted-state/shadowbox_config.json| jq '.accessKeys[] | select(.name | contains("Jadid")) | .id'
```

Then use the following command to reset the volume:
```
curl -X PUT   -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={access_key="<ID>"}'
```

**Comment by maddyhof** [comment]
Thanks for reaching out! Hopefully the workaround shared by @torabkheslat helps. The feature request for a reset option is at https://github.com/Jigsaw-Code/outline-apps/issues/1860 so I'll close this as a duplicate.
