### ISSUE TITLE
Bug? Cannot connect to the server if install the manger twice

### ISSUE THREAD

**Issue by teddychan** [Jigsaw-Code/outline-server#158]
How to reproduce:

run the install command in GCP brand new ubuntu 16.04 LTS

```
bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"

```
After the first install, it can be connected to outline manager.

However, if we run the install script again, the port number and secret is updated.
No matter use the new or old value, it said cannot connect.

**Comment by sailosha** [comment]
Dear teddychan,
if you are using GCP, be careful. GCP need you to set up firewall to allow all the tcp udp forwarding. 
VM firewall rule-----add tcp:0-65535，udp --65535. Set a tag for this rule, and add this tag to ur servers. 
I checked your profile, maybe Chinese is better for u to explain this issue. Here is Chinese version.

谷歌gcp需要自己設置網絡防火墻，你需要給你的服務器設置允許tcp udp出口，
具體設在在你的vm實例中選擇網絡接口， 查看詳情，
添加防火墻規則 tcp:0-65535，udp --65535， 然後目標設置一個名字，確保你服務器有這個目標網絡名字。

**Comment by teddychan** [comment]
Actually, I have enabled all traffic.
As said, for the first install, it can be connected without any problem.
I just want to validate this bug, so I set up a new GCP and run the installation script twice.
After the 2nd install, it will fail to connect.

BTW, thanks for the nice Chinese tranlsation~~

**Comment by sailosha** [comment]
I installed many times on my servers after reset ip.
I think after you installed the bash command again you need reset your connection on the outline servers.
For example. after you did BASH command, you need give outline server app a new api and password to manage your server

**Comment by teddychan** [comment]
okay, I double checked and now I found the problem.

I use google console built in SSH console.

It has a nice feature that auto copy of the selected text.

But it will have a line break!

![image](https://user-images.githubusercontent.com/1013507/40922502-e93b2ea2-6844-11e8-9f14-9d76907b03a6.png)

So, its my mistake.
Thanks for helping me to test and now its verify all works!

**Comment by fortuna** [comment]
I had the same issue in the past setting up on GCP. @alalamav: we could remove all line breaks in the string to avoid that problem.

**Comment by alalamav** [comment]
Done in #164.
