### ISSUE TITLE
Question: How to add existing server to manager?

### ISSUE THREAD

**Issue by bvn13** [Jigsaw-Code/outline-server#1583]
First, thanks to great app! :)

I have reinstalled my broken OS on my laptop and miss the settings to my VPN server. 
How do I add the existing server to Outline VPN Manager without reinstalling the Server?

**Comment by sbruens** [comment]
You can find the details on your server and then add them to your Manager. This comment may help: https://github.com/Jigsaw-Code/outline-server/issues/1268#issuecomment-1813954948
