### ISSUE TITLE
SS-AEAD blocked in Russia

### ISSUE THREAD

**Issue by pjUKW1hJn8g1Ntzg8A4IW9wrD8M-9fGb548eF** [Jigsaw-Code/outline-server#1599]

**Comment by sbruens** [comment]
Can you provide more information on what is not working?

**Comment by i-am-tama-tama** [comment]
In October 2024, Outline client stopped connecting to the server through one operator. Now it is already blocked by two operators I know. After switching to vless, everything worked.
