### ISSUE TITLE
Outline servers (with prefixing) getting blocked in Iran very fast

### ISSUE THREAD

**Issue by noodle-junkie** [Jigsaw-Code/outline-server#1602]
It's been four to three days since blocking of Outline servers are getting very fast in Iran. like in few hours after setting up the server!
Prefixing only delays it but even using TLS prefixes don't prevent the server from getting blocked.

Any solution, novel prefix or patch/update ??

**Comment by sbruens** [comment]
Could you try other prefixes? It might be due to your VPS provider. Have you tried changing providers or try different IP rules (e.g. fixed vs dynamic)?
