### ISSUE TITLE
After the last update, dynamic keys in clients stopped working. 

### ISSUE THREAD

**Issue by goodboy34-tech** [Jigsaw-Code/outline-server#1618]
However, static ones also work. Report in the client's subsection: https://github.com/Jigsaw-Code/outline-apps/issues/2266

Static key: 
![2024-11-14_08-34-52](https://github.com/user-attachments/assets/41193094-902b-4adf-b45b-cda99cc90206)

Dynamic key:
![2024-11-14_08-36-40](https://github.com/user-attachments/assets/84504e0f-7815-4259-894a-5f4ad153d18e)

The bug is not always reproduced, but it is noticeably frequent. Reinstalling doesn't help, and the reboot doesn't help either.

**Comment by sbruens** [comment]
This is indeed a client issue. Let's use https://github.com/Jigsaw-Code/outline-apps/issues/2266 for this.
