### ISSUE TITLE
Port changing when requesting it from API

### ISSUE THREAD

**Issue by mcipovic** [Jigsaw-Code/outline-server#1619]
I have a couple of outline servers installed in various locations. I have noticed that API sometimes returns a different port from the one defined inside the .json config.  

So this is for example "portForNewAccessKeys":4917 and I get 55430 port

Is there some solution for this?

**Comment by sbruens** [comment]
Where are you seeing the 55430 port? How are you creating new keys? Are you using the API or the Manager application?

Please provide steps to reproduce this so we can investigate.

**Comment by sbruens** [comment]
I'm not sure what that is. We don't have a .NET library. Are you referring to https://github.com/FBA-Studio/OutlineManager? If so, that is not an official library and you may want to reach out to the owner of that library instead. For reference, these are our only official repositories: https://github.com/Jigsaw-Code?q=outline.

You can try and see if this also happens using the [API directly](https://github.com/Jigsaw-Code/outline-server/blob/f558117b29ebccfa807f8c6c72c6ea50cc02ae86/src/shadowbox/README.md#access-keys-management-api), which that .NET library seems to wrap. If you're able to reproduce it with the API, feel free to re-open this issue.
