### ISSUE TITLE
Multiple IP Adress In One Server

### ISSUE THREAD

**Issue by ahmetugur91** [Jigsaw-Code/outline-server#1624]
Hi, i have one ubuntu server, lets say i have 2 IP adress, is it possible to serving 2 IP adress as VPN same time? If its yes how? Thank you.

**Comment by sbruens** [comment]
Yes this should work if you point both IPs at the same Outline server. You will need to decide which IPs to put in the static keys for them to connect or use a dynamic key to set the IP you want the key to use.
