### ISSUE TITLE
Connect to outline server through not official client app.

### ISSUE THREAD

**Issue by ZergZe** [Jigsaw-Code/outline-server#163]
I'm trying to substitute the origin outline client for mac with something the same, and to connect to the outline server. 

I took ShadowsocksX-ng (since it is mac) and set it up. Now my safari it tunneled though outline server.
Problem: other mac applications bypass the outline server, but i want all traffic to go through the shadowsocks and outline server.
How can i do that?

First i thought that outline is vpn tunneled through shadowsocks. But in the issues here i read that outline is not vpn, but just a shadowsocks proxy whose client-apps manage to tunnel all the traffic, right? Thus i can't just set up vpn on mac additionally to shadowsocks proxy?

What can i do to tunnel all the traffic through shadowsocks proxy to outline server?

**Comment by fortuna** [comment]
This seems to be an issue with the client you are using, not with the Outline Server. I recommend you install the Outline client for macOS, which is a full system VPN.
