### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by NightMachinary** [Jigsaw-Code/outline-server#169]
I just used the one-liner that used Docker. It is using way too much memory on my VPS, and I wish to uninstall it. How do I proceed?

**Comment by fortuna** [comment]
I'm sorry to hear.

You can delete the running containers with `docker rm -f shadowbox watchtower`
And then clean up the images with `docker system prune -a,
You can delete the `shadowbox` directory as well

**Comment by IvanTurgenev** [comment]
Thanks, os x distribution through mac app store, i dont want to marry apple

**Comment by HassanZahirnia** [comment]
@fortuna Is the uninstall process same as today ? Since your instructions were posted 4 years ago

**Comment by sergey-somkov** [comment]
Looks like directory names changed.
```
$ sudo docker container inspect shadowbox | jq -r '.[0] | .Mounts'
[
  {
    "Type": "bind",
    "Source": "/opt/outline/persisted-state",
    "Destination": "/opt/outline/persisted-state",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  }
]
```
I believe it is `/opt/outline/` directory now.

**Comment by shumtravi** [comment]
> I'm sorry to hear.

It was my favorite app, but today my country can successfully block outline.

**Comment by st4rry** [comment]
Hi, @fortuna,  I'm from MM. I installed the outline server using the oneliner installation instructions, mentioned in the Manager app. I installed it on a server in Bangkok. When we connect it, we can connect it sometimes but mostly we can't. When we cannot connect, it says because of "ServerUnreachable" sometimes or "Invalid Key" sometimes (even if we could be able to connect it using the same key when we can connect). I doubt if I configured it wrong. I've opened the required ports (management and access key). Does it require me to do more firewall configuration like specific port forwardings? Or it's because of the low-cost server I'm running it on? Could you please help me? I can get you on the server if you need.

**Comment by fortuna** [comment]
@st4rry I'm sorry to hear you're are having issues.

There are multiple factors that can affect access:
- The user's internet provider. Is the server working on some but not others?
- The port number. Sometimes blocking on standard ports like 80 or 443 behaves differently than on high port numbers. Try different ports.
- The server cloud provider. Some clouds are popular with VPNs, so they are more targeted. Try different clouds.
- Server location. Sometimes using a different location in the same cloud provider helps.

If none of that works, you can also try using prefix disguises:
https://www.reddit.com/r/outlinevpn/s/2nuGCiupgw

I also recommend dynamic keys, which lets you change the underlying key without having to redistribute them:
https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys

**Comment by st4rry** [comment]
> @st4rry I'm sorry to hear you're are having issues.
> 
> There are multiple factors that can affect access:
> 
>     * The user's internet provider. Is the server working on some but not others?
> 
>     * The port number. Sometimes blocking on standard ports like 80 or 443 behaves differently than on high port numbers. Try different ports.
> 
>     * The server cloud provider. Some clouds are popular with VPNs, so they are more targeted. Try different clouds.
> 
>     * Server location. Sometimes using a different location in the same cloud provider helps.
> 
> 
> If none of that works, you can also try using prefix disguises: https://www.reddit.com/r/outlinevpn/s/2nuGCiupgw
> 
> I also recommend dynamic keys, which lets you change the underlying key without having to redistribute them: https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys

**Comment by st4rry** [comment]
> @st4rry I'm sorry to hear you're are having issues.
> 
> There are multiple factors that can affect access:
> 
>     * The user's internet provider. Is the server working on some but not others?
> 
>     * The port number. Sometimes blocking on standard ports like 80 or 443 behaves differently than on high port numbers. Try different ports.
> 
>     * The server cloud provider. Some clouds are popular with VPNs, so they are more targeted. Try different clouds.
> 
>     * Server location. Sometimes using a different location in the same cloud provider helps.
> 
> 
> If none of that works, you can also try using prefix disguises: https://www.reddit.com/r/outlinevpn/s/2nuGCiupgw
> 
> I also recommend dynamic keys, which lets you change the underlying key without having to redistribute them: https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys

Hi, @fortuna. That's awesome! I've managed to make it work.
