### ISSUE TITLE
Server issue report

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#171]
I am running the server on Azure Japan; I recently had a wired issue on my server port setting. The first port on the server A failed all the time.

-Server IP couldn't ping directly(ping overtime in mainland China)
-Server connection is good; average speed is about 11MB/s to 15MB/s.
-the server is running on the Google cloud and Azure
-Issue server A is located in Japan, owned by Azure:

I can connect A, and I have already done the test, including IP check, blacklist website check.
But I CANNOT connect the first key in this server. (it is key 0 shadowbox_config.json) Even though I rebuild the server(ip doesn't change), the same issue happens. Other keys are fine, and I have already tested today.
I can't connect this key with the outline, or shadowsocks client.
Server B locate in Japan different city, I did same things on this server, but there is no issue. 

Questions: 

If we changed the shadowbox_config.json file directly, like add/remove user data, is this still works?
Should we support more protocols on the servers? Recently, I feel the internet are easy to lose connection or lost for few seconds. I have already tested 8 different servers in Asia, (including aws, azure and gcp) 
The internet will show no connection, but after 10-30s, it can be reconnected again. (my psyscial router works fine, and I checked the router log for connection)
Could we add the connection test script? So I could report more detailed information(like connection issue) to the developers.

**Comment by trevj** [comment]
@sailosha Wow, sorry for the slow repsonse. Seems like you have a related question at https://github.com/Jigsaw-Code/outline-server/issues/230, how about we continue discussion there.
