### ISSUE TITLE
Add random background noise option.

### ISSUE THREAD

**Issue by YegorIevlev** [Jigsaw-Code/outline-server#176]
I suggest adding an option to add random background noise to the traffic, proportional to real traffic, like requests to Alexa/China top-100 websites. This will create the appearance of normal Internet usage, fooling systems that block the foreign IP if all user traffic goes to it.

**Comment by studentmain** [comment]
Good idea. But how/when to enable it? Control by user ( who doesn't
understand it )? Configure in link ( seems good, but can only configure
once )? Enable by default?
Generate noise will generate additional traffic, cause low perfomance with
bad network, and use more data quota, should we deploy it on mobile?

Yegor Ievlev <notifications@github.com> 于 2018年6月16日周六 16:10写道：

**Comment by hadifarnoud** [comment]
allow the user to enable it. they will understand if the explanation is good enough. it can be configured on the server for everyone.

it can be automated too. adding the noise when the connection seems to be slowed down too much. but it may be so hard to detect that

**Comment by hadifarnoud** [comment]
when the shadowsocks connection become so slow, I disable it for a few minutes and re-enable it. that seems to work in Iran. this seems to confirm the noise will work

**Comment by studentmain** [comment]
Maybe you can use wget or curl to manually generate some noise. My server
works well for some days, so I can't test it. I'm in south-west China, my
server in Japan and west America.

Hadi Farnoud <notifications@github.com> 于 2018年6月16日周六 20:06写道：

**Comment by studentmain** [comment]
I suggest write/use a dedicate noise maker service, or implement it as a ss
plugin, so other ss user can use and help enchance it.

If we generate HTTP/HTTPS, we can use simple-obfs or other HTTP/TLS based
technique on real connection.

Hadi Farnoud <notifications@github.com> 于 2018年6月16日周六 20:05写道：

**Comment by YegorIevlev** [comment]
@studentmain `simple-obfs` is incompatible with KCP tunneling and is slower, and detecting it is not very hard without TLS, and even with TLS it has a unique fingerprint.

**Comment by studentmain** [comment]
I think kcptun is unnecessary, I use bbr.
simple-obfs is widely used and works. Of course, if there are other
technique better, we can use better one.

Yegor Ievlev <notifications@github.com> 于 2018年6月17日周日 02:27写道：

**Comment by YegorIevlev** [comment]
@studentmain Can you tell why do you think KCP is unneccessary? Also, does BBR work on Windows?

**Comment by YegorIevlev** [comment]
@studentmain We also need the noise to be indistingushable from real browsing. I think the best option is to make a browser extension for noise generation and making requests to the VPN server.

**Comment by trevj** [comment]
Not sure if this should be client or server-side, but either way one of this or https://github.com/Jigsaw-Code/outline-client/issues/132 is a duplicate :-)

**Comment by YegorIevlev** [comment]
@trevj It should be client.
