### ISSUE TITLE
can't post to snapchat (possible keepalive issue)

### ISSUE THREAD

**Issue by john8862** [Jigsaw-Code/outline-server#178]
Just deployed Outline Server on my own VPS running on CentOS 7.4. Everything seems working fine except Snapchat. I can't send and receive messages in this app. Additionally I've checked VPS firewall rule and necessary ports should already been opened. May I ask which log I can check the network traffic?

Alternatively if someone could help me on some methods I can use to to conduct self-debugging. Honestly not a programmer in life but just have some knowledge on Linux OS usage.

If I missed any important information on this issue request, please feel free to let me know

Have another issue opened in shadowsocks-libev
[https://github.com/shadowsocks/shadowsocks-libev/issues/2098](url)

**Comment by bemasc** [comment]
I wonder if this is related to #85.

**Comment by fortuna** [comment]
@bemasc I wonder that too.

@john8862 what's the client OS you are using?

**Comment by john8862** [comment]
@fortuna It's iOS11.4

**Comment by trevj** [comment]
Wow, this has been idle for a long time. I'm going to bundle it with this keepalive issue, which I think must be related:
https://github.com/Jigsaw-Code/outline-server/issues/85

**Comment by MrBenFTW** [comment]
Hi, I am facing this issue on my app.
