### ISSUE TITLE
Can't find any mention about shadowsocks project on homepage

### ISSUE THREAD

**Issue by 7sDream** [Jigsaw-Code/outline-server#18]
I tried this project (setup a server successfully and connect from Linux and Android), outline is definitely an excited and beautiful work. :100: 

But when I connect the server from client, I was surprised to find the URI is start with `ss://`, so the underlying network protocol and implement are from shadowsocks project, right?

I feel surprised because I don't see any information about shadowsocks project in outline's homepage(even in HTML source code) when I follow the guide to setup a server.

Emmm, there is nothing wrong because open source project don't request any mention in other's homepage when they are using it.

But is it meet the spirit of open source? 

IMHO, add some words like `powered by` or `based on shadowsocks` with a link maybe a good idea?

Or hide the implement detail in homepage can give new user a `easy-to-use` feeling?

Discussion welcome :speech_balloon:

**Comment by hybtoy** [comment]
It look like pure shadowsocks with slight ui and code change.
They added manager and way the way to buy it in few clicks. So, most of the people can protect themselves without Linux knowledge. Bravo.

**Comment by fortuna** [comment]
Hey there!

There's mention of Shadowsocks at the top entry of the Help Center:
http://getoutline.org/en/support/outlineUnique

> Outline is open source. You can check out and contribute to the Outline code on GitHub. **Outline uses Shadowsocks, a secure open-source protocol that is trusted by millions of users to access the free and open web**. In November 2017, Outline was audited by Radically Open Security, a non-profit cybersecurity firm in the Netherlands. You can read their public report here.

**Comment by fortuna** [comment]
I'll reopen the issue because the mention is not on the homepage as the original issue expected. I'm sorry for closing it so fast.

@7sDream and others from the Shadowsocks community: is the mention on the Help Center enough? What do you think is fair?

**Comment by 7sDream** [comment]
Oh, I missed the Help Center page in whole tour of setting up an Outline server and use it, which shows how good your work is, keeping it simple while making it powerful. :+1: 

I think it's OK to introduce implement detail and underlying project in Help(or About) page.

But I also think this issue is not all depends on my opinion, I suggest just keep it open and do more discuss.

**Comment by gledos** [comment]
不把 shadowsocks 写在官网上是十分不道德是事，没想到谷歌下面的工作室就是这么对待开源项目的。

**Comment by peterzcc** [comment]
I'd suggest to clarify the position of SS in the homepage if this tool is basically the original version of Shadowsocks wrapped with GUI. The misleading description and media exposure have disappointed us.

**Comment by laosb** [comment]
Personally I don't think mentioning Shadowsocks makes much sense to those non-tech users, and tech users can easily find it's based on Shadowsocks. Jigsaw's behavior doesn't break the law and actually it does mention it in Help Center. I don't see the necessity doing so, but it won't be big deal mentioning on Homepage.

**Comment by sandrigo** [comment]
Thanks for voicing this! Sorry for the delay in getting back to this.

Upon launch we had a couple of mentions of Shadowsocks: in the [Help Center](https://getoutline.org/en/support) and in the official [blog post](https://medium.com/jigsaw/introducing-outline-making-it-safer-to-break-the-news-feda4d047b4) in Medium. But we heard you, so just to avoid any doubts we added a mention on [the homepage](https://getoutline.org/en/home), the ‘About’ section of the Outline Manager and Clients, the Github repository descriptions, and the README files. Hope this clarifies, thanks!
