### ISSUE TITLE
Server LOG

### ISSUE THREAD

**Issue by kalhori124** [Jigsaw-Code/outline-server#183]
I Installed Outline-Server through docker and sometimes I cannot connect to the server and I want to see the log. Where can I see it ?

**Comment by fortuna** [comment]
Do you mean the install log? You can try `cat /root/shadowbox/install-shadowbox-output`

**Comment by lipangit** [comment]
Sometimes I cannot connect too, I want to know where is the running log?

**Comment by v-osnovnom-bezvreden** [comment]
same problem here. Sometimes there is no connection through outline. How do I  troubleshoot?

**Comment by kndenisenko** [comment]
Same problem. Suddenly connection drops from phone or from Mac. Maybe it might be related to sleep mode. When device wakes up, connection can be dropped
