### ISSUE TITLE
Configuring openwrt router as a client

### ISSUE THREAD

**Issue by naveensrinivasan** [Jigsaw-Code/outline-server#187]
I have the server running. I have openwrt router. How do I connect to the server? I didn't find any instructions.

Thanks

**Comment by fortuna** [comment]
We don't support OpenWRT.
You can check the OpenWRT client listed at https://shadowsocks.org/en/download/clients.html.

**Comment by yegorkryukov** [comment]
@fortuna
Does it mean that you don’t provide help with openwrt or that openwrt in general cannot be connected to the outline server?

**Comment by fortuna** [comment]
We don't have the resources to support OpenWRT, though technically one should be able to make it work.
Outline Servers work with Shaodwsocks clients. You just need to configure the client with the ss:// link

**Comment by AnonymousWebHacker** [comment]
> 2021 ¿no hay noticias de actualización para la configuración del enrutador openwrt, señor?

https://openwrt.org/docs/guide-user/services/proxy/shadowsocks

**Comment by radlevich12** [comment]
Here is the guide for it https://andrevi.ch/2023/07/15/setting-up-the-outline-vpn-client-on-openwrt/
