### ISSUE TITLE
Outline-server down - how to fix? [solved - still...]

### ISSUE THREAD

**Issue by 4044ever** [Jigsaw-Code/outline-server#189]
Outline-server is down. How can I fix it?  (it works now, but I like to ask what would be the most efficient way, what I did worked, but seems clumsy)

I wanted to simply re-install, for that I need to remove the containers, so i did:

`docker rm -fv watchtower shadowbox   `

But got an error message:

`Error response from daemon: unable to remove filesystem for 804***bfad5/mounts/shm: device or resource busy`

Then I used the brute force method:

`docker system prune -a `

That worked, And a `wget......`

There I got stuck with:

```
> Starting Shadowbox .......................... FAILED
Unable to find image 'quay.io/outline/shadowbox:stable' locally
stable: Pulling from outline/shadowbox
```

Then I get to: 

```
root@oline01:~# sudo wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash
> Verifying that Docker is installed .......... OK
***
> Generating SHA-256 certificate fingerprint .. OK
> Starting Shadowbox .......................... FAILED
Unable to find image 'quay.io/outline/shadowbox:stable' locally
stable: Pulling from outline/shadowbox
605ce1bd3f31: Pulling fs layer
****
1436fe24816f: Pull complete
Digest: sha256:007b8a2***c32891
Status: Downloaded newer image for quay.io/outline/shadowbox:stable
docker: Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container "8049b73810***c3dbfad5". You have to remove (or rename) that container to be able to reuse that name.
```

I did ftp to` /var/lib/docker/containers/`

There where 3 directories /var/lib/docker/containers/7a2cf7f*** (+1 more) that didn't allow, delete, but rename. After the re-name I did:

```
docker rm -fv watchtower shadowbox   
docker system prune -a   
```

And installation was fine. Strangely for me, all keys in the manager still work.

I wonder what was going on?

**Comment by sailosha** [comment]
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-serve
r/master/src/server_manager/install_scripts/install_server.sh)"`

try this one, and give all the premission.

**Comment by trevj** [comment]
@4044ever Thanks for trying Outline! Sorry you've been having troubles. Can I ask which OS and cloud provider you're running on?

**Comment by 4044ever** [comment]
@trevj
Debian8 on ArubaCloud. A 1Gb VPS. It happen only once so far. Since I posted it a few weeks ago there wasn't any other stalling.

If a server reboots, wouldn't Outline-Server start automatically? I guess it does. 

Anyway, I had another Outline on another VPS that I could use.

**Comment by trevj** [comment]
@4044ever OK I'm glad you got it up and running! Yes, if server reboots then Outline should restart on startup (via Docker).

**Comment by samascience** [comment]
chmod: changing permissions of '/opt/outline': Operation not permitted
