### ISSUE TITLE
Bower with root access error

### ISSUE THREAD

**Issue by 4faramita** [Jigsaw-Code/outline-server#19]
When building outline-server, if I run "yarn" with root, it stops at "bower install" with error "bower ESUDO         Cannot be run with sudo"
I have to manually run "/home/ubuntu/outline-server/src/server_manager/node_modules/.bin/bower install --allow-root"

**Comment by albertolalama** [comment]
@4faramita, I believe you can get around this issue by creating a `/root/.bowerrc` file with the following contents: `{ "allow_root": true }`. `yarn` should succeed thereafter.

**Comment by sailosha** [comment]
Hey 4faramita I have the same issue. I build it on google cloud platform. Also, I have problem for yarn primission denied.

**Comment by fortuna** [comment]
For your own safety, you should probably use a non-root user for bower install.

I'll close this issue because we don't really support building as root and it can be a security issue to developers to support that.

**Comment by fortuna** [comment]
It might be reasonable to build as root in a container, so I added a line to the README file explaining how you can get it working: https://github.com/Jigsaw-Code/outline-server/blob/master/README.md#setup

**Comment by 4faramita** [comment]
@fortuna I think this reminder would be enough.
cheers
