### ISSUE TITLE
[FEATURE REQUEST] Support multiple servers in Outline Manager

### ISSUE THREAD

**Issue by NightMachinary** [Jigsaw-Code/outline-server#190]
PS: How can I get the string needed by Outline Manager to connect to the server from a server that was set up sometime before? `docker logs shadowbox`? Which line would I need then?

**Comment by fortuna** [comment]
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/78

**Comment by fortuna** [comment]
You can find the access config at `/root/shadowbox/access.txt`

**Comment by NightMachinary** [comment]
@fortuna `cat: /root/shadowbox/access.txt: No such file or directory`
