### ISSUE TITLE
build failed solution

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#192]
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-serve
r/master/src/server_manager/install_scripts/install_server.sh)"`

Try to use this one to start up your servers just for now.

**Comment by fortuna** [comment]
@sailosha, what's the issue here?

**Comment by sailosha** [comment]
@fortuna The build was failed by the processing program 4 days ago. At that time, there is error on my servers to build up with src/shadowbox command.

**Comment by fortuna** [comment]
My understanding is that you are trying to run the server on your own machine. What's the OS? The server runs on Linux only. What was the error message?

**Comment by fortuna** [comment]
I'll close since I heard no response, so I'm assuming it's fixed. Feel free to reopen if needed.
