### ISSUE TITLE
Limit Simultaneous Connections per User

### ISSUE THREAD

**Issue by yakovmanshin** [Jigsaw-Code/outline-server#208]
I’d like to be able to limit the number of simultaneously connected devices per access key: just like Netflix limits the number of devices you can stream on at the same time.

**Comment by trevj** [comment]
@yakovmanshin Thanks for the suggestion! I forgot about this long-standing request which I think also covers this:
https://github.com/Jigsaw-Code/outline-server/issues/32

**Comment by DonAsasi** [comment]
Hi, is this feature completed? added? So can I limit a key to only 1 device connection at a time? Wonderful. How is it work?

Thanks
