### ISSUE TITLE
Half dialog covers other UI

### ISSUE THREAD

**Issue by cybort** [Jigsaw-Code/outline-server#218]
![default](https://user-images.githubusercontent.com/11025365/43686719-05a2faa0-98fd-11e8-867f-e3c39c0dd9e0.png)
Can not resize the window or move right to click button on the dialog. Stuck at this stage.

**Comment by cybort** [comment]
And just find another bug: after I destroy my old server and create a new one(which has different ip), the "get connected" still provide me with the old key.
![default](https://user-images.githubusercontent.com/11025365/43686909-bc431e1e-98ff-11e8-9933-88557fb40519.png)
I have to add a key manually to generate key with my new server.

**Comment by trevj** [comment]
@cybort Thanks for trying Outline. Sorry you've been having problems. Can I ask on which platform you're running the Outline Manager?

**Comment by cybort** [comment]
Windows 10 x64

**Comment by alalamav** [comment]
We redesigned the app's UI a while back. Please reopen if the problem persists on the latest version of the app.
