### ISSUE TITLE
503 on outline manager download.

### ISSUE THREAD

**Issue by JeffCleverley** [Jigsaw-Code/outline-server#224]
Looking forward to it being back up.

<img width="1312" alt="screen shot 2018-08-10 at 18 33 14" src="https://user-images.githubusercontent.com/25419360/43972342-ef510616-9ccb-11e8-90a1-9ee00946019b.png">

**Comment by trevj** [comment]
@JeffCleverley Looks like a temporary failure - working now for me, want to retry?
