### ISSUE TITLE
when i used the command "yarn do $ACTION" it repo this...

### ISSUE THREAD

**Issue by was277** [Jigsaw-Code/outline-server#23]
yarn run v1.5.1
$ bash ./scripts/do_action.sh
++ git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
+ export ROOT_DIR=
+ ROOT_DIR=
+ export BUILD_DIR=/build
+ BUILD_DIR=/build
+ export -f do_action
+ do_action
+ readonly 'STYLE_BOLD_WHITE=\033[1;37m'
+ STYLE_BOLD_WHITE='\033[1;37m'
+ readonly 'STYLE_RESET=\033[0m'
+ STYLE_RESET='\033[0m'
./scripts/do_action.sh: line 29: $1: unbound variable
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c bash ./scripts/do_action.sh
Directory: /home/ec2-user/outline-server-master
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/ec2-user/outline-server-master/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bemasc** [comment]
Did you run the literal command `yarn do $ACTION`?  This is just a generic example.  It will not do anything.

You probably want to run a command like `yarn do server_manager/electron_app/run`.

**Comment by trevj** [comment]
@was277 Thanks for the report. Can you tell us what you were trying to do?

**Comment by trevj** [comment]
@was277 Please re-open if you still need help with this.

**Comment by gulprun** [comment]
the instruction with `yarn do {$ACTION}` was really vague, actually the first run was so confusing.
