### ISSUE TITLE
 Where is the shadowsocks setting in the server? 

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#230]
There should be a file named shadowsocks.json in the server to manage some setting for the shadowsocks.
I am Optimizing Shadowsocks by using TCP Fast Open, but I couldn't find the setting file in my server.
Could someone give me a hand please?

**Comment by trevj** [comment]
@sailosha I'm afraid there's currently no easy way to do this:
- the arguments supplied to `ss-server` are hard-coded into Shadowbox: https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/libev_shadowsocks_server.ts#L39
- Shadowbox doesn't supply the `-c` argument to `ss-server`

We'd have to modify Shadowbox to add the `-c` switch, allowing you edit the options.

**Comment by sailosha** [comment]
@trevj  Thanks!  Problem solved

**Comment by sailosha** [comment]
@trevj for the issue  #171 all good now, I think it is old version shadowsocks-libev and gfw issue. GFW has some special machine learning algo to judge vpn socket.
