### ISSUE TITLE
I use digital ocean and it created a 512MB ram droplet

### ISSUE THREAD

**Issue by temon** [Jigsaw-Code/outline-server#24]
I am not sure why the outline-server created the 512MB ram droplet instead of 1GB ram droplet.

if I check, the cheapest droplet in the Digital Ocean is $5 for 1GB ram droplet.

thanks.

**Comment by chipz** [comment]
Seems like it's hardcoded to 512mb

```
const MACHINE_SIZE = '512mb';
```
taken from:
https://github.com/Jigsaw-Code/outline-server/blob/d8cb1575d10358c2312d4e0ef286092763258acc/src/server_manager/web_app/digitalocean_server.ts

I'll try to create a PR to change this
