### ISSUE TITLE
Installation on raspberry pi | Setting up as Node

### ISSUE THREAD

**Issue by erapto** [Jigsaw-Code/outline-server#244]
Hello,
I am trying to execute the script on a Raspberry pi 3 B+ and installation hangs on the step "Waiting for Outline Server to be healthy"
I have opened the ports and restarted the script but no luck. It seems that the script cannot get out of the loop in the wait_shadowbox function and hangs at the step:
`until curl --insecure -s "${LOCAL_API_URL}/access-keys" >/dev/null; do sleep 1; done`
Can you please help me out?
I already looked at the comments from @fortuna and  @ex7r3me in thread #27 

Docker logs display:
`standard_init_linux.go:190: exec user process caused "exec format error"`

I have started trying to build a docker image **directly from the Dockerfile**. As the Dockerfile is based on an Alpine image I have changed the FROM statement to:
`FROM resin/rpi-raspbian`
Also the `RUN apk`  command had to be replaced to apt-get to install `lsof` on the image:
`RUN apt-get update`
`RUN apt-get install lsof`
I believe `curl` is already part of the raspian so no need to fetch that in

If someone with experience can help that would be highly appreciated

**Comment by erapto** [comment]
Update:
I abandoned the Docker method and tried to build the outline server as a Node.js.
While I managed to build the app with yarn as described in the README file, I am not able to run the server.

When I run the script `run_action.sh` I get an error message:
`internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/outline-server/src/shadowbox/server/outline-server/shadowbox/app/server/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)`

Any ideas why?

**Comment by trevj** [comment]
@erapto Thanks for trying Outline. As I guess you've figured out by now, we don't currently maintain Docker images for the Raspberry Pi - that's why you need to run "manually" via Node.js. I'm afraid I don't have a Pi for testing but I don't see why `yarn do shadowbox/server/run` would fail. Which versions of Node and yarn do you have installed?

**Comment by erapto** [comment]
Hi @trevj and thank you for helping out!
I managed to overcome this issue - apparently I had to modify the directory path in the script, as for some reason the above directory was built up incorrectly.
Following that I tried to modify your install script and remove the docker (and watchtower) references trying to follow the same logic. That got me to a point where the "install string" for shadowbox was successfully generated, however the server seems not to be running correctly (this is despite I opened the generated port on my router NAT and firewall).
Also I have the issue that `maxminddb` is not present on my system. Do I have to install this or can I ignore the error message?
The modified script reads as follows just in case you can help me figure out if I did something wrong.
Thanks again!

**Comment by erapto** [comment]
@trevj I posted a copy of the modified script

**Comment by trevj** [comment]
@erapto Good to hear you had some success! I think you;ll need to run Shadowbox in the background, perhaps with the `&` operator, e.g. line 173 would become:
```bash
  node main &
```
That's not really the right way to run a process in the background (you will have to kill it manually with a command like `pkill -f node`) but I hope that helps a little.

**Comment by erapto** [comment]
Thank you @trevj. Finally I managed to install maxminddb and get past the error message. I also had to install jasmine, npm, tcp which were not present on the raspberry. Using the modified script (and after commenting out the `run_step` functions related to docker, I managed to run the node without errors.
I now use a modified version of `run_action.sh` to pass on the generated server configuration (certificates, port) in order to run the node. 

Following that was also able to install the server in the Outline Manager app (the string generated from the install.sh worked), however I am still not able to connect to the server. On top when I try to add a key in the Outline Manager I get the following error:

`tf-poly1305","password":"GM1mTyWn3xod"}],"nextId":1}`
`I2018-09-17T15:24:51.091Z 15723 libev_shadowsocks_server.js:31] Starting server on port 1841`
`I2018-09-17T15:24:51.092Z 15723 libev_shadowsocks_server.js:40] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 1841 -k GM1mTyWn3xod --manager-address 127.0.0.1:24796`
`E2018-09-17T15:24:51.115Z 15723 libev_shadowsocks_server.js:53] Error spawning server on port 1841: Error: spawn ss-server ENOENT`
`D2018-09-17T15:27:35.779Z 15723 manager_service.js:92] listAccessKeys request [object Object]`

Just to highlight that the address 127.0.0.1 is not the IP of the host (actually this address is not on my network).

Also when I run

**Comment by aguilajesus** [comment]
@erapto in case you still want to pursue docker on Pi; I was able to created a docker image with some small changes to the Dockerfile and replacing two ARM binaries.

 for dockerfile you need to use the ARM image versions :
- https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/docker/Dockerfile#L15
   - FROM arm32v6/golang:1-alpine as outline-ss-server
- https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/docker/Dockerfile#L20
   - FROM arm32v6/node:8.12-alpine

for the ARM binaries, you will need to replace these files with their ARM counter parts:

- https://github.com/Jigsaw-Code/outline-server/blob/master/third_party/prometheus/prometheus
- https://github.com/Jigsaw-Code/outline-server/blob/master/third_party/prometheus/promtool

you can download the [code](https://github.com/prometheus/prometheus#building-from-source) and build the binaries on your raspberry

if you use the preferred build method `yarn do shadow/docker/build` you will have to set the variable `DOCKER_CONTENT_TRUST` to 0

Please note that you might also have to download and install nodejs and yarn from their sources.

**Comment by siavashs** [comment]
As I checked the `node` docker images also support **ARM** architecture and the linux client fetches the correct image automatically. So technically I should be able to build my own `shadowbox` docker image for **ARM**. The default `shadowbox` image that the installer uses can be overridden using `${SB_IMAGE}` variable.
For `v2tec/watchtower` there are `armhf*` tags. This image name is hardcoded in the installer script so I need to modify it.

I'll open a PR later if I manage to get it running.

**Comment by shaomeng** [comment]
I wish the Outline Team officially support a Raspberry Pi build. @siavashs , do you have a PR for your script? If so, I'd like to give it a test ;)

**Comment by EricQmore** [comment]
@erapto Do you had solved the problems to install outline server on raspbian? I just got the raspberry pi 4 and it still has the same issue. I could install the outline server on Ubuntu 16.0.4 and it works very well. However, the latest Ubuntu Mate still can't support the raspberry pi 4. It seems I should still try to run it in on raspbian. Could you please kindly to share your solution?

**Comment by siavashs** [comment]
I have a PR open for the `ss-server` since April but it was ignored: https://github.com/Jigsaw-Code/outline-ss-server/pull/23

**Comment by oreoluwa** [comment]
I have a reference implementation for arm architecture here: https://github.com/Jigsaw-Code/outline-server/pull/496

Basically, it 
1. builds the outline-ss-server from source, but could also pull the latest release(wasn't available when I started building this, but it's now available)
2. pulls the prometheus binary from the latest release

To use the `install_server.sh` on your RaspberryPi or an arm arch, 
1. you can build the docker image and tag and push appropriately, then set the `SB_IMAGE` env variable OR you can use the `oreoluwa/shadowbox:latest` image on dockerhub(but I wouldn't advice that because I may not be able to keep up with the releases in the upstream)
2. set the `WATCHTOWER_IMAGE` to `v2tec/watchtower:armhf` and run your script.

**Comment by AwesomestCode** [comment]
Mind giving slightly more detailed instructions on how to set up for raspi 3B+? I'm new to docker, and am sort of confused.

**Comment by ken1029** [comment]
> Mind giving slightly more detailed instructions on how to set up for raspi 3B+? I'm new to docker, and am sort of confused.

I built an arm version of the outline server.
You can try it,This includes armv7 (PI) and arm64
[https://github.com/ken1029/outline-vpn-arm](https://github.com/ken1029/outline-vpn-arm)

**Comment by AwesomestCode** [comment]
Thanks, has worked for me!

**Comment by EricQmore** [comment]
Thanks for your great works. It works for me. 

However, it seems the watchtower can't update the latest version of Outline server. 

I checked the server version on Outline manager it always show 1.2.0, meanwhile, my another Outline server on GCP, the server version is 1.2.2. And the latest version is more reachable by the China users. 

Do you have any idea to update the Outline Server version by  manual? 

> > Mind giving slightly more detailed instructions on how to set up for raspi 3B+? I'm new to docker, and am sort of confused.
> 
> I built an arm version of the outline server.
> You can try it,This includes armv7 (PI) and arm64
> https://github.com/ken1029/outline-vpn-arm

**Comment by oreoluwa** [comment]
Great job on this @ken1029.
FWIW, the newest versions of the [watchtower](https://github.com/containrrr/watchtower) images were built for the ARM architecture, so you may not need to rebuild that.

@EricQmore to try to highlight the issue here:
While [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server)(the shadowsocks wrapper) has an ARM binary build, the [outline-server](https://github.com/Jigsaw-Code/outline-server) docker image does not yet support ARM arch, primarily because the bundled prometheus and outline-ss-server binaries were packaged for macos and linux(on x86 and amd64 arch).
Therefore, until the Outline team decides to start supporting the ARM architecture, anyone providing an image probably have to do it manually and may not always have the time to go through this process. Hence why @ken1029 might not have an updated build.
Anyway, I have just completed the setup of a daily build to deploy a new image using the master branch, so if you're not bothered about getting experimental/unreleased updates, you can use the image at: https://hub.docker.com/r/oreoluwa/shadowbox
And you can always see what's in the builds @https://github.com/oreoluwa/outline-server/tree/shadowbox/deploy
I deployed my instance on the RPi4 using the following command: 
```bash 
SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh
```

**Comment by EricQmore** [comment]
Thanks for your explanation. @oreoluwa 

I have tried your command, it seems works. However, my outline manager can't reach my server anymore. Should I try to get the ApiUrl again? 

The following is the output, FYI. 





> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
> The container name "shadowbox" is already in use by another container. This may happen when running this script multiple times. We will attempt to remove the existing container and restart it. Would you like to proceed? [Y/n] Y
> Removing shadowbox container ................ OK
> Restarting shadowbox ........................ OK
> Starting Watchtower ......................... FAILED
docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "b781fa51cefa03e28a65b92e80907cea3d7e28f119525ad0bec5d4568ed287b5". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you._


> Great job on this @ken1029.
> FWIW, the newest versions of the [watchtower](https://github.com/containrrr/watchtower) images were built for the ARM architecture, so you may not need to rebuild that.
> 
> @EricQmore to try to highlight the issue here:
> While [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server)(the shadowsocks wrapper) has an ARM binary build, the [outline-server](https://github.com/Jigsaw-Code/outline-server) docker image does not yet support ARM arch, primarily because the bundled prometheus and outline-ss-server binaries were packaged for macos and linux(on x86 and amd64 arch).
> Therefore, until the Outline team decides to start supporting the ARM architecture, anyone providing an image probably have to do it manually and may not always have the time to go through this process. Hence why @ken1029 might not have an updated build.
> Anyway, I have just completed the setup of a daily build to deploy a new image using the master branch, so if you're not bothered about getting experimental/unreleased updates, you can use the image at: https://hub.docker.com/r/oreoluwa/shadowbox
> And you can always see what's in the builds @https://github.com/oreoluwa/outline-server/tree/shadowbox/deploy
> I deployed my instance on the RPi4 using the following command:
> 
> ```shell
> SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh
> ```
> 
> PS: please always be sure you're using the `daily` tag

**Comment by EricQmore** [comment]
Thanks for your explanation. @oreoluwa 

I have tried your command, it seems works. However, my outline manager can't reach my server anymore. Should I try to get the ApiUrl again? 

The following is the output, FYI. 



> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
> The container name "shadowbox" is already in use by another container. This may happen when running this script multiple times. We will attempt to remove the existing container and restart it. Would you like to proceed? [Y/n] Y
> Removing shadowbox container ................ OK
> Restarting shadowbox ........................ OK
> Starting Watchtower ......................... FAILED
docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "b781fa51cefa03e28a65b92e80907cea3d7e28f119525ad0bec5d4568ed287b5". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you._


> Great job on this @ken1029.
> FWIW, the newest versions of the [watchtower](https://github.com/containrrr/watchtower) images were built for the ARM architecture, so you may not need to rebuild that.
> 
> @EricQmore to try to highlight the issue here:
> While [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server)(the shadowsocks wrapper) has an ARM binary build, the [outline-server](https://github.com/Jigsaw-Code/outline-server) docker image does not yet support ARM arch, primarily because the bundled prometheus and outline-ss-server binaries were packaged for macos and linux(on x86 and amd64 arch).
> Therefore, until the Outline team decides to start supporting the ARM architecture, anyone providing an image probably have to do it manually and may not always have the time to go through this process. Hence why @ken1029 might not have an updated build.
> Anyway, I have just completed the setup of a daily build to deploy a new image using the master branch, so if you're not bothered about getting experimental/unreleased updates, you can use the image at: https://hub.docker.com/r/oreoluwa/shadowbox
> And you can always see what's in the builds @https://github.com/oreoluwa/outline-server/tree/shadowbox/deploy
> I deployed my instance on the RPi4 using the following command:
> 
> ```shell
> SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh
> ```
> 
> PS: please always be sure you're using the `daily` tag

**Comment by oreoluwa** [comment]
@EricQmore that's basically saying your previous install is still running. You can stop and remove the container with: `docker rm -f shadowbox watchtower`

**Comment by EricQmore** [comment]
@oreoluwa Thank your great work!! It works very well now, and it's the latest Outline server version 1.2.3.

**Comment by EricQmore** [comment]
@oreoluwa Thanks for your great work!! It works very well now, and it's the latest Outline server version 1.2.3.

**Comment by EricQmore** [comment]
> @EricQmore that's basically saying your previous install is still running. You can stop and remove the container with: `docker rm -f shadowbox watchtower`.
> Specifically, that the watchtower container is still running
@oreoluwa If the watchtower docker would pull the latest shadowbox daily? Because my Outline server on GCP is updated to version 1.3.0 from 3 days ago. However, my outline server on RPi 4 is version 1.2.4, and I tried to reboot the RPi everyday, it's still don't updated.

**Comment by EricQmore** [comment]
@oreoluwa If the watchtower docker would pull the latest shadowbox daily? Because my Outline server on GCP is updated to version 1.3.0 from 3 days ago. However, my outline server on RPi 4 is version 1.2.4, and I tried to reboot the RPi everyday, it's still don't updated.

**Comment by EricQmore** [comment]
@oreoluwa If the watchtower docker would pull the latest shadowbox daily? Because my Outline server on GCP was updated to version 1.3.0 from 3 days ago. However, my outline server on RPi 4 is version 1.2.4, and I tried to reboot the RPi everyday, it's still don't updated.

**Comment by oreoluwa** [comment]
@EricQmore that should have been updated to 1.3.1 now; I made some mistakes in the build script hence why it wasn't updated previously.

**Comment by EricQmore** [comment]
> @EricQmore that should have been updated to 1.3.1 now; I made some mistakes in the build script hence why it wasn't updated previously.

Thank you, it works again!

**Comment by scopolamine1401** [comment]
> Thanks for your explanation. @oreoluwa
> 
> I have tried your command, it seems works. However, my outline manager can't reach my server anymore. Should I try to get the ApiUrl again?
> 
> The following is the output, FYI.
> 
> > Verifying that Docker is installed .......... OK
> > Verifying that Docker daemon is running ..... OK
> > Creating persistent state dir ............... OK
> > Generating secret key ....................... OK
> > Generating TLS certificate .................. OK
> > Generating SHA-256 certificate fingerprint .. OK
> > Writing config .............................. OK
> > Starting Shadowbox .......................... FAILED
> > The container name "shadowbox" is already in use by another container. This may happen when running this script multiple times. We will attempt to remove the existing container and restart it. Would you like to proceed? [Y/n] Y
> > Removing shadowbox container ................ OK
> > Restarting shadowbox ........................ OK
> > Starting Watchtower ......................... FAILED
> > docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "b781fa51cefa03e28a65b92e80907cea3d7e28f119525ad0bec5d4568ed287b5". You have to remove (or rename) that container to be able to reuse that name.
> > See 'docker run --help'.
> 
> Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you._
> 
> > Great job on this @ken1029.
> > FWIW, the newest versions of the [watchtower](https://github.com/containrrr/watchtower) images were built for the ARM architecture, so you may not need to rebuild that.
> > @EricQmore to try to highlight the issue here:
> > While [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server)(the shadowsocks wrapper) has an ARM binary build, the [outline-server](https://github.com/Jigsaw-Code/outline-server) docker image does not yet support ARM arch, primarily because the bundled prometheus and outline-ss-server binaries were packaged for macos and linux(on x86 and amd64 arch).
> > Therefore, until the Outline team decides to start supporting the ARM architecture, anyone providing an image probably have to do it manually and may not always have the time to go through this process. Hence why @ken1029 might not have an updated build.
> > Anyway, I have just completed the setup of a daily build to deploy a new image using the master branch, so if you're not bothered about getting experimental/unreleased updates, you can use the image at: https://hub.docker.com/r/oreoluwa/shadowbox
> > And you can always see what's in the builds @https://github.com/oreoluwa/outline-server/tree/shadowbox/deploy
> > I deployed my instance on the RPi4 using the following command:
> > ```shell
> > SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: please always be sure you're using the `daily` tag

@oreoluwa This is what I get when I run your code: 
`SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh`

Unsupported machine type: aarch64. Please run this script on a x86_64 machine

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_log9Fb

**Comment by SmartBoy84** [comment]
For some reason, they've added a check to ensure the machine's architecture, just search for ```MACHINE_TYPE``` in the file and set it's value to ```x86_64```
Works for me. @scopolamine1401

**Comment by scopolamine1401** [comment]
Thank you so much @SmartBoy84 It does work

**Comment by EricQmore** [comment]
> For some reason, they've added a check to ensure the machine's architecture, just search for `MACHINE_TYPE` in the file and set it's value to `x86_64` Works for me. @scopolamine1401

@SmartBoy84 Thank you, it works for me also. I modified the install script like the following command according to your suggestion:

`SB_IMAGE=oreoluwa/shadowbox:daily sudo --preserve-env bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh`

**Comment by Joy096** [comment]
> 

Hello, I try to run the following command on my ARM64 VPS, but I get the next error

```
> Installing Docker ........................... Docker installation failed, plea                                                                                                             se visit https://docs.docker.com/install for instructions.

Last error: # Executing docker install script, commit: b2e29ef7a9a89840d2333637f                                                                                                             7d1900a83e7153f
+ sh -c apt-get update -qq >/dev/null
E: Репозиторий «http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release» н                                                                                                             е содержит файла Release.

Sorry! Something went wrong. If you can't figure this out, please copy and paste                                                                                                              all this output into the Outline Manager screen, and send it to us, to see if w                                                                                                             e can help you.
Full log: /tmp/outline_logHsn

```

**Comment by Joy096** [comment]
@[EricQmore](https://github.com/EricQmore)

**Comment by EricQmore** [comment]
@oreoluwa Hi Oreoluwa, the latest version of Outline, 1.8.1, has been released, but the image file pulled from your Docker Hub is still version 1.6.1. Is there a way to update to the latest version, 1.8.1? 
Thank you very much.

**Comment by EricQmore** [comment]
@oreoluwa 
Hi Oreoluwa, the latest version of Outline, 1.8.1, has been released, but the image file pulled from your Docker Hub is still version 1.6.1. Is there a way to update to the latest version, 1.8.1?
Thank you very much.

[https://github.com/Jigsaw-Code/outline-server/releases/tag/server-v1.8.1](url)

**Comment by ylexus** [comment]
@oreoluwa yes would it be difficult to rebuild it against the latest Outline please?
