### ISSUE TITLE
Is that passible to config custom port instead of random port in docker while server is created? 

### ISSUE THREAD

**Issue by Rezhe** [Jigsaw-Code/outline-server#248]
Here is situation, our school is blocked every port except 443 / 80, so I hope there is a way to config this by some simple command.

**Comment by Rezhe** [comment]
Thinks XD

**Comment by studentmain** [comment]
You need set a enviroment variable before start script. You can look at earlier issue for it.
If my memory is correct, it's `export SB_SERVER_PORT=80`
Or you can just use ss-libev or other ss server

**Comment by Rezhe** [comment]
@studentmain thx for reply, the only port variable I found is SB_API_PORT, which doesn't work at all

**Comment by Rezhe** [comment]
I think the port is [here](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/infrastructure/get_port.ts)
````
const MAX_PORT = 65535;
const MIN_PORT = 1024;
`````
If so, does that means shadowbox can not be simply installed by 
````
bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
`````
in order to have 443 port?

**Comment by trevj** [comment]
@Rezhe Thanks for trying Outline. Great question. I'm afraid there are multiple ports in play:
- one port for the management API, used by the server manager (configured by `SB_API_PORT`)
- multiple ports, one for each access key

If your firewall blocks everything except port 80/443 I'm afraid you're out of luck. We're working to change this - all access keys and management API on one port - but it's not ready for testing just yet.

**Comment by trevj** [comment]
BTW, this has been requested multiple times:
https://github.com/Jigsaw-Code/outline-server/issues/44
