### ISSUE TITLE
Invalid Access Key Error on custom server 

### ISSUE THREAD

**Issue by bingoelzouhery** [Jigsaw-Code/outline-server#252]
I have installed Ouline manager and created a server on Digital Ocean and this one connects just fine, then i followed these steps to setup my own server since i already have a server on Digital Ocean 
https://www.jumpthegreatfirewall.com/shadowsocks/#step1
All steps were successful on my server and then when i tried to generate the access key and try it on my client i got the Invalid access key 
![image](https://user-images.githubusercontent.com/3327554/45259876-ab6a2180-b3d7-11e8-9586-2fa5b1b17251.png)

**Comment by bingoelzouhery** [comment]
I also tried Android but i get the same issue

**Comment by bingoelzouhery** [comment]
Never mind it was a firewall issue, sorry for the invonveniance

**Comment by trevj** [comment]
@bingoelzouhery Glad you got it working!

**Comment by Axoncodes** [comment]
@elzouhery What did you change exactly that solved your problem
