### ISSUE TITLE
How to connect to existing Outline Server using Outline Manager?

### ISSUE THREAD

**Issue by lgg** [Jigsaw-Code/outline-server#253]
I have Outline Server installed manually on VPS. But Outline Manager wiped out for some reason, how i can add Outline Server again?

I have ssh access to VPS.

**Comment by alalamav** [comment]
Hi @lgg, sorry that you're experiencing this issue and thank's for reaching out. The server credentials are stored in `/root/shadowbox/access.txt`. To import the server, paste the output of the file in the manager application.

Please refer to #98 and #156. If you have any questions feel free to re-open this issue.

**Comment by 7urkm3n** [comment]
@alalamav Where is this `/root/shadowbox/access.txt` file located in VPS ? 

Because, current installation outline uses docker and i cant find in the VPS and docker images.
