### ISSUE TITLE
Where can I find documentation on retrieving connection settings to be used with Outline Manager?

### ISSUE THREAD

**Issue by JacobDB** [Jigsaw-Code/outline-server#270]
Forgive me if this isn't the right place for this, it's the only place I can find to communicate that seems remotely relevant.

How do I retrieve the JSON that got output during setup at a later date? I can't find any documentation on this anywhere.

**Comment by lgg** [comment]
@JacobDB check this: https://github.com/Jigsaw-Code/outline-server/issues/211

If it didn't help, please, can you clarify your question?

**Comment by trevj** [comment]
@JacobDB Thanks for trying Outline. @lgg Thanks for the pointer - yes, that is currently the only real way to retrieve that info.

Closing this now, please re-open if you have further questions.
