### ISSUE TITLE
Outline Manager connect to exisitng Outline servers ?

### ISSUE THREAD

**Issue by shaomeng** [Jigsaw-Code/outline-server#277]
Hello,

I'm not sure if the following use case is supported, or encouraged, and would like to hear your opinions.

1) I set up an Outline server using Outline Manager on my laptop No. 1.
2) While I'm using my laptop No. 2, I wanted to manage the Outline server, say add a new key. 
3) I wish I could connect the Outline Manager on laptop No. 2 to the existing outline server and perform management tasks.

Currently I have to go find my laptop No. 1 and do the work.

Thanks,
Sam

**Comment by thelonious89** [comment]
I tested this and I used the same key on No. 2 as I had used on No 1.

On #2 I was able to connect to the server and view the user key. However, when I closed the Manager on #1 and re-opened it, it said it was unable to connect to the server... so it seems like this use case is not currently supported.

But I hope it could be supported. it's important to manage from multiple devices, both from a security policy standpoint and a usability standpoint.

**Comment by lgg** [comment]
@shaomeng i think you should check that ports that needed by Outline is opened and then just copied installation configuration from laptop1 to Outline Manager on laptop2

Also check this: https://github.com/Jigsaw-Code/outline-server/issues/211

**Comment by thelonious89** [comment]
> @shaomeng i think you should check that ports that needed by Outline is opened and then just copied installation configuration from laptop1 to Outline Manager on laptop2
> 
> Also check this: #211 

Thank you, but I think #211 references a different use case? #211 applies to the end user having the same config used across multiple servers, but @shaomeng and I are seeking to connect to the same server with different Outline Managers... so we are seeking to give the admin more convenience.

**Comment by lgg** [comment]
@thelonious89 as i can understand you: 
you have Outline-Server installed on `laptop1` during the installation you got string like this:
`{"apiUrl":"https://00.000.00.00:00000/blaBlaBlAblablaBlaBla","certSha256":"WOWSOMESECRETSHERE"}`

You can use it on `laptop2` to add server for management

Also which type of outline-server installation you used?

**Comment by thelonious89** [comment]
> @thelonious89 as i can understand you:
> you have Outline-Server installed on `laptop1` during the installation you got string like this:
> `{"apiUrl":"https://00.000.00.00:00000/blaBlaBlAblablaBlaBla","certSha256":"WOWSOMESECRETSHERE"}`
> 
> You can use it on `laptop2` to add server for management
> 
> Also which type of outline-server installation you used?

Hi, actually the Outline Server is installed on a VM at AWS. But I want to manage it with laptop1 using Outline Manager. I then also want to manage the outline server on VM at AWS with laptop2.

**Comment by shaomeng** [comment]
@thelonious89  Thanks a lot for describing the difference between here and #211 . I think you just gave a good summary. 

@lgg , I got a string like this `{"apiUrl":"https://00.000.00.00:00000/blaBlaBlAblablaBlaBla","certSha256":"WOWSOMESECRETSHERE"}` from the server side, and paste to my Outline Manager in `laptop1`. Now I suspect that if I paste the same string to the Outline Manager in my `laptop2`, it would work. Is that right? If so, where can I retrieve this string (somewhere in the server??), since I don't have that string kept anywhere...

Thanks you both for the discussion.

**Comment by thelonious89** [comment]
@shaomeng It will work on laptop2 but then laptop1 will *not* work anymore. I tested a few times. 

You can actually rebuild the VM and all users will still be there and not affected. Then get the string and a paste into laptop2. You can test it on laptop2 and see it all works fine. But then put that into laptop1 again and you will see laptop2 can’t connect. I’m not sure why.

**Comment by shaomeng** [comment]
@lgg cannot believe this question is raised many times already. That's right that I could find access info from both `~/shadowbox/access.txt` and `~/shadowbox/access.txt.bak` files. Thanks for the tip! 

@thelonious89 I use the string `{"apiUrl":"PASTEURLHERE","certSha256":"PASTECERTHERE"}` to add my existing server to Outline Managers on my Mac laptop and Ubuntu desktop, and it seems both are working well. You described that `put that into laptop1 again and you will see laptop2 can’t connect`, what exactly `laptop2` is reporting?

**Comment by shaomeng** [comment]
I'm gonna close this issue since my problem has been resolved.

**Comment by shaomeng** [comment]
@thelonious89 Regarding your problem 1), I get "Unable to connect to your Outline server" message sometimes, but I don't have a sequence of actions that consistently bring it up... For 2), I could connect to my DigitOcean server from a MacOS and Ubuntu desktop simultaneously... We'll need an Outline developer to help resolve your issues!

**Comment by zlfccnu** [comment]
> @thelonious89 Regarding your problem 1), I get "Unable to connect to your Outline server" message sometimes, but I don't have a sequence of actions that consistently bring it up... For 2), I could connect to my DigitOcean server from a MacOS and Ubuntu desktop simultaneously... We'll need an Outline developer to help resolve your issues!

you may need to check the info from both `~/shadowbox/access.txt` and `~/shadowbox/access.txt.bak`. The actual problem is that the info from both files are somehow inconsistent:
from access.txt, I only have `certSha256`
from access.txt.bak, I actually have the `apiUrl` and `certSha256`
both `certSha256` are different.
I manage to solve that problem by replacing the `certSha256` in file `access.txt.bak` with `certSha256` in file `access.txt`
I suspect that the problem is once I forget the server, the outline server will regenerate a new credential but without new apiUrl. Thus the old string is invalid.

**Comment by immartian** [comment]
it's now under /opt : 
`cat /opt/outline/access.txt `

**Comment by mytory** [comment]
Connect vpn server. and...

~~~ bash
sudo su
docker cp shadowbox:/opt/outline/persisted-state/shadowbox-selfsigned.crt .
openssl x509 -in "shadowbox-selfsigned.crt" -noout -sha256 -fingerprint | tr --delete :
# result: SHA256 Fingerprint=3B538730...
rm shadowbox-selfsigned.crt
~~~

Use after `Fingerprint=`. 😄
