### ISSUE TITLE
Unable to connect to your Outline Server

### ISSUE THREAD

**Issue by aminsource** [Jigsaw-Code/outline-server#291]
Hi
I have installed outline on my instance (on digitalocean) with ubuntu 16.04 
but I get flowing message when I want create server via outline manager:
#### I open port as on Ubuntu Firewall  as bellow :
```bash
To                                   Action      From
--                                      ------      ----
1024,65535/tcp             ALLOW IN    Anywhere
1024,65535/udp            ALLOW IN    Anywhere
22                                  ALLOW IN    Anywhere
15220                            ALLOW IN    Anywhere
443/udp                        ALLOW IN    Anywhere
443/tcp                         ALLOW IN    Anywhere
1024,65535/tcp (v6)      ALLOW IN    Anywhere (v6)
1024,65535/udp (v6)     ALLOW IN    Anywhere (v6)
22 (v6)                           ALLOW IN    Anywhere (v6)
15220 (v6)                     ALLOW IN    Anywhere (v6)
22/tcp (OpenSSH (v6))  ALLOW IN    Anywhere (v6)
443/udp (v6)                 ALLOW IN    Anywhere (v6)
443/tcp (v6)                  ALLOW IN    Anywhere (v6)
```

ps : I want create from Iran , is this issue depend my location?

**Comment by shaomeng** [comment]
Issue #165 reports that Google Cloud Platform blocks IP coming from Iran... Not sure if DigitalOcean has the same policy. But it looks like you can ssh to your droplet, so it might be a different problem?

**Comment by aminsource** [comment]
> Issue #165 reports that Google Cloud Platform blocks IP coming from Iran... Not sure if DigitalOcean has the same policy. But it looks like you can ssh to your droplet, so it might be a different problem?

yes I can ssh to my droplet

**Comment by fortuna** [comment]
I'm sorry for the trouble.
@aminsource  Could you ssh and run `docker logs shadowbox` on your host and see if there's any error there?

**Comment by trevj** [comment]
@aminsource Can you tell us how you created your server: via the command-line, or using the server manager's automated flow?

**Comment by ed96win** [comment]
Hey. I'm having the same problem here (On a DigitalOcean Server). there are no errors in the log file.

I have installed Outline server manually using SSH commands.

**Comment by fortuna** [comment]
Can you try the connectivity test to your server with this tool and report the result?
https://fortuna-outline-connectivity.netlify.com/

**Comment by Zhang668** [comment]
@trevj 
I have also encountered this situation and need to solve it.       Unable to connect to your Outline Server
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is
because your server's firewall rules are blocking incoming connections. Please review them and
make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.

**Comment by Frinkey** [comment]
@trevj The same problem

**Comment by kouchakyazdi** [comment]
@fortuna 
I had the same problem.
I just test my connectivity with your tool : https://fortuna-outline-connectivity.netlify.com/
and the result is :
Your network does not block port 9824
Port 9824 on 5.9.211.60 is open and accessible

**Comment by fortuna** [comment]
Shadowbox uses the host network interface, removing the need to open the ports of the container.

**Comment by fortuna** [comment]
@kouchakyazdi What error behavior are you seeing? You can successfully establish a TCP connection to your server port. That means there's no blocking happening in the network you tested from. And your firewall set up is fine too.

It's unclear why you can't connect. Try submitting feedback via the form so we can see potential errors.

**Comment by marqueymarc** [comment]
When I installed outline the installation ended with this message:
```
If you have connection problems, it may be that your router or cloud provider
blocks inbound connections, even though your machine seems to allow them.

Make sure to open the following ports on your firewall, router or cloud provider:
- Management port 52526, for TCP
- Access key port 57244, for TCP and UDP
```

I then ran:
```
sudo ufw allow 52526/tcp
sudo ufw allow 57244
```

and Outline Manager was then able to create a connection.

**Comment by Zhangyulong98** [comment]
谢谢Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"marc meyer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 凌晨5:22
收件人:&nbsp;"Jigsaw-Code/outline-server"<outline-server@noreply.github.com&gt;;
抄送:&nbsp;"878781806"<878781806@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Jigsaw-Code/outline-server] Unable to connect to your Outline Server (#291)





 
When I installed outline the installation ended with this message:
 If you have connection problems, it may be that your router or cloud provider blocks inbound connections, even though your machine seems to allow them. Make sure to open the following ports on your firewall, router or cloud provider: - Management port 52526, for TCP - Access key port 57244, for TCP and UDP  
I then ran:
 sudo ufw allow 52526/tcp sudo ufw allow 57244  
and Outline Manager was then able to create a connection.

**Comment by samrth012** [comment]
Unable to create server due to ports issue on Ubuntu 20.04

**Comment by fortuna** [comment]
This is an old stale issue. A lot has changed since then, so I'm closing the issue. Feel free to open a new one with with fresh information if needed

**Comment by 0000ali9999** [comment]
i faced the same problem i bought cloud server from provider A and it worked correctly while i bought another cloud server from azaronline outline manager did not connect the only difference was cloud server provider. problem still exist

**Comment by manhte2** [comment]
Hi guys, can someone help me?
I subdently facing unreacheable connect to server after migrated server days, at the time migrated I can connect to server by Outline manager without any problem.
I tried to check ufw configuration which nothing change that till allow all tcp/udp port.

I also try to create a new fresh outline server, then migrate again by backup /opt/outline/persisted-state folder, after migrate, client can vpn to new svr but outline manager said need to check firewall (while ufw rule not change anything).

would you please help me, 
thank much,

**Comment by manhte2** [comment]
can someone advise any idea ?

**Comment by fortuna** [comment]
When you migrate the keys, if the server has a different IP, they won’t work.

You can reach out to support@google.com for more help.

**Comment by manhte2** [comment]
> When you migrate the keys, if the server has a different IP, they won’t work.
> 
> You can reach out to [support@google.com](mailto:support@google.com) for more help.

thanks bro, but before I did migrate same way and it worked well , of couse when do migrating, it always difference IP.
The isssue only happen after a week new server works. And now I do any migrate, issue happen

Can u advise again support email address ? is that support@google.com ?

**Comment by fortuna** [comment]
My mistake, the email is support@getoutline.org
