### ISSUE TITLE
Unable to invalid key

### ISSUE THREAD

**Issue by JiangTJ** [Jigsaw-Code/outline-server#292]
I used outline manager ‘Advanced Mode’ to created service.  
But when removing a key，it appears to have been removed, but it is still valid.

**Comment by JiangTJ** [comment]
I test it again, and key is invalid.
So will it expire after a period of deletion?

**Comment by fortuna** [comment]
@JiangTJ I'm sorry, there was a bug that was briefly introduced in a rollout last week.
It's now fixed. Are you still seeing the problem?
Do you see errors when you run `docker logs shadowbox` on your host?

**Comment by JiangTJ** [comment]
@fortuna It's work well now.
Thank you very much！
