### ISSUE TITLE
Windows device support browser only

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#297]
Is this possible to add browser data only though outline on Windows, we used to have it as default on the windows os? 

it seems unnecessary, but we need it for lots of reason: (for China only)
1. CN2 data usage is expensive (China official high speed out port to another country, cost about 0.11USD/GB). Otherwise, it will have a large delay. 

2. We used lots of application such as QQ, wechat, game, music apps. They have some issues when you have the foreign IP address, like huge delay and location lock.

**Comment by studentmain** [comment]
Use older version or just use ss-windows. In fact, it wasn't default
option, it was the only option...

Saikorin <notifications@github.com> 于 2018年11月2日周五 上午12:35写道：

**Comment by shaomeng** [comment]
The feature request definitely adds quite some complexity to the application, especially considering that Outline supports multiple platforms (Windows, Linux, MacOS, Android, iOS, ChromeOS). 

Meanwhile, as a workaround, you could try dedicate a device for Outline use, and another device for QQ, Wechat etc. use.

**Comment by sailosha** [comment]
> 
> 
> The feature request definitely adds quite some complexity to the application, especially considering that Outline supports multiple platforms (Windows, Linux, MacOS, Android, iOS, ChromeOS).
> 
> Meanwhile, as a workaround, you could try dedicate a device for Outline use, and another device for QQ, Wechat etc. use.

I do understand how to use different Internet TAP/mask on the winodws, but I didn't build outline for myself. I built it for my friends who lives in China. Actually, if you use orginal SS client and grab information from your servers, your ss will run as normal and it will have opition for web only. I am trying to lower the diffcult usage level for the people who don't understand computer.

**Comment by trevj** [comment]
@sailosha Thanks for the suggestion. This is not something we plan to support right now, partly because of the effort required to document and support two very different types of connections just on Windows. Regarding including/excluding certain apps that is something we're thinking about implementing (across all platforms):
https://github.com/Jigsaw-Code/outline-client/issues/180
