### ISSUE TITLE
cannot install on OpenVZ

### ISSUE THREAD

**Issue by malikshi** [Jigsaw-Code/outline-server#302]
i cant install outline server on my vps Openvz, is it only support to KVM?

**Comment by trevj** [comment]
@malikshi Thanks for trying Outline.

@studentmain Thanks for the pointer. I'm not familiar with OpenVZ myself - but if you can install Docker on your system then it should be straightforward to install Outline.

**Comment by malikshi** [comment]
HI, its solved but i need to install ubuntu 18.04 when am i trying stock from ISP cloud provide ubuntu 14.04- 16.04 cant installed perfectly

**Comment by trevj** [comment]
@malikshi I don't quite follow - closing this for now if your original issue with OpenVZ is resolved.
