### ISSUE TITLE
Nothing happens after DO login

### ISSUE THREAD

**Issue by utgarda** [Jigsaw-Code/outline-server#307]
####Environment and version
Running v1.1.8 on Arch Linux 4.18.16: 

####What happens
After I click on the "Digital Ocean - get started" element, I see "Sign in or create an account with DigitalOcean." message, and a browser opens DO login page. When I log in, nothing happens - OutlineManager doesn't connect to DO and doesn't reacts in any visible way.

####Expected behavior
After DO login OutlineManager should show DO-related UI

```[etsvigun@jotunheim apps]$ ./Outline-Manager.AppImage 
Outline Manager is starting
Launching web app from outline://web_app/index.html?version=1.1.8&sentryDsn=https%3A%2F%2F533e56d1b2d64314bd6092a574e6d0f1%40sentry.io%2F215496
Checking for update
Update for version 1.1.8 is not available (latest version: 1.1.8, downgrade is disallowed).
QApplication: invalid style override passed, ignoring it.
QApplication: invalid style override passed, ignoring it.
kf5.kservice.sycoca: Parse error in  "/home/etsvigun/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"

[etsvigun@jotunheim apps]$ uname -a
Linux jotunheim 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
```

**Comment by utgarda** [comment]
![image](https://user-images.githubusercontent.com/15115/48217544-b53ce080-e398-11e8-8cb0-88030517c3fa.png)

**Comment by pascalandy** [comment]
This is an issue with DO.
It's not related to this project.

**Comment by alalamav** [comment]
Please reopen if the issue persists on the latest version of the app.
