### ISSUE TITLE
my outline wont open websites on ubuntu 18.04.01

### ISSUE THREAD

**Issue by majid-abdollahi** [Jigsaw-Code/outline-server#310]
hi dear,

i have outline on my ubuntu 18.04.01 server. its work for telegram and whatsapp but it cant open any websites and youtube application.
what happened ? how can i solve that ?
is there any problem on ubuntu 18.04.01 or any other problems? because when i had ubuntu 16.04 it worked as well as always. also i opened all 1024-65535 ports for tcp and udp.

Thanks.

**Comment by dsk9** [comment]
I have the same problem.

**Comment by fortuna** [comment]
@majid-abdollahi @dsk9 I'm sorry for your trouble
What clients are you using?

Outline creates servers with Ubuntu 18.04 now, and enables the TCP BBR congestion control. I wonder if that's related. @trevj FYI

**Comment by majid-abdollahi** [comment]
> @majid-abdollahi @dsk9 I'm sorry for your trouble
> What clients are you using?
> 
> Outline creates servers with Ubuntu 18.04 now, and enables the TCP BBR congestion control. I wonder if that's related. @trevj FYI

I'm using android and windows client applications. I opened ports 1024-65535 both tcp and udp. Is that enough or I should do anything else ? Now I have 18.04.1

**Comment by fortuna** [comment]
The script you mention is the right one. Your installation steps seem right.

Are you having the issue on *both* Windows and Android or only one of the systems?
When you open a website on your browser, what error message do you get? Could you paste the exact message here?

@alalamav FYI

**Comment by YahiaAbdelWahab** [comment]
I have the same problem. I can send and receive WhatsApp messages but I can't visit websites.
I am having this problem on Windows and Android.
I am using AWS EC2 running Ubuntu 18.04.
I don't have this problem on new instances, it starts happening after 20-24 hours from creating the instance.

**Comment by YahiaAbdelWahab** [comment]
Another problem I noticed recently that I can't access tweets or twitter profiles (the app crashes), even though I can browse the home feed just fine.
https://imgur.com/S4Q6gCD

**Comment by fortuna** [comment]
@YahiaAbdelWahab where are you creating your server?
There are some cloud providers that don't give you a fixed IP by default (e.g. Google Compute Engine), and it may change if the server gets reprovisioned or restarted.

**Comment by YahiaAbdelWahab** [comment]
I am using AWS EC2.

**Comment by YahiaAbdelWahab** [comment]
I tried setting up Outline on DigitalOcean and I got the exact same problem.
I also tried setting up shadowsocks-libev on DigitalOcean and I got the same problem.
I guess there is something wrong with shadowsocks itself, not with Outline.

**Comment by YahiaAbdelWahab** [comment]
I think this is the same issue
https://github.com/shadowsocks/shadowsocks-libev/issues/2219

**Comment by kooshan75** [comment]
any luck?! :(
