### ISSUE TITLE
any guides how to install on docker hosting prodivers

### ISSUE THREAD

**Issue by hbakhtiyor** [Jigsaw-Code/outline-server#319]
[installing scripts](https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh) doesn't work, need installing from dockerfile or docker image

**Comment by fortuna** [comment]
The `docker run` command can be found here:
https://github.com/Jigsaw-Code/outline-server/blob/8aacfde7109b93d56457b42b15c58b210d88acc4/src/server_manager/install_scripts/install_server.sh#L232-L247

**Comment by pascalandy** [comment]
I just installed it and it works A++ here.
I had to open the two port as mentioned after the installation.

**Comment by fortuna** [comment]
You'll will need to open all ports >= 1024 if you'd like to create new access keys, as each key runs on a new, random port.

**Comment by trevj** [comment]
@hbakhtiyor We need more information before we can really help you, e.g. output from the installation scripts.

**Comment by hbakhtiyor** [comment]
@trevj for example https://www.clever-cloud.com/en/docker-hosting

**Comment by alalamav** [comment]
Feel free to reopen if the issue persists.
