### ISSUE TITLE
Outline Server for Company Access

### ISSUE THREAD

**Issue by ehsansoltaniazad** [Jigsaw-Code/outline-server#344]
Can I deploy Outline in my home office and use it as VPN Server? I want to have access from remote to the office. Here most VPN traffics are blocked, but Outline is OK.

**Comment by trevj** [comment]
@ehsansoltaniazad Yes you can, though I'm afraid we don't currently make this easy. Two things to note:
- on most networks you'll have to configure port forwarding on your router to make this work
- you can't currently use Outline to connect to other machines on your network (it will only serve the internet, not your LAN)

**Comment by trevj** [comment]
Let me know if I can be of any more help!

**Comment by trevj** [comment]
@zackijack See this answer I just sent to you:
https://github.com/Jigsaw-Code/outline-server/issues/368#issuecomment-451439332
