### ISSUE TITLE
Unable to connect to your outline server

### ISSUE THREAD

**Issue by ZachTheDev** [Jigsaw-Code/outline-server#355]
I setup my outline server through a VirtualBox VM running Ubuntu Server 18.04.1 LTS
I am running VirtualBox 5.2.22r126460, and Outline Manager 1.2.1. Everything worked until I tried to connect from my host PC to the VM. I enabled 'Bridge Adapter' mode on the VM so that it would get it's own IP and act like a server on my main network. I opened up ports 1024-65535/tcp on the VM and on the Host both on the outgoing and incoming. I have run out of ideas what could be causing this problem. Any troubleshooting tips? Thanks for the lovely product!

**Comment by Zangoran** [comment]
@fortuna Any ideas what the issue may be?
