### ISSUE TITLE
[Question] How to deploy server on Windows?

### ISSUE THREAD

**Issue by AberSheeran** [Jigsaw-Code/outline-server#365]
I want to deploy outline-server on a Windows Server 2012, what should I do?

**Comment by trevj** [comment]
@AberSheeran Thanks for trying Outline. I'm afraid @sailosha is correct: currently, it's not possible to run an Outline server on Windows. However, it should get a little easier soon when we stop using Docker's `--net=host` option. Then, it will be possible to run on both Windows and macOS - however, I still doubt it will be a priority for us.

**Comment by stonedreamforest** [comment]
@trevj  we need this😅
