### ISSUE TITLE
Outline for connect on LAN network

### ISSUE THREAD

**Issue by zackijack** [Jigsaw-Code/outline-server#368]
Is it possible to use Outline to connect to other machine in LAN network (not internet)? And why?

**Comment by trevj** [comment]
@zackijack Currently, the Outline client bypasses local addresses and local networks - see here for more info:
https://github.com/Jigsaw-Code/outline-client/issues/355

As far as the server goes, currently it disallows access to local addresses but will route to local networks - however, you will need to use another Shadowsocks client to do so.
