### ISSUE TITLE
Watchtower conflict

### ISSUE THREAD

**Issue by davidsarkany** [Jigsaw-Code/outline-server#37]
The installer does not check whether or not there is an already running container under the name watchtower which caused the following issue:

> docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "75aec57acd0567cdcb44e691b33729c76cf40591ee6ca47a8b6cea7304c41f43". You have to remove (or rename) that container to be able to reuse that name.
> See 'docker run --help'.

**Comment by studentmain** [comment]
run
`docker container kill 75
docker container rm 75`
we need clear old container manually
Dávid Sárkány <notifications@github.com> 于 2018年3月24日周六 05:30写道：

**Comment by davidsarkany** [comment]
I know, but its not user friendly.

**Comment by studentmain** [comment]
Maybe we can check and delete it at start of install script.

Dávid Sárkány <notifications@github.com> 于 2018年3月24日周六 08:44写道：

**Comment by thomamvt** [comment]
what i did was "docker stop watchtower"
then
"docker rm watchtower"

**Comment by davidsarkany** [comment]
I know how to delete and rename my own watchtower container.
My issue is with it is why is it necessary?
Why does it not check first if there is a name confliction?
Why does it install a new watchtower if I already have one set up for my own liking? (for example it sends emails about updates)?
Having a properly documented shadowbox image (that I can configure to my liking) would be far superior instead of the install_server.sh

**Comment by trevj** [comment]
@davidsarkany Thanks for the report. We'll take your suggestion into consideration.

**Comment by trevj** [comment]
I believe this has been addressed some time ago; the installer now asks whether you want to keep or replace the `watchtower` container.
