### ISSUE TITLE
we can use port ??

### ISSUE THREAD

**Issue by CyberTheReape** [Jigsaw-Code/outline-server#371]
hello.First of all thank you for this beautiful project..today I have created vpn server with digitalocean and outline manager ...now vpn is working very well ..but I have a problem.I want to use port after connecting to vpn server..so I want to use vpn server ports..can i do it ?How can I use vpn server's ports ?thank you for your interest

**Comment by trevj** [comment]
@CyberTheReape Thanks for using Outline! I'm afraid I don't fully understand your question: do you want to access services on the VPN server itself?

**Comment by CyberTheReape** [comment]
Hello. I asked if I could use the ports of my vps machine. i can't open port from modem in my home.because I have ipv6 ip address.. I want to create vpn server and I want to use the ports for some programs.but yesterday I did it. for now there is no problem .. you can close topic. Thanks for everything

**Comment by CyberTheReape** [comment]
I guess I solved the problem . I am using a digitalocean vps machine .ports are not working because it works in docker ..I'll ask you another question now . outline manager himself creates vps machine. but I want to install it manually because the vps installed machine is docker.so I'll create a new ubuntu vps machine first.then I will try to install the outline manager program. can I do that?..can I get the access key this way?if I can get access key in this way, I can forward the ports of my vps machine to my own computer. Can I get access key if I download and install the files of outline program on github site to vps machine?

**Comment by alashow** [comment]
If you want to install Outline to your server manually, you can run this script provided by Outline:
```bash
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
```

**Comment by CyberTheReape** [comment]
Thanks
