### ISSUE TITLE
Outline requires a user with a owner role, can't only be a member

### ISSUE THREAD

**Issue by zackijack** [Jigsaw-Code/outline-server#378]
Every time I connect Outline manager with my DigitalOcean account that only has a member role,  I always get this error:
![image](https://user-images.githubusercontent.com/1515471/50876512-06506b80-1400-11e9-817f-1dbc4950f3f8.png)
even though my team bill has been set-up.
why?

**Comment by McGish** [comment]
Hi @zackijack how did you fix this issue?

Thanks
