### ISSUE TITLE
Connecting to existing Outline server

### ISSUE THREAD

**Issue by Fastidious** [Jigsaw-Code/outline-server#385]
I have an existing Outline server, and I want to add it to the Outline Manager on a different machine. I do not have the initial API information. Where do I get that information from, on the server running Outline? I have tried:

```
docker exec -it CONTAINERID cat ~/shadowbox/access.txt
```
But that renders:

```
cat: can't open '/root/shadowbox/access.txt': No such file or directory
```

Contents of `/opt/outine/persisted-state` are:

```
root@shadow:/home/david# docker exec -it CONTAINERID ls -lasFh /opt/outline/persisted-state/
total 32
     4 drwxrws---    4 root     root        4.0K Jan 18 15:50 ./
     4 drwxr-xr-x    3 root     root        4.0K Jan 17 22:29 ../
     4 drwxrws---    2 root     root        4.0K Jan 17 14:28 outline-ss-server/
     4 drwxrws---    3 root     root        4.0K Jan 17 14:28 prometheus/
     4 -rw-rw----    1 root     root        1.1K Jan 17 14:27 shadowbox-selfsigned.crt
     4 -rw-------    1 root     root        1.7K Jan 17 14:27 shadowbox-selfsigned.key
     4 -rw-rw----    1 root     root         659 Jan 18 15:50 shadowbox_config.json
     4 -rw-rw----    1 root     root         160 Jan 17 22:29 shadowbox_server_config.json
```
Contents of `~/shadowbox/` are:
```
root@shadow:/home/david# docker exec -it CONTAINERID ls -lasFh ~/shadowbox
total 48
     4 drwxr-xr-x    1 root     root        4.0K Jan 17 21:26 ./
     4 drwx------    1 root     root        4.0K Jan 17 21:26 ../
     4 drwxr-xr-x    5 root     root        4.0K Jan 17 21:26 app/
     4 drwxr-xr-x    1 root     root        4.0K Jan 17 21:26 bin/
     4 drwxr-xr-x   87 root     root        4.0K Jan 17 21:26 node_modules/
     4 -rw-rw-r--    1 root     root         712 Jan 17 21:24 package.json
     4 drwxr-xr-x    2 root     root        4.0K Jan 17 21:26 persisted-state/
    20 -rw-rw-r--    1 root     root       17.3K Jan 17 21:26 yarn.lock
```
Replies to similar issue (#277) do not seem to apply any longer. Again, I do not have the API key, where can I get it from on the container running the Outline server?

**Comment by trevj** [comment]
@Fastidious Thanks for trying Outline. We recently changed the location on disk where these files are stored. They're now in `/opt/outline`. I think this is the file you're looking for:
```
/opt/outline/access.txt
```

**Comment by Fastidious** [comment]
@trevj if I remember correctly, the only thing inside ‘/opt/outline’ is persisted-state (which contents I listed). I will check when I get home.

**Comment by Fastidious** [comment]
@trevj, this is what I see on that directory:
```
root@shadow:/home/david# docker exec -it CONTAINERID ls -lasFH /opt/outline/
total 12
     4 drwxr-xr-x    3 root     root          4096 Jan 17 22:29 ./
     4 drwxr-xr-x    1 root     root          4096 Jan 17 22:29 ../
     4 drwxrws---    4 root     root          4096 Jan 18 15:50 persisted-state/
root@shadow:/home/David#
```

**Comment by Fastidious** [comment]
@trevj just destroyed all containers, and pruned them, and started from scratch. On a brand new install, that file doesn't exist. This seems to be a bug.

**Comment by trevj** [comment]
@Fastidious What are the contents of `/opt/outline` on the host system? I don't think the entire `/opt/outline` folder is mounted on the Shadowbox container.

**Comment by Fastidious** [comment]
@trevj the file location I was expecting was within the container. For a solution that is containerised, that would be the obvious place to look for, the container itself (all my commands above refer to the shadowbox container itself, as you can see).

It would be best if a distinction was made, when referring to files locations. The `access.txt` file you referred to is, indeed, on the **host** `/opt/outline/` directory, and *not* on the **container's** equally named directory.

**Comment by davletovb** [comment]
when I do sudo cat /opt/outline/access.txt the only information I get is certSha256:xxxxxxx. No apiUrl.

**Comment by Fastidious** [comment]
@davletovb see #398 for some pointers.
