### ISSUE TITLE
installation error on VPS running Ubuntu 18.04 with Docker installed

### ISSUE THREAD

**Issue by kkdot** [Jigsaw-Code/outline-server#389]
sudo  wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
mkdir: cannot create directory ‘/opt/outline’: Permission denied

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

**Comment by danyhm** [comment]
@kkdot 
that script is from an old GitHub tutorial page.
you need to use the script in outline-manager instead which is  : 
`sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"`
you must not be root.

**Comment by fortuna** [comment]
@kkdot Please follow @danyhm 's suggestion.

I believe the command you used is running wget as root, but not bash

**Comment by samascience** [comment]
even then the above mentioned command is getting us into bash 

cloud9-1:~$ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)
>
> ^C
