### ISSUE TITLE
【@bandwagonhost】 Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by suonli** [Jigsaw-Code/outline-server#39]
【@bandwagonhost】

[root@localhost ~]# wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash
> Verifying that Docker is installed .......... OK
> Setting up key functions and constants ...... OK
> Creating persistent state dir ............... OK
> Setting up directory ........................ OK
> Generating secret key ....................... OK
> Generating self-signed certificate .......... OK
> Generating SHA-256 fingerprint .............. OK
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

**Comment by trevj** [comment]
@suonli Thanks for the report. Happy to hear your server is now working.

**Comment by sasherafat** [comment]
> It done after below command:
> sudo service docker restart

it's Worked...
