### ISSUE TITLE
v2ray support please

### ISSUE THREAD

**Issue by malikshi** [Jigsaw-Code/outline-server#391]
as you can see simple-obfs not deprecated and now come up with v2ray with many features, can you support this v2ray in outline?

[https://github.com/shadowsocks/v2ray-plugin](url)

**Comment by studentmain** [comment]
https://github.com/Jigsaw-Code/outline-server/issues?utf8=✓&q=v2ray

**Comment by malikshi** [comment]
> [https://github.com/Jigsaw-Code/outline-server/issues?utf8=✓&q=v2ray](https://github.com/Jigsaw-Code/outline-server/issues?utf8=%E2%9C%93&q=v2ray)

thanks.

**Comment by trevj** [comment]
Duplicate of:
https://github.com/Jigsaw-Code/outline-server/issues/16
