### ISSUE TITLE
Why do we have a private key in a GitHub repo?

### ISSUE THREAD

**Issue by pipboy96** [Jigsaw-Code/outline-server#395]
https://github.com/Jigsaw-Code/outline-server/blob/master/key.txt

**Comment by michaellee8** [comment]
It seems that it is from this commit https://github.com/Jigsaw-Code/outline-server/commit/a7641eefb2055dc4b2188d2e16f84e4066fd0f87#diff-65c2a527098e1f7747eec58e1925b453 , with actually another rsa private key as well. @fortuna

**Comment by trevj** [comment]
@pipboy96 @michaellee8 Thanks for the report.

@fortuna Looks like we need a followup to https://github.com/Jigsaw-Code/outline-server/pull/382.
