### ISSUE TITLE
What should I do if reset computer with outline manager installed

### ISSUE THREAD

**Issue by SJang1** [Jigsaw-Code/outline-server#398]
Using Ubuntu server as an Outline Server, Windows to Outline Manager Program.
If I reset / re-install Windows, What should I have to do to revoke access / add access key / ... for the outline server? or can I get outline manager or get / revoke keys on ubuntu server(which is using for outline server)

**Comment by Fastidious** [comment]
@SJang1 reinstall Outline Manager, connect it to your Outline Server, and manage keys as you did before. Also see #385.

**Comment by SJang1** [comment]
@Fastidious Cannot understand well, so are you saying doing this step again?
![image](https://user-images.githubusercontent.com/29011440/52804622-03fcc380-30c8-11e9-9dd3-2dc8c68db08b.png)

**Comment by Fastidious** [comment]
@SJang1 the server part is already done, no need to do it again. The "Paste your installation output here." is what you need to do. If you do not have that information handy, refer to #385, I had the same question.

**Comment by SJang1** [comment]
@Fastidious Oh. Found it. Thanks. 👍 Does it revoke access to manager in previous device? if not is there a way?

**Comment by Fastidious** [comment]
@SJang1 the manager contains nothing, it is simply a manager for a running server. If you do not remove the access keys from server (using a manager), they are always valid.

**Comment by Fastidious** [comment]
Close this ticket, if problem is solved. Do not leave it hanging! 🙂

**Comment by SJang1** [comment]
I was just came to close the ticket. Thanks!
