### ISSUE TITLE
Can you add Obfs4 to be a Confusion for your software?

### ISSUE THREAD

**Issue by lordarthas1995** [Jigsaw-Code/outline-server#40]
Obfs4 :https://github.com/Yawning/obfs4 Add I hope you can run a meek tor bridge too.

**Comment by fortuna** [comment]
Hi @lordarthas1995, thanks for the suggestion.
We are aware of obfs4, but could you clarify where that would help? We haven't seen evidence that the shadowsocks protocol can be detected.

**Comment by lordarthas1995** [comment]
@fortuna In fact, ip of my VPS has always been blocked by GFW recently when I run shadowsocks. So I don't think Shadowsocks is as safe as before. I use Tor obfs4 bridge, Openconnect and SSH without any trouble but not Shadowsocks. So I hope your project can add more ways.

**Comment by BarrieShieh** [comment]
I think it might be true that the deep packet inspection is already capable of detecting the shadowsocks protocol(Part of it, i think. Especially for the old ones). The new AEAD Ciphers(SIP004 and SIP007) might help, but not for sure. From the feedback of most users who use shadowsocks, The servers without obfs have higher risk of being blocked than those have one.

**Comment by studentmain** [comment]
In my experience, server with misconfigured obfs is more dangerous.

obfs should work with a httpd and a real, unfamous tls website. When The
Firewall detected a tls (or a 'tls') session, it will test  is the server a
real website. If not, then block it.
And some ss server with weak password, no plugins and depreciated
encryption is still safe.

If ss protocol is dangerous, we can switch to v2ray. It's brand new,
powerful, compatible with ss, and it use MIT license.



Barrie <notifications@github.com> 于 2018年4月15日周日 15:00写道：

**Comment by BarrieShieh** [comment]
I don't think test a website if it is a real one is doable for firewall. Because, if you want to TEST it, you need to get the content of the website with correct url path. Then, you need to parse the content to check if is a valid one. There are too many variables here. You can't simply test it, it takes extra computing resources. And it's way more complicated than just analysis the logs of switchs and routers. As far as we know, the dpi devices are setup at the international internet exit. The log streams might at PB/s I guess. So it's not easy to doing both dpi and test at high speed at the same time.

**Comment by studentmain** [comment]
Just some information of how to use obfs. We believe they can analyzing tls
traffic (just analyze server name, ca name ,etc. in server certification)
they did it in domestic network. They were replace ShimakazeGo's (a proxy
tool for few games) self-signed cert.

About test a website if it is real. Parse full content isn't neccessary.
Just parse first line of response. Ofcourse they can't do DPI and test at
same time, but they can do it later. It reported their device use a
well-optimized stateless model to capture and interference tls traffic,
record possible fake site isn't so hard. Extra computing resource isn't a
big trouble, if they need, they have...

Then, for example, you use a self-signed cert with server name "
cloudflare.com" at port 443... Yes, someone did, then got banned few days
later...

If use obfuscation based on tls, we should make sure obfs is well
configured

Barrie <notifications@github.com> 于 2018年4月15日周日 18:54写道：

**Comment by BarrieShieh** [comment]
I think you're talking about MITM attack. Replace certificate can not be done dynamically. It needs deployments. So they can only spy on specific website not all of them. I agree with your opinion, we do need to pick the obfs hosts carefully.

**Comment by studentmain** [comment]
Yes, they did MITM on that case.

The first problem is how to pick the host. We pick one, write in code,
widely deployed, then get banned. If we generate a hostname when deploy,
how to get a valid cert. If we ask user to input a hostname, which means
they need buy one, deploy will become hard. So I think it can only be an
optional feature.

Another problem is which port to use. 443? Random? Forward by nginx (or
other httpd)? If there is already have a tls website, I suggest forward by
httpd at specific path. If not, use random port also seems ok (but I'll
install a httpd, then I have a website).

Barrie <notifications@github.com> 于 2018年4月15日周日 23:38写道：

**Comment by ehhthing** [comment]
I would like to also confirm that shadowsocks has been detected by the Chinese firewall, at least since last year. 

On the same IP, I hosted two different proxy instances, one shadowsocks and one [brook](https://github.com/txthinking/brook). The shadowsocks proxy would get connections reset and the brook proxy worked fine.

**Comment by fortuna** [comment]
A lot has changed since this issue was open. The Outline server is a lot more resistant to detection now, so I'll be closing this issue and we can reopen with fresh data if needed.
