### ISSUE TITLE
Too slow to start loading page if first load or loaded few minutes ago

### ISSUE THREAD

**Issue by SJang1** [Jigsaw-Code/outline-server#401]
If connecting to website/server, for the first load for that webpage, it loads too slow. Almost takes 20-30 seconds to load the page first.

After that loading, a page goes fast with same server, but accessing to another server, it takes so long again.
Accessing to the server which was connected before, it loads fast, but if it was loaded few minutes ago, have to wait for few seconds to start the page loading again.

Work like this example)
https://kkk.com(first load took 30sec to start load) -> https://kkk.com/blabal(loads fast) -> https://yyy.com(takes 30sec to start load) -> https://kkk.com(if it is accessed more then few minutes ago 30sec to start load but if not, loads fast.).

**Comment by SJang1** [comment]
I'm not sure, but seems it only happens if connecting to the server using https.

**Comment by SJang1** [comment]
I don't know why, but tried few different servers, it is not. I think it was a server problem.

**Comment by trevj** [comment]
Thanks for the update @SJang1, glad to hear it's working for you.
