### ISSUE TITLE
TLS Cert generating fail...

### ISSUE THREAD

**Issue by gohlihan** [Jigsaw-Code/outline-server#405]
[root@malaysiaboleh ~]# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. 
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

somebody help please...

**Comment by wasd845** [comment]
Have you installed **openssl** ?
`yum install openssl` works for me.
hope this helps.

**Comment by gohlihan** [comment]
Thanks for your reply, it works!

Have a nice day.

Regards,
Goh

________________________________
发件人: wasd845 <notifications@github.com>
发送时间: Monday, September 2, 2019 5:29:05 PM
收件人: Jigsaw-Code/outline-server <outline-server@noreply.github.com>
抄送: gohlihan <han_0607@msn.com>; Author <author@noreply.github.com>
主题: Re: [Jigsaw-Code/outline-server] TLS Cert generating fail... (#405)


Have you installed openssl ?
yum install openssl works for me.
hope this helps.

―
