### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by ZiaChiu** [Jigsaw-Code/outline-server#406]
I tried uninstalling docker and redeploying the outline, resulting in the following:

Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Starting Shadowbox .......................... FAILED
Unable to find image 'quay.io/outline/shadowbox:stable' locally
stable: Pulling from outline/shadowbox
4fe2ade4980c: Pulling fs layer
0ade4f5bae45: Pulling fs layer
fd1dceaf77f3: Pulling fs layer
2b7312d0c22f: Pulling fs layer
de3ba562dae3: Pulling fs layer
81be2925b0cf: Pulling fs layer
6b1bce44311c: Pulling fs layer
82b69c25ca40: Pulling fs layer
381524330685: Pulling fs layer
0057e33f6eec: Pulling fs layer
da01506257f3: Pulling fs layer
9640f09409fd: Pulling fs layer
819acc740447: Pulling fs layer
b346c034e194: Pulling fs layer
355386ff8ca0: Pulling fs layer
be47dbd48fef: Pulling fs layer
de3ba562dae3: Waiting
81be2925b0cf: Waiting
6b1bce44311c: Waiting
82b69c25ca40: Waiting
381524330685: Waiting
0057e33f6eec: Waiting
da01506257f3: Waiting
9640f09409fd: Waiting
819acc740447: Waiting
b346c034e194: Waiting
355386ff8ca0: Waiting
be47dbd48fef: Waiting
2b7312d0c22f: Waiting
4fe2ade4980c: Verifying Checksum
4fe2ade4980c: Download complete
fd1dceaf77f3: Verifying Checksum
fd1dceaf77f3: Download complete
4fe2ade4980c: Pull complete
de3ba562dae3: Verifying Checksum
de3ba562dae3: Download complete
0ade4f5bae45: Verifying Checksum
0ade4f5bae45: Download complete
2b7312d0c22f: Verifying Checksum
2b7312d0c22f: Download complete
82b69c25ca40: Verifying Checksum
82b69c25ca40: Download complete
6b1bce44311c: Verifying Checksum
6b1bce44311c: Download complete
81be2925b0cf: Verifying Checksum
81be2925b0cf: Download complete
0ade4f5bae45: Pull complete
fd1dceaf77f3: Pull complete
da01506257f3: Verifying Checksum
da01506257f3: Download complete
2b7312d0c22f: Pull complete
de3ba562dae3: Pull complete
81be2925b0cf: Pull complete
6b1bce44311c: Pull complete
82b69c25ca40: Pull complete
381524330685: Verifying Checksum
9640f09409fd: Verifying Checksum
9640f09409fd: Download complete
381524330685: Pull complete
b346c034e194: Download complete
0057e33f6eec: Verifying Checksum
0057e33f6eec: Download complete
355386ff8ca0: Verifying Checksum
355386ff8ca0: Download complete
819acc740447: Verifying Checksum
819acc740447: Download complete
be47dbd48fef: Verifying Checksum
be47dbd48fef: Download complete
0057e33f6eec: Pull complete
da01506257f3: Pull complete
9640f09409fd: Pull complete
819acc740447: Pull complete
b346c034e194: Pull complete
355386ff8ca0: Pull complete
be47dbd48fef: Pull complete
Digest: sha256:25641a13d012e10e70b4727d99f82157aec5c1c66c77d032c946
252d7d78ac28
Status: Downloaded newer image for quay.io/outline/shadowbox:stable
docker: Error response from daemon: OCI runtime create failed: cont
ainer_linux.go:344: starting container process caused "process_linu
x.go:293: copying bootstrap data to pipe caused "write init-p: brok
en pipe"": unknown.

Sorry! Something went wrong. If you can't figure this out, please c
opy and paste all this output into the Outline Manager screen, and
send it to us, to see if we can help you.

**Comment by fortuna** [comment]
What's the host OS you are using?
