### ISSUE TITLE
Always generater the same ss key

### ISSUE THREAD

**Issue by Sugar250** [Jigsaw-Code/outline-server#408]
Vultr 3.5$VPS in Japan, CentOS7 with kernel 5.0.2 and the last version of outline.
Everytime I try to generater a new ss key ,It show's me the same key as My access key.

**Comment by alalamav** [comment]
Hi @Sugar250,
* How are you creating the access keys, through the Outline Manager or via API?
* How are you determining these are different? They may have the same host and port, depending on when you created the server.

**Comment by Sugar250** [comment]
1. I create the  access keys from Outline Manager.
2. with the share button. It always shows the same ss:// url. I don't have image for that but I tried both ubuntu18.04 and CentOS7. This problems are still here.

**Comment by Sugar250** [comment]
And I also try to install outline on a new fedora server. But It block with "Waiting for Outline server to be healthy .... " with no reson for about half hour now =_=

**Comment by Sugar250** [comment]
@alalamav I just tried generater two new keys.So it seams like two keys with the same ports and different password. But last time the ss:// url with so many keys I generated are all same. Looks like this problem just been fix with no reason?
I will close this issues. Thanks for your help.

**Comment by alalamav** [comment]
The default behavior is to create keys on the same port; this is why I was asking how you were determining that the keys were similar.
