### ISSUE TITLE
Server running, but no internet on some android devices

### ISSUE THREAD

**Issue by thomamvt** [Jigsaw-Code/outline-server#41]
I've outline servers running on google cloud, amazon and digital ocean. I'm able to connect to VPN via the client application on android. After connecting to vpn, there is no internet. This device with no internet connection is andorid 6.0.

 I've another android device connected to outline via same wifi, has excellent performance for speed tests, everything is working fine and this device is android 8.0. every setup is same on both devices. But i dont have any idea why i'm not able to connect to internet on device 1. 

Please update the apk.

**Comment by trevj** [comment]
@thomamvt Thanks for the report. Can you please give us some more details on your Android 6.0 device?:
* open Outline on your Android 6.0 device
* try to connect
* open the menu (top-left button)
* click Submit Feedback
* Add any details, and click Submit.

You don't have to add any details before submitting feedback but if we have your GitHub username then we will be able to followup here :-)

FYI @alalamav who knows Android best.

**Comment by thomamvt** [comment]
Hi @alalamav i've submitted a feedback from the device, but i was not able to send the report from the device after connecting, because i am not getting Internet after connecting to vpn, so i sent the feedback after disconnecting.

**Comment by alalamav** [comment]
Hi @thomamvt, thanks for submitting feedback. Could you please share with us your Android 6.0 device make and model?

**Comment by thomamvt** [comment]
Its actually running on a dell inspiron laptop Intel processor, android
6.0, 32 bit version from http://www.android-x86.org

**Comment by alalamav** [comment]
The Android client does not currently support x86 devices unless arm emulation is supported by the OS. It could also be an issue with the porting of Android VPN APIs to Android x86.

Are you able to connect from the laptop through the official Shadowsocks Android client? Is your Android 8.0 device also x86?

**Comment by thomamvt** [comment]
@alalamav , i installed and configured shadowsocks client on my Android X86. It is working fine and i'm now able to connect to the server with full internet access. Thank you for advising about this app.
