### ISSUE TITLE
Abnormal Network I/O Usage

### ISSUE THREAD

**Issue by fjn308** [Jigsaw-Code/outline-server#418]
When downloading large files (7 GB, for example as I did) from a link (web page) shared by Google Drive, from the control panel of my sever I noticed that the network input is approximately 4 times more than output (100 Mbps out vs 500 Mbps in, for example), which means if I download files sized 150 GB, the bandwidth usage is nearly 1 TB. High CPU usage occurs, too, which caused my server limited. I wonder why, so I then tried the same thing on another server equipped with shadowsocks-go (but with lower service plan, mainly lower CPU), nothing abnormal happened.

You can test to find if it is a common problem.

**Comment by shaomeng** [comment]
I report that I don't observe the same behavior on a DigitalOcean Ubuntu18.04 Server. I.e., when I download a large file from Google Drive, the inbound and outbound traffic are approximately the same at ~50Mbps.

**Comment by fjn308** [comment]
> I report that I don't observe the same behavior on a DigitalOcean Ubuntu18.04 Server. I.e., when I download a large file from Google Drive, the inbound and outbound traffic are approximately the same at ~50Mbps.

Many thanks, I will do a more detailed test after my bandwidth is reset and outline is reinstalled on my sever.

**Comment by shaomeng** [comment]
@fjn308 I should specify that I manually created a droplet on DigitalOcean, and manually deployed Outline server using that one command/script.

Also note, this issue might be related to #364 .

**Comment by fjn308** [comment]
> @fjn308 I should specify that I manually created a droplet on DigitalOcean, and manually deployed Outline server using that one command/script.
> 
> Also note, this issue might be related to #364 .

Sorry I forgot to explain that it was a fresh installed Ubuntu 18.04, and _**I enabled BBR as default TCP congestion control algorithm**_ before the installation of Outline Sever. I think I need to find out if BBR is related. But it's a pity that the bandwidth will not be reset until 10 days later, and my server is unavailable till then.

**Comment by fortuna** [comment]
Hi @fjn308, what do you mean with "the control panel of my server"? The Outline Manager doesn't show you the input and output, so it would be helpful to know where you got the information from.

For example, the server total traffic will be double the client traffic, because you have the client<->server connection and the server<->target connection. Also, the server total traffic will include things like server software updates.

**Comment by fjn308** [comment]
> Hi @fjn308, what do you mean with "the control panel of my server"? The Outline Manager doesn't show you the input and output, so it would be helpful to know where you got the information from.
> 
> For example, the server total traffic will be double the client traffic, because you have the client-server connection and the server-target connection. Also, the server total traffic will include things like server software updates.

Thanks for your replying!
Sorry I didn’t make that clear. The control panel is from the webpage of the VPS supplier, where I can observe its real-time in/out traffic.
After submitting this issue I should have done a further test on it, but soon I forgot it. For my personal reasons I cannot do it through this month, but whenever I can I will test and report ASAP.

**Comment by fjn308** [comment]
I'm so embarrassed to explain the situation that my VPS (the one with I/O problem mentioned here) had been baned by the GFW for months, and there's no tendency towards an unblock when I can do a further test. A similar problem has not been found on my new VPS, so I guess it's time to close this comment.
