### ISSUE TITLE
Tip for google cloud and amzon aws setup

### ISSUE THREAD

**Issue by thomamvt** [Jigsaw-Code/outline-server#42]
I managed to run outline server on google cloud and amazon aws. This is what i did.

1. I created an EC2 server (compute engine on google). 
2. Assigned a static IP (Elastic IP on amazon)
3. Opened the ports from firewall on google cloud and amazon aws (not the operating system instance).
4. Opened the ports on firewall on the server OS.
5. Excecuted the outline script from the outline application.
6. Amazon instance was asking to install docker (copy the instruction on screen)
7. Got the output
8. Copied to the outline manager windows app
9. shared the key to android
10. working VPN (with bugs on some android devices)

**Comment by trevj** [comment]
@thomamvt Thanks for the report! Happy to hear you got up and running on both environments.

**Comment by mariovol** [comment]
Thanks a lot for the tips!
on point 4. what ports did you open?

**Comment by trevj** [comment]
@thomamvt You might be interested to see that the server manager will soon guide you through the process of configuring the firewall on Amazon and Google Cloud:
https://github.com/Jigsaw-Code/outline-server/pull/212

**Comment by jdsimcoe** [comment]
@trevj @thomamvt What are the costs of running on AWS EC2 or Google Cloud compared to Digital Ocean's $5/mo.?

**Comment by trevj** [comment]
@jdsimcoe Comparable, I believe - the cheapest plans on both should be fine for running an Outline server for a handful of people - but I'm afraid you'll have to research the specifics yourself.

**Comment by immartian** [comment]
any chance to automate Google Cloud/Amazon server setup like Digital Ocean, in Outline Manager?
