### ISSUE TITLE
API reference doc

### ISSUE THREAD

**Issue by rahilwazir** [Jigsaw-Code/outline-server#420]
Where can I find the API reference doc for Outline Server? Specifically for Outline Manager if that helps.

Basically, **I want to create users in Outline Manager through the API**, is it possible? If so, please can you guide me to the documentation or a code snippet or any hint? Like request URL, request body etc.

Thank you.

**Comment by alalamav** [comment]
Hi @rahilwazir, thanks for trying Outline. You can find the API documentation and examples [here](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/README.md). 
Feel free to re-open this issue if you have further questions.

**Comment by rahilwazir** [comment]
@alalamav OK thanks. Can you please assist. The access key is basically to create new users in Outline server?

**Comment by alalamav** [comment]
An access key represents a user of your server. While there is no restriction to how many users (or devices) can use an access key, we recommend having a one-to-one mapping between users and access keys.
