### ISSUE TITLE
Delay before start loading a website and loss of internet connection

### ISSUE THREAD

**Issue by alinol** [Jigsaw-Code/outline-server#426]
My problem is similar to this issue [https://github.com/Jigsaw-Code/outline-server/issues/401](url), but this solution (changing the server) didn't work for me.

Every time i start loading a website for the first time there's a delay before it actually starts loading. This only happens on my PC, while my Android smartfone works fine.
I tried using different servers - Digital Ocean (Amsterdam and Frankfurt) and Scaleway, but still had the same problem (however Scaleway server sometimes stops to connect to websites at all and I need to reconnect to the server; and again on my smartphone everything is OK even on Scaleway).
I also tried to turn off my AV (NOD Smart Security) but nothing changed.

And like in the issue mensioned above connecting to the same website within a short period of time doesn't cause a delay.

**Comment by alinol** [comment]
Before I said that only Scaleway server fails to connect to websites at all after some time of being able to do it.
It turns out Digital Ocean server has this problem as well - I am able to connect to websites for some time, but in an hour or so (sometimes much earlier) I just can't load a single page, and I need to reconnect to my Outline server to do so.

**Comment by vysecurity** [comment]
I've noticed this too.

**Comment by vysecurity** [comment]
Potential solution, please try and come back to me:

```iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to 1.1.1.1:53;
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to 1.1.1.1:53;
iptables -t nat -A POSTROUTING -j MASQUERADE```

**Comment by vysecurity** [comment]
OK, the issue is on Windows, it uses your router most likely for DNS before it reaches out to your VPN. So if you set your Wireless network DNS server to a public DNS server such as 1.1.1.1 or the one used by your VPS, then it won't have this issue.

I resolve this and have a second layer of redundancy by setting primary 1.1.1.1 and secondary to my router. So if it can't resolve with 1.1.1.1, it uses my secondary.

**Comment by alinol** [comment]
Hello, vysecurity
Thanks a lot for your answer

Unfortunately it looks like your advise didn't work.

My PC indeed uses my router DNS so I tried changing DNS to 1.1.1.1 on my router, but it didn't help. I tried to set DNS for my PC itself (so that it doesn't use router DNS) and I also tried setting DNS for the Outline connection, but none of than helped either.

Changing DNS to the one used by my VPS (10.8.30.8 and 10.8.30.9) blocked my internet connection in a weird way: when changing router settings it didn't have any effect; changing PC settings blocked connection to some sites (i.e. youtube worked ok while laracasts was not available); changing Outline settings didn't let me connect to anything at all.

Some other things I noticed: Outline connection settings had some preset DNS addresses (208.67.222.222 and 216.146.35.35) which I couldn't ping while connected though Outline (but could ping otherwise); btw DNS settings for Outline don't have an option to 'get DNS automatically' (the check is inactive). Also Outline connection has some preset IP address starting with 10.0.

I also tried setting those Outline preset DNS for my router and my PC but it still had no effect.

**Comment by alalamav** [comment]
Hi @alinol, I'm sorry you're experiencing this issue. What version of the Outline Windows client are you running? Could try uninstalling Outline, removing the TAP device (you can do so in the Device Manager), and re-installing Outline? 
Please let me know if the problem persists after these steps. Thanks.

**Comment by vysecurity** [comment]
You can’t ping using Outline because it doesn’t tunnel ICMP.

**Comment by alinol** [comment]
Hi @alalamav, thanks for your answer.
Unfortunately, your advice didn't help. I've uninstalled Outline Client, removed the TAP device (with drivers), reloaded my PC and then installed the Client again.
Moreover, recently (before starting this issue) I reinstalled my Windows (it was 7, now it's 10). I had the same problem on 7 and it persisted on 10.

As for the Client version, I didn't pay attention to it before uninstalling it, but I usually try to keep it up to date, so I guess it was not lower then 1.2.31. Now it's 1.2.32.

**Comment by DeanStern** [comment]
I also encourage this issue in Vultr, what are the servers hosting you managed to get work with SS?

**Comment by gragragrab** [comment]
Good afternoon.
I have the same issue, and the steps suggested here didn't help.

Details:
Last versions of Outline server and clients on Mac os 10.13.6, iOS 12.3.1, Android 9.

**Comment by iguitaryou** [comment]
I have the same problem. Is there any solution?

**Comment by weepingswords** [comment]
I am experiencing this issue as well. Outline works great on my iPhone but on my PC websites take forever to start loading.

**Comment by maddyhof** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
