### ISSUE TITLE
How do I send server metrics to my Google Cloud Function

### ISSUE THREAD

**Issue by youngchingjui** [Jigsaw-Code/outline-server#427]
Following the instructions for `src/metrics_server`, I've successfully set up a Google Cloud Function to parse usage data from my server and save it to Google BigQuery.

However, I'm confused how to get my server to start sending the data to my Google Cloud Function? After my Google Cloud Function is set up, then what?

**Comment by fortuna** [comment]
The easiest way for you to get metrics is to access the [Prometheus.io](https://prometheus.io/docs/prometheus/latest/getting_started/) endpoint at `localhost:9090`
You can setup a [Grafana dashboard](https://grafana.com/) based on the Prometheus endpoint. I have an example Grafana dashboard config here: https://gist.github.com/fortuna/ea92f0ac0e7543ed5feea75902880ca0

There's no need to create and maintain your own metrics endpoint. If you really want to do that (not recommended) you would have to override the [SB_METRICS_URL environment variable on installation](https://github.com/Jigsaw-Code/outline-server/blob/6e93cdc3f2af64aa3ad46651ce807d586fc05dd9/src/server_manager/install_scripts/install_server.sh#L271).
