### ISSUE TITLE
UDP enable

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#428]
Could we enable UDP and let user to choose TCP/UDP?

In some environment, UDP works much better than TCP, UDP doesn't need to ack like TCP. So in the gaming, streaming, it is not necessary to force to use TCP.

**Comment by fortuna** [comment]
Outline supports both. We don't force the use of TCP. If the server and the client app support UDP, and the server firewall doesn't block, UDP will be available for apps to use.

**Comment by sailosha** [comment]
> 
> 
> Outline supports both. We don't force the use of TCP. If the server and the client app support UDP (which is the case for Outline), and the server or client firewalls don't block, UDP will be available for apps to use.

thanks, I was confusing for logn time. So could we choose to use UDP or TCP for the client. Or we need to block on server firewall

**Comment by alalamav** [comment]
Feel free to re-open with further questions.
