### ISSUE TITLE
install_server.sh hangs on ipinfo.io

### ISSUE THREAD

**Issue by trick77** [Jigsaw-Code/outline-server#43]
Please use a curl connect timeout with proper error handling so the server_install.sh script won't just hang forever. Found out the hard way that ipinfo.io is dropping traffic from entire hosting network ranges. I'd suggest using a different public IP detection service.

**Comment by trevj** [comment]
@trick77 Thanks for the feedback. We are working to improve our installation script.

**Comment by trevj** [comment]
We no longer use ipinfo.io so I think issue should be resolved. Thanks again for the feedback!
