### ISSUE TITLE
Usage statistics often missing from manager

### ISSUE THREAD

**Issue by MaybeGoogle** [Jigsaw-Code/outline-server#433]
Oftentimes, when I open up the manager, the usage statistics are missing completely. Usually, they'll show up after a while (10 minutes). Sometimes, however, I can't get it to show at all. 

![image](https://user-images.githubusercontent.com/30007491/58295552-6afbd980-7d95-11e9-91a8-c67f534d0353.png)

As you can see, the main bandwidth display is blank, while individual usage has a `...` placeholder.

**Comment by alalamav** [comment]
Hi @MaybeGoogle, sorry you're experiencing this issue. Could you please submit feedback through the app and tag it with this (GitHub) issue number? 
Do you see similar latencies with other fields, such as access keys?

**Comment by MaybeGoogle** [comment]
Submitted feedback through the app as requested.  
I don't have any latency with getting the access keys, and creating/renaming users always works fine.

**Comment by R-MiN** [comment]
Hi **@maybegoogle** , i have the same issue with 2 servers and 230 users ... is there any solution to this ?

best regards

**Comment by jadolg** [comment]
Same issue here with only 25 keys

**Comment by fortuna** [comment]
I think this had to do with the stats backend (Prometheus) crashing and not coming back up. Since then we made the backend restart on crashes. I believe this is fixed, but feel free to reopen if not.

**Comment by esirK** [comment]
Hello @fortuna  I just experienced this issue in `Version 1.8.1 (1.8.1.4407)` 
The `metrics/transfer` endpoint returns 
```
{
code: "InternalServer",
message: ""
}
```

**Comment by Simplici** [comment]
same issue on my server(V1.7.2), about 200 keys.
I am not sure if there is a way to fix for my server.
