### ISSUE TITLE
DNS LEAK 

### ISSUE THREAD

**Issue by saifalbadi** [Jigsaw-Code/outline-server#434]
DNS LEAK WebRTC leaks

what i think it is not outline server, it might be docker making the leak.
my VPS is :
debian 9
and docker as below
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by saifalbadi** [comment]
![dnsleak](https://user-images.githubusercontent.com/51148890/58532028-5e440f00-81f5-11e9-900f-c761b5a1e04a.JPG)

**Comment by fortuna** [comment]
What site are you using to run the test?

**Comment by saifalbadi** [comment]
> What site are you using to run the test?

ipleak.net
dnsleak.com

i am used chrome and firefox browsers in pc and android, both of them are the same .

i think it is not outline, it is docker for sure .

**Comment by fortuna** [comment]
How do you know there's a DNS leak? It's not clear from the image you sent.

I checked some of the IPs in your image and I got OpenDNS and Vultr. No ISP there, which makes me conclude there's no leak.

**Comment by prinako** [comment]
> How do you know there's a DNS leak? It's not clear from the image you sent.
> 
> I checked some of the IPs in your image and I got OpenDNS and Vultr. No ISP there, which makes me conclude there's no leak.

So pls can show how dns leak look like ?. 
Please because me to having same issues and I think is dns leak ..

**Comment by fortuna** [comment]
If a DNS leak was happening, you would see the IPs of the DNS resolver from your ISP.
