### ISSUE TITLE
feature request ~ enable use from port restricted client networks

### ISSUE THREAD

**Issue by rivy** [Jigsaw-Code/outline-server#44]
Some client networks are more locked down than others, limiting traffic to use of only a small number of specific ports. But, even on these limited networks, the usual web ports ("80", "443", ...) are almost always functional. A VPN connection, in addition to encrypting content, can also liberalize these limited networks back to full operation.

Unfortunately, the current Outline VPN implementation is unusable on those networks, even though other, commercial / main stream, VPN services can be used (eg, Private Internet Access (PIA)).

By allowing use of specific ports, especially port "443" (which is expected to be encrypted) or even "8443" (less ideal), would allow stealth usage on those networks. The server wouldn't have to be attached specifically to "443"; a server or host firewall could redirect traffic from "443" to another, less privileged port. But, the server would ultimately need to respond to traffic on a specific port or port range.

Not knowing `shadowsocks`, I'm not sure whether this is already possible. If so, some instruction on a working configuration would be welcome.

I'm happy to assist with a Wiki page detailing the process, if helpful.

**Comment by trevj** [comment]
@rivy Thanks for the feedback. This is one we'll take into consideration.

**Comment by enesismail** [comment]
+1 

Ability to change connection port or able to accept connections from different ports (80, 443, 53) would be great.

**Comment by krotish** [comment]
Hi!

Any updates on this enhancement request?
All outgoing ports, expect 80, 443 and a few more are restricted in my network.

Help, please.

**Comment by VictoriaRaymond** [comment]
Using Shadowsocks on port 443 (or other well-known ports) is not recommended, as Shadowsocks protocol doesn't look like TLS (that runs on port 443). It is easy to tell that your client connects to some 443 port, but transferring non-TLS data. This is a highly suspicious footprint, and may be easily blocked.

You may consider [V2Ray](https://v2ray.com/) which has an ability to transfer data over TLS+WebSocket. It can combine with web servers (such as Nginx) to create purely HTTPS traffic against censorship. 

Here is some reference (mainly in Chinese, sorry):

* https://toutyrater.github.io/advanced/tls.html
* https://v2ray.com/en/configuration/transport/websocket.html
* https://www.xpath.org/blog/001531048571577582cfa0ea2804e5f9cb224de052a4975000

**Comment by trevj** [comment]
@lorenooliveira Yes, ports <1024 should be possible.

**Comment by trevj** [comment]
@VictoriaRaymond Agreed - we will not be selecting port 443 by default.

**Comment by hkyq** [comment]
Hey, are there any updates on this issue?

**Comment by hfcheng66** [comment]
in the current implementation, is it true that the server running outline server docker has to open wide range of ports? thanks.

**Comment by alalamav** [comment]
@hkyq, per #415 it is now possible to use flags in the install script to specify the hostname and port. We are working on a feature to configure these from the Outline Manager.

@hfcheng66, you need only open the ports used for the API and the access keys (they are all created on a single port). That said, DigitalOcean opens all high-numbered ports by default.

**Comment by stonedreamforest** [comment]
> @hkyq, per #415 it is now possible to use flags in the install script to specify the hostname and port. We are working on a feature to configure these from the Outline Manager.
> 
> @hfcheng66, you need only open the ports used for the API and the access keys (they are all created on a single port). That said, DigitalOcean opens all high-numbered ports by default.

hello , any progress ?

**Comment by iineva** [comment]
Temporary solution:
1. Edit files change all current port to you want:

```shell
/opt/outline/persisted-state/outline-ss-server/config.yml
/opt/outline/persisted-state/shadowbox_server_config.json
/opt/outline/persisted-state/shadowbox_config.json
```

2. Restart containers:

```shell
docker restart watchtower
docker restart shadowbox

# Or just restart docker (Ubuntu):
# systemctl restart docker
```

**Comment by krotish** [comment]
Currently you don't need to edit any configs.

just use install_server.sh --hostname=example.com --keys-port=10000 --api-port=8080 when installing.

**Comment by darkk** [comment]
@krotish those options do not change the port of shadowsocks server, if I understand everything correctly. They change two management ports.

**Comment by alalamav** [comment]
The `--keys-port` option sets the port for new access keys. For reference:

```bash
Usage: install_server.sh [--hostname <hostname>] [--api-port <port>] [--keys-port <port>]

  --hostname   The hostname to be used to access the management API and access keys
  --api-port   The port number for the management API
  --keys-port  The port number for the access keys
```

We are getting closer to making these options configurable, at the very least the API management port. Thank you all for your patience.

**Comment by hfcheng66** [comment]
> Temporary solution:
> 
> 1. Edit following files change all current port to you want:
> 
> ```shell
> /opt/outline/persisted-state/outline-ss-server/config.yml
> /opt/outline/persisted-state/shadowbox_server_config.json
> /opt/outline/persisted-state/shadowbox_config.json
> ```
> 
> 1. Restart containers:
> 
> ```shell
> docker restart watchtower
> docker restart shadowbox
> 
> # Or just restart docker (Ubuntu):
> # systemctl restart docker
> ```

I've manually changed port to 443 on above three files and restarted.
Where can I get the json string (installation output) I paste to outline manager?

**Comment by krrisztian** [comment]
The installation output that one needs to paste into Outline Manager can be found (after the installation) under /opt/outline/access.txt

**Comment by fortuna** [comment]
This has been fixed for a while. You can change the port for new keys on the manager, and we have TCP fallback for DNS in case UDP is blocked.
