### ISSUE TITLE
Please optimize the penetration and confusion for the current GWF in China. Thank you.

### ISSUE THREAD

**Issue by hktalent** [Jigsaw-Code/outline-server#440]
Please optimize the penetration and confusion for the current GWF in China. Thank you.

**Comment by sailosha** [comment]
I don't think it is outline issue. It is more about SS protocol issue.

**Comment by immartian** [comment]
seem GFW has upgraded to identify SS protocol easily now. Normally it takes days to be spotted, now quick to hours if you use Outline there.
