### ISSUE TITLE
FYI - GFW begins to intercept Outline + Shadowsocks traffic

### ISSUE THREAD

**Issue by vysecurity** [Jigsaw-Code/outline-server#449]
There's been news that the GFW is now intercepting the Shadowsocks protocol.

**Comment by vysecurity** [comment]
Are servers blocked when using port 443 or only when using high number ports?
- I don't know, the manager will auto allocate a high port.

Are servers blocked when disabling UDP?
- Not sure, using the default outline.

Are servers blocked when all clients use non-Outline apps that support selective proxying (e.g. gfwlist)?
- I don't use gfwlist

Are non-Outline servers being blocked?
- I only use Outline.

Are the Outline servers being probed, and is there something giving them away?
- I heard the protocol is being fingerprinted and analysed.

Is WeChat sharing invitation links with the government?
- Most likely, but I can't comment :)

**Comment by vysecurity** [comment]
Word has it that a security researcher cracked the protocol for SSR.

Apparently, V2Ray is stable still. But I don't use V2Ray.

**Comment by stonedreamforest** [comment]
https://github.com/Jigsaw-Code/outline-client/issues/551

**Comment by LBYPatrick** [comment]
Network: China Mobile, Guandong Province.

It isn't necessarily anything to do with WeChat, but based on my experience with both the original Shadowsocks clients (i.e. shadowsocks-android, shadowsocks-windows) and Outline, our GFW might be randomly blocking **ALL** non-HTTP/HTTPS traffic.

> And yes non-Outline servers are getting blocked by **IP Address**. If you ever have a chance to rent a server on [Linode](www.linode.com), [BandwagonHost](https://bandwagonhost.com/) or [Vultr](https://vultr.com) then ping it on [ping.pe](https://ping.pe), you might notice that all servers in China would show 100% packet loss. (Which is a clear sign of IP Ban. 90% chance of occurrence)

> I am not sure about Google Cloud Platform since I don't have any server on it.

**Comment by fortuna** [comment]
We have hard evidence of Outline servers running in China for over 6 months without being blocked, so Shadowsocks detection is certainly not consistent.

It may be related to the port number. I recommend using port 443 for access keys. That can be specified on manual server creation, and soon on the Manager UI.

**Comment by vysecurity** [comment]
How does one perform manual server creation?

**Comment by vysecurity** [comment]
Also it's not fully blocked, just that the connection drops after a few minutes :)

**Comment by fortuna** [comment]
@vysecurity  What operating system you are using when seeing the connections being dropped?

We released a fix to Windows and Linux that should address some connection issues.

**Comment by sysk** [comment]
China is definitely throttling/blocking shadowsocks traffic and it is indeed very inconsistent which makes it harder to figure out. For example, my Hong Kong based Outline server works reasonably well from my home ISP (China Telecom) and when I go to my office 10 mins from here (also China Telecom), I can't connect to any of my outline servers (or it will let me connect and then nothing works).

I strongly suggest you have a chat with the v2ray developers, they can tell you all you need to know about shadowsocks in China.

**Comment by sicaboy** [comment]
It looks like there is no way for Outline to change ports? I installed Outline (with fixed ports), blocked by GFW, but installed ShadowsockR with customised port and works.

**Comment by g-faucheux** [comment]
After I installed outline yesterday night on an Amazon EC2 Singapore, the first 24h were so fast in IOS, watching HD videos and surfing in high speeds, then I slept and woke up to find out that the port 4120 assigned by the Outline Manager got blocked by the GFW.

@sicaboy ShadowSockR isn't encrypted and therefore your connections are not secure.

**Comment by hang333** [comment]
@g-faucheux ShadowSocksR isn't encrypted??

**Comment by WoodpeckerBaby** [comment]
GFW is unable to detect Shadowsocks traffic. They are just throwing pop on server IPs that are sending a large amount of traffic to any particular client. 

This is especially true when they probe the server IP and can't validate the server SSL certificate to be a legitimate host. 

They are able to catch on to this first within a day, then when they target a single client and backtrace, they can discover within hours.

**Comment by vysecurity** [comment]
Doesn't matter, Outline is useless in China right now anyway.

**Comment by fortuna** [comment]
Since this bug was reported we fixed multiple detection vulnerabilities.
We have reports that Outline is working well in China now.

I'll close this old bug and we can file a new one with fresh information if needed.
