### ISSUE TITLE
Wrong icon display on macos

### ISSUE THREAD

**Issue by ErvingWu** [Jigsaw-Code/outline-server#452]
![Screenshot 2019-06-26 at 01 01 04](https://user-images.githubusercontent.com/52124755/60118089-1f7e8600-97ae-11e9-9c10-720d9df27507.png)

**Comment by fortuna** [comment]
@alalamav didn't we have this fixed? What was the workaround?

**Comment by cjhenck** [comment]
Duplicate of #320
