### ISSUE TITLE
Unable to connect to Outline server from Ubuntu

### ISSUE THREAD

**Issue by Flakturm** [Jigsaw-Code/outline-server#453]
I have set up an Outline server on DigitalOcean.  I'm able to connect to that server from my Android phone and iPad.  The VPN works as it's supposed to.

I also installed the Outline-Client.AppImage on my laptop which runs Ubuntu 16.04.  For some reasons, it connects to my Outline server no problem but the VPN does not work.

Where should I look?

**Comment by fortuna** [comment]
The support team can help you troubleshoot: https://support.getoutline.org/s/contactsupport

**Comment by Liontamer25** [comment]
Hello Flakturm, 
Please reach out to our support (https://support.getoutline.org/s/contactsupport) team by filling out a feedback form. Please don't forget to include your email address so we can reply to you.  

Best,
-Nino
