### ISSUE TITLE
Install script fails on CentOS with "declare -g"

### ISSUE THREAD

**Issue by NotSoSuper** [Jigsaw-Code/outline-server#459]
CentOS release 6.10 (Final)
GNU bash, version 5.0.0(1)-release (x86_64-pc-linux-gnu)

The server install script from the outline manager fails with:
```sh
[root@VPN ~]# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
bash: line 450: declare: -g: invalid option
declare: usage: declare [-aAfFilrtux] [-p] [name[=value] ...]

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
```

`declare -g` does not work on my local Mac OS bash terminal either, but it does work on Ubuntu Server's bash.

https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh#L451-L453

**Comment by JonathanDCohen** [comment]
What version of bash are you running?  Looking at similar issues on SO it was pointed out that declare -g only exists in bash 4.2 and above

**Comment by NotSoSuper** [comment]
I built the latest bash on the server, to test that theory, and it didn't work. I've included the bash version in the OG issue - GNU bash, version 5.0.0(1)-release (x86_64-pc-linux-gnu).

**Comment by JonathanDCohen** [comment]
Interesting, it seems like CentOS is shipping a weird versin of bash?  Anyways can you pull down from the referenced PR and see if it solves the issue?
