### ISSUE TITLE
stuck on "curl --cacert /root/.shadowbox/persisted-state/shadowbox-selfsigned.crt -s https://my_amazon_ec2:62614/zTKkAXHPd0JsGVNzpEiG3g/access-keys"

### ISSUE THREAD

**Issue by banhao** [Jigsaw-Code/outline-server#46]
I'm using this command to show the install detail "wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash -x"

the install process stuck on this command "curl --cacert /root/.shadowbox/persisted-state/shadowbox-selfsigned.crt -s https://my_amazon_ec2:62614/zTKkAXHPd0JsGVNzpEiG3g/access-keys"

use "netstat -ltnp | grep 62614" to show which process open the port
tcp6       0      0 :::62614                :::*                    LISTEN      1639/node

why the port was opened in TCP/IP v6? How can I force the install to using TCP/IP v4?

**Comment by banhao** [comment]
I was so silly! I attached the "default" security group to my aws-ec2 server, but forgot to change the source, it only allowed my specific group to access. Changed it to "AnyWhere" the installation was successful.

**Comment by trevj** [comment]
@banhao I'm glad you got it working! Thanks for the feedback!
