### ISSUE TITLE
Set Watchtower to selectively watch shadowbox

### ISSUE THREAD

**Issue by evanjarrett** [Jigsaw-Code/outline-server#48]
I'll admit I should have read the install script a little more carefully, but while running the install, watchtower tried updating all my other containers, which ended up breaking my wordpress container :(

I would like to suggest only setting watchtower to selectively watch shadowbox.

Reading the watchtower documentation, this can be done by passing in `--label-enable` as a param on watchtower and adding `--label=com.centurylinklabs.watchtower.enable=true` on shadowbox.

More information can be found on the [watchtower repo](https://github.com/v2tec/watchtower#selectively-watching-containers)

**Comment by trevj** [comment]
@00firestar00 Many thanks for the report. I'm happy you got up and running with Outline. Regarding Watchtower settings, we're going to take that into consideration.

**Comment by alxndrkalinin** [comment]
I think I faced the same issue. After reinstalling Outline and eventually restarting the server, my another container got updated and cleaned up :slightly_frowning_face: Would be great if Outline's watchtower didn't mess with existing containers.

**Comment by AlekSi** [comment]
See #1255
