### ISSUE TITLE
Hope you can customize network ports

### ISSUE THREAD

**Issue by w698** [Jigsaw-Code/outline-server#483]
**Some companies only have fixed ports on their public networks, and if you can't set them up, you can't cross the wall.**

**Comment by alalamav** [comment]
Hi @w698, we are working on a feature to customize the access key port from the Outline Manager. In the meantime, if you are running the server install script yourself, you can use the `--api-port` and `--keys-port` flags to customize the ports.

**Comment by alalamav** [comment]
This feature has been released in the Outline Manager v1.3.0.
