### ISSUE TITLE
outline server - backup / restore

### ISSUE THREAD

**Issue by B451YbUz75Rn** [Jigsaw-Code/outline-server#490]
Hi @a1exus, we are working on a feature to share server management. In the meantime, you can find your server's credentials at opt/outline/access.txt (unless it's a legacy server, in which case it should be in /root/shadowbox/access.txt). There you'll find the apiUrl and certSha256, which you can format as JSON and import it to another Outline Manager.

Hope this helps; feel free to reopen this issue if you have any questions.
-------------------------------------------------------------------------------------------------
Please explain how to do it!
I don't know how to do it.
Thank you very much for your reply.

**Comment by chedxb** [comment]
I am unable to locate the access.txt file. I tried both options, but there is no such file.

could you assist pls?

**Comment by B451YbUz75Rn** [comment]
> I am unable to locate the access.txt file. I tried both options, but there is no such file.
> 
> could you assist pls?

It should be a server-side software update, and now it can't be found.
I can see it a week ago.

**Comment by CuiJinku** [comment]
I found "access.txt" in this folder: /opt/outline.

**Comment by alalamav** [comment]
Feel free to re-open with further questions.
