### ISSUE TITLE
How do i modify the access key port?

### ISSUE THREAD

**Issue by ti4n1993** [Jigsaw-Code/outline-server#493]
I tried to reinstall,but it didn't help

**Comment by oreoluwa** [comment]
There are 2 ways I can think of:
1. Add/edit the `portForNewAccessKeys` in your `shadowbox_server_config.json` file. If you went with the default options during installation, depending on when you installed the server, this should either be in `/opt/outline/persisted-state/shadowbox_server_config.json` or `/var/lib/outline/persisted-state/shadowbox_server_config.json` or `/root/shadowbox/persisted-state/shadowbox_server_config.json` then restart your shadowbox server. If the old/previous ports are not available any longer, this would also mean your clients connected to the ports would not be able to connect
2. [DO THIS AT YOUR OWN RISK] Reset everything, i.e. stop the shadowbox container, delete your outline/shadowbox config directory, then install the server with the `--keys-port=12345`, where 12345 is the port for the new access keys. If doing this, please make sure your `[keys|api]-port`s are reachable from outside the network.

**Comment by krrisztian** [comment]
The server config file is located under either of the three locations mentioned above. Modify the file while paying close attention to the quotation marks, if you restart your server having a misplaced or deleted quotation mark, Shadowsocks will not boot up.
From then on, new keys will be created using the new port. Old keys stay untouched.

I believe the API is (almost?) functional in the new releases as well?

Issue solved?

**Comment by ti4n1993** [comment]
@krrisztian Sorry,I have switched to v2ray.

**Comment by krrisztian** [comment]
> @krrisztian Sorry,I have switched to v2ray.

Please close ticken then.

**Comment by p5ydn0** [comment]
> There are 2 ways I can think of:
> 
> 1. Add/edit the `portForNewAccessKeys` in your `shadowbox_server_config.json` file. If you went with the default options during installation, depending on when you installed the server, this should either be in `/opt/outline/persisted-state/shadowbox_server_config.json` or `/var/lib/outline/persisted-state/shadowbox_server_config.json` or `/root/shadowbox/persisted-state/shadowbox_server_config.json` then restart your shadowbox server. If the old/previous ports are not available any longer, this would also mean your clients connected to the ports would not be able to connect
> 2. [DO THIS AT YOUR OWN RISK] Reset everything, i.e. stop the shadowbox container, delete your outline/shadowbox config directory, then install the server with the `--keys-port=12345`, where 12345 is the port for the new access keys. If doing this, please make sure your `[keys|api]-port`s are reachable from outside the network.

@oreoluwa Thank you for your answer, it's very helpful for me.

I would like to ask you a question: Where can I find information about the password configure of shadowsocks?

Because I want to use other client to connect to the server, and these apps all need the password information of shadowsocks.

Looking forward to your reply. Thank you.

**Comment by oreoluwa** [comment]
@p5ydn0 I think you can find that either in `/opt/outline/persisted-state/outline-ss-server/config.yml` or `/opt/outline/persisted-state/shadowbox_config.json`. But you must be careful to use the correct port, cipher and password combination.

**Comment by p5ydn0** [comment]
> @p5ydn0 I think you can find that either in `/opt/outline/persisted-state/outline-ss-server/config.yml` or `/opt/outline/persisted-state/shadowbox_config.json`. But you must be careful to use the correct port, cipher and password combination.

@oreoluwa OK，I get it. Thanks for your reply. ^_^
