### ISSUE TITLE
shadowsocks plugin support?

### ISSUE THREAD

**Issue by fishead** [Jigsaw-Code/outline-server#498]
Do we have shadowsocks plugin support inside? like [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin).

**Comment by marcos1** [comment]
i agree with this with China's National Day approaching server's are getting hit very often and having something such as v2ray-plugin to obfuscate the traffic would be really useful.

**Comment by fortuna** [comment]
Outline doesn't support plugins, but a number of censorship-resistance improvements have been made since this bug was opened.

Please try Outline again and let us know if you have issues.
