### ISSUE TITLE
Bugs in outline-ss-server v1.0.7?

### ISSUE THREAD

**Issue by aquax1** [Jigsaw-Code/outline-server#499]
Tested on different VPS with different IPs, either cannot connect to Outline server, or after connecting, can only get on Youtube.

Older VPS without the v1.0.7 works fine.

**Comment by alalamav** [comment]
outline-ss-server v1.0.7 has not been rolled out to production yet. Could you provide more context on how you set up your server?

**Comment by alalamav** [comment]
Feel free to re-open with more information.
