### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by liononon** [Jigsaw-Code/outline-server#502]
I visit every website and get ERR_EMPTY_RESPONSE response when outline client conected and outline server no err logs. I can ping website  through

**Comment by alalamav** [comment]
Hi @liononon, please provide more context to this issue.
* Are you using the Outline clients to connnect? If so, which version?
* What is the client OS?
* Is your Outline server managed (DigitalOcean) or advanced (installed manually)?
* Where are the client and server located (if you feel comfortable answering)?
* Could you post some of the server logs (redacting PII)? SSH to the server and run `docker logs shadowbox`.

Thanks.

**Comment by liononon** [comment]
mac osx 10.14.6, outline client 1.3.1 version, installed manually.
client in china ,server in Chicago
server is restore from other server's snapshot , docker restart  normally, shadowbox container and watchower container restart normally.
`D2019-09-19T23:06:44.023Z 8 main.js:80] === Config ===
D2019-09-19T23:06:44.026Z 8 main.js:81] SB_PUBLIC_IP: 144.202.57.151
D2019-09-19T23:06:44.026Z 8 main.js:82] SB_METRICS_URL: https://metrics-prod.uproxy.org
D2019-09-19T23:06:44.026Z 8 main.js:83] ==============
I2019-09-19T23:06:44.028Z 8 main.js:92] Starting...
I2019-09-19T23:06:44.036Z 8 main.js:101] Prometheus is at 127.0.0.1:9090
I2019-09-19T23:06:44.036Z 8 main.js:102] Node metrics is at 127.0.0.1:9091
I2019-09-19T23:06:44.036Z 8 main.js:113] outline-ss-server metrics is at 127.0.0.1:9092
D2019-09-19T23:06:44.051Z 8 prometheus_scraper.js:97] Waiting for Prometheus to be ready...
level=info ts=2019-09-19T23:06:44.109431939Z caller=main.go:238 msg="Starting Prometheus" version="(version=2.4.3, branch=HEAD, revision=167a4b4e73a8eca8df648d2d2043e21bdb9a7449)"
level=info ts=2019-09-19T23:06:44.109671607Z caller=main.go:239 build_context="(go=go1.11.1, user=root@1e42b46043e9, date=20181004-08:42:02)"
level=info ts=2019-09-19T23:06:44.109706064Z caller=main.go:240 host_details="(Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 dongdong (none))"
level=info ts=2019-09-19T23:06:44.109767921Z caller=main.go:241 fd_limits="(soft=32768, hard=32768)"
level=info ts=2019-09-19T23:06:44.109799375Z caller=main.go:242 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-09-19T23:06:44.112371312Z caller=main.go:554 msg="Starting TSDB ..."
level=info ts=2019-09-19T23:06:44.113430356Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1566086400000 maxt=1566280800000 ulid=01DJQ42DQ4TQYG4BC35RXNJDHD
level=info ts=2019-09-19T23:06:44.113609983Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1566280800000 maxt=1566475200000 ulid=01DJWXF1EX3WRA5TJJXJ8H45T0
level=info ts=2019-09-19T23:06:44.113803686Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1566475200000 maxt=1566669600000 ulid=01DK2PVN5J0D2YRAFBC7KP8H5R
level=info ts=2019-09-19T23:06:44.113944556Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1566669600000 maxt=1566864000000 ulid=01DK8G88ZN0JNGNA4W2BY8ADGH
level=info ts=2019-09-19T23:06:44.11411396Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1566864000000 maxt=1567058400000 ulid=01DKE9MWNJMN522EKQ2VPB35TT
level=info ts=2019-09-19T23:06:44.114282178Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1567058400000 maxt=1567252800000 ulid=01DKM31GFW9TXYEPCJMVD1E0NC
level=info ts=2019-09-19T23:06:44.114421868Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1567252800000 maxt=1567447200000 ulid=01DKSWE45PH852Z6SG295GNVP3
level=info ts=2019-09-19T23:06:44.114561986Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1567447200000 maxt=1567641600000 ulid=01DKZNTQYTZBYH5AN8EFRHC8B3
level=info ts=2019-09-19T23:06:44.114723275Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1567641600000 maxt=1567836000000 ulid=01DM5F7BPKM3Y7W138G46YGS4N
level=info ts=2019-09-19T23:06:44.11489082Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1567836000000 maxt=1568030400000 ulid=01DMB8KZFF9VQEWFXRHBVB94TX
level=info ts=2019-09-19T23:06:44.115026096Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568030400000 maxt=1568224800000 ulid=01DMH20K5Y4A7XY7RMJ5EY4M0G
level=info ts=2019-09-19T23:06:44.115238694Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568224800000 maxt=1568419200000 ulid=01DMPVD6YFK2E02VFBXM0XS4CA
level=info ts=2019-09-19T23:06:44.115365347Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568419200000 maxt=1568613600000 ulid=01DMWMSTNT2Q2DC2MSQYFTRYDY
level=info ts=2019-09-19T23:06:44.115508323Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568613600000 maxt=1568808000000 ulid=01DN2E6GMEG6TFMWGC0S1TM80H
level=info ts=2019-09-19T23:06:44.11564035Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568808000000 maxt=1568872800000 ulid=01DN4C099KVKY9FMPPQ0T4X4PT
level=info ts=2019-09-19T23:06:44.115764745Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568872800000 maxt=1568894400000 ulid=01DN50K1YQA858AMV9NYSTHXV2
level=info ts=2019-09-19T23:06:44.115857482Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568916000000 maxt=1568923200000 ulid=01DN5N67JJ7GSV1M3CQAYVE9GE
level=info ts=2019-09-19T23:06:44.11597412Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568894400000 maxt=1568916000000 ulid=01DN5N67PQSD2MQJPEH1Y5K0ES
level=info ts=2019-09-19T23:06:44.116043895Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1568923200000 maxt=1568930400000 ulid=01DN5W1YTH504T0T89BF4BSKAQ
level=info ts=2019-09-19T23:06:44.139214472Z caller=web.go:397 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=warn ts=2019-09-19T23:06:52.584328129Z caller=head.go:371 component=tsdb msg="unknown series references" count=4272
level=info ts=2019-09-19T23:06:52.584846008Z caller=main.go:564 msg="TSDB started"
level=info ts=2019-09-19T23:06:52.584898898Z caller=main.go:624 msg="Loading configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=info ts=2019-09-19T23:06:52.601531073Z caller=main.go:650 msg="Completed loading of configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=info ts=2019-09-19T23:06:52.601595458Z caller=main.go:523 msg="Server is ready to receive web requests."
D2019-09-19T23:06:53.424Z 8 prometheus_scraper.js:101] Prometheus is ready
I2019-09-19T23:06:53.536Z 8 main.js:153] Manager listening at https://[::]:5924/6P1CSqfQRl5zUZHS-Bdd1w
I2019-09-19T23:06:54.514Z 24 server.go:227] Metrics on http://127.0.0.1:9092/metrics
I2019-09-19T23:06:54.514Z 24 server.go:233] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb
I2019-09-19T23:06:54.525Z 24 server.go:78] Listening TCP and UDP on port 12722
I2019-09-19T23:06:54.525Z 24 server.go:152] Loaded 3 access keys
level=info ts=2019-09-20T01:00:02.225461682Z caller=compact.go:398 component=tsdb msg="write block" mint=1568930400000 maxt=1568937600000 ulid=01DN62XPP8GKKA22ZFEF45K8WM
level=info ts=2019-09-20T01:00:02.246736754Z caller=head.go:446 component=tsdb msg="head GC completed" duration=5.114007ms`

**Comment by liononon** [comment]
I thought there might be fingerprints on the previous server in the snapshot, so I stopped the container and deleted the image  and install outline server again.

**Comment by alalamav** [comment]
Feel free to re-open when you have more information.

**Comment by Dimit77** [comment]
Hi 
I have the same problem.
PIng is OK but pages don't open (error ERR_EMPTY_RESPONSE)
ping :
ping : C:\Users\Dimit>ping -t 8.8.8.8
Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64

OS: windows
Server managed manually on ionos.de
Server in Germany, client in Russia
log in attachment
[log.txt](https://github.com/user-attachments/files/17376666/log.txt)
