### ISSUE TITLE
Outline-Server docker memory usage keep going up

### ISSUE THREAD

**Issue by ruoxijiang** [Jigsaw-Code/outline-server#506]
After installing outline server on AWS vps using the method provided by outline-manager.
When running docker stats, I would notice the shadowbox memory usage would keep going up.

Below is the docker info output

> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 2
>   Running: 2
>   Paused: 0
>   Stopped: 0
>  Images: 2
>  Server Version: 19.03.2
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.15.0-1050-aws
>  Operating System: Ubuntu 18.04.3 LTS
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 1
>  Total Memory: 984MiB
>  Name: ***
>  ID: ***
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No swap limit support

**Comment by fortuna** [comment]
This has probably been fixed.
