### ISSUE TITLE
Deleted Outline Manager and can't find apiURL in /opt/outline/access.txt

### ISSUE THREAD

**Issue by gulfecom** [Jigsaw-Code/outline-server#508]
Hello,

I have deleted by error Outline Manager and therefore the credentials to access the server (mainly apiUrl & certSHA256.
Since I have access to sudo by SSH, I looked for it in /opt/outline/access.txt as explained in other resolved issues.
Nevertheless, on my server : VI /opt/outline/access.txt only shows certSha256 and no apiUrl

![image](https://user-images.githubusercontent.com/9799234/66291647-a7624900-e8e2-11e9-9ff0-98625aaac379.png)

Thx for your help,

G.

**Comment by alalamav** [comment]
Hi @gulfecom, that's strange. Did your installation succeed?
Maybe you can try re-installing Outline - that should write the API URL per https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh#L415.

**Comment by gulfecom** [comment]
Hello,
Yes the installation was good and I have installed this server a while ago.
Just the access.txt did not include the apiUrl.

I reinstalled like you said. I was afraid it would remove all my users and change the port but this did not happen and now I have the apiUrl in access.txt

Thx :)

G
