### ISSUE TITLE
RESOLVED: Can not "re-connect" latest version of Outline Manager to existing VPN for management

### ISSUE THREAD

**Issue by jtlevy** [Jigsaw-Code/outline-server#526]
My VPN is out on DigitalOcean. Its been over a year since I fired up the Outline Mgr, so I downloaded the latest version. I am unable to 'connect' / manage my existing VPN. 

2 notes: 
1) the prior version of Manager wasn't connecting either
2) regarding just destroying my current VPN and creating a new one... My VPN is providing access across dozens of publisher content systems. The process to update each publisher with a new IP address is going to be a nightmare.

Much thanks!

**Comment by alalamav** [comment]
Hi @jtlevy, I have a few questions that may help us diagnose the issue:
- What error do you get when you open the Outline Manager? 
- Have you signed in to DigitalOcean from the app? (Signing out of DO from the app may help).
- On which platform are you running the Outline Manager?

**Comment by jtlevy** [comment]
No error in Outline Mgr
I am signed in and tested by creating a new instance in Germany - all OK
I am running on a Mac

**Comment by jtlevy** [comment]
I figured it out. The 'shadowbox' tag was missing from my server instance. Adding it back allowed the Manager to see the instance.
