### ISSUE TITLE
I lost my Outline Manager connection info 

### ISSUE THREAD

**Issue by chenxushuo** [Jigsaw-Code/outline-server#533]
I lost my Outline Manager connecting info ，like this：
{
  "apiUrl": "https://XXXXXX:12345/xxxxxxxxxxxxxxxxxxxxxxx",
  "certSha256": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
How can i get it again？

**Comment by alalamav** [comment]
Hi @chenxushuo, you can find your server's credentials in the host machine, at `/opt/outline/access.txt`. You can then format it as JSON and import it to the Outline Manager. Let us know if that works.

**Comment by chenxushuo** [comment]
Oh！it worked！thank you！
