### ISSUE TITLE
Add compression feature

### ISSUE THREAD

**Issue by saifalbadi** [Jigsaw-Code/outline-server#536]
Hello,
It would be great if you could add feature to compress the data in/out. 
Like LZO compression in openvpn
Maybe most of the internet nowadays does not need to be compress, but some people would love to see this feature 

Many thanks

**Comment by fortuna** [comment]
Most traffic is HTTPS, which can't be compressed meaningfully. Many HTTP servers already use gzip. Compression at the VPN layer doesn't seem like it would help much. Do you have any evidence?
