### ISSUE TITLE
Waiting for Outline server to be healthy

### ISSUE THREAD

**Issue by thejaswip** [Jigsaw-Code/outline-server#538]
Getting stuck at 
Waiting for Outline server to be healthy
docker logs shadowbox gives

standard_init_linux.go:211: exec user process caused "exec format error"

repeatedely, i am running this in Raspberry Pi 4,  and i am assuming this has to with that  ie; it being ARM pretty strange even running from docker will create this issue, my docker is running fine otherwise.

**Comment by R-MiN** [comment]
i have the same problem however i think it is because of customized command ... for instance hostname or specific port assigned

**Comment by ferdavs** [comment]
there is a problem here 
https://github.com/Jigsaw-Code/outline-server/blob/46b7ee0e33d8126f43f7fd030dd748413b9ff27b/src/server_manager/install_scripts/install_server.sh#L249

when using `--keys-port`  arg, config file is broken.
it should put comma between `hostname` and `portForNewAccessKeys` json properties
