### ISSUE TITLE
install_server.sh firewall blocked

### ISSUE THREAD

**Issue by m1st0** [Jigsaw-Code/outline-server#54]
After repeatedly cleaning out the docker-ce containers and images, every installation would stop at

    > Checking host firewall ...................... BLOCKED

on Google Cloud.  I further attempted to open all ports internally using UFW on Ubtuntu 17.10 as well as the firewall management utilities from the Google Cloud Console.  No improvement even after disabling UFW.

**Comment by trevj** [comment]
@m1st0 Thanks for the feedback. Sorry you've been having troubles with installation.

When you say the installation stops at this point, do you mean it fails with an error message (starts with "You won’t be able to access it externally...")?

**Comment by liquidblack** [comment]
seeing the same issue with debian on GCP - fresh install (plus updates)

4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

> 
> Status: Downloaded newer image for v2tec/watchtower:latest
> OK
> > Waiting for Outline server to be healthy .... OK
> > Creating first user ......................... OK
> > Adding API URL to config .................... OK
> > Checking host firewall ...................... BLOCKED
> > Sorry! Something went wrong.

"docker containers ls" shows both watchtower and shadowbox running - where am I looking for useful logs?

**Comment by liquidblack** [comment]
Sorry for the multiple updates but for someone else looking for this in the short term 

For Google Cloud Platform (GCP) 
- Go into the GCP console (https://console.cloud.google.com)
- In the VPC firewall section create a tag with the port number you want
- In the instance section find your VM, edit the VM and add the tag you just created to the networking section, click save

in your terminal session, assuming you have already tried and failed to get the install to work
- clean up the settings by running "rm /root/shadowbox/persisted-state/shadowbox_config.json"
- clean up the containers by running "docker container stop watchtower shadowbox; docker container prune -f"
- download the install script to a file with " wget -q https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh"
- edit the install_server.sh file and add the line "SB_API_PORT=xxxx" where xxxx is your port number from above, save the file
- edit the file to allow execution with "chmod a+x install_server.sh"
- run the script ".\install_server.sh"

At this point the install appears to run as normal - good times!

**Comment by m1st0** [comment]
Good times indeed!  It worked fine after setting the port manually and providing it.

**Comment by seyeeet** [comment]
can someone help ,  I also have this issue
