### ISSUE TITLE
Outline Manager cannot be installed on MacOs Catalina 10.15.1

### ISSUE THREAD

**Issue by maltewirz** [Jigsaw-Code/outline-server#543]
The error message comes after trying to start the app from inside Finder: "Outline Manager cannot be opened since Apple cannot scan for malware. This software needs to be updated, get in touch with the developers."

**Comment by krrisztian** [comment]
I personally have never seen such an error response while opening an app.
I just downloaded the latest Outline Manager on my Catalina 10.15.1 and it works flawlessly.

Please make sure to adjust your app-security settings under System Preferences->Security and Privacy->Allow app downloaded from...

Adjusting the Gatekeeper preferences is also recommended through the "spctl" command in terminal.

**Comment by alalamav** [comment]
@maltewirz, can you let us know if @krrisztian's solution worked for you?

**Comment by maltewirz** [comment]
Hi @alalamav and @krrisztian thanks for your response. When opening the app, there was no prompt as mentioned in "System Preferences->Security and Privacy->Allow app downloaded from..."  I did not adjust the gatekeeper preferences yet, will update if i do.

**Comment by BitcoinSDK** [comment]
Not working and not convenient. Why mess with this strange fixing? **Just update and sign, guys!**

**Comment by JonathanDCohen** [comment]
Just checked the prod version of Outline MAnager 1.3.0:

```
$ codesign -dv --verbose=4 Outline\ Manager.app
Executable=/Applications/Outline Manager.app/Contents/MacOS/Outline Manager
Identifier=com.electron.outline-manager
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=1768 flags=0x10000(runtime) hashes=46+5 location=embedded
VersionPlatform=1
VersionMin=657920
VersionSDK=658688
Hash type=sha256 size=32
CandidateCDHash sha1=f99c5c61c43e5c3585ef8979f137bd292fd1cc00
CandidateCDHash sha256=735a5b47fae45aee94c931c6c34812058e89caf7
Hash choices=sha1,sha256
Page size=4096
CDHash=735a5b47fae45aee94c931c6c34812058e89caf7
Signature size=9022
Authority=Developer ID Application: Jigsaw Operations LLC (QT8Z3Q9V3A)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Nov 7, 2019 at 12:33:37 PM
Info.plist entries=26
TeamIdentifier=QT8Z3Q9V3A
Runtime Version=10.13.0
Sealed Resources version=2 rules=13 files=61
Internal requirements count=1 size=188
```

The binary is signed, so I'm not sure what the issue is.

**Comment by BitcoinSDK** [comment]
You need to sign it with Apple developer account.

**Comment by alalamav** [comment]
It is signed through our Apple Developer account:

> Authority=Developer ID Certification Authority
   Authority=Apple Root CA

**Comment by zanerock** [comment]
I had this issues as well. I was able to install after manually going to the security settings and selecting "install anyway". (Catalina 10.15.2, outline downloaded from getoutline.org 2020-02-03).
