### ISSUE TITLE
Accessing private networks

### ISSUE THREAD

**Issue by flosoft** [Jigsaw-Code/outline-server#545]
I've installed Outline Server using Docker on both Ubuntu Linux and a Synology box, however I am unable to access my private networks through the VPN on both networks.

I'm trying to access hosts in 10.0.0.0/8. Both hosts have a route for this network and other Docker containers have no issue reaching these.

On the client side, I'm using Android and the OSX desktop client.

Does anyone have any idea why the private networks can't be reached?

**Comment by alalamav** [comment]
@flosoft, due to security reasons the Outline server blocks traffic to its LAN; the Outline clients' VPN bypasses private networks in order to access the LAN (i.e. printers, Chromecast).

**Comment by MasterGroosha** [comment]
Why not making it an option (disabled by default)?
