### ISSUE TITLE
Sharing Key, Gives Only IP, Not Hostname

### ISSUE THREAD

**Issue by besoeasy** [Jigsaw-Code/outline-server#549]
PROBLEM 

Ui only gives ip share link, not hostname. UI should give option of  ip & hostname 💯 

Example :

IP
ss://..........=@35.223.94.64:55507/?outline=1

HOSTNAME
ss://..........=@myserver.com:55507/?outline=1

**Comment by alalamav** [comment]
Hi @besoeasy, thank you for the feedback. @JonathanDCohen is working on a feature to allow changing the server IP displayed in the invite to a hostname.

**Comment by besoeasy** [comment]
nice !
