### ISSUE TITLE
How to export Prometheus data from Outline server to Grafana? (Exporter)

### ISSUE THREAD

**Issue by baoc75** [Jigsaw-Code/outline-server#564]
If I want to export data from Prometheus, I will likely need an exporter. But seems that we don't have it here, so which exporter I need right now?

**Comment by Goldenstarc** [comment]
same problem here.
Outline exporter is on localhost:9091, node-exporter on 9092
and prometheus is running on  localhost:9090 and accesseble only on localhost
i run grafana docker on same host but cant add prometheus Data Sources! 

grafana URL:
http://localhost:9090
grafana error:
NetworkError when attempting to fetch resource.

**Comment by xReLee** [comment]
You can use SSH tools log into your server with tunnels, which sets up Prometheus and Grafana URLs and ports. Then you can use http://localhost:3000 to open your Grafana portal. After reset the default admin password for the first sign-in, you can add Prometheus data source into Grafana via configuration tab on the left menu. In the setting area, fill in http://localhost:9090 as URL for HTTP, choose Browser or Server as you like to Access the data.

**Comment by abhinavprateek** [comment]
facing the same issue here

grafana error:
NetworkError when attempting to fetch resource while trying to add the data source, any workaround?
