### ISSUE TITLE
Authentication Logging

### ISSUE THREAD

**Issue by mmwilson0** [Jigsaw-Code/outline-server#575]
Hello, 

I was wondering if/where Outline Server logs authentication attempts and any other audit logging? 

Thanks!

**Comment by alalamav** [comment]
Hi @mmwilson0, [outline-ss-server ](https://github.com/Jigsaw-Code/outline-ss-server) internally collects TCP probes, the time it takes to authenticate a user, and some other metrics. These are exposed by a local Prometheus server on port 9090.

Feel free to reopen this issue if you have further questions.
