### ISSUE TITLE
Getting stuck during setup at: "Waiting for Outline server to be healthy ...."

### ISSUE THREAD

**Issue by Zangoran** [Jigsaw-Code/outline-server#58]
I am Running docker in WSL, and running Docker ToolBox as I am not on Windows Pro

Had to mess with the profile in /var/lib/boot2docker to imitate the "Expose daemon on tcp://localhost:2375 without tls" setting that is on Docker for Windows.

Any help with this would be great, I am knew to docker, so forgive me if I am doing something dumb. Thanks!

**Comment by 4044ever** [comment]
Not sure this helps, I got stuck there too, but managed to go further by manually editing `install_server.sh`

Original:
```
# Waits for Shadowbox to be up and healthy
function wait_shadowbox() {
  # We use insecure connection because our threat model doesn't include localhost port
  # interception and our certificate doesn't have localhost as a subject alternative name
 until curl --insecure -s "${LOCAL_API_URL}/access-keys" >/dev/null; do sleep 1; done
}
```

My Change:
```
# Waits for Shadowbox to be up and healthy
function wait_shadowbox() {
  # We use insecure connection because our threat model doesn't include localhost port
  # interception and our certificate doesn't have localhost as a subject alternative name
   until curl --insecure -s "https://66.211.11.44/access-keys" >/dev/null; do sleep 1; done         
}
```

Error looks now like this:
```
> ...............
> Waiting for Outline server to be healthy .... OK
> Creating first user ......................... OK
> Adding API URL to config .................... OK
> Checking host firewall ...................... Error response from daemon: Container 618c5deb16b74f37430629818b6b7757060f0f09eaba42ace9eee68ee9fa5587 is restarting, wait until the container is running
BLOCKED
```

**Comment by damongant** [comment]
I got this. Shadowbox seems to be constantly restarting due to segfault. Looks like it might depend on the kernel being mostly vanilla. Here's what I run:

```
Linux 4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 GNU/Linux
```

Logs:

```

incognito:~# docker logs shadowbox
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
```

**Comment by Zangoran** [comment]
@fortuna 
Tagging you as you seem to be the main contributor.

It looks like this issue is somewhat related to [this issue](https://github.com/Jigsaw-Code/outline-server/issues/27#issuecomment-376347755)

Is this issue possible to fix when running WSL? Thanks!

**Comment by trevj** [comment]
Sorry you've been having issues with Outline, @Zangoran. I'm afraid the server can currently only run on Linux systems, even though it's distributed as a Docker application. The main reason is that we make use of Docker's `--net=host` option - this also prevents the server running on macOS.

**Comment by trevj** [comment]
@damongant thanks your feedback but I think you're seeing a different problem. If you're running on a different system to @Zangoran can you please open another issue? Thanks!

**Comment by Zangoran** [comment]
Thanks for the help!

**Comment by jhongenator** [comment]
@trevj is it still that case that this won't run on MacOS? Because getOutline.org seems to say that it does work on MacOS now.. but my install hangs at "Waiting for Outline server to be healthy". thanks!

**Comment by alalamav** [comment]
@jhongenator, the Outline manager application is supported in macOS; however, the server itself only  supports Linux at the moment. Did you get this far installing the server on a macOS host?

**Comment by thejaswip** [comment]
Same getting stuck
Getting this with docker logs 
exec user process caused "exec format error" ...
btwn i am running this in Raspberry Pi , i am assuming this has to do something with the fact it being ARM

**Comment by 7C-Coding-Eric** [comment]
@thejaswip same here, I'm running 64 bit debian but it's just stuck there

**Comment by zzj0402** [comment]
> Same getting stuck Getting this with docker logs exec user process caused "exec format error" ... btwn i am running this in Raspberry Pi , i am assuming this has to do something with the fact it being ARM

This seems to be a solution for you: https://github.com/Jigsaw-Code/outline-server/issues/58#issuecomment-557489586

WSL Ubuntu 20.04 on Windows 10 Home 21H1 19043.1415 with Docker Desktop 4.3.1 (72247)

```
PS C:\Users\zzj04> docker logs shadowbox
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     38      0 --:--:-- --:--:-- --:--:--    38
D2021-12-19T20:55:50.870Z 13 main.js:29] === Config ===
D2021-12-19T20:55:50.871Z 13 main.js:29] Hostname:
D2021-12-19T20:55:50.871Z 13 main.js:29] SB_METRICS_URL: https://prod.metrics.getoutline.org
D2021-12-19T20:55:50.871Z 13 main.js:29] ==============
I2021-12-19T20:55:50.872Z 13 main.js:29] Starting...
I2021-12-19T20:55:50.875Z 13 main.js:29] Prometheus is at 127.0.0.1:9090
I2021-12-19T20:55:50.875Z 13 main.js:29] Node metrics is at 127.0.0.1:9091
I2021-12-19T20:55:50.876Z 13 main.js:29] outline-ss-server metrics is at 127.0.0.1:9092
I2021-12-19T20:55:50.876Z 13 main.js:29] Replay protection enabled: true
I2021-12-19T20:55:50.880Z 13 main.js:108] Starting Prometheus with args [--config.file,/opt/outline/persisted-state/prometheus/config.yml,--web.enable-admin-api,--storage.tsdb.retention.time,31d,--storage.tsdb.path,/opt/outline/persisted-state/prometheus/data,--web.listen-address,127.0.0.1:9090,--log.level,info]
level=info ts=2021-12-19T20:55:50.945Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
level=info ts=2021-12-19T20:55:50.946Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-16:51:47)"
level=info ts=2021-12-19T20:55:50.946Z caller=main.go:339 host_details="(Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 docker-desktop localdomain)"
level=info ts=2021-12-19T20:55:50.946Z caller=main.go:340 fd_limits="(soft=32768, hard=32768)"
level=info ts=2021-12-19T20:55:50.946Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-12-19T20:55:50.947Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2021-12-19T20:55:50.948Z caller=web.go:523 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2021-12-19T20:55:50.952Z caller=head.go:575 component=tsdb msg="Replaying WAL, this may take awhile"
level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=2
level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=2
level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=2
level=info ts=2021-12-19T20:55:50.955Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=3.2207ms
level=info ts=2021-12-19T20:55:50.957Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
level=info ts=2021-12-19T20:55:50.957Z caller=main.go:695 msg="TSDB started"
level=info ts=2021-12-19T20:55:50.957Z caller=main.go:799 msg="Loading configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=info ts=2021-12-19T20:55:53.118Z caller=main.go:827 msg="Completed loading of configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=info ts=2021-12-19T20:55:53.118Z caller=main.go:646 msg="Server is ready to receive web requests."
I2021-12-19T20:55:53.901Z 13 main.js:108] Prometheus is ready!
I2021-12-19T20:55:53.934Z 13 main.js:29] Manager listening at https://[::]:
I2021-12-19T20:55:53.941Z 37 server.go:254] Metrics on http://127.0.0.1:9092/metrics
I2021-12-19T20:55:53.941Z 37 server.go:260] Using IP-Country database at /var/lib/libmaxminddb/ip-country.mmdb
I2021-12-19T20:55:53.941Z 37 server.go:154] Loaded 0 access keys
```

**Comment by MateusBMP** [comment]
> > Same getting stuck Getting this with docker logs exec user process caused "exec format error" ... btwn i am running this in Raspberry Pi , i am assuming this has to do something with the fact it being ARM
> 
> This seems to be a solution for you: https://forums.raspberrypi.com/viewtopic.php?t=209426
> 
> $ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> 
> > Verifying that Docker is installed .......... OK
> > Verifying that Docker daemon is running ..... OK
> > Setting PUBLIC_HOSTNAME to external IP ...... OK
> > Creating persistent state dir ............... OK
> > Generating secret key ....................... OK
> > Generating TLS certificate .................. OK
> > Generating SHA-256 certificate fingerprint .. OK
> > Writing config .............................. OK
> > Starting Shadowbox .......................... FAILED
> > The container name "shadowbox" is already in use by another container. This may happen when running this script multiple times. We will attempt to remove the existing container and restart it. Would you like to proceed? [Y/n] Y
> > Removing shadowbox container ................ OK
> > Restarting shadowbox ........................ OK
> > Starting Watchtower ......................... FAILED
> > The container name "watchtower" is already in use by another container. This may happen when running this script multiple times. Would you like to replace this container? If you answer no, we will proceed with the remainder of the installation. [Y/n] Y
> > Removing watchtower container ............... OK
> > Restarting watchtower ....................... OK
> > Waiting for Outline server to be healthy ....
> 
> And it stucks.
> 
> WSL Ubuntu 20.04 on Windows 10 Home 21H1 19043.1415 with Docker Desktop 4.3.1 (72247)
> 
> ```
> PS C:\Users\zzj04> docker logs shadowbox
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    15  100    15    0     0     38      0 --:--:-- --:--:-- --:--:--    38
> D2021-12-19T20:55:50.870Z 13 main.js:29] === Config ===
> D2021-12-19T20:55:50.871Z 13 main.js:29] Hostname:
> D2021-12-19T20:55:50.871Z 13 main.js:29] SB_METRICS_URL: https://prod.metrics.getoutline.org
> D2021-12-19T20:55:50.871Z 13 main.js:29] ==============
> I2021-12-19T20:55:50.872Z 13 main.js:29] Starting...
> I2021-12-19T20:55:50.875Z 13 main.js:29] Prometheus is at 127.0.0.1:9090
> I2021-12-19T20:55:50.875Z 13 main.js:29] Node metrics is at 127.0.0.1:9091
> I2021-12-19T20:55:50.876Z 13 main.js:29] outline-ss-server metrics is at 127.0.0.1:9092
> I2021-12-19T20:55:50.876Z 13 main.js:29] Replay protection enabled: true
> I2021-12-19T20:55:50.880Z 13 main.js:108] Starting Prometheus with args [--config.file,/opt/outline/persisted-state/prometheus/config.yml,--web.enable-admin-api,--storage.tsdb.retention.time,31d,--storage.tsdb.path,/opt/outline/persisted-state/prometheus/data,--web.listen-address,127.0.0.1:9090,--log.level,info]
> level=info ts=2021-12-19T20:55:50.945Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
> level=info ts=2021-12-19T20:55:50.946Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-16:51:47)"
> level=info ts=2021-12-19T20:55:50.946Z caller=main.go:339 host_details="(Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 docker-desktop localdomain)"
> level=info ts=2021-12-19T20:55:50.946Z caller=main.go:340 fd_limits="(soft=32768, hard=32768)"
> level=info ts=2021-12-19T20:55:50.946Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
> level=info ts=2021-12-19T20:55:50.947Z caller=main.go:678 msg="Starting TSDB ..."
> level=info ts=2021-12-19T20:55:50.948Z caller=web.go:523 component=web msg="Start listening for connections" address=127.0.0.1:9090
> level=info ts=2021-12-19T20:55:50.952Z caller=head.go:575 component=tsdb msg="Replaying WAL, this may take awhile"
> level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=2
> level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=2
> level=info ts=2021-12-19T20:55:50.955Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=2
> level=info ts=2021-12-19T20:55:50.955Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=3.2207ms
> level=info ts=2021-12-19T20:55:50.957Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
> level=info ts=2021-12-19T20:55:50.957Z caller=main.go:695 msg="TSDB started"
> level=info ts=2021-12-19T20:55:50.957Z caller=main.go:799 msg="Loading configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
> level=info ts=2021-12-19T20:55:53.118Z caller=main.go:827 msg="Completed loading of configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
> level=info ts=2021-12-19T20:55:53.118Z caller=main.go:646 msg="Server is ready to receive web requests."
> I2021-12-19T20:55:53.901Z 13 main.js:108] Prometheus is ready!
> I2021-12-19T20:55:53.934Z 13 main.js:29] Manager listening at https://[::]:
> I2021-12-19T20:55:53.941Z 37 server.go:254] Metrics on http://127.0.0.1:9092/metrics
> I2021-12-19T20:55:53.941Z 37 server.go:260] Using IP-Country database at /var/lib/libmaxminddb/ip-country.mmdb
> I2021-12-19T20:55:53.941Z 37 server.go:154] Loaded 0 access keys
> ```

It's worker for me! Thanks!

For simplicity, the full command is: `sudo SB_IMAGE=ken1029/shadowbox:latest bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"`

**Comment by hktalent** [comment]
centos 9
same:
Waiting for Outline server to be healthy ....

 caller=main.go:758 err="opening storage failed: lock DB directory: resource temporarily unavailable"
E2022-08-20T17:54:54.366Z 12 main.js:108] Prometheus has exited with error. Code: 1, Signal: null
E2022-08-20T17:54:54.366Z 12 main.js:108] Restarting Prometheus...
I2022-08-20T17:54:54.366Z 12 main.js:108] Starting Prometheus with args [--config.file,/opt/outline/persisted-state/prometheus/config.yml,--web.enable-admin-api,--storage.tsdb.retention.time,31d,--storage.tsdb.path,/opt/outline/persisted-state/prometheus/data,--web.listen-address,127.0.0.1:9093,--log.level,info]
