### ISSUE TITLE
Can't install in GCP CentOS

### ISSUE THREAD

**Issue by srikkbhat** [Jigsaw-Code/outline-server#580]
The installation gets stuck in "Waiting for outline server to be healthy".

I am using Shielded VM CentOS in GCP.

Looking into docker logs shadowbox, I see below error. Any ideas how to fix this?
````
E2020-02-17T12:39:15.187Z 10 json_config.js:49] Error writing config /opt/outline/persisted-state/shadowbox_server_config.json Error: EACCES: permission denied, open '/opt/outline/persisted-state/shadowbox_server_config.json.1581943155186'
D2020-02-17T12:39:15.189Z 10 main.js:89] === Config ===
D2020-02-17T12:39:15.189Z 10 main.js:90] Hostname: blah
D2020-02-17T12:39:15.189Z 10 main.js:91] SB_METRICS_URL: https://metrics-prod.uproxy.org
D2020-02-17T12:39:15.189Z 10 main.js:92] ==============
I2020-02-17T12:39:15.189Z 10 main.js:93] Starting...
I2020-02-17T12:39:15.199Z 10 main.js:102] Prometheus is at 127.0.0.1:9090
I2020-02-17T12:39:15.199Z 10 main.js:103] Node metrics is at 127.0.0.1:9091
I2020-02-17T12:39:15.199Z 10 main.js:114] outline-ss-server metrics is at 127.0.0.1:9092
E2020-02-17T12:39:15.201Z 10 main.js:172] Error: EACCES: permission denied, mkdir '/opt/outline/persisted-state/prometheus'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/root/shadowbox/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/root/shadowbox/app/infrastructure/prometheus_scraper.js:65:16)
    at Generator.next (<anonymous>)
    at /root/shadowbox/app/infrastructure/prometheus_scraper.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/root/shadowbox/app/infrastructure/prometheus_scraper.js:17:12)
    at Object.runPrometheusScraper (/root/shadowbox/app/infrastructure/prometheus_scraper.js:64:12)
    at /root/shadowbox/app/server/main.js:120:36
    at Generator.next (<anonymous>)
````

**Comment by alalamav** [comment]
Hi @srikkbhat, seems like outline doesn't have permisisons to access some directories, notably `/opt/outline/`. Could you try runing as `sudo`or updating the directory permissiions to allow your user?

> The installation gets stuck in "Waiting for outline server to be healthy".

Please make sure to disable update the firewall settings to allow incoming traffic to the ports output by the Outline server installer.

**Comment by srikkbhat** [comment]
1. I am running using sudo
2. I have firewall rules based on what outline manager suggested. I have created `outline` tag which pretty much has all he access and attached the tag to the host.

I am using Shielded VM from Google Cloud. I am not sure if that would limit some abilities in the VM that is the cause for the issue.

**Comment by JonathanDCohen** [comment]
> I tried to install on a regular VM rather than Shielded VM and it worked

That's good to know.  Glad you got it running!  I'm closing this issue but please feel free to re-open if you need to.
