### ISSUE TITLE
Specify proxy paramters on Access Key creation API

### ISSUE THREAD

**Issue by eddycat** [Jigsaw-Code/outline-server#581]
[Creates a new access key](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys/post) API add optional parameters: id, password,method.

I use API to link other programs.

**Comment by eddycat** [comment]
[Returns the data transferred per access key](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1metrics~1transfer/get) the returned data is constantly changing, increasing or decreasing, unstable. This is the result of four successive visits:

```
{"bytesTransferredByUserId":{"0":21045224,"3":31570246}}
{"bytesTransferredByUserId":{"0":21055377,"3":31586350}}
{"bytesTransferredByUserId":{"0":21071544,"3":31611996}}
{"bytesTransferredByUserId":{"0":21069041,"3":31595958}}
```

With Prometheus query, there is no change in the returned data.

**Comment by JonathanDCohen** [comment]
Let me make sure I'm reading your comments correctly:

You'd like us to add optional parameters to the POST/access-keys endpoint, and are also reporting instability in the GET metrics/transfer endpoint.

Is that correct?

**Comment by eddycat** [comment]
> Let me make sure I'm reading your comments correctly:
> 
> You'd like us to add optional parameters to the POST/access-keys endpoint, and are also reporting instability in the GET metrics/transfer endpoint.
> 
> Is that correct?

yes

**Comment by JonathanDCohen** [comment]
Awesome.  I'll look into the second issue.  For the first issue, what are you trying to do that you need to manually set the password and access key id as opposed to using the generated ones?

I'd be worried about creating an option to set the encryption method.  Stream ciphers in particular aren't recommended, even though Shadowsocks accepts them.  Can I ask why you're trying to customize this?

**Comment by eddycat** [comment]
> Awesome. I'll look into the second issue. For the first issue, what are you trying to do that you need to manually set the password and access key id as opposed to using the generated ones?
> 
> I'd be worried about creating an option to set the encryption method. Stream ciphers in particular aren't recommended, even though Shadowsocks accepts them. Can I ask why you're trying to customize this?

I provide users with multiple servers. If I can customize the password, I can create the same password. Users only need to remember one. Randomly generating them needs to remember complex passwords or links. Ports and encryption are not necessary.

**Comment by JonathanDCohen** [comment]
Are your users not using the Outline client?  I'm not sure why they'd need to remember a password

**Comment by eddycat** [comment]
Yes, many users use the original Shadowsocks-Windows or shadowsocks-libev to configure the server manually, they are more lightweight.

**Comment by eddycat** [comment]
In addition, the outline manager shows that the traffic statistics are 30 days. Suppose a user uses 1GB of traffic per day. Will the traffic statistics be 31GB or 30GB after 31 days?

**Comment by JonathanDCohen** [comment]
Makes sense to me.  I would review a PR adding an optional password parameter in a JSON format if you'd like to do it, otherwise I'll put it on our maintenance backlog

**Comment by JonathanDCohen** [comment]
To your other question, look here https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/server_access_key.ts#L209

It's a 30 day trailing window, so at the beginning of the 30th day it would read 30 GB.  The statistics would then waver up and down depending on the specifics of the usage on the 1st and 31st days, but at the end of the 31st day it would read 30 GB

**Comment by JonathanDCohen** [comment]
For your first issue, if you look https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/manager_metrics.ts#L31 you can see we're querying prometheus directly from the api call.  It's not expected that data transfer would be completely stable, as it depends on what the user is doing now as well as 30 days ago.

**Comment by fortuna** [comment]
@eddycat The variation you are seeing in the numbers is an artifact of how Prometheus interpolates the timeseries values. There's a variation, but it should be minimal and not important in practice.

As for the extra API parameters, what are you trying to accomplish?
We are looking into supporting [online configs](https://github.com/shadowsocks/shadowsocks-org/issues/89), which should make it easy to migrate users to different servers.

**Comment by fortuna** [comment]
The method parameter is being added: https://github.com/Jigsaw-Code/outline-server/pull/1002
