### ISSUE TITLE
How to stop and start outline server?

### ISSUE THREAD

**Issue by mrmmg** [Jigsaw-Code/outline-server#587]
Sometimes we have to stop the service due to server maintenance but we can't find a way out.
Is there a command for this?
Note: We also need to restart the service after server maintenance.

**Comment by capriciousduck** [comment]
You have to stop the docker container. SSH into your machine and run the following commands.

`docker stop watchtower`
`docker stop shadowbox`

**Comment by davidwerent** [comment]
hey, how my outline server cant restart automatically after reboot VPS server...
how i can do it manually?
docker restart shadowbox - doesnt work

**Comment by capriciousduck** [comment]
@capriciousduck Do you see the container in the output of `docker ps -a`?

**Comment by davidwerent** [comment]
> @davidwerent Do you see the container in the output of `docker ps -a`?
yep, 
![image](https://user-images.githubusercontent.com/70973230/185384953-134be9a2-08fe-45b5-9900-8484864be917.png)

**Comment by capriciousduck** [comment]
@davidwerent What error do you see while connecting to your Outline server from your clients? Are you sure you opened the appropriate ports in the firewall?

**Comment by davidwerent** [comment]
@capriciousduck can't connect to server, smth like this

im solved this problem with reset iptables

iptables -L -v -n
iptables -F
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT
sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

**Comment by VityaSchel** [comment]
I accidentally removed `shadowbox` container, how to run it with docker again?

**Comment by Dean2149** [comment]
> `docker stop watchtower`
> `docker stop shadowbox`

For my AWS Ubuntu 22.04 LTS instance, it need prefix sudo to grant stop privilege

docker stop watchtower
docker stop shadowbox
