### ISSUE TITLE
Any plans to update the base Node.js image?

### ISSUE THREAD

**Issue by oreoluwa** [Jigsaw-Code/outline-server#599]
Given that Node.js v8 reached EOL this January(see [here](https://nodejs.org/en/about/releases/)), I was wondering whether there were plans underway to update the Node version.
In addition to that, Node 8's image wasn't built with arm v7 architecture, but I think subsequent LTS releases included that. 
```sh
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect node:8.15.0-alpine
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect node:10.19.0-alpine
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect node:12.16.1-alpine # LTS
```
Also, I was wondering what the criteria for the selection of a Node version were? 
Because, I've been using the current LTS(12.16.x) for a while now, and I've not observed any issues with this so far.

**Comment by alalamav** [comment]
HI @oreoluwa, we would like to update the Node image version soon. I have been running into content-trust issues when trying to pull the `node:10.19.0-alpine` and `node:12.6.1-alpine` images in my local machine. I did some digging around and found [these](https://github.com/docker-library/official-images/issues/6838) [issues](https://github.com/docker-library/official-images/issues/5874); it seems like the latest node images are unsigned.

Have you run into these issues? Did you have to disable docker content trust for it to work?

**Comment by oreoluwa** [comment]
Ha, I see and yes, I had disabled DCT for some time on my machine now.
You are absolutely right, enabling DCT breaks my build.
I knew there must have been something else holding back those updates, beyond what was mentioned in #326 
Thanks for clarifying.
FWIW, one of `node:alpine`'s image that was created about a year ago is signed, but the manifest for armv7 wasn't included in the build too.😳😳😳😳
