### ISSUE TITLE
iptables doesn't apply

### ISSUE THREAD

**Issue by kierandavies** [Jigsaw-Code/outline-server#600]
Hi, currently running the latest build on deb10.

For some reason changes made to iptables are overwritten or in most cases not even applied.

Is there a guide on getting them to save, ideally need to block SSH etc.

Thanks in advance.

**Comment by JonathanDCohen** [comment]
Any context on why you closed the issue?  

I develop on a Debian machine and have never seen this issue.

**Comment by kierandavies** [comment]
Hi Jonathan,

I closed it when I realised **I** was saving to iptables-legacy  - error on my part sorry!

**Comment by JonathanDCohen** [comment]
No worries, I'm glad you were able to figure it out!
