### ISSUE TITLE
How to create a custom name key via a POST request.

### ISSUE THREAD

**Issue by subutay** [Jigsaw-Code/outline-server#609]
I use urlkey(access-key) to create a new access key,
I want to add a name to the newly created key, how can I do it?

**Comment by subutay** [comment]
I use Python and requests module

**Comment by JonathanDCohen** [comment]
I'm not sure what `urlkey` is, but if you look [at the API documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys~1{id}~1name/put) You'll see that you need to make a PUT request to https://{managementUrl}/{prefix}/access-keys/{id}/name.  The documentation there is wrong (thanks for pointing me to the bug!) but the body of the request needs to be JSON with a "name" field with the new name for the key.

**Comment by subutay** [comment]
Got it, thank you for your answer, it worked for me!


在 2020年3月31日，23:26，Jonathan Cohen <notifications@github.com> 写道：

﻿

I'm not sure what urlkey is, but if you look at the API documentation<https://nam11.safelinks.protection.outlook.com/?url=https:%2F%2Fredocly.github.io%2Fredoc%2F%3Furl%3Dhttps:%2F%2Fraw.githubusercontent.com%2FJigsaw-Code%2Foutline-server%2Fmaster%2Fsrc%2Fshadowbox%2Fserver%2Fapi.yml%23tag%2FAccess-Key%2Fpaths%2F~1access-keys~1%257Bid%257D~1name%2Fput&data=02%7C01%7C%7C38d8db6b62794a54c51308d7d587ee3d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637212652106247051&sdata=S9LZeTtWSTbV3SZX1%2FitdVHeGEfEgOGb3X9r8q8y6Lg%3D&reserved=0> You'll see that you need to make a PUT request to https://{managementUrl}/{prefix}/access-keys/{id}/name. The documentation there is wrong (thanks for pointing me to the bug!) but the body of the request needs to be JSON with a "name" field with the new name for the key.

**Comment by subutay** [comment]
> I'm not sure what `urlkey` is, but if you look [at the API documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys~1%7Bid%7D~1name/put) You'll see that you need to make a PUT request to https://{managementUrl}/{prefix}/access-keys/{id}/name. The documentation there is wrong (thanks for pointing me to the bug!) but the body of the request needs to be JSON with a "name" field with the new name for the key.

Got it, thank you for your answer, it worked for me!

**Comment by JonathanDCohen** [comment]
Perfect.  I'm closing the issue, please feel free to re-open if you need to.
