### ISSUE TITLE
why is my windows pc network speed very very slow,but android is normal in the same network?

### ISSUE THREAD

**Issue by ti4n1993** [Jigsaw-Code/outline-server#61]

**Comment by trevj** [comment]
Thanks for reaching out, @lianyueforever. Sorry you've been having trouble with Windows. We are aware that speed is currently slower on Windows than other platforms and we're working to address this in the near future.

**Comment by trevj** [comment]
@ti4n1993 We've traced the problem to performance issues in the Windows client. I recently merged a fix that should address it:
https://github.com/Jigsaw-Code/outline-client/pull/162

We plan to release it in the next couple of days. Thanks again for the report!
