### ISSUE TITLE
How to use the Management API to delete a key with a specified ID.

### ISSUE THREAD

**Issue by subutay** [Jigsaw-Code/outline-server#611]
I try to write code in python and delete the specified access key with Management API.
But it failed with an error.
The code (python) is as follows:
import requests, json, time

`
url = 'https://1.1.1.1:2222/NweOoX2uC********HINYrQ/
key = 'access-keys/'
ss = requests.delete(
    url + key,
    verify=False,
    json={
        'id': '30'
                    }
                     )
print(ss.json())
`
Output:

`{'code': 'MethodNotAllowedError', 'message': 'DELETE is not allowed'}
`

What exactly is going wrong? I need help.

**Comment by alalamav** [comment]
Hi @subutay, you need to pass the access key id as part of the URL:

`curl -X DELETE $API_URL/access-keys/$ACCESS_KEY_ID`

See the [API documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml) for more information. Feel free to reopen this issue if you have further questions.
