### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by vinc3m1** [Jigsaw-Code/outline-server#615]
Last line of `docker container logs` is:

`level=error ts=2020-04-01T07:53:10.069420248Z caller=main.go:617 err="opening storage failed: block dir: \"/home/vince/shadowbox/persisted-state/prometheus/data/{HASH}\": unexpected end of JSON input"`

where `{HASH}` is a 26 character hash of some sort.

I went to `shadowbox/persisted-state/prometheus/data/...` and renamed the most recent folder to `{HASH}.bak` and then the image started fine.

```
$ sudo ls -lah {HASH}/
total 108K
drwxrwx---  3 root root 4.0K Mar 10 18:00 .
drwxr-xr-x 20 root root  20K Apr 12 10:39 ..
drwxrwx---  2 root root 4.0K Mar 10 18:00 chunks
-rw-rw----  1 root root  75K Mar 10 18:00 index
-rw-rw----  1 root root    0 Mar 10 18:00 meta.json
-rw-rw----  1 root root    0 Mar 10 18:00 tombstones
```

I assume the reason for the failure was that `meta.json` size is 0? In other folders both meta.json and tombstones are nonzero.

Seems like whatever the issue is shouldn't stop the container from starting and should fail gracefully or fall back somehow?

**Comment by maddyhof** [comment]
Is this still an issue for you?

**Comment by vinc3m1** [comment]
Nope too long ago, works fine now
