### ISSUE TITLE
Can the user web be developed?

### ISSUE THREAD

**Issue by vpn-web** [Jigsaw-Code/outline-server#617]
Can the user web terminal be developed? The user registers an account in the cloud to create a node link to enter the client, and can control user traffic usage time and usage

**Comment by hdavy2002** [comment]
I would be interested too

**Comment by hdavy2002** [comment]
Interested too.

**Comment by fortuna** [comment]
Thanks for you interest on Outline.
What do you mean with "web terminal"? Developed in what way?
