### ISSUE TITLE
[OT] DigitalOcean Integration

### ISSUE THREAD

**Issue by SusanKenneth** [Jigsaw-Code/outline-server#62]
Outline is extremely awesome and I love the easy setup featuring @digitalocean.
Thank you so much!  😍 
My off-topic question is: Are there other projects that have such a wonderful @digitalocean integration?

**Comment by binoyxj** [comment]
Check out DigitalOcean- Zapier integration here https://zapier.com/apps/digital-ocean/integrations

**Comment by trevj** [comment]
Glad you are enjoying Outline @SusanKenneth - many thanks for the feedback!

Thanks @binoyxj for the pointer :-)
