### ISSUE TITLE
Integrate KCPTUN with shadowsocks for faster udp

### ISSUE THREAD

**Issue by arminmacx** [Jigsaw-Code/outline-server#63]
Hi,

as i already have shadowsocks on my server and integrate kcptun on my server its make my proxy much faster with less latency. I hope you can integrate it inside your VPN as i saw its based on shadowsocks (if im wrong correct me).
you can find official kcptun on github from this link : [https://github.com/xtaci/kcptun](url)

VTW when we could get our hands for outline server manger on macOS

**Comment by trevj** [comment]
Many thanks for the suggestions, @arminmacx. We're aware of kcptun and have been evaluating a variety of other performance-enhancing issues.

BTW, Outline Manager for macOS is now available from our website:
https://getoutline.org

**Comment by fortuna** [comment]
FYI, there's a more developed conversation on KCPTUN at https://github.com/Jigsaw-Code/outline-server/issues/177.

I'll close this one so we can keep the conversation in one place.
