### ISSUE TITLE
Install for Outline Manager on Windows 10 gets stuck at about 30% completion

### ISSUE THREAD

**Issue by JacobDB** [Jigsaw-Code/outline-server#637]
Tried multiple times, rebooting, running as admin, nothing seems to work. It gets stuck right here and just never progresses. I've let it sit for 8 hours, and it just stays there forever.

![image](https://user-images.githubusercontent.com/1123997/80810567-c29beb00-8b89-11ea-9b2b-8a930ab4d312.png)

Windows 10 2004

**Comment by alalamav** [comment]
Hi @JacobDB, sorry to hear about this issue. What version of the app are you installing?
Could you try downloading the latest, [v1.5.1](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.1)?

**Comment by JacobDB** [comment]
It was the latest release as of... Tuesday or so (probably 1.5.0). I've just tried 1.5.1, seems to be doing the same thing unfortunately.

**Comment by Izanatos** [comment]
Hi,

I am experiencing the exact same symptoms.

Did we figured out what's causing this issue ?

thanks,

**Comment by LogicFan** [comment]
A similar issue also happens in the Outline-Client app for windows.

**Comment by chaokang-refundlabs** [comment]
same issue happened in windows 10 , is there any way to solve ?

**Comment by maddyhof** [comment]
Is this issue still occurring on the latest version of the Manager?
