### ISSUE TITLE
Connect with alternative client

### ISSUE THREAD

**Issue by maddhin** [Jigsaw-Code/outline-server#648]
Hi,
I want to set up a Raspberry Pi as an access point which connects to Outline-Server (in order to give access to free internet for some devices which cannot install client).

As there is no native Outline-client which works on a RPi, I need to use a alternative client - probably shadowsocks-libev. I am a noob, so pardon my ignorance. 

How can I connect with such a client to Outline, when I "only" have the ss:// link but no info about the password, etc which is necessary in order to connect?

**Comment by samfriend** [comment]
If you base64 decode the first part of the URL ---->. ss://[base64encodedString]@123.234.456.444:38790

It will be string of [encryption_method]:[password]
eg chacha20-ietf-poly1305:iuyuYii4f

then you will have all info needed

host IP:123.234.456.444
port:38790
encryption method:chacha20-ietf-poly1305
password:iuyuYii4f

**Comment by fortuna** [comment]
I hope that answers your questions.

Those questions may be more appropriate on the Reddit community: https://www.reddit.com/r/outlinevpn/

**Comment by fortuna** [comment]
Perhaps we should do a better job at saying what the configuration parameters are, so one doesn't have to decode the ss:// URL. Though most clients support the ss:// url.
