### ISSUE TITLE
Outline VPN API: PUT not working

### ISSUE THREAD

**Issue by rhijjawi** [Jigsaw-Code/outline-server#654]
I'm basing a semi-large project revolving this wonderful infrastructure but I'm unable to get the POST part of the provided API to work. Mostly because, I think that the command provided is incorrect: 
 **curl --insecure -X PUT curl -F 'name=albion' $API_URL/access-keys/2/name**
`
#!/usr/bin/python
import smtplib #
import requests #
import json #
import pyperclip #
api_keynl = 'https://RED.ACT.ED.IP:REDACTEDPORT/REDACTEDKEY'
api_keyus = 'https://RED.ACT.ED.IP:REDACTEDPORT/REDACTEDKEY'
api_key = ''

choice = input("""
On what server would you like to create a account?
[0] List all access keys
[1] US
[2] NL
[3] All
[4] Delete Key
""")
if choice == "0":
    responsenl = requests.get(api_keynl+'/access-keys',verify=False)
    datanl = responsenl.json()
    responseus = requests.get(api_keyus+'/access-keys',verify=False)
    dataus = responseus.json()
    keyus = dataus['accessUrl']
    keynl = datanl['accessUrl']
    print(dataus)
    print("\n")
    print(datanl)
if choice == "1":
    responseus = requests.post((api_keyus+'/access-keys'),verify=False)
    print("Successfully added new key to US servers.")
    dataus = responseus.json()
    print(dataus)
    keyus = dataus['accessUrl']
    print(keyus)
    keynl = 'You did not request an access key for the Dutch VPN, if you believe this is an error, please reply to this email.'
    idus = dataus['id']
    print(idun)
if choice == "2":
    responsenl = requests.post((api_keynl+'/access-keys'),verify=False)
    print("Successfully added new key to US servers.")
    datanl = responsenl.json()
    print(datanl)
    keynl = datanl['accessUrl']
    keyus = 'You did not request an access key for the American VPN, if you believe this is an error, please reply to this email.'
    idnl = datanl['id']
    print(idnl)
if choice == "3":
    responseus = requests.post((api_keyus+'/access-keys'),verify=False)
    dataus = responseus.json()
    responsenl = requests.post((api_keynl+'/access-keys'),verify=False)
    datanl = responsenl.json()
    print("Successfully added new key to all servers.")
    print(dataus)
    print("\n")
    print(datanl)
    keyus = dataus['accessUrl']
    keynl = datanl['accessUrl']
    idus = dataus['id']
    idnl = datanl['id']
    print(idus,idnl)

finalkeystosend = str('NL') + str(keynl) + str('\n') + str('NL') + str(keyus)

choice = input("""
What would you like to do? (All options require you to rename the key!)
[0] Send key via email?
[1] Copy key to clipboard
[2] Just rename key(s)
""")
if choice == "0": #[0] Send key via email?
    email = input("Enter recipient's email:")
    receivers = email
    sender = 'ramzihijjawi@gmail.com'
    gmail_pass = ''
    message = """From: OutlineVPNissuer <OutlineVPNissuer@digisec.tools>
To: OutlineVPNUser <(OutlineUser@digisec.tools)>
Subject: Your VPN keys have arrived!

To avoid issues, I recommend you install Outline VPN Client, which is a client specifically made for the VPN server's infrastructure.
"""
    message += 'Your VPN keys:' + str('\n')
    message += 'US:' + '\n' + str(keyus)
    message += 'NL:' + '\n' + str(keynl)
    try:
       smtpObj = smtplib.SMTP('smtp.gmail.com', 587)
       smtpObj.ehlo()
       smtpObj.starttls()
       smtpObj.ehlo()
       smtpObj.login(sender, gmail_pass)
       smtpObj.sendmail(sender, receivers, message)
       smtpObj.quit()
       print("Successfully sent email")
    except SMTPException:
       print("Error: unable to send email")

if choice == "1": #[1] Copy key to clipboard
    pyperclip.copy(finalkeystosend)
    responseus = requests.put((api_keyus+'/access-keys/'+idus+'/'+email),verify=False)
    responsenl = requests.put((api_keynl+'/access-keys/'+idnl+'/'+email),verify=False)
if choice == "2": #[2] Just rename key(s)
    responseus = requests.put((api_keyus+'/access-keys/'+str(idus)+'/'+email),verify=False)
    responsenl = requests.put((api_keynl+'/access-keys/'+str(idnl)+'/'+email),verify=False)
`

**Comment by fortuna** [comment]
What error do you get?

The API does work. The Manager uses it:
https://github.com/Jigsaw-Code/outline-server/blob/a4a326e1163172006457e0d235d9d264d67808e1/src/server_manager/web_app/shadowbox_server.ts#L60

Make sure the API URL is what you get from the Manager screen.

**Comment by zedaff** [comment]
Hi,

Trying to send the PUT request to the server:

**https://server-ip:server-port/API-secret-path/access-keys/89/name**

with the content:

**"{name: \"New Key Name\"}"** - from the [Re-Doc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys~1%7Bid%7D/delete)

But it always gives me an error :

**code:MissingParameter
message	Parameter `id` is missing**

Why is this happening? Could someone help me, please?

**Comment by fortuna** [comment]
Obsolete
