### ISSUE TITLE
Outline manager can't work with digital ocean

### ISSUE THREAD

**Issue by g1un** [Jigsaw-Code/outline-server#658]
Hi!
Since 20th of May outline client stopped to work. Then I removed the server and tried to create a new one with outline manager, but was no success. Manager creates the server at digital ocean, but for some reason can't go further showing its spinner infinitely.
I've tried different countries. I also tried to create the digital ocean server being under vpn from Germany and without it from Russia. But It doesn't matter.
For now I can create Amazon server by means of outline manager.
Macos 10.15.4.
<img width="788" alt="Screenshot 2020-05-21 at 19 54 26" src="https://user-images.githubusercontent.com/13907881/82584287-f83a5f80-9b9c-11ea-9140-5502d5076814.png">

**Comment by alalamav** [comment]
Hi @g1un, what version of the Outline Manager are you running? We had some issues with the DigitalOcean API last week that we fixed on [v1.5.2](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.2), but we may have introduced this issue.

**Comment by g1un** [comment]
@alalamav Version 1.5.2 (1.5.2.3486)

**Comment by alalamav** [comment]
Thanks. This has been fixed in #659 and will be released shortly in v1.5.3.

**Comment by alalamav** [comment]
[Outline Manager v1.5.3](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.3) has been released. Please let us know if it works for you and thanks for reporting the issue.

**Comment by g1un** [comment]
@alalamav Thank you, it works.
I am wonder, why in the whole internet I could not google any claims on outline+DO work and had to create one myself) Looks like only few people use it and I thought there are millions or at least thousands of users.
