### ISSUE TITLE
Provide instructions to update Outline server

### ISSUE THREAD

**Issue by 5amfung** [Jigsaw-Code/outline-server#662]
I'm currently running Outline server v1.2.1 on Google Cloud and looking for ways to update to the latest v1.5.x.  I couldn't find any instruction online to easily update.  The only way I could think of is to create a completely new instance and remove the old one but that would create disruption to all users because all users will have to go through the setup again.

Is there a command or something that I can run by ssh-ing into my instance?

**Comment by fortuna** [comment]
The Outline server is automatically updated using watchtower. No need to manually update it.
