### ISSUE TITLE
Unable to find image 'quay.io/outline/shadowbox:stable' locally

### ISSUE THREAD

**Issue by TheDoop** [Jigsaw-Code/outline-server#668]
Ubuntu 20.04
`root@ubuntu:~# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
Unable to find image 'quay.io/outline/shadowbox:stable' locally
docker: Error response from daemon: Get https://quay.io/v2/: EOF.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
root@ubuntu:~#
`

**Comment by alalamav** [comment]
Hi @TheDoop, [quay.io](https://status.quay.io) (where we host the server image) was down recently. It should be working now, so please try again and let us know if it works.
