### ISSUE TITLE
DNS routing

### ISSUE THREAD

**Issue by francobee** [Jigsaw-Code/outline-server#672]
Hi,
I'm doing a dns leak test and found that my outline server is sending dns requests to opendns, dyndns. 
How do i change/configure the dns to route all it requests to a pi-hole ?

**Comment by hdavy2002** [comment]
I used iptables to redirect DNS. In your case host pihole on another machine/vps and then change the IP. I tried pihole on the same machine as Outline. No luck. I realized it will create a loop, if pihole is hosted locally.

iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to 1.1.1.1:53
iptables -t nat -A OUTPUT -p tcp  --dport 53 -j DNAT --to  8.8.8.8:53

**Comment by fortuna** [comment]
The server uses the system DNS. You just need to change the system DNS. You can usually do that by editting /etc/resolv.conf on Linux
