### ISSUE TITLE
Poosible to block desktop outline clients

### ISSUE THREAD

**Issue by hdavy2002** [Jigsaw-Code/outline-server#677]
Hi guys,

I am inviting family to my outline server. However, I dont want them to use my little VPS with 1 TB bandwidth. They will consume in a day. Is it possible to only allow Android and iPhone Outline apps and block Outline desktop clients?

many thanks

Cheers

**Comment by alalamav** [comment]
Hi @hdavy2002, Outline currently doesn't support selectively blocking desktop apps. The team is thinking of solutions to limit concurrect connections. For your use case, I recommend you enable access key [data limits](https://www.reddit.com/r/outlinevpn/comments/fnqxqg/try_experimental_data_limits_in_outline_140/) to set a cap on the data transfer of each key.

Let me know if that helps.

**Comment by hdavy2002** [comment]
> Hi @hdavy2002, Outline currently doesn't support selectively blocking desktop apps. The team is thinking of solutions to limit concurrect connections. For your use case, I recommend you enable access key [data limits](https://www.reddit.com/r/outlinevpn/comments/fnqxqg/try_experimental_data_limits_in_outline_140/) to set a cap on the data transfer of each key.
> 
> Let me know if that helps.

Thanks. Data limits sounds like a plan. Cheers

**Comment by fortuna** [comment]
I'm glad that works for you. In the future we can consider bandwidth limits too, but we found that hard for an admin to specify.
