### ISSUE TITLE
how to monitor outline?

### ISSUE THREAD

**Issue by todatamining** [Jigsaw-Code/outline-server#680]
Platform: debian 10

I would like to check who(ip address) is connecting outline server. 
Currently I have to use lsof -i. This only show the active connection.
How can I check all the history connection?

**Comment by sabreys** [comment]
+1 i am looking for that too. how  can we track ips and histories ?

**Comment by fortuna** [comment]
That's not supported by Outline. Storing IP addresses has privacy issues, and it's not something we intend to support.
