### ISSUE TITLE
Outline manager Error

### ISSUE THREAD

**Issue by garbage-debug** [Jigsaw-Code/outline-server#683]
**Hi Outline Team,**
I,m encountered the issue in the outline manager, whenever I open the outline manager the error message just popup. I don't know wants wrong with its application.

![outline manager java error](https://user-images.githubusercontent.com/66560805/83971544-7155e880-a8f9-11ea-9cd0-2660b0f650ae.PNG)
![outline manager javascript error -1](https://user-images.githubusercontent.com/66560805/83971566-9ba7a600-a8f9-11ea-9f01-fa6101124a35.PNG)

**Comment by alalamav** [comment]
Hi @garbage-debug, what version of the Outline Manager are you using? Please update to the [latest release](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.3), which has a fix for this issue.

**Comment by garbage-debug** [comment]
what version of the Outline Manager ?
1.5.3.
Well, after the installation of the latest version outline manager, I got a new issue. my outline manager application has been stuck in waiting to connect your account. I don't know what is wrong with the outline manager but the older version is working fine.

![digitaloceanoauth15062020](https://user-images.githubusercontent.com/66560805/84689681-f2972600-af5e-11ea-98f2-8b2232df99cd.PNG)




![digital ocean successfully oauth15062020](https://user-images.githubusercontent.com/66560805/84689742-080c5000-af5f-11ea-8fc3-572347b7087c.PNG)



![outline manager 15062020](https://user-images.githubusercontent.com/66560805/84689751-0cd10400-af5f-11ea-8d4c-675ae2f44c3e.PNG)

**Comment by bnicholas** [comment]
Same here.

**Comment by fortuna** [comment]
I believe this has been fixed. Could you confirm?

Current macOS Manager version is 1.6.1
