### ISSUE TITLE
How to do a repetable install

### ISSUE THREAD

**Issue by rverma-jm** [Jigsaw-Code/outline-server#684]
The installation steps are very straight forward for a general use.
Wondering if I have a static ip, can i make the installation repeatable.
i.e. the output `apiurl` and `certsha56` will be same even if I recreate the instance.

**Comment by alalamav** [comment]
Hi @rverma-jm, unfortunately there is no easy way of accomplishing this at the moment.

However, if you are willing to modify the install script you can do the following:
- Pass the `--hostname`option to the script with your static IP.
- Pass the `--api-port` option to the script with your managment API port.
- Comment out the [command](https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh#L399) to generate a random API prefix. Instead, `export SB_API_PREFIX` to your prefix.
- Comment out the [command](https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh#L400) to generate the certificate and private key. Assuming the hostname is the same, copy your existing certificate to `/opt/outline/shadowbox-selfsigned.[crt|key]`.

I realize this is not straightforward. The team has been thinking of solutions to migrate servers, so please continue to bear with us.

**Comment by fortuna** [comment]
@rverma-jm why do you need the installation to be repeatable?
