### ISSUE TITLE
Whitelist some hosts

### ISSUE THREAD

**Issue by 4ndv** [Jigsaw-Code/outline-server#69]
Is there any way to whitelist some hosts, that don't need to be connected over proxy?

**Comment by 4ndv** [comment]
Server... i think?

**Comment by trevj** [comment]
Thanks for reaching out to us, @4ndv. Outline does not currently support host whitelisting, although we are always evaluating new features. As @bemasc's comment suggests, this would probably be a feature for the client.

**Comment by 4044ever** [comment]
OT: Shadowsocks/ShadowsocksR has that feature. When you are in in the and you google for "my ip" it shows the IP your Shadowsocks is hosted on, if you go to myip.cn you local IP shows. Neat function.

**Comment by 4ndv** [comment]
It would be nice, if there will be ability to sync that lists (or copy/paste), cause there can be a lot of these hosts (like i prefer to whitelist all my servers that i connect via ssh, social networks, google, etc...)

**Comment by trevj** [comment]
I think is better tracked in the client issue tracker - I think this covers it:
https://github.com/Jigsaw-Code/outline-client/issues/8
