### ISSUE TITLE
CORS issues when connected to VPN

### ISSUE THREAD

**Issue by daveredfern** [Jigsaw-Code/outline-server#690]
Hi everyone,

Thank you for your hard work creating this product. It works really well.

Often, when visiting certain websites, assets won’t load in (custom fonts, etc). When looking in Chrome Dev tools I see CORS issues:

> CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is there a way to resolve this? When not connected to the VPN everything is fine. Also, I tried some commercial VPN providers and they work okay too.

Cheers,

Dave.

**Comment by fortuna** [comment]
This doesn't seem related to the Outline software, as it doesn't modify any user traffic. Perhaps some sites behave differently depending on your location.

What client are you using?
