### ISSUE TITLE
manual install does not print firewall help if firewall check fails

### ISSUE THREAD

**Issue by qoli** [Jigsaw-Code/outline-server#70]
```
qoli@sarayun-gcm:~$ wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | sudo bash
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... OK
> Waiting for Outline server to be healthy .... OK
> Creating first user ......................... OK
> Adding API URL to config .................... OK
> Checking host firewall ...................... BLOCKED

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

```
Checking host firewall ...................... BLOCKED

Please show what port need to open.
I don't know open which port.

**Comment by bemasc** [comment]
Currently, the Outline Server selects new ports at random as you add new access keys.  Therefore, it requires you to open all ports above 1024.

Once you are done generating access keys, you can close all ports that are not used in any Access Key.

**Comment by fortuna** [comment]
I'm reopening because this is a bug in the install script. It is supposed to show the ports for the user management API and the admin shadowsocks instance: https://github.com/Jigsaw-Code/outline-server/blob/ecd937a6fedd66692121f80b49895ff3865a7346/src/server_manager/install_scripts/install_server.sh#L210-L211.

@qoli, could you try again with 
```
 wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | sudo bash -x
```
(note the `-x` at the end)

**Comment by krrisztian** [comment]
It would be useful if the script would say which ports need to be opened when it gives the "host firewall BLOCKED" error. Now we have to go on Google (may be blocked - China) and look for the ports (or worse open up ALL of them not knowing which ones are used).
Simply echoing out "open all ports above 1024 until set-up has been finished" would help a lot.

**Comment by trevj** [comment]
Thanks for the report, @qoli.

@fortuna The value of `FIREWALL_STATUS` is only being printed on successful install. Can you please submit a PR to print it whether or not the firewall check succeeds?

**Comment by fortuna** [comment]
Thanks @qoli for the output dump. That's very helpful. I believe @trevj is right, so we know where the problem probably is. That's my fault, sorry about that (and damn shell programming! :disappointed:).

I'll work on it later today.

**Comment by fortuna** [comment]
@qoli, could you try again? The script should be fixed now

**Comment by qoli** [comment]
@fortuna 

thx. It is work!

```
> Adding API URL to config .................... OK
> Checking host firewall ...................... BLOCKED
OK

CONGRATULATIONS! Your Outline server is up and running.

To manage your Outline server, please copy the following text (including curly
brackets) into Step 2 of the Outline Manager interface:

{
  "apiUrl": "",
  "certSha256": ""
}

You won’t be able to access it externally, despite your server being correctly
set up, because there's a firewall (in this machine, your router or cloud
provider) that is preventing incoming connections to ports 46015 and
52272.

- If you plan to have a single access key to access your server, opening those
  ports for TCP and UDP should suffice.
- If you plan on adding additional access keys, you’ll have to open ports 1024
  through 65535 on your firewall since the Outline server may allocate any of
  those ports to new access keys.

```
