### ISSUE TITLE
Slow Download Speed in outline mobile app and pc

### ISSUE THREAD

**Issue by sande265** [Jigsaw-Code/outline-server#709]
When i installed outline on my server hosted on AWS, i selected 4 cores and 8gb ram . So the server has enough resources to handle at least 100 simultaneous clients, but even with 2-3 clients logged in the download speed is very low , while on the other hand the upload speed is full of the client computer or phone. For ex: I have a 40mbps up/down connection for home and i get 2-5 mbps down and full up bandwidth, looked up for this issue and checked my connection from AWS virtual network adapter was 5 gbps. Tried it from different locations as well as different ISP's but no luck.  So no bottleneck there too, unable to find my answers posting in the problem section of Github.
If you find the issue, thanks in advance please post in the comments.

**Comment by AnonymousWebHacker** [comment]
fixed?
