### ISSUE TITLE
outline server - backup / restore

### ISSUE THREAD

**Issue by woosungchoi** [Jigsaw-Code/outline-server#712]
I was able to find a solution to the same problem https://github.com/Jigsaw-Code/outline-server/issues/450 last year.

I cannot find server's credentials at '/opt/outline/access.txt' nor '/root/shadowbox/access.txt'

@alalamav  Help me!

**Comment by woosungchoi** [comment]
I found at /opt/outline/access.txt.

thx!

**Comment by woosungchoi** [comment]
How to ~

https://www.wsgvet.com/bbs/board.php?bo_table=web&wr_id=242

**Comment by pymen** [comment]
Python code to prepare ss:// address from data from config

on ubuntu22 the config was here `cat /home/$USER/.config/Outline/connection_store | jq ".config" `

```

def get_outline_address(host, port, password, method):
    info_str = f'{method}:{password}@{host}:{port}'.encode('utf-8')  # Convert the string to bytes
    accessKey_encoded = base64.b64encode(info_str).decode('utf-8')
    accessKey = f'ss://{accessKey_encoded}'
    return accessKey
```
