### ISSUE TITLE
How to enable Port Forwarding on both TCP and UDP?

### ISSUE THREAD

**Issue by ItzMeDry** [Jigsaw-Code/outline-server#717]
I don't know if there is a feature of port forwarding.
If there is , how to enable it on ubuntu 18.04?

**Comment by unicorn667** [comment]
vim /etc/sysctl.conf 

add 
net.ipv4.ip_forward=1

execute
sysctl net.ipv4.ip_forward

**Comment by fortuna** [comment]
Outline supports both TCP and UDP. This question is not really about the Outline product, so I'll close the issue.
