### ISSUE TITLE
Manager uninstall residue

### ISSUE THREAD

**Issue by abersheeran** [Jigsaw-Code/outline-server#737]
I have uninstalled Outline Manager from my computer, but it still shows the following.

![image](https://user-images.githubusercontent.com/25364828/94402778-0f1e3d80-019f-11eb-86c3-d40d91ea911b.png)

Show after selecting uninstall

![image](https://user-images.githubusercontent.com/25364828/94402806-16dde200-019f-11eb-9164-8755fff720f0.png)

**Comment by jianshangwei94** [comment]
你可以使用 uninstall tool 应用卸载器可以试一试

**Comment by jinze101** [comment]
你可以在控制面板裡面卸載，哪裏卸載的乾淨，我就是這樣做的

**Comment by maddyhof** [comment]
This is a bug caused by the antivirus software, not by Outline.
