### ISSUE TITLE
Outline Manager doesn't walk through process

### ISSUE THREAD

**Issue by pandemicsoul** [Jigsaw-Code/outline-server#74]
I'm using the Mac tool. When I open it, in the DigitalOcean section, I choose "I have an account, sign me in" and go through the process of signing in. 

I'm then brought to a screen, inside the app, where I get two red error boxes (I think they say something like "Oops, something's wrong!" overlayed on a DigitalOcean page asking me to authorize either my personal DigitalOcean account or my organization account. Lots of images on the page aren't loading. I choose the org account and "Authorize." But then I'm brought to the standard DigitalOcean dashboard – that's way too big for the Outline Manager window, so I have to scroll left/right. I tried setting up a new server this way, but there seemed to be no way to connect it, within the Outline Manager app, to Outline itself. 

I tried starting over numerous times and got the same issues.

**Comment by dborkan** [comment]
Hi, thanks for the error report.  I'm seeing something similar to your initial report (the "Oops, something's wrong!" error with 2 red boxes) when I try to login with an account that hasn't completed either the email verification or billing info steps.  However for accounts that have both email verification and billing the OAuth page looks as expected and after completing it I'm directed back into the Outline app.

Can you try logging in at https://cloud.digitalocean.com/login and see if this takes you to either the email verification or billing steps?  If so, you will need to complete these to continue.  However if that is already completed then there appears to be something else wrong.

Regarding the screenshots of your droplet screen, when Outline successfully authenticates with DigitalOcean you should never actually see this screen (droplets should be managed from the Outline UI, not DigitalOcean), so I'm hoping that if you resolve any account setup issues then you will no longer see this screen.

**Comment by pandemicsoul** [comment]
@dborkan Yup, that was it. I have an account with my email address, and then a team account connected to it, and I don't use the email address account and only manage servers under the team account, so I've never had a reason to finish the setup using my email address. Once I did that, everything worked flawlessly. 

Thank you so much for the help!
