### ISSUE TITLE
Failed to get DigitalOcean account information

### ISSUE THREAD

**Issue by tliu39** [Jigsaw-Code/outline-server#747]
When I started the Outline Manager just now, there is a text box prompted at the bottom left of the window that says "**_Failed to get DigitalOcean account information_**". 

The Manager also failed to retrieve any information regarding the server I created on DigitalOcean. There is just nothing there. 

This apparent authentication error also disables me from creating a new server on DigitalOcean. 

The Manager was working perfectly fine until just now. 

I am running a Ubuntu 18 on my local machine, and the Outline Manager is version 1.6.0. Is there anything that I can do to resolve this issue?

**Comment by alalamav** [comment]
Hi @tliu39, thanks for reporting this issue. We have fixed in #743 and will release it shortly on v1.6.1.
