### ISSUE TITLE
firewall port

### ISSUE THREAD

**Issue by sxy88** [Jigsaw-Code/outline-server#751]
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.

When I deploy outline on my vmware virtual machine，and I've closed the firewall.
Checking host firewall ...................... BLOCKED
OK

help me, ball ball le

**Comment by sxy88** [comment]
there are my command：

apt-get install curl   
sudo apt update   
sudo apt install apt-transport-https ca-certificates curl software-properties-common   
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add –   
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"   
sudo apt update   
sudo apt -y install docker-ce 
bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"

**Comment by fortuna** [comment]
It seems you closed the firewall. You need to open the ports that the script mentions.
