### ISSUE TITLE
Starting Shadowbox .......................... FAILED

### ISSUE THREAD

**Issue by kieran6704** [Jigsaw-Code/outline-server#759]
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

**Comment by fortuna** [comment]
There's something wrong with Docker. Perhaps restart Docker and try again?

**Comment by kieran6704** [comment]
Yeah thanks, I got it it was something to do with WSL and docker \.
