### ISSUE TITLE
Checking host firewall ...................... BLOCKED

### ISSUE THREAD

**Issue by jointmeister** [Jigsaw-Code/outline-server#762]
spikkerlol@cloudshell:~ (vpn-jointmeister)$ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... OK
> Waiting for Outline server to be healthy .... OK
> Creating first user ......................... OK
> Adding API URL to config .................... OK
> Checking host firewall ...................... BLOCKED
OK

on server "protocols and ports - allow all", how to fix the problem? in outline manager writes that it is necessary to enable ports from 1024 to 65535

**Comment by fortuna** [comment]
You need to figure out what firewall your system is using.

If your system is using ufw, you can call:
```
ufw allow 1024:65535 
```
