### ISSUE TITLE
DigitalOcean install server issue

### ISSUE THREAD

**Issue by AnergCorp001** [Jigsaw-Code/outline-server#773]
Hi, I am trying to install, Outline Server Manager to my laptop/desktop here is also outline server management blocked, so I am trying to install it on server and add clients there, How I can do it, please help

**Comment by alalamav** [comment]
Hi @AnergCorp001, what do you mean with "here is also outline server management blocked"? Is getoutline.org inacessible for you?

You can download the Outline Manager app directly from [outline-server/releases](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.6.1) or [outline-releases](https://github.com/Jigsaw-Code/outline-releases/tree/master/manager/stable). 

If none of these options work and you are able to ssh into your server, you can run:

```bash
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
```

You will need to disable any firewalls on the ports output by the install script. Then you can create client access keys through the [server management API](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys~1{id}~1name/put).
