### ISSUE TITLE
[outline-shadowsocksconfig] `userinfo` in generated ss:// links shouldn't include padding characters

### ISSUE THREAD

**Issue by database64128** [Jigsaw-Code/outline-server#774]
This issue was intended for [Jigsaw-Code/outline-shadowsocksconfig](https://github.com/Jigsaw-Code/outline-shadowsocksconfig). But since the repo has the issues area disabled, I have no choice but to post it here.

[SIP002](https://shadowsocks.org/en/wiki/SIP002-URI-Scheme.html) requires the `userinfo` to be `base64url`-encoded. That means the trailing padding characters (`=`) shouldn't be included. For example, instead of `ss://YWVzLTI1Ni1nY206cGFzc3dvcmQ=@github.com:443/#GitHub`, the link should be `ss://YWVzLTI1Ni1nY206cGFzc3dvcmQ@github.com:443/#GitHub`.

Note that previously the standard document has some incorrect examples. I have fixed them in [this commit](https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme/_compare/dc364be339684947d3778193166768f474bb43ea...73c73295e7bb256b0c80975db16c152405dff05d).

**Comment by ohnorobo** [comment]
This still needs a release to be cut for for outline-shadowsocksconfig

**Comment by ohnorobo** [comment]
cut a release https://github.com/Jigsaw-Code/outline-shadowsocksconfig/releases/tag/v0.1.1

**Comment by database64128** [comment]
Thank you for taking time to address the issue! 👍

**Comment by ohnorobo** [comment]
Also updated in https://github.com/Jigsaw-Code/outline-client/pull/965
