### ISSUE TITLE
[Manager] Multiple Server Support.

### ISSUE THREAD

**Issue by laosb** [Jigsaw-Code/outline-server#78]
Well done!

We're currently using this across many departments, and we surely needs more than just one server to proxy all connections for our team members (more than 1000+ long connections to one infamous sounds like easy to be found and block). Could you support setting up more than one server per Manager instance?

PS: I'm also thinking should we have some ways to backup server managing credentials? Maybe another issue to open.

**Comment by ow** [comment]
This is the first thing I wanted, and the thing I came here to look for. Adding my support for this, as having a single region is quite frustration/a blocker for me!

**Comment by trevj** [comment]
@laosb and @ow, thanks for the feedback and suggestions!

**Comment by tsekityam** [comment]
I can manage multiple servers with Outline Manager by backup/restore the local storage (i.e. `~/Library/Application Support/Outline Manager/Local Storage/` for macOS) of the manager. 
It is not a good solution but, at least, it works.

**Comment by Nz666-Kshatriya** [comment]
The same suggestion as I'd like to give

**Comment by MaXFalstein** [comment]
I would like to take this further by supporting DigitalOcean load balancers and multiple droplets.

**Comment by trevj** [comment]
Popular feature!

Duplicates:
- https://github.com/Jigsaw-Code/outline-server/issues/127
- https://github.com/Jigsaw-Code/outline-server/issues/112
- https://github.com/Jigsaw-Code/outline-server/issues/122

**Comment by viralking** [comment]
Agree! This would be awesome, to have multiple locations in the manager :)

**Comment by xukaifu** [comment]
Awesome, I'm looking forward to it!

**Comment by NEXUS2345** [comment]
In terms of multiple servers, could we allow multiple servers from different providers? The ability to diversify the providers used would make the service more stable and provide more options for people who are getting some providers blocked in some countries but not others.

**Comment by trevj** [comment]
@alalamav Can you add a little colour here to what you've been working on? Thanks.

**Comment by alalamav** [comment]
This feature is indeed prioritized. I have been working on a UI refactor (#273) that will enable us to add support for managing multiple servers. Here's a sneak peek into our team's vision for the Outline manager app:

![mss-mock](https://user-images.githubusercontent.com/2132122/47032902-7de46680-d141-11e8-99c0-ec0064d6d39a.png)

**Comment by NEXUS2345** [comment]
@alalamav this looks really nice. I'm looking forward to getting to use it. Thank you very much for your work.

**Comment by alalamav** [comment]
Hi all, we have started the rollout of the Outline Manager with multiple server support. If you'd like to try it out before we roll it out to all users, you can download it [here](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.2.0). As always, we appreciate your feedback and suggestions. Thanks!

**Comment by scottrobertson** [comment]
@alalamav This looks awesome. One bit of feedback though: Will you allow multiple accounts per provider eventually? I have work VPN's and Personal ones on the same provider, and it's not possible with this currently from what i can see.

**Comment by lgg** [comment]
@scottrobertson didn't understand your case. Can you clarify it, please?

**Comment by trevj** [comment]
@scottrobertson We are considering multiple DigitalOcean accounts though I'm afraid I can't tell you when it will happen.

**Comment by scottrobertson** [comment]
@lgg I have personal and work VPNs. I don't want to use work VPNs when watching videos etc. Manager currently does not allow multiple accounts for 1 provider.

@trevj thank you. No rush, just wanted to check it was on your radar 👍

**Comment by alexfedoseev** [comment]
+1 to multiple accounts support. I have personal DO account + DO team. I can create/manage servers only @ one of them.
