### ISSUE TITLE
The device or resource (localhost) is not set up to accept connections on port "55189".

### ISSUE THREAD

**Issue by oividioscaeremos** [Jigsaw-Code/outline-server#781]
Hey,

When I try to connect Outline Manager to the DigitalOcean account, the redirect url which is `https://localhost:55189/` shows the below error;

![image](https://user-images.githubusercontent.com/24587852/102818413-9f58d100-43e2-11eb-864a-399855bcb919.png)

I added new rules on allowing both inbound and outbound TCP connections on port 55189 but it hasn't solved my issue. I haven't managed to find the same error on my browse so this is the place to file an issue I guess.

Anyone got any ideas?

**Comment by JonathanDCohen** [comment]
Hey there, sorry for the delay in response.

This is when you're signing up to DigitalOcean? It looks like that url is for the server we use on your computer to get your DigitalOcean credentials once you've logged in, and this shouldn't be happening.  

You may want to try clearing your browsing data

**Comment by oividioscaeremos** [comment]
Hi :)
Not a problem for the delay. As it turns out it was the "browser" that caused the problem. Apparently you shouldn't use Brave for authenticating Outline to Digital Ocean. Once I switched to Chrome, the issue was gone.
Sorry for not closing this once I got my problem fixed.
Thank you for your reply :)
