### ISSUE TITLE
not working data limit for the given access key command

### ISSUE THREAD

**Issue by ssilistre** [Jigsaw-Code/outline-server#786]
Hello guys, i try data limit for the given access key command in here : https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Access-Key/paths/~1access-keys~1{id}~1name/put also i check this page : https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/api.yml line 207 . But didnt work. 

This comamand not used or what is my problem ? 

Thanks.

**Comment by imgk** [comment]
You should build docker image by yourself to use latest version.

**Comment by ssilistre** [comment]
I do already but not working

**Comment by dannyreis** [comment]
According to this the data limits are enforced hourly.
https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/server/server_access_key.ts#L86

They're also enforced when the data limits are set/removed as well. So you can try resetting the data limit and the user should be blocked.

**Comment by JonathanDCohen** [comment]
Hey there, sorry for the delay in response.  Did you get the issue resolved?  What command were you using?  

@dannyreis is correct in that limits are enforced hourly and whenever the API endpoints are called, so you can force data limit enforcement by resetting the current data limit to the same value as it has currently.

**Comment by fortuna** [comment]
The per-key data limit is not rolled out to production yet. Currently you can only set a common limit for all the keys in the server. The new feature should become live next week, with server version v1.6.0

**Comment by ssilistre** [comment]
@fortuna thans for writeing i wait new update closed this subs

**Comment by JonathanDCohen** [comment]
@ssilistre The update is live and all servers should have updated themselves to v1.6.0.  You can check the [API documentation](https://redocly.github.io/redoc/?url=https%3A%2F%2Fraw.githubusercontent.com%2FJigsaw-Code%2Foutline-server%2Fmaster%2Fsrc%2Fshadowbox%2Fserver%2Fapi.yml#tag/Access-Key/paths/~1access-keys~1{id}~1data-limit/put) to see how to use the new API, and we'll shortly be rolling out an API and localized Support Center material along with it

**Comment by fortuna** [comment]
You can see the server version on the Settings tab of the server: 
![image](https://user-images.githubusercontent.com/113565/105716967-89609380-5eed-11eb-9b92-5dcde7e94486.png)

**Comment by fortuna** [comment]
@ssilistre This should be working now. Let us know if you are still having trouble.

**Comment by iTem186** [comment]
Hi there!
I'm trying to set data limit for access-key through [API](https://redocly.github.io/redoc/?url=https%3A%2F%2Fraw.githubusercontent.com%2FJigsaw-Code%2Foutline-server%2Fmaster%2Fsrc%2Fshadowbox%2Fserver%2Fapi.yml#tag/Access-Key/paths/~1access-keys~1%7Bid%7D~1data-limit/put)

```python
url = OUTLINE_MANAGMENT_API_URL + f"/access-keys/65/data-limit" 
payload = {"limit":{"bytes": 8492374}} 
response = requests.put(url, data=payload, verify=False) 
response.text
```

But got an error:
`'{"code":"InvalidArgument","message":"limit.bytes must be an non-negative integer"}'`

Anybody know what is a problem with my request?

**Comment by iTem186** [comment]
@fortuna CURL command also doesn't work
`curl -X PUT -d limit='{'bytes': 10000}' $OUTLINE_MANAGMENT_API_URL/access-keys/1/data-limit --insecure`

![изображение](https://user-images.githubusercontent.com/26230210/194800947-cf5755b9-0800-4f7b-9650-62e66ad253f4.png)

Btw, I tried manually change the value of dataLimit in file `/opt/outline/persisted-state/shadowbox_config.json` but there is no effect. Maybe I should change this value elsewhere?
