### ISSUE TITLE
Version and release notes?

### ISSUE THREAD

**Issue by 4044ever** [Jigsaw-Code/outline-server#79]
Are there any version numbers for the outline-server? Just to make sure the latest is installed.

And are there any release notes with new versions to know about bug fixes and new functions?

**Comment by trevj** [comment]
Thanks for reaching out, @4044ever.

Yes, Outline Manager has version numbers and release notes.

To see which version you're running:
* Open Outline Manager.
* Click the hamburger icon in the top-left corner, revealing the side menu.
* From the side menu, click About Outline.
* A dialog will appear. The version number is beneath the Outline Manager logo.

You can find releases notes for the latest release here:
https://github.com/Jigsaw-Code/outline-server/releases/latest

You can find release notes for older releases by searching on this page for releases not marked pre-release (currently they are named in the format `vx.x.x`, where x.x.x is the version number):
To find release notes, look at our releases page:
https://github.com/Jigsaw-Code/outline-server/releases

**Comment by trevj** [comment]
@4044ever Please re-open if you have any further questions.
