### ISSUE TITLE
API: `GET` data limit

### ISSUE THREAD

**Issue by database64128** [Jigsaw-Code/outline-server#792]
Currently the API can only `PUT` or `DELETE` a data limit. This makes it difficult to track the actual data limit being enforced to the server or an access key. We should allow `GET` on `/access-keys/{id}/data-limit` and `/experimental/access-key-data-limit`.

**Comment by JonathanDCohen** [comment]
I agree it's a little clunky.  Currently you can use [jq](https://stedolan.github.io/jq/) to get information on individual keys

```
$ curl -k  https://my.server/$PREFIX/access-keys \
  | jq '.accessKeys[] | select(.id == "$KEYID")'
      
{
  "id": "201",
  "name": "Key Name",
  "password": "SomePassword",
  "port": 12345,
  "method": "chacha20-ietf-poly1305",
  "dataLimit": {
    "bytes": 2500000000
  },
  "accessUrl": "ss://..."
}
```

**Comment by JonathanDCohen** [comment]
Hey there!  Thanks for bringing up the issue.  I agree that the API for individual access keys is a bit clunky, but thankfully you don't need it to get the information you need.

You can currently get the data limit enforced on each key either through the UI

<img width="706" alt="Screen Shot 2021-01-13 at 12 46 47 PM" src="https://user-images.githubusercontent.com/3297872/104489291-74a30800-559d-11eb-9834-5a708812d261.png">

Or using [GET /server](https://redocly.github.io/redoc/?url=https%3A%2F%2Fraw.githubusercontent.com%2FJigsaw-Code%2Foutline-server%2Fmaster%2Fsrc%2Fshadowbox%2Fserver%2Fapi.yml#tag/Server/paths/~1server/get), which returns a JSON blob looking something like

```
{
  ...
  "accessKeyDataLimit": {
    "bytes": 5000000000
  },
  ...
}
```


To get programmatic access to information about individual access keys using the API, you could use something like [jq](https://stedolan.github.io/jq/):

```
$ curl -k https://my.server:address/$PREFIX/access-keys | jq '.accessKeys[] | select(.id == "1")'

{
  "id": "1",
  "name": "Key Name",
  "password": "somePassword",
  "port": 12345,
  "method": "chacha20-ietf-poly1305",
  "accessUrl": "ss://..."
}
```

We have a [Help Article](https://support.getoutline.org/s/article/data-limits) about data limits which might also help you out.

**Comment by JonathanDCohen** [comment]
@database64128 I'm assuming from your reaction that this all worked out for you.  I'm going to close the issue as fixed, but please feel free to re-open it or start another one if you need more help!

**Comment by parsalotfy** [comment]
@JonathanDCohen  Hi, What is that $PREFIX ?

**Comment by database64128** [comment]
@parsalotfy It's the path in the API URL. For example, if your API URL is `https://example.com/secret`, you can `GET https://example.com/secret/access-keys` to list the access keys.

**Comment by parsalotfy** [comment]
> @parsalotfy It's the path in the API URL. For example, if your API URL is `https://example.com/secret`, you can `GET https://example.com/secret/access-keys` to list the access keys.

wow, Thank you very much for your quick answer, I'll check that out.
