### ISSUE TITLE
I need client for Linux Manjaro(Arch), confused on what to install

### ISSUE THREAD

**Issue by slrslr** [Jigsaw-Code/outline-server#797]
Hello, i am wondering what is the best way to install outline client (i mean app that preferably has GUI and that will allow me to connect the server which i will later create on my headless Ubuntu Linux server).

1. AppImage
https://appimage.github.io/Outline-Manager/ - https://github.com/Jigsaw-Code/outline-server/releases
(they are linking to outline-server github page, a bit confusing one may think server and manager are two products, and on that page is not server app, but is Outline-Manager.AppImage)

2. SNAP called "outliner" CLI tool to setup and deploy Outline VPN (server? - they do not state it is for server in that snap package description):
https://github.com/Jyny/outliner
https://snapcraft.io/outliner

3. AUR (Linux Arch User-contributed Repository)
outline-client-appimage                 1.2-1                         AUR
https://aur.archlinux.org/packages/outline-client-appimage/
$ pamac build outline-client-appimage

my aim on Manjaro is to have reliable Outline client service (ideally with GUI) to connect the Outline server which i plan to create later on my remote headless Linux Ubuntu server. So i can later set certain port in my web browser and this connection will be proxified using the outline proxy "tunnel" for system proxy i am using Wir€guard.
What do you suggest please?

**Comment by JonathanDCohen** [comment]
You can download binaries for both the client and the manager from [the Outline website](https://getoutline.org/).

**Comment by JonathanDCohen** [comment]
Hey there @slrslr.  Have you figured out how to install Outline?

**Comment by slrslr** [comment]
> using Outline all web traffic from your computer will be sent through the Outline proxy

@JonathanDCohen 

Thank you, if you are aware there is a workaround to prevent app setting system proxy on Linux and so i can instead just set certain app to use 127.0.0.1:outlineport ; or if is simple to add setting for this purpose, kindly let me know.

**Comment by JonathanDCohen** [comment]
@slrslr If I understand correctly you're asking if you can only use the VPN for certain apps.  We don't currently support this, as Outline adjusts your system's routing table, although you're the second person to request that feature recently.

What you can do, if your app supports SOCKS proxies, is to use a different Shadowsocks client (https://github.com/shadowsocks/shadowsocks-rust for example) to start up `ss-local` on your system, which you can point your app to. As a simple example, for an `ss-local` instance running on your machine listening on port 9998, you could run

    ncat --proxy 127.0.0.1:9998 --proxy-type socks5 ${DESTINATION_IP} ${DESTINATION_PORT} 

to send data to your destination through the tunnel without affecting other apps.
