### ISSUE TITLE
How backup configuration file

### ISSUE THREAD

**Issue by liuzipeng** [Jigsaw-Code/outline-server#800]
How to backup configuration file and restore on another computer?

**Comment by fortuna** [comment]
You need to SSH into the machine and copy the persisted-state directory.

Keep in mind that migrating to another server will break existing keys anyway, so you might as well regenerate them. You may consider using a domain name for the new server to allow migration:
https://www.reddit.com/r/outlinevpn/comments/hrbhz4/new_guide_set_up_a_blockingresistant_server_with/
