### ISSUE TITLE
Unable to connect to your Outline Server

### ISSUE THREAD

**Issue by maxpw** [Jigsaw-Code/outline-server#806]
Outline Manager ;

Unable to connect to your Outline Server
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.

Google Cloud Console;

CONGRATULATIONS! Your Outline server is up and running.
To manage your Outline server, please copy the following line (including curly
brackets) into Step 2 of the Outline Manager interface:
{-----------------------------}

You won’t be able to access it externally, despite your server being correctly
set up, because there's a firewall (in this machine, your router or cloud
provider) that is preventing incoming connections to ports XXXXX and YYYYY.
Make sure to open the following ports on your firewall, router or cloud provider:
- Management port XXXXX, for TCP
- Access key port YYYYY, for TCP and UDP

please help

**Comment by fortuna** [comment]
The Outline Manager has instructions on how to set up the firewall. You have to expand the "Instructions" section:
![image](https://user-images.githubusercontent.com/113565/107052333-8726f080-679b-11eb-8753-1476a25845c2.png)
![image](https://user-images.githubusercontent.com/113565/107052384-9312b280-679b-11eb-8a34-71592a20175e.png)
