### ISSUE TITLE
Raise or remove limit on open file descriptors

### ISSUE THREAD

**Issue by bemasc** [Jigsaw-Code/outline-server#819]
Currently, `cmd.sh` imposes a limit of 32768 open file descriptors.  This value was chosen in early versions of outline-server that used shadowsocks-libev.  Higher values, paradoxically, resulted in worse performance, for reasons that we were never able to explain.

Now that outline-server uses a different shadowsocks implementation, we should revisit this limit and see if it can be raised or removed.  Each proxied TCP connection consumes two file descriptors, so this limit could theoretically constrain an extremely active server.

**Comment by nimaadib** [comment]
I think you can close this issue since @fortuna has removed ulimit in this [commit](https://github.com/Jigsaw-Code/outline-server/commit/3d2c3db4940c960f7fdbd7e369936e80b62e74bd).
