### ISSUE TITLE
Using custom DNS server instead of OpenDNS

### ISSUE THREAD

**Issue by NanoG6** [Jigsaw-Code/outline-server#83]
Anyone knows how can I change the DNS for the clients? Currently they are using OpenDNS by default. I need to use my internal DNS server.

**Comment by navidlukas** [comment]
It uses what is in here

nano /etc/resolv.conf

**Comment by bemasc** [comment]
Currently, the Outline clients for different platforms behave differently.  The Windows client uses the server's default DNS configuration, which is often controlled by /etc/resolv.conf.  The clients for other operating systems use a hardcoded public DNS resolver (currently OpenDNS or Dyn Internet Guide).

**Comment by NanoG6** [comment]
Can we just edit the code before it install/compile?

**Comment by KerstinMaur** [comment]
Does Outline use [DNSCrypt](https://en.wikipedia.org/wiki/DNSCrypt)?

FYI @jedisct1, @bitbeans, @KOLANICH & @CHEF-KOCH

**Comment by jedisct1** [comment]
@KerstinMaur It doesn't seem to.

**Comment by NanoG6** [comment]
By the way, I end up with NAT iptables rules to redirect all DNS request

**Comment by CHEF-KOCH** [comment]
> Does Outline use DNSCrypt?

No.

**Comment by MartinHennrich** [comment]
Maybe [1.1.1.1](https://1.1.1.1/) would be an option too?

**Comment by KerstinMaur** [comment]
Thanks for checking @jedisct1, @NanoG6 & @CHEF-KOCH  😘

**Comment by hd-deman** [comment]
Solve it by
```
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to $custom_dns_ip:53;
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to $custom_dns_ip:53;
iptables -t nat -A POSTROUTING -j MASQUERADE
```
It means:
1) Any local user contacting out world to port tcp 53 send to $custom_dns_ip at port 53.
2) Same as 1 but for udp
3) Set the source information on the outgoing packet as coming from us.

**Comment by DavidXochipilli** [comment]
Thanks, @hd-deman! 😘

**Comment by trevj** [comment]
@NanoG6 Thanks for trying Outline! I think this one would be better in the client issue tracker:
https://github.com/Jigsaw-Code/outline-client/issues

**Comment by oleiolei** [comment]
@hd-deman, could you tell me how to change the setting, please? Your solution works but I could not change it by using the same command. And I want to give it 2 DNS addresses, it that possible?

**Comment by pascalandy** [comment]
Just to confirm, if I want to use [Cloudflare DNS](https://blog.cloudflare.com/announcing-1111/) (1.1.1.1), I just need to do this?

```
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to 1.1.1.1:53;
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to 1.1.1.1:53;
iptables -t nat -A POSTROUTING -j MASQUERADE
```
