### ISSUE TITLE
Can't scroll to bottom on the control panel

### ISSUE THREAD

**Issue by leihuang69** [Jigsaw-Code/outline-server#86]
When I logged in to Digital Ocean, I was brought to the interface that asks me to confirm authorization. But I wasn't able to scroll the page down to confirm.

It looks like this:
<img width="600" alt="screen shot 2018-04-11 at 6 19 24 pm" src="https://user-images.githubusercontent.com/24438174/38610992-1b3d3392-3db5-11e8-8586-b3a8e8546b4d.png">

**Comment by fortuna** [comment]
@alalamav @dborkan FYI

**Comment by fortuna** [comment]
The authorization flow happens on the browser now.
