### ISSUE TITLE
freegeoip json api will stop working in July 

### ISSUE THREAD

**Issue by jab** [Jigsaw-Code/outline-server#87]
I noticed that https://freegeoip.net/json/ is now returning the following message included in its payload: `“__deprecation_message__":"This API endpoint is deprecated and will stop working on July 1st, 2018. For more information please visit: https://github.com/apilayer/freegeoip#readme”`. The good news is they’re offering the same service for free over at ipstack.com. The bad news is it now requires register for an API key first, which complicates integration in the server manager (especially if there’s e.g. an email confirmation step – have to check).

Fortunately at least the server manager is self-updating, so if 
this is fixed by a bit before the deprecated freegeoip service is shut down, then no Outline 
users should get stuck with a broken server manager.

Besides fixing this direct issue, this is a good reminder that it’s worth auditing anywhere that the code makes remote connections to make sure it’s handling all the edge cases gracefully. 

From https://github.com/Jigsaw-Code/outline-server/blob/d8cb1575d10358c2312d4e0ef286092763258acc/src/shadowbox/infrastructure/ip_location.ts#L55 it looks like the code is already gracefully handling 5xx errors from freegeoip, but it doesn’t look like it gracefully handles 40x errors, or the service not being online at all. (Will that connection just hang there until the node default socket timeout (2 minutes, I think?) elapses?)

All call sites of any remote APIs that assume a timely response (and maybe hold up other important stuff in the meantime) should probably set explicit timeouts, and/or be reworked to explicitly handle the various kinds of possible flakiness that inevitably occurs at some point.

(Computers are cursed – the lot of them – but at least we have some choice curses too. 🧙🏻‍♂️🔮🌩 )

**Comment by jab** [comment]
The signup form on https://ipstack.com/signup/free looks pretty gnarly, bummer.

**Comment by trevj** [comment]
@jab Thanks for the heads up! FYI, I just pushed a new Shadowbox release that should address all this. It includes:
- https://github.com/Jigsaw-Code/outline-server/pull/180
- https://github.com/Jigsaw-Code/outline-server/pull/196
- https://github.com/Jigsaw-Code/outline-server/pull/199
