### ISSUE TITLE
One Client, One Access Key

### ISSUE THREAD

**Issue by parsalotfy** [Jigsaw-Code/outline-server#900]
Hi, is there a feature, that prevent users to use an access key in different clients ?
For example I have an access key, and I enter that key in my Laptop and my cellphone and my friends' phone and many other clients. That means 5 clients are using 1 access key.
What I want is that just one client use an access key.
So others can not connect or if someone else connects, the current user disconnect.
Is this feature exist right now?

**Comment by lgg** [comment]
Duplicate: https://github.com/Jigsaw-Code/outline-server/issues/546

**Comment by parsalotfy** [comment]
Ok, I close this issue to discuss about it on #546
