### ISSUE TITLE
Blocked when set_hostname

### ISSUE THREAD

**Issue by ArchonM** [Jigsaw-Code/outline-server#901]
Current websites for function set_hostname could be blocked by the great firewall and causes no response.
A temporary solution would be add 'http://members.3322.org/dyndns/getip' to the list of urls
Original: line 395-398:
`local -ar urls=(`
    `'https://ipinfo.io/ip'`
    `'https://domains.google.com/checkip'`
 ` )`
After:
`local -ar urls=(`
    `'https://ipinfo.io/ip'`
    `'https://domains.google.com/checkip'`
   ` 'http://members.3322.org/dyndns/getip'`
 ` )`

**Comment by JonathanDCohen** [comment]
Thanks for the suggestion!  A couple things:

First, using plaintext http for this is a non-starter.

Second, and more importantly, this script runs from the machine where the proxy server will be located, so it needs to be on an uncensored network.  If it's on a censored network then the proxying won't help us get around censorship at all.

I'm going to close this issue but please feel free to re-open if you think I've missed something
