### ISSUE TITLE
bandwidth remaining 0

### ISSUE THREAD

**Issue by someoneIG** [Jigsaw-Code/outline-server#906]
Hi
My 3 servers have a problem
They don't count the traffic usage anymore :/

How can I solve this?
I didn't have this problem at first

https://pasteboard.co/K4JrnOr.png

**Comment by someoneIG** [comment]
Hi
My 3 servers have a problem
They don't count the traffic usage anymore :/

**Comment by someoneIG** [comment]
This isn't solved yet

**Comment by fortuna** [comment]
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/953
