### ISSUE TITLE
Is Node v12 required?

### ISSUE THREAD

**Issue by mrbluecoat** [Jigsaw-Code/outline-server#907]
I'm following your instructions on https://github.com/Jigsaw-Code/outline-server#code-prerequisites but I get this error:

```
# yarn
yarn install v1.22.10
[1/5] Validating package.json...
error outline-server@: The engine "node" is incompatible with this module. Expected version "^12". Got "16.2.0"
error Found incompatible module.
```

Do I need to downgrade to Node version 12 or can I safely update package.json from `"node": "^12"` to `"node": ">=12"`, like yarn?

**Comment by mrbluecoat** [comment]
Should I use this guide instead? https://github.com/Jigsaw-Code/outline-server#code-prerequisites

(trying to install on a Raspberry Pi 4 B)

**Comment by 62w71st** [comment]
Were you able to solve the issue?
