### ISSUE TITLE
How to customize the method when creating a node?

### ISSUE THREAD

**Issue by av365app** [Jigsaw-Code/outline-server#908]
For example, I want to change the encryption protocol to "chacha20"

**Comment by JonathanDCohen** [comment]
You can't change the encryption method.  Outline chooses secure encryption parameters for you.  In general you shouldn't use chacha20 as a cipher since it's a stream cipher which is open to attack and not recommended by the Shadowsocks developers.

**Comment by av365app** [comment]
> You can't change the encryption method. Outline chooses secure encryption parameters for you. In general you shouldn't use chacha20 as a cipher since it's a stream cipher which is open to attack and not recommended by the Shadowsocks developers.

Thanks your support. ^-^
