### ISSUE TITLE
Can not connect to my server buy my access key

### ISSUE THREAD

**Issue by f48vj** [Jigsaw-Code/outline-server#91]
Can not connect to my server buy my access key, but use another key is fine.
I restart the server, not working.
Is there a way to fix it, but without losing my config?

**Comment by krrisztian** [comment]
Hey @zhangweijie-cn . A bit more info is needed here. 
1. What kind of server? 
2. Where is it hosted (if it's even a VPS)? 
3. Has it worked before and now it doesn't anymore? 

If you answer these questions, we can go forward in figuring it out.

I actually have this sometimes, that Outline (Mac, High Sierra) says that my key is invalid and works on retry.

**Comment by zhangweijie-cn** [comment]
My Outline server is host at a BandwagonHost KVM VPS.
It works before and still works with some clients like Shadowrocket at iOS.
(Shadowrocket must do some hack things).
When use ShadowsocksX-NG (macOS) it works sometimes, so weird.

**Comment by fortuna** [comment]
Seems obsolete. Closing.
