### ISSUE TITLE
Methods for sharing keys

### ISSUE THREAD

**Issue by krrisztian** [Jigsaw-Code/outline-server#94]
Referencing issues #47 #89 and a bit of #32, I think the method how the access keys can be shared/used right now are not optimal.

Issue 1: the currently used Amazon AWS host link that one can share when it comes to key sharing, is NOT available in Mainland China for example, but there are many countries with internet censorship. (I know the GFW tester websites say it is but IRL it's not) This makes it hard to "set-up" a friend who does not currently have a VPN. This kind of software is needed in places where it's frowned upon or even illegal to use. The less "trail", the better.

Issue 2: Once a key is shared (over probably a non-secure gateway like WeChat or Facebook), it can be used without any limitations. Anybody who has the key can use it, on unlimited devices. Bad example: If my friend posts it on a reddit thread (non tech-savvy users can do this), anybody on the internet has access to my Outline server. Even if just in his/her circle of friends, it's not great to have your server key out in the blue.

--

Solutions could be:
1: 
- QR Code. There could be a QR Code on the "Connect another device" page. In the apps, under "Add server" a simple QR code reader.
- Host the key on the Outline server itself (lightweight apache or nginx server - may not be easy to implement securely //f.e. SSL)
- Get rid of the AWS part completely and just share the ss:// link right away. I believe the reason behind the AWS gateway is to be able to add a server on a phone with one button, but copy-paste is easy enough too. So instead of getting the AWS link when "Connect another device", we could just get the ss:// link straight away.

2:
- Passphrase per key. I am not sure how easy/difficult would this be to implement, but this would give some security when the keys are shared over non-secure channels.
- Single use keys. Once a key is added on a client, it becomes unavailable for any other device who would try to use it. I don't know how this could be implemented but it would be a fairly straight-forward and solid way of "having a leesh" on the keys.
 

Let me know what you guys think!✌🏻

(notes: sharing keys between Mac and iOS works only through handoff. Copy the ss:// link on the mac and you can paste it on your iPhone. It works, but not a proper way of sharing a key between devices.)

I love Outline so much lol thank you everybody who has worked and/or still working on it! It can change the world.

**Comment by 4044ever** [comment]
It's not related to sharing keys directly, but if you share a key with somebody in China and they do not have the Outline client already installed they can not get it from Playstore since that is blocked in China too.

**Comment by krrisztian** [comment]
@4044ever wow, great idea! the .apk could be hosted on your Outline server with the same http server instead of the aws one!

**Comment by laosb** [comment]
Does Jigsaw consider this?

**Comment by idrigo** [comment]
@4044ever that's nice, but how can I give a key to my server for somebody, without AWS link? Is there any option to copy&send key like ss://blaHblAHbla=@11.11.7.11:24525/?outline=1 to my friend?

Thanks, guys! You do help Russia a lot now:)

**Comment by krrisztian** [comment]
@idrigo currently there is only the AWS method of sharing keys. This is why this issue exists, we are trying to create better methods for sharing keys.

**Comment by krrisztian** [comment]
The Outline Manager app shows directly the ss:// link when creating a new one now.

**Comment by DonAsasi** [comment]
I read these but still confused. Is there any way to limit each key to single device at a time? I mean user can not connect to more than 1 device at the same time with single key. Is it possible now? and how?

Thanks a alot
