### ISSUE TITLE
Outline Manager transfer limit incorrect? 

### ISSUE THREAD

**Issue by pandemicsoul** [Jigsaw-Code/outline-server#95]
In Outline Manager, it says that I have 500GB of transfer. But on the [DigitalOcean pricing page](https://www.digitalocean.com/pricing/), it says that $5/m droplets have 1TB? 

<img width="267" alt="screen shot 2018-04-12 at 4 04 59 pm" src="https://user-images.githubusercontent.com/7229022/38708488-584e4e90-3e6b-11e8-9b8f-5c6737850436.png">

**Comment by alalamav** [comment]
@pandemicsoul, the DigitalOcean 1TB transfer refers to both inbound and outbound traffic. Since the server is proxying your connections, it effectively has 500GB of transfer.
