### ISSUE TITLE
404 on setting up read and write access for application

### ISSUE THREAD

**Issue by Phyo1493** [Jigsaw-Code/outline-server#954]
I want to create a server on digitalocean via outline manger. But when I clicked authorize application for read and write acces. There is 404 error occur. Why ? 

My browser console has no error. This is the error on outline manager or digital ocean. 

I want to know how to solve this error.

Thanks.
![Capture](https://user-images.githubusercontent.com/88629419/128641590-e8b8b72f-c872-4ccd-a311-70eee22ffe8c.PNG)
![1](https://user-images.githubusercontent.com/88629419/128641597-e28118c3-3d40-44fe-aa26-1f57da93b9a3.PNG)

**Comment by fortuna** [comment]
Is this still happening? I was not able to reproduce. Perhaps it was something on the DigitalOcean side.
