### ISSUE TITLE
Issue with DNS defaulting to cloudflare

### ISSUE THREAD

**Issue by uTogglin** [Jigsaw-Code/outline-server#964]
Is it possible to make outline use your Pi-hole DNS located on the same node?

**Comment by uTogglin** [comment]
I go to hostname and it is set to the IP of my pihole for it's host name

**Comment by fortuna** [comment]
The Outline Client doesn't support selection of the DNS resolver: https://github.com/Jigsaw-Code/outline-client/issues/1014
Some other Shadowsocks clients do.
If you use a Shadowsocks-to-SOCKS5 client like shadowsocks-libev, then the server will use the resolver configured in the server. In that case you need to configure DNS as in any Linux machine, most likely with resolv.conf.
