### ISSUE TITLE
What O/S outline-server can run on? CentOS ok?

### ISSUE THREAD

**Issue by 4044ever** [Jigsaw-Code/outline-server#965]
I miss some basic requirements.

What O/S outline-server can run on?

Currently I run it on Debian (runs perfectly fine) but thinking of switching to CentOS 7 (I know in the past CentOS didn't work and wonder if that changed).

**Comment by fortuna** [comment]
It's a docker container, so you should be able to run it on CentOS.
The install script is at https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh

You may need to manuall install Docker. You need to have curl, wget and openssl in your machine.
