### ISSUE TITLE
Unable to connect to your Outline Server

### ISSUE THREAD

**Issue by someoneIG** [Jigsaw-Code/outline-server#972]
![image](https://user-images.githubusercontent.com/59090192/130945429-65f9a1f7-a32f-4b33-8d9d-abb20e9fb504.png)

I'm getting this error in Outline Manager
ports are open, and I can add & delete access key with API
only Outline Manager isn't working

**Comment by WarenGonzaga** [comment]
Where is your server hosted? @someoneIG

**Comment by someoneIG** [comment]
> 
> 
> Where is your server hosted? @someoneIG

hetzner.com and redstation.com

**Comment by WarenGonzaga** [comment]
> > Where is your server hosted? @someoneIG
> 
> hetzner.com and redstation.com

ask your provider to open the following ports on your firewall.
1024 to 65535

**Comment by someoneIG** [comment]
> 
> 
> > > Where is your server hosted? @someoneIG
> > 
> > 
> > hetzner.com and redstation.com
> 
> ask your provider to open the following ports on your firewall.
> 1024 to 65535

ports are open
I can add & delete access key with API

**Comment by djnotes** [comment]
Does it matter where the server is located? I have opened all the required ports and port ranges, but I am using podman instead of Docker. This error pops up when I try to connect to the server after successfully running the setup script on the server.
