### ISSUE TITLE
Failed to build the correct link on centos7 of GCP VPS platform.

### ISSUE THREAD

**Issue by jpmorgon** [Jigsaw-Code/outline-server#976]
After installed docker on GCP centos7 successfully, and key the outlinemanger link command in GCP shell, I will get errors as below like that:

sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed ......OK
> Verifying that Docker daemon is running ......OK
> Setting PUBLIC_HOSTNAME to extrnal IP......OK
> Creating persistent state dir......OK
> Generating secret key......OK
> Generating TLS certificate......
**Sorry! Someting went wrong. If you cant't figure this out, please copy and past all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logWMv**

please help me out ,THX

**Comment by Saika-Z** [comment]
Have you installed openssl ?
yum install openssl works for me.
hope this helps.
