### ISSUE TITLE
How to redisplay the output apiurl?

### ISSUE THREAD

**Issue by Nz666-Kshatriya** [Jigsaw-Code/outline-server#98]
How to redisplay the output apiurl after restarting ssh?

**Comment by abrikman** [comment]
Hello!
Thanks, I studied structure my server, and I can find API keys for me.
I apologize for your help.

28 апр. 2018 г., 21:19 +0700, Ilya Chidyakin <notifications@github.com>, писал:

**Comment by loopycc** [comment]
There is only "certSha256" value. 
Where is "apiUrl" ?

**Comment by fortuna** [comment]
You can use `cat /root/shadowbox/install-shadowbox-output`

**Comment by sonpython** [comment]
It's here now

`cat /opt/outline/access.txt.bak`

**Comment by cnmade** [comment]
It is now `cat /opt/outline/access.txt`
