### ISSUE TITLE
How to query data usage on the server with command

### ISSUE THREAD

**Issue by acp6** [Jigsaw-Code/outline-server#99]
I'd like to query the data usage for each key via ssh terminal, instead of using outline manager GUI. I know there is an api function getDataUsage() used by the outline manager, but don't know how to use it with curl on the server.

**Comment by rmin** [comment]
You can use something like this:
```
curl --insecure https://localhost:<PORT>/<PREFIX>/metrics/transfer
{"bytesTransferredByUserId":{{"0":22227010,"1":55912337}}
```
It returns the usage by key ID, so to get the key names for each ID you need to call another URL:

`curl --insecure https://localhost:<PORT>/<PREFIX>/access-keys`

To get the full API URL check the access file:

`cat ~/shadowbox/access.txt`
